### ISSUE TITLE
Server crashes occasionally when breaking trees

### ISSUE THREAD

**Issue by Resistance** [NillerMedDild/Enigmatica2#1]
#### Issue Description

Server crashes occasionally when breaking trees

#### What happens

Server crashes

#### What you expected to happen

No crash

#### Modpack version (Do not use "latest")

1.13

#### Your most recent log file where the issue was present

https://pastebin.com/xLVjB84P

**Comment by Resistance** [comment]
Possibly caused by interaction between minecolony and quick leaf decay, at least one such crash was observed to happen after chopping a tree inside an active construction site

**Comment by NillerMedDild** [comment]
Is this after a player cuts down a tree, or a Minecolony NPC?

**Comment by Resistance** [comment]
A player was cutting down the tree in a construction site with a builder. Don't know if a lumberjack was also present

**Comment by NillerMedDild** [comment]
Thank you for the report, I'll relay it to https://github.com/Minecolonies/minecolonies/

**Comment by NillerMedDild** [comment]
Can you reproduce the crash?

**Comment by NillerMedDild** [comment]
Fixed: https://github.com/Minecolonies/minecolonies/issues/1751
