### ISSUE TITLE
Cannot Complete AE2 quest [Better Than Wifi!]

### ISSUE THREAD

**Issue by angryansari** [NillerMedDild/Enigmatica2#10]
#### Issue Description
Cannot Complete AE2 Quest [Better Than Wifi!]
#### What happens
Required [Item Placeholder]
#### What you expected to happen
No such thing as a Wireless_crafting_terminal anymore so this reference is not valid
#### Modpack version (Do not use "latest")
1.26
#### Your most recent log file where the issue was present
N/A
[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
Thanks for reporting, will be fixed in the next update.

**Comment by NillerMedDild** [comment]
Finally done!
