### ISSUE TITLE
Quests reset? when loading in my world

### ISSUE THREAD

**Issue by MaucnAD** [NillerMedDild/Enigmatica2#100]
**Issue Description**
Random quests changed to 'New Quest'. Some of these quests were not unlocked yet, some of them were even locked behind a gate still. When I used the reset quest book command, the 'new quests' stay unlocked, they have changed back to the original quest but I can claim them (I am obviously not going to do this). 

This happened to some serious quests, like the ultimate crafting table quest and the creative EU quest. I quit my world and reloaded and now it stopped.

**Modpack version (Do not use "latest")**
1.37

**Screenshots**
Didn't make any screenshots

**Additional context**
Whenever it happened, it was as if I had completed a quest, only it said 'New Quest' completed with a netherstar icon.

I have not changed any settings whatsoever.

**Comment by NillerMedDild** [comment]
Sorry about the bot, it's clearly wrong. I'll help asap :)

**Comment by NillerMedDild** [comment]
Oh nevermind, I just realized you deleted Logs and remade the issue. Thank you.
