### ISSUE TITLE
Quests resetting?

### ISSUE THREAD

**Issue by MaucnAD** [NillerMedDild/Enigmatica2#101]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Random quests changed to 'New Quest'. Some of these quests were not unlocked yet, some of them were even locked behind a gate still. When I used the reset quest book command, the 'new quests' stay unlocked, they have changed back to the original quest but I can claim them (I am obviously not going to do this). This happened to some already handed in quests and I got the rewards a second time.

This happened to some serious quests, like the ultimate crafting table quest and the creative EU quest. I quit my world and reloaded and now it stopped.

**Modpack version (Do not use "latest")**
1.37

**Logs**
Didn't crash and latest.log is too long for hastebin

Uploaded Latest.log
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/2431576/latest.log)

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**
Some screen shots from quest book

Creative EU: https://gyazo.com/f1502d687a572e893e6deb2dde2cb133
Forestry: https://gyazo.com/0ce9a6c74802d9cc60c8103d678b77ac
Gates: https://gyazo.com/571d7eb8e1cfc660518152f19e745de9

**Additional context**
Whenever it happened, it was as if I had completed a quest, only it said 'New Quest' completed with a netherstar icon.

I have not changed any settings whatsoever.

**Comment by NillerMedDild** [comment]
Please see https://github.com/NillerMedDild/Enigmatica2Expert/issues/243 as it is duplicate to this issue. 
I've noted in that thread how to fix it temporarily, but I'll put it here too:



There's nothing to do but reset the quests I'm afraid, either through the command /bq_admin reset playername questid or the editor with /bq_admin edit

Run the command /bq_admin default load
Activate Advanced Tooltips with F3+H
Find the IDs of all quests that have converted to "New Quest", hover over the quest to see the ID.
Use the command /bq_admin reset questid playername on all the IDs you've found.



I do not have a fix, and I doubt one will ever be made, sorry :/
