### ISSUE TITLE
Case Sensitivity Issue Causes CustomMainMenu Texture Not Found Texture

### ISSUE THREAD

**Issue by rallias** [NillerMedDild/Enigmatica2#11]
#### Issue Description
Line 187 of ({"other":{"panorama":{"images"}}}), following configuration exists:

            "images" : "modpack:textures/panoramas/crag/panorama_%c.png",

However, in the modpack directory, the file is located at textures/panoramas/Crag. Due to case-sensitivity issues on computers other than Windows, this file is unable to be found by whatever is loading this resource.

#### What happens
The purple and black texture not found texture is used on main menu.

![2018-03-19_14 31 13](https://user-images.githubusercontent.com/1843506/37617831-39babfb4-2b82-11e8-8f45-2739e9e5477d.png)

#### What you expected to happen
Whatever the intended image is should show.

#### Modpack version (Do not use "latest")
Enigmatica 2 - 1.28

**Comment by NillerMedDild** [comment]
Thank you very much for reporting this, I had no idea. Will be fixed in the next update, which *should* be out within 3 days.
