### ISSUE TITLE
Mekanism Basic Gas Tank - Recipe missing!

### ISSUE THREAD

**Issue by KingRizla** [NillerMedDild/Enigmatica2#110]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
seems like there is a issue with a recipe for the mekanism basic gas tank, JEI shows nothing so atm its unmakeable, any way this can be fixed?

**Modpack Version**

1.39

**Additional Context**

**Comment by NillerMedDild** [comment]
You're in the wrong issue tracker, moving you
/move e2e
