### ISSUE TITLE
Ender IO Dimensional Transceiver not saving settings

### ISSUE THREAD

**Issue by KodiakJak** [NillerMedDild/Enigmatica2#111]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

When setting power send or receive channels on the Ender IO Dimensional Transceiver, it does not save these settings when closing the GUI. This was not a problem in the previous version of this modpack.

**Modpack version (Do not use "latest")**

Enigmatica 2 (Normal) 1.49

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
It has been reported and fixed by the Ender IO devs, thank you for the report :)

https://github.com/SleepyTrousers/EnderIO/issues/4890
