### ISSUE TITLE
Lapis /dank/null Panel not craftable

### ISSUE THREAD

**Issue by Ghost942** [NillerMedDild/Enigmatica2#112]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Attempting to craft "Lapis /dank/null Panel" results in no output on a crafting table

**Modpack version (Do not use "latest")**

Version 1.49

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

Saw that in 1.48, mod author had reenabled the use of higher tier /dank/nulls. Wanting to hold more items, I wished to craft the panels to then upgrade /dank/null Mk I. Unable to do so at this time.

**Comment by Ghost942** [comment]
Additional testing has shown that none of the later upgrade panels are craftable in 1.49, and thus the /dank/null Mk I is still the only option for use

**Comment by NillerMedDild** [comment]
![billede](https://user-images.githubusercontent.com/21295394/46682815-e639c200-cbee-11e8-9892-3be60d058913.png)

It works just fine for me. Is it possible you forgot to update the scripts folder of your server? :)
