### ISSUE TITLE
Config File Names

### ISSUE THREAD

**Issue by Tellik** [NillerMedDild/Enigmatica2#119]
Linux file systems are case sensitive. There are currently a couple config files in the server pack that aren't correct.

Normally this doesn't cause an issue. (I found one pack recently where it does.)

The situation is server files come with preinstalled config files.
The mod looks for a specific config file when loading, and if it doesn't see it, it generates a default config file.
If the pack or server is running on Linux, case sensitivity comes into play with this. There could be a config file for the mod there, but since it has the incorrect casing in the file name, it doesn't see it so it generates the default config file.
Since windows doesn't have this issue, the user is able to load the pack correctly with the config file provided.
Depending on the differences between the modified config file and the default, this could prevent players from connecting to the server with a mismatch config file. (For example, if the config file on the server is default and doesn't disable a block that the user has disabled.)

There are two config files that I found that are incorrect. I'm hoping there aren't more, but some of the config folders have lots of files and folders to inspect.

Exchangers.cfg (server files provide exchangers.cfg)
IntegrationForegoing.cfg (server files provide integrationforegoing.cfg)

Edit: Very minor but separate issue, can we rename StartServer(Linux).sh to StarServerLinux.sh in future server file releases?

**Comment by NillerMedDild** [comment]
Damn, I thought I got all the files on the last sweep :p the issue usually occurs when a new modder realizes configuration files should be lowercase, and switches it out. I never catch it since I develop on Windows.

Thank you for the report :)
