### ISSUE TITLE
Missing ore(s) still in Enigmatica 2 v1.29

### ISSUE THREAD

**Issue by seanjohnbell** [NillerMedDild/Enigmatica2#12]
#### Issue Description
Aluminum/Bauxite Ore's still not spawning
#### What happens
Above ores are not being added to world gen, so there appears to be no way to mine either of these ores, and by extension make anything that needs them. Currently the ore cannot be found when searching in JEI by name, but can be found when backtracking through JEI from Aluminum Ingots back to the raw ore. The "actions" available for the ore do not include a "world gen" tab as can be seen below:
  - When looking at aluminium ore (from thermal foundation).
![nooregen](https://user-images.githubusercontent.com/5022929/37743366-2f876104-2d40-11e8-95fd-652673d4fb63.png)
  - When looking at iron ore from base minecraft
![oregen](https://user-images.githubusercontent.com/5022929/37743440-740a20be-2d40-11e8-9aff-be88a49a07e2.png)
#### What you expected to happen
One or both of these ores to spawn when a new world is created and for there to be an entry in the "world gen" tab for these ores in JEI.
#### Modpack version (Do not use "latest")
1.29 Enigmatica 2 - Fresh install and new world generated.
#### Your most recent log file where the issue was present
No log file as reproduction steps are quite simple.
[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
Ore Graphs are not based on individual worlds, they're pregenerated by me. I forgot to edit Bauxite > Aluminum ore in JEI, will be fixed in the next update.

However, Aluminum does generate.
