### ISSUE TITLE
Forestry Book Uncraftable

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2#121]
**Notes**
Things to keep in mind when completing the task, possible solutions etc.

**Additional context**
Add any other context or screenshots about the task here.

**Comment by tyler489** [comment]
If its a simple recipy conflict with botania? Just use the forestry worktable and u can choose the outpit

**Comment by NillerMedDild** [comment]
It is not, I added a recipe for it that takes 2 saplings and a book.

**Comment by NillerMedDild** [comment]
Turns out the reporter was wrong.
