### ISSUE TITLE
Enigmatica Crash Report

### ISSUE THREAD

**Issue by cryusion** [NillerMedDild/Enigmatica2#128]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
crashing upon entering a world,

**Modpack version (Do not use "latest")**
Enigmatica 2 1.49 (release)

**Logs**

https://pastebin.com/wKhyb72u

**Screenshots**

**Additional context**

i wasnt doing much other than mining some resources to get started with some quests, force closed the game do to it freezing up, and can no longer access the world i made, i dunno if its corrupted or not

**Comment by NillerMedDild** [comment]
I think your player is holding something with too much data on, I suggest you either try to find this information:
-- NBT Tag --
Details:
    Tag name: Sections
    Tag type: 9
and delete it, or delete all of your player.data.
