### ISSUE TITLE
Can't craft Mekanism Fusion Reactor Controller

### ISSUE THREAD

**Issue by jestesared** [NillerMedDild/Enigmatica2#129]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
Even though I triple checked that I'm using the correct ingredients, I can't craft the Reactor Controller from Mekanism. Tried using a vanilla crafting table as well, still no luck. My guess is maybe a meta-data using with the fusion controller or the ultimate gas tank maybe?

**Modpack Version**
1.10

**Additional Context**
![2018-10-17](https://user-images.githubusercontent.com/27898593/47131816-0526fc80-d25e-11e8-9b83-0a11fdc693d0.png)

**Comment by NillerMedDild** [comment]
I'm guessing this relates to the Expert Skyblock pack.

/move e2es
