### ISSUE TITLE
Crash upon launch

### ISSUE THREAD

**Issue by Pm0001** [NillerMedDild/Enigmatica2#13]
#### Issue Description 
Crash upon launch

#### What happens
While in loading screen: loading stops -> then after a few minutes: crash

#### 
Already reinstalled the pack twice. Issue continues to happen every single time I wanna start the pack.

#### Modpack version (Do not use "latest")
1.30

#### Your most recent log file where the issue was present

[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/1887232/latest.log)

**Comment by NillerMedDild** [comment]
I'd like the crash report please.

I suspect you're not allocating enough RAM to Minecraft. If you're using the Twitch launcher, this can be done under Settings > Minecraft

**Comment by Pm0001** [comment]
No way! Apperently my settings were reset at some point. Now that I have attributed the same RAM as befor it is working again. Thank you so much!

**Comment by NillerMedDild** [comment]
Sure thing :)
