### ISSUE TITLE
Crash with Thaumcraft Infusion Altar

### ISSUE THREAD

**Issue by MechanosG** [NillerMedDild/Enigmatica2#131]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Thaumcraft infusion altar crashes servers upon loading the chunk the altar is in.  It's fixed now, but the modpack needs to point at the new file with the same name.
https://github.com/Azanor/thaumcraft-beta/issues/1505

**Modpack version (Do not use "latest")**
1.50

**Logs**
https://gist.github.com/kencinder/7adbbbc1c7f8c7d60ab48e11487f988a

**Screenshots**
Only thing I could screenshot would be the message saying server has closed.

**Additional context**
https://minecraft.curseforge.com/projects/thaumcraft/files/2629023 This "should" fix it.

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll upload a hotfix asap :)
