### ISSUE TITLE
[Quest Completion] Two Mekanism quests not completing

### ISSUE THREAD

**Issue by nodey420** [NillerMedDild/Enigmatica2#136]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The following quests will not complete:
Storing the Gas and the Jetpack quest ( sorry, the pack is not open ).

**Modpack version (Do not use "latest")**
1.49

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by drakkensong21** [comment]
I got the quests to complete by putting some gas in the items.

**Comment by NillerMedDild** [comment]
Well that's concerning. Will get it fixed :)

**Comment by NillerMedDild** [comment]
Bad bot!
