### ISSUE TITLE
malformed_QuestDatabase.json0

### ISSUE THREAD

**Issue by NLinCH** [NillerMedDild/Enigmatica2#140]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
the QuestDatabase has been malformed like you see (screenshot 1)
loading the default quests (with /bq_admin default load) resets all quest of mine (screenshot 2)
the latest backup of the Quests is corupted to (so i mad the pictures)
/bq_user refresh  and /bqs_loot default load  dont work

**Modpack version (Do not use "latest")**

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).
it didn't crash there is no log
I tried the questdatabase but I couldn't get it in a acceptable formate from JSON to TXT

**Screenshots**

![image](https://user-images.githubusercontent.com/43685452/47254849-a3d27980-d467-11e8-9bfb-c8ad15d47ad5.png)
![image](https://user-images.githubusercontent.com/43685452/47254868-cfedfa80-d467-11e8-9239-67fab100a9b3.png)

**Additional context**

sorry if it doesnt realy help and If it is just a mistake by betterquesting
still I hope this can help to improve

If you tell write me how to translate it without having it all in one lane I would be open to send the JSON in a better form
I shall try to send the JSON by email
hope it works

**Comment by NillerMedDild** [comment]
What about loading a backup from your backups folder, and then doing /bq_admin default load?

**Comment by NLinCH** [comment]
kinda workt I took the backup.JSONs from my most recent backup of the quests and the questdatabase from an older one it works thanks for your time
