### ISSUE TITLE
Recipe conflict -  Frame block and Wooden Bushing Set

### ISSUE THREAD

**Issue by MissRobyn102** [NillerMedDild/Enigmatica2#146]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
The frame block from BlockCraftery sticks and the Wooden Bushing Set have the same recipe.

**Modpack Version**
1.51

**Additional Context**

**Comment by NillerMedDild** [comment]
Duplicate of #137
