### ISSUE TITLE
Can't seem to milk any of the animania cows

### ISSUE THREAD

**Issue by xonixo** [NillerMedDild/Enigmatica2#152]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Can't seem to milk any of the animania cows. They are well fed

**Modpack version (Do not use "latest")**
1.51

**Comment by drakkensong21** [comment]
The cows need to have just given birth to give milk.

**Comment by NillerMedDild** [comment]
Did you try mating them, as Drakkensong suggests?

**Comment by xonixo** [comment]
Oh is that so, i tried to dig up info about how to milk them and nowhere did i find mention of that. I'll try it out

**Comment by NillerMedDild** [comment]
Please let us know how it turns out :)
