### ISSUE TITLE
Errors on connection

### ISSUE THREAD

**Issue by ArtOfCombat** [NillerMedDild/Enigmatica2#157]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Every time I try to connect to a certain server, I cannot. The first time I get an I/O error, after that it's always "A fatal error has occurred, this connection is terminated." I have reinstalled the pack, and others can connect fine.

**Modpack version (Do not use "latest")** 1.51

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report. I need your `latest.log` file to troubleshoot the issue.

The `latest.log` file can be found in the `logs` folder of the Enigmatica modpack folder.

**Comment by NillerMedDild** [comment]
https://gist.github.com/

**Comment by ArtOfCombat** [comment]
https://gist.github.com/ArtOfCombat/267d0eb1429dd45024b759d082598ee9

**Comment by NillerMedDild** [comment]
It seems to be this issue: https://github.com/Funwayguy/BetterQuesting/issues/492
which has been resolved in a new version of Better Questing. Unfortunately I can't really update, because newer version seem to be an issue with bandwidth usage.

**Comment by ArtOfCombat** [comment]
This is now also happening on the official server.

**Comment by NillerMedDild** [comment]
Do you know if it's happening for anyone else on the official server?

**Comment by ArtOfCombat** [comment]
I do not. Latest log is here: https://gist.github.com/ArtOfCombat/df4758f6d196dbc59bfb94b0271e4de7

**Comment by urikkiru** [comment]
Over Christmas I setup an Enigmatica 2 server for some family and friends. Every one of us(about 6 players) has this issue. We're all playing version 1.54 of the pack.

**Comment by NillerMedDild** [comment]
I'm hoping updating Advanced Rocketry will fix part of the issue, but I don't know about the other part.
