### ISSUE TITLE
Can collect, but can't use OpenBlocks' Liquid XP

### ISSUE THREAD

**Issue by gallowglass** [NillerMedDild/Enigmatica2#159]
**Issue Description**

OpenBlocks' liquid XP is easy to collect and impossible to use.  Slap an XP drain on a tank and hop on to collect liquid XP.  But when you want to cash in that liquid XP there is no way to do it.  The XP shower won't connect to any tank or fluid pipe, the Forestry bottler won't bottle it....  Am I missing something here?  How are we supposed to use OpenBlocks' liquid XP?

**Modpack version (Do not use "latest")**

1.49

**Logs**

N/A

**Screenshots**

N/A

**Additional context**

N/A

**Comment by NillerMedDild** [comment]
Put it in an OpenBlocks tank and right click it, that should do the trick :) The OpenBlocks tanks are crafted with a + sign of Glass Panes, and Obsidian in all 4 corners.
