### ISSUE TITLE
Certain blocks like slabs wont place inside storage drawers or right click properly on inventories

### ISSUE THREAD

**Issue by Huginn-Odinbro** [NillerMedDild/Enigmatica2#16]
#### Issue Description
When I try placing certain blocks like slabs (vanilla or modded) into an empty storage drawer it places the slab on the drawer instead of inside it. Same thing with crafting tables, it jus tplaces the slab next to the table instead of opening up the inventory.
#### What happens
Certain blocks like slabs wont place inside a storage drawer
#### What you expected to happen
They are supposed to be able to be held inside storage drawers
#### Modpack version (Do not use "latest")
1.31
#### Your most recent crash report or log file where the issue was present
No crashes from the issue
[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
The cause is the mod EDX Multipart, I'll remove it. Thanks for the report.

**Comment by Huginn-Odinbro** [comment]
No problem, thanks for making this pack. Seriously, thanks for offering your time up for other's enjoyment.
