### ISSUE TITLE
Shadow Mage crashing on loading during server start

### ISSUE THREAD

**Issue by SnowMntGaming** [NillerMedDild/Enigmatica2#160]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Server crashes on start up

**Modpack version (Do not use "latest")**
1.5.1

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).
https://hastebin.com/vadolijini.rb

**Screenshots**

**Additional context**

**Comment by SnowMntGaming** [comment]
I got around this issue, by starting the server in peaceful.

**Comment by NillerMedDild** [comment]
Thank you for the report, it has been reported to the appropriate mod developer :)
https://github.com/P3pp3rF1y/AncientWarfare2/issues/855

**Comment by NillerMedDild** [comment]
Could you please try removing AI Improvements, and see if the issue persists?

**Comment by SnowMntGaming** [comment]
https://hastebin.com/uzeyavebep.rb

I had this crash today, would AI improvements being removed solve both issues?

**Comment by SnowMntGaming** [comment]
The same error happens with ancient warfare

**Comment by NillerMedDild** [comment]
I don't know, that's why I asked you to try :) It's the same crash though, just with a different mob.

**Comment by NillerMedDild** [comment]
Downgrading your Java version could solve it, I don't know how stable version 192 is.

**Comment by NillerMedDild** [comment]
I see. What about the java downgrade?

**Comment by SnowMntGaming** [comment]
I can only select between java 7 and 8.

**Comment by SnowMntGaming** [comment]
The same error happen with the new update.

**Comment by NillerMedDild** [comment]
I'm closing this as I have not received any reports of it happening for others.
