### ISSUE TITLE
Extra Utilities 2 generators are eating fuel

### ISSUE THREAD

**Issue by jumpkain** [NillerMedDild/Enigmatica2#164]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Attempting to insert fuel into Extra Utilities 2 generators via means other than manually dragging it in with the mouse (both shift-click and hoppers have been tested) when the generator is both...

1: Currently running
and 2: Has at least one item in its input slot, but not a full stack

...will result in the item you've attempted to insert disappearing entirely.

I tested this with the Furnace Generator and the Culinary Generator, with both Coal/Charcoal in the former and Raw Mutton in the latter. All items that were inserted when the above criteria were wasted.

**Modpack version (Do not use "latest")**

1.51

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

Here's a short gifv of the issue being shown off with Charcoal in a Furnace generator:

https://i.imgur.com/u37fwtO.gifv

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, the issue has been fixed on the mod's end :)
