### ISSUE TITLE
Extra Utilities 2 generators still eating fuel under certain circumstances

### ISSUE THREAD

**Issue by jumpkain** [NillerMedDild/Enigmatica2#169]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Updating EU2 in the latest version of the modpack fixed the issue with fuel disappearing when shift-clicking and hopping it into EU2's generators, but this version of EU2 (1.9.8, for reference) has a bug where attempting to put fuel into a generator manually (with left or right-click) under the following circumstances (same conditions as before) will eat the fuel from your hands:

1: Currently running
and 2: Has at least one item in its input slot, but not a full stack

I assume that this affects all generators and all fuel sources since testing a couple with the last bug resulted in the fuel disappearing with every combination I tried, but I've only personally tested Charcoal in a Furnace Generator this time around.

**Modpack version (Do not use "latest")**

1.52

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

Here's a short gifv of the issue being shown off with Charcoal in a Furnace generator:

https://i.imgur.com/fXrbYGZ.gifv

**Additional context**

Before Enigmatica 2 updated, I looked on EU2's GitHub and found players saying that downgrading to 1.9.5 fixes all of the "disappearing fuel" issues, however this version has another bug that causes the Resonator to eat materials (basically resulting in a stack of x items turning into 1 item when being processed). You can see the issue here: 

https://github.com/rwtema/Extra-Utilities-2-Source/issues/204

Looking back further (though 1.9.5 is the only version I've tested), it seems that prior updates to EU2 fixed crashes, so downgrading further probably isn't an option. We're probably stuck waiting for EU2 to update again in order to fix these issues.

**Comment by NillerMedDild** [comment]
Thank you for the thorough report :) I'll wait patiently for the update then.
