### ISSUE TITLE
Thaumcraft giving endless amounts of unusable backpacks

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica2#17]
#### Issue Description
thaumcraft arcane workbench giving endless amounts of middle backpacks from backpack mod.
#### What happens
After doing the very first steps of thaumcraft and getting the arcane workbench, every time you open it, it shows a middle backpack in the result slot and if you pick it up, close and reopen the workbench there's a new one every time. 
https://gyazo.com/6cb2fdafe42b657f975db9526eb399cf

You can't do anything with those backpacks, it's like you cheat the backpack from JEI, it doesn't open. 
#### What you expected to happen
Not having the backpack in that slot :)
#### Modpack version (Do not use "latest")
1.33a

**Comment by jinkhya** [comment]
Actually found this : https://github.com/Azanor/thaumcraft-beta/issues/503
I should have checked thaumcraft issues before posting this...
This issue is more of a heads up then :D

**Comment by NillerMedDild** [comment]
Thanks for the report.
