### ISSUE TITLE
Enable Fresh Water Squid

### ISSUE THREAD

**Issue by ozankaraali** [NillerMedDild/Enigmatica2#171]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Squids do not spawn.
I was trying to do Angel Ring quest then I noticed that there is no squids in the world.
I recreated same seed, still there were no squids.
Used "/testfor {at}e[type=squid]" to check. 
Did "/cofh killall" and "/kill {at}e[type=!Player]" to respawn everything.
Opened creative mode and tried to spawn squids with both Spawn Squid (Minecraft) and Morb Squid (Thermal Expansion).
Says squid swims but no entities appear.
"/spawn squid" makes teleport to initial location.

**Modpack version (Do not use "latest")**
1.52

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

Nothing related with this issue appears in logs.

**Screenshots**

**Additional context**

I edited @ as {at} because {at}e refers to a Github user.

**Comment by ozankaraali** [comment]
In /config/animania.cfg:
```
# Allow Squids tp Spawn in Fresh Water
B:spawnFreshWaterSquids=false
```
should be 
```
B:spawnFreshWaterSquids=true
```
I will not close this issue until a maintainer notices, then it can be closed.

**Comment by drakkensong21** [comment]
![squid](https://user-images.githubusercontent.com/38679368/48666168-0d06d600-ea82-11e8-998b-41b2eadc020a.png)
they spawn for me on a new instillation of the pack with know changes

**Comment by ozankaraali** [comment]
> ![squid](https://user-images.githubusercontent.com/38679368/48666168-0d06d600-ea82-11e8-998b-41b2eadc020a.png)
> they spawn for me on a new instillation of the pack with know changes

Correct me if I am wrong but the latest pack is 1.52 and there is no changes. I downloaded it from Twitch app.

**Comment by drakkensong21** [comment]
i don't think he changed any squid spawning in 1.52 I downloaded a clean version and locked for the squid and found them spawning.

**Comment by NillerMedDild** [comment]
Thank you for the report. Although I've been unable to reproduce this, I think you're right about the config change.

**Comment by NillerMedDild** [comment]
Also, thank you for your help @drakkensong21
