### ISSUE TITLE
[1.12.2] - Add ALL /dank/null nulls to be available

### ISSUE THREAD

**Issue by Ghost942** [NillerMedDild/Enigmatica2#172]
**Is your feature request related to a problem? Please describe.**
Mk1 to Mk4 /dank/null nulls are available, but not Mk5 and Mk6
**Describe the solution you'd like**
Requesting for Mk5 and Mk6 to be available
**Additional context**
With one playthrough, I had to use three Mk4 /dank/nulls to store ores and other blocks. Not happy with current available nulls

**Comment by drakkensong21** [comment]
the others are to op for 1 block storage that's why he disabled them.

**Comment by NillerMedDild** [comment]
I think their storage is far too large, which is why I disabled the last 2 tiers.
