### ISSUE TITLE
Recipe conflict - TiCon item rack and slab to block recipe

### ISSUE THREAD

**Issue by MorganSimic** [NillerMedDild/Enigmatica2#174]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The recipe for TiCon item rack, two wooden slabs side by side, is conflicting with the shapeless slab to block recipe, which is presumably provided by Quark. 

**Modpack version (Do not use "latest")**
1.51, according to changelog not fixed in 1.52

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thanks for the report :)

**Comment by NillerMedDild** [comment]
Resolving this issue would mean making Item Rack recipes for each wood type, or alternatively remove the Quark Slabs to Block recipe. I don't think either option would be worth it, seeing as Item Racks are just Drying Racks that don't dry stuff. Could you use Drying Racks instead, or does something prevent it? :)

**Comment by MorganSimic** [comment]
Yeah, the issue is pretty minor. You could just disable the item rack. There are a few edge cases where that would conflict, if you want to hang something up that has a drying recipe. But that is negligible I think. If I have some time and feel like it, I could write the script for it. If I do so I will let you know, otherwise consider this issue closed.

**Comment by NillerMedDild** [comment]
Sounds good!
