### ISSUE TITLE
Crash when shift left clicking an item into a machine

### ISSUE THREAD

**Issue by Nicko-Black** [NillerMedDild/Enigmatica2#175]
**Question or Issue**
Shift left clicking redstone to fill the heated redstone generator will cause the game to crash when redstone is already present inside the generator. For example, when 22 redstone is in the generator and you shift left click a stack of 64 to fill it, the game crashes.

**Modpack Version**
1.52

**Additional Context**
I've only been able to replicate it with the heated redstone furnace, but someone on the server I play on noted that its happened in other instances that were similar. I also tested it with a vanilla furnace and it seemed to work fine.

**Comment by Nicko-Black** [comment]
Realized it was a documented bug in extra utilities 2 gonna close.

**Comment by NillerMedDild** [comment]
Thanks for the report anyway :)
