### ISSUE TITLE
Crash during play.

### ISSUE THREAD

**Issue by GldnSabre74** [NillerMedDild/Enigmatica2#177]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
At random I get a crash during play and it is always describing Netty.

**Modpack version (Do not use "latest")**
1.52
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/2601420/latest.log)

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Is this happening on a SpongeForge server?

**Comment by GldnSabre74** [comment]
No regular Forge 2768

**Comment by NillerMedDild** [comment]
Mkay, single or multiplayer?

**Comment by GldnSabre74** [comment]
Sorry Multiplayer, no crash from server just client.

**Comment by NillerMedDild** [comment]
Sorry to be rude, but are you certain the server isn't using SpongeForge?

**Comment by GldnSabre74** [comment]
Yes downloaded the universal forge jar directly from forge

**Comment by NillerMedDild** [comment]
Fair enough, I'll do some digging :)

**Comment by NillerMedDild** [comment]
I'm guessing your two issues are linked, as they're both relating to a network exception. I'm closing this one :)
