### ISSUE TITLE
crash on connect to server 

### ISSUE THREAD

**Issue by GldnSabre74** [NillerMedDild/Enigmatica2#178]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Client crash on first load after restart all clients.
"A Fatal Error Has Occured, This Connection Has Been Terminated."
Works again if you login after that.

**Modpack version (Do not use "latest")**

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/2604525/latest.log)

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Does it matter where you are in-game?

**Comment by GldnSabre74** [comment]
No, it only happens the first time anyone logs into my server after a restart or first time ever joining. Then you can rejoin right after without issue.

**Comment by GldnSabre74** [comment]
This one only happens when you connect, the other one happens at random during play.

**Comment by NillerMedDild** [comment]
Have you tested whether it's still an issue on update 1.53?

**Comment by NillerMedDild** [comment]
Also, I'd like the server's latest.log please

**Comment by GldnSabre74** [comment]
Bug gone in current pack 1.53. Confirmed for me today.
