### ISSUE TITLE
[1.53] ChunkNibbleArrays should be 2048 bytes not: 0

### ISSUE THREAD

**Issue by nodey420** [NillerMedDild/Enigmatica2#179]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Upgraded from 1.52 to 1.53 and getting a crash every time I join.

Crash log hastebin attached.  Let me know if you need full logs.

**Modpack version (Do not use "latest")**
1.53

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).
https://hastebin.com/inibewetek.rb
**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
It looks like one of your chunks is corrupt. Either try loading a backup, or try to fix the chunk corruption - See [this link](https://www.reddit.com/r/Minecraft/comments/835uz4/help_with_modded_client_crash/) for a guide to the latter :)

**Comment by nodey420** [comment]
That's what I was afraid of :(

**Comment by nodey420** [comment]
Happened with my backup too.  This happened right after I updated to 1.53.  I will downgrade and test again with my backup.

**Comment by nodey420** [comment]
Looks like this was prior to the update and is likely related to world corruption :(

**Comment by NillerMedDild** [comment]
Sorry to hear that :( I hope the tool in my link can help.
