### ISSUE TITLE
Crash: Tessalating block model - punching blueberry bush (natura)

### ISSUE THREAD

**Issue by Obbdot** [NillerMedDild/Enigmatica2#18]
#### Issue Description
Crash: Tessaling block model

#### What happens
Created a new world - Lost Cities - Realistic. I walk a few steps, punch a blueberry bush from Natura with my book and crash. Reload the game, punch the blueberry bush with my fist. Crash again. 

RAM allocated is 8192 MB (16GB of RAM hardware). Using the jar launcher with JAVA 1.8.0.161 64 bits.
Using Java arguments: 
-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

#### What you expected to happen
the blueberry bush to drop a sword of the cosmos /s

#### Modpack version (Do not use "latest")
1.33a, I did not manually upgrade any mod. 

#### Your most recent crash report or log file where the issue was present
https://pastebin.com/xdqeiVzs

**Comment by b52src** [comment]
I am also seeing this now with 1.33a except with other blocks as well the Ender IO travel anchor has caused it once along with regular stone

**Comment by NillerMedDild** [comment]
Both of these crashes seem to originate from ArchitectureCraft blocks, I suggest you both remove any you have in the area :/ This bug has been happening for quite some time, and I'm afraid I can't fix it.

**Comment by b52src** [comment]
I did not have any ArchitectureCraft blocks, but i removed it and i'm still getting the crash just breaking stone.

https://pastebin.com/EhJvVrJE

**Comment by NillerMedDild** [comment]
I uploaded an update to Curse, it should be approved within 3 hours - Could you check if it's still happening with that?

**Comment by b52src** [comment]
have not had the issue occur since the update, so far.

**Comment by NillerMedDild** [comment]
Sounds good, you can reopen it if it reappears.
