### ISSUE TITLE
Crash on startup: out of bounds exception

### ISSUE THREAD

**Issue by chancock1991** [NillerMedDild/Enigmatica2#185]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Crash upon launch of modpack from twitch. Never loads the Minecraft screen and give the Error: java.lang.IndexOutOfBoundsException.

**Modpack version (Do not use "latest")**
Version 1.44

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).
https://hastebin.com/ixijukoqon.rb
**Screenshots**

**Additional context**

I've only played for about 30 minutes and was working on collecting clay for the smeltery quest. Interesting, the game crashed while trying to change WAILA key bind from default numpad 1 to something else (I used n when the crash happened).

**Comment by chancock1991** [comment]
Edit:
When placing back my copied save file back into a newly downloaded mod pack, it solved the issue.

**Comment by NillerMedDild** [comment]
Cool :)
