### ISSUE TITLE
Holding right mouse button isn't working as intended

### ISSUE THREAD

**Issue by StumpedForIdeas** [NillerMedDild/Enigmatica2#19]
#### Issue Description

Holding down the right mouse button is not repeatedly placing blocks or activating machines.

#### What happens

A single block is placed or a machine is activated a single time i.e. Quartz Grindstone.
Doesn't affect TiCon Shurikens or similar weapons.

#### What you expected to happen

Blocks to be placed consecutively or machines/doors be activated multiple times.

#### Modpack version 

Version 1.35

#### Your most recent crash report or log file where the issue was present

[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/1979721/latest.log)

**Comment by Lukas45** [comment]
Side effect from https://www.curseforge.com/minecraft/mc-mods/better-placement

**Comment by StumpedForIdeas** [comment]
Thank you. Apologies for the oversight on my part.
