### ISSUE TITLE
Black Hole tank in Industrial Forgoing verion bugged.

### ISSUE THREAD

**Issue by sonvar** [NillerMedDild/Enigmatica2#190]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Industrial Forgoing black hole tank making fluids it holds incompatible with same fluids after breaking. The Github for industrial forgoing someone reported this issue, that in version 1.11.6 this happens, but in version 1.11.5 it didnt seem to happen. This issue was "closed" with no response of resolution. I assume the mod author does not plan to address this issue. 

**Modpack version (Do not use "latest")**
1.53

**Logs**

none

**Screenshots**

nothing useful

**Additional context**

reverting to version 1.11.5 of Industrial Forgoing might help resolve this.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Seems to be fixed in the current version.
