### ISSUE TITLE
Chunks added by JAOPCA can't be processed in a macerator, while chunks added by Mekanism can.

### ISSUE THREAD

**Issue by rohankalva** [NillerMedDild/Enigmatica2#191]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**

The title explains it adequately.

**Modpack Version**

Pack version 1.44.

**Additional Context**

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll get this reported to JAOPCA as soon as I can :)

**Comment by NillerMedDild** [comment]
I'm guessing you mean Clumps?

**Comment by NillerMedDild** [comment]
https://github.com/TheLMiffy1111/JAOPCA/issues/100
