### ISSUE TITLE
 Bug quest

### ISSUE THREAD

**Issue by Naoya99** [NillerMedDild/Enigmatica2#192]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

I only craft lava mill and the quest is validated

**Modpack version (Do not use "latest")**

1.53

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

![screenshot_1](https://user-images.githubusercontent.com/45720987/49690412-f7407a00-fb30-11e8-89f5-d4720c614d97.png)
![screenshot_2](https://user-images.githubusercontent.com/45720987/49690415-00c9e200-fb31-11e8-92e6-47de9c868b66.png)
![screenshot_3](https://user-images.githubusercontent.com/45720987/49690416-01627880-fb31-11e8-9698-418f249d5c85.png)
![screenshot_4](https://user-images.githubusercontent.com/45720987/49690417-0293a580-fb31-11e8-9e61-cb4aaeab47b6.png)

**Additional context**

I only craft 4 lava mill and i finish the quest

**Comment by NillerMedDild** [comment]
Have you read the quest description?

**Comment by Naoya99** [comment]
sorry I didn't read

**Comment by NillerMedDild** [comment]
No worries.
