### ISSUE TITLE
NuclearCraft Ores Through ET Voidminer

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2#197]
All tiers, all 4 ores.

**Comment by AwesomeLikeThis** [comment]
dead thread, but was this ever added? because I don't see a recipe from the void ore miners that produce nuclearcraft ores. I was about to post a feature request when I saw this.

**Comment by NillerMedDild** [comment]
Yep it was, all tiers of Void Ore Miner.

**Comment by NillerMedDild** [comment]
Just checked and it works and appears correctly in JEI.

**Comment by AwesomeLikeThis** [comment]
Ah shoot, my blind self didn't realize that this isn't the enigmatica 2 **expert** github. My bad.

**Comment by NillerMedDild** [comment]
Ah, it was never added to Expert mode, since you can sieve for them there.
