### ISSUE TITLE
IE revolver - crash when realoding ammo

### ISSUE THREAD

**Issue by hadrosak** [NillerMedDild/Enigmatica2#198]
**Issue Description**

Game crashes when i try to load/reload Immersive engeneering revolver. Same for IE speedloader for revolver.

**Modpack version (Do not use "latest")**

1.54

**Logs**

 https://pastebin.com/6AwBiJv3

**Screenshots**

N/a

**Additional context**

**Comment by NillerMedDild** [comment]
Upload the crash log to pastebin or hastebin, like the issue template asked you to, please.

**Comment by hadrosak** [comment]
> Upload the crash log to pastebin or hastebin, like the issue template asked you to, please.

Updated,

**Comment by NillerMedDild** [comment]
Thank you :) I'll investigate.

**Comment by NillerMedDild** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/3319
The issue has been fixed on their end, we're just waiting for an update :D

**Comment by zombiebill** [comment]
any idea when the update will be just had the same reload crash with the revolver and am interested in using the gun

**Comment by NillerMedDild** [comment]
It should be today :)
