### ISSUE TITLE
Massive TPS hit with Mekanism turbine

### ISSUE THREAD

**Issue by Shurhaian** [NillerMedDild/Enigmatica2#2]
#### Issue Description
Mekanism's Industrial Turbine causes huge TPS drops when formed - from 20 TPS down to 5-10 immediately, quickly leading to multiple-second latency.

#### What happens
As above; forming the turbine multiblock instantly results in a severe TPS drop, breaking a single block so the multiblock unforms allows it to recover.

#### What you expected to happen
Turbine did not previously result in this level of performance hit, especially on a world that doesn't otherwise have much happening.

#### Modpack version (Do not use "latest")
1.14

#### Your most recent log file where the issue was present
https://paste.ee/p/GRfm7

**Comment by Shurhaian** [comment]
Still happens after updating the pack to 1.20.

**Comment by NillerMedDild** [comment]
No changes to Mekanism Turbines were made in the versions between 1.07 and 1.20 - Could you move this to the Mekanism repo, https://github.com/aidancbrady/Mekanism/issues, or would you prefer that I do it?

**Comment by Shurhaian** [comment]
Odd. If the Mekanism version hasn't changed, though, that must mean something in the environment has - wouldn't the Mekanism dev(s) just bounce me back here, if nothing else because it's not the absolute latest version (9.4.2.327 vs .328)? Because this wasn't happening in modpack v1.13 - only since updating to 1.14.

Possibly relevant: I've also noticed that steam is rendering strangely. It used to get progressively denser as the container got more full, like other gas-type fluids - but now, if there's any in the multiblock at all, it's immediately opaque, and when the throughput is fairly low this leads to rapid flickering. This seems to be an issue with Mekanism's multiblocks (turbine, boiler, and dynamic tank tested), but doesn't affect other tanks - the tinker tank, certus tank, and Cyclic fluid tank all fill from the bottom up like a liquid, while the ender tank, TE portable tank, and even Mekanism's own single-block fluid tank, as well as TE fluiducts, all have gradual reduction in transparency (and never go opaque like in pipes/multiblocks). Mekanism's own mechanical pipes do have progressive filling but go completely opaque when at capacity. I've tested to be sure it's still Mekanism steam and not being auto-converted to IC2 (which is the only other steam available in buckets), but has something else changed that might affect how it's rendering? That, too, was working properly before pack v1.14.

I can't tell if it's possibly becoming NuclearCraft steam that's being converted into Mekanism when it's bucketed - there's no buckets or cells for NuclearCraft steam and I don't know the mod enough (i.e. at all) to test on my own on short notice, even in creative. But that's the only potential gotcha I can think of on my own.

If you think this would be useful to the Mekanism crew, by all means - I'm just used to a response of "are you playing in a modpack? Talk to the pack dev".

**Comment by NillerMedDild** [comment]
Good point, it's probably on my end. NuclearCraft may have steam, I'll look into it :)

**Comment by NillerMedDild** [comment]
Update: NuclearCraft does add steam, and my FPS does drop by 15-30 when placing it down. 
I haven't had time to investigate further.

**Comment by NillerMedDild** [comment]
Shurhaian - Do you know if the issue is still there?

**Comment by Shurhaian** [comment]
I hadn't poked it for a while, but I just made a test world and put down a turbine. Even without using opaque blocks, it seems to be working better - the turbine doesn't instantly drag down a test world in which it's the only device running like it used to. As nobody else seems to have weighed in, I'll go ahead and close it; sorry for not staying on top of it on my own!
