### ISSUE TITLE
Zoom not working on MiniMap (by JourneyMap)

### ISSUE THREAD

**Issue by russfort** [NillerMedDild/Enigmatica2#204]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Normally I can Zoom the MiniMap in/out with =/- keys.  This is not working in the Enigmatica 2 Expert pack.  I tried to look for keybinding conflicts and found none.  I assumed this was a JourneyMap issue, but my searches are not turning up anyone else with the issue.

**Modpack version (Do not use "latest")**
1.46

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
The keybindings aren't bound, you will have to bind them yourself.
