### ISSUE TITLE
Using Thermal Expansion Tanks with Fluid Nodes Extra utilities causes server crash.

### ISSUE THREAD

**Issue by GldnSabre74** [NillerMedDild/Enigmatica2#205]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Attached a Thermal Expansion Portable tank to a fluid node and now I get server crash on startup.

**Modpack version (Do not use "latest")**
Version 1.54
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/2711137/latest.log)
[crash-2018-12-26_20.11.59-server.txt](https://github.com/NillerMedDild/Enigmatica2/files/2711138/crash-2018-12-26_20.11.59-server.txt)

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
According to the crash report, you placed the Transfer Node on a Chisels & Bits Fluid Tank, is that correct?

**Comment by GldnSabre74** [comment]
That worked without issue but yes it was connected that way, however I attached a thermal expansion portable tank to the pipe to fill it and that is when the crash happened

**Comment by NillerMedDild** [comment]
Can you replicate it without the C&B Fluid Tank?

**Comment by GldnSabre74** [comment]
I will when I get home

**Comment by redgoblin88** [comment]
![2018-12-27_18 37 16](https://user-images.githubusercontent.com/13396472/50490715-77f2e780-0a06-11e9-9310-7bd5521d4fc9.png)

i have tried to replicate this crash and have had no luck, i even tried doing it accross a chunk edge which is where the most likely area of crashes happen (indicated by the yellow grid)

furthermore as you can see i tried all side of the pipe and even a chisels and bits tank (which doesnt accept any fluid unless its under half full it seems?)

could you provide more context such as the specific "design" you had for the transfer node fluid pipes, what fluid storage devices were attached and if any upgrades were used (for the node and anything on the pipes like if the tanks had kits?)

**Comment by NillerMedDild** [comment]
It may only affect servers in that case.

**Comment by NillerMedDild** [comment]
Thank you both for testing for me, I really appreciate it :)
