### ISSUE TITLE
Always fails to initialize 

### ISSUE THREAD

**Issue by Swagnificence** [NillerMedDild/Enigmatica2#209]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
[crash-2018-12-28_17.28.31-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/2715901/crash-2018-12-28_17.28.31-client.txt)

**Modpack version (Do not use "latest")**
1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by Gimpler** [comment]
Allocate more RAM to the pack, at least 6gb is required.

**Comment by Gimpler** [comment]
twitch launcher > your username > settings > minecraft > scroll down to java arguments, add -Xmx6G
