### ISSUE TITLE
Crash on loading save

### ISSUE THREAD

**Issue by Swagnificence** [NillerMedDild/Enigmatica2#211]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Crash on loading world

**Modpack version (Do not use "latest")**
1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

If i try to reload a world I made the game crashes while trying to load the game

**Comment by NillerMedDild** [comment]
I'm going to need your crash report...

**Comment by Swagnificence** [comment]
It didn't give a report, does it store it somewhere?

**Comment by NillerMedDild** [comment]
In the crash-reports folder of your instance.

**Comment by NillerMedDild** [comment]
The default path for Enigmatica 2: Expert downloaded through the Twitch launcher is `C:\Users\<YourUserNameHere>\Documents\Curse\Minecraft\Instances\Enigmatica 2 Expert\crash-reports`

**Comment by NillerMedDild** [comment]
The default path for Enigmatica 2: Expert downloaded through the Twitch launcher is `C:\Users\<YourUserNameHere>\Documents\Curse\Minecraft\Instances\Enigmatica 2 Expert\crash-reports`

**Comment by Swagnificence** [comment]
![folder](https://user-images.githubusercontent.com/46231382/50541595-adb2e000-0b6e-11e9-995a-5331649862b2.jpg)
Is it within another folder here or is it just not there? Sorry if I'm being blind or something

**Comment by NillerMedDild** [comment]
Wait err.. is this issue for Enigmatica 2 or Enigmatica 2: Expert?

**Comment by Swagnificence** [comment]
expert, i just realized where i was sorry, lol, should i repost this there?

**Comment by NillerMedDild** [comment]
Nah that's alright. It would appear you didn't actually crash. Did the window just hang? Your `latest` log file from the `logs` folder would be helpful :)

**Comment by Swagnificence** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/2716682/latest.log)
no it crashes to the minecraft launcher each time

**Comment by NillerMedDild** [comment]
Delete this file: `C:\Users\Morgan\Documents\Curse\Minecraft\Instances\Enigmatica 2 Expert\saves\New World\advRocketry\planetDefs.xml`

**Comment by Swagnificence** [comment]
thank you for helping

**Comment by NillerMedDild** [comment]
Sure thing.
