### ISSUE TITLE
No crafting recipes for light gray alabaster

### ISSUE THREAD

**Issue by hAmpzter** [NillerMedDild/Enigmatica2#222]
**Is your feature request related to a problem? Please describe.**
Yeah, I'm not able to craft light gray alabaster!

**Describe the solution you'd like**
A possibility to create light gray alabaster. Preferably by combinding light gray dye in the middle and with any alabaster around it as with the other versions of alabaster.

**Additional context**
Nothing needed.

**Comment by NillerMedDild** [comment]
Wow, I let the mod author know about this issue in March 2018, I'm impressed that he hasn't fixed it himself.

Anyhow, thanks for the report, I'll fix it :)
