### ISSUE TITLE
Remove EnderIO Vanilla Recipes

### ISSUE THREAD

**Issue by lucidobservor** [NillerMedDild/Enigmatica2#223]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Upon updating to version 1.20 of the pack, I noticed a recipe for 8 logs -> 4 chests, something which completely negates the need for the pack's more complicated recipes. Digging into the issue, I noticed this recipe seemed to come from EnderIO in the form of an xml recipe. Also present in that xml file (config/enderio/recipes/misc.xml) were recipes for two logs -> 16 sticks, and 5 iron ingots + 2 logs -> 1 hopper, which are also a problem. 

The recipes added have no names, and so cannot be removed with CraftTweaker. They should be removed by following the directions in the config/enderio/recipes/misc.xml file.

**Modpack version (Do not use "latest")**

1.20

**Logs**

n/a

**Screenshots**

n/a

**Additional context**

n/a

**Comment by NillerMedDild** [comment]
Although they appear in JEI, they don't actually work.

But, thanks for the report and fix!
