### ISSUE TITLE
RFTools Dimensions and JourneyMap - missing dimension info

### ISSUE THREAD

**Issue by talonb** [NillerMedDild/Enigmatica2#225]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
RFTools fails to send dimension information to Journeymap while in a dimension. Console output floods and grinds the game to a halt.

**Modpack version (Do not use "latest")**
1.49

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

I cannot upload the entire latest.log because they are between 600 and 900 MB
Here's a small excerpt: https://hastebin.com/eferutazid.rb
I can find a way to post the whole latest.log if you need it.

**Screenshots**

**Additional context**

This is happening on a server and other players are reporting bloated logfiles too.

**Comment by talonb** [comment]
I've posted this in the wrong forum, we are playing Enigmatica 2 Expert

**Comment by NillerMedDild** [comment]
It has been reported here: https://github.com/McJtyMods/RFToolsDimensions/issues/244
I will try to reproduce it.
