### ISSUE TITLE
Regular Furnace Lost Items

### ISSUE THREAD

**Issue by jhagrid77** [NillerMedDild/Enigmatica2#226]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

I had three furnaces, each with an opening on top, with one stack of mini coal and grout in each. It started to smelt however all items disappeared as soon as they did.

**Modpack version (Do not use "latest")**

1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

https://gist.github.com/jhagrid77/90176950ddea7dd5ed852cb799a37ef7

**Screenshots**

![2019-01-04_18 20 53](https://user-images.githubusercontent.com/15268715/50715983-8b790080-104d-11e9-97ba-6b423e24be0b.png)

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Cannot reproduce in 1.56
