### ISSUE TITLE
Better Quests Book Often Become Blanked In Server

### ISSUE THREAD

**Issue by SunnyFarmDay** [NillerMedDild/Enigmatica2#227]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

I have been experiencing a number of time which the better quest book become blanked. I have to reload to the default to fix it all the time. Is it some kind of bug that it turns blank so often in server? Whenever I come back to the server next day, it become blank as the image attached.

**Modpack version (Do not use "latest")**

Enigmatica 2 1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

![image](https://user-images.githubusercontent.com/46389143/50718896-8197e180-10cf-11e9-9f04-8572b69c1038.png)

**Additional context**

**Comment by NillerMedDild** [comment]
Yep, that happens :/ there's nothing you can do other than keep plenty of backups to restore the quest progress from.
