### ISSUE TITLE
Mekanism Personal Chest Duplication Error

### ISSUE THREAD

**Issue by SunnyFarmDay** [NillerMedDild/Enigmatica2#228]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

I have tried Mekanism Personal Chest in server and I made two of them. There is a bug which when I put both of them in my inventory, I open Personal Chest (A) in my hotbar, e.g. slot 3. Then, I hover my mouse to another Personal Chest (B) I got and tap 3, which is putting the item to hotbar 3 and exchange each others' slot. Afterward I closed the chest and open another Personal Chest (B), the item inside have become the same as Personal Chest (A). 

**Modpack version (Do not use "latest")**

Enigmatica 2 1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Dupes caused by moving things like that cannot be solved, as far as I know
