### ISSUE TITLE
Scroll wheel transfer to ExtraUtils2 Crusher deletes items 

### ISSUE THREAD

**Issue by matthew117** [NillerMedDild/Enigmatica2#232]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

When using scroll wheel transfer to move items into the ExtraUtils2 Crusher, one item is moved into the Crusher but subsequent items from the same type/stack are deleted.

To reproduce: open the Crusher, hover over a stack of bones and scroll the mouse wheel. One bone will begin processing but others will be deleted.

**Modpack version (Do not use "latest")**

1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report :)

**Comment by matthew117** [comment]
Seems to happen with a few different machines https://github.com/rwtema/Extra-Utilities-2-Source/issues/235 it might be worth downgrading the version of XU2 in the pack until the issue is resolved

**Comment by NillerMedDild** [comment]
Hmm, I'll give it a shot.
