### ISSUE TITLE
Questbook, visual glitch

### ISSUE THREAD

**Issue by M3wM3w** [NillerMedDild/Enigmatica2#233]
**Issue Description**
Strange visual glitch in the questbook.
Looks like energy bars of the items?

**Modpack version (Do not use "latest")**
1.54

**Screenshots**
![image](https://user-images.githubusercontent.com/28768641/50741239-9a50e600-11fa-11e9-9c97-3da8ac525de0.png)

**Comment by NillerMedDild** [comment]
That is odd o_o Do you have Optifine installed?

**Comment by M3wM3w** [comment]
Only just now installed the (amazing) modpack via twitch launcher.
No options were changed, no additional plugins or mods.
Created a new world and just saw this in the questbook.

**Comment by NillerMedDild** [comment]
Hm, I do see it in my questbook aswell, only much smaller. I'm guessing the model is messing up because it's 3D? Frankly, I don't know, and it would take quite a bit of effort to find the source of the issue. If it's really bothering you, I'll give it a shot, otherwise we can call it a feature :D

**Comment by NillerMedDild** [comment]
I feel like that was sarcasm? xD

**Comment by M3wM3w** [comment]
:D :D :D
