### ISSUE TITLE
Crash when starting Minecraft

### ISSUE THREAD

**Issue by Dertin95** [NillerMedDild/Enigmatica2#234]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Game Freeze/Crash on Ender IO - Dark Steel Upgrades

**Modpack version (Do not use "latest")**
1.54

**Logs**

[crash-2019-01-06_22.09.15-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/2730892/crash-2019-01-06_22.09.15-client.txt)

**Screenshots**

**Additional context**

sometimes the game just freeze at this point, sometimes it crashes.
the loading bars as follows:

Loading - Finishing up
6/7
Registering plugins - crazypants.enderio.base.integration.jei.jeiPlugin
68/98
Ender IO - Dark Steel Upgrades
1/7

Already tryed going back 1 version, same issue.
also already changed the starting mode to jar launcher, same issue

**Comment by NillerMedDild** [comment]
Needs more RAM - Answered in full in Discord.
