### ISSUE TITLE
Cooking For Blockheads' Cooking table doesn't recognize damaged knives as usable in crafting

### ISSUE THREAD

**Issue by BadsyEdgecat** [NillerMedDild/Enigmatica2#24]
Sorry for so many reports.

**Comment by NillerMedDild** [comment]
That's alright, but don't delete the issue template, follow it.

**Comment by NillerMedDild** [comment]
https://github.com/blay09/CookingForBlockheads/issues/283

**Comment by NillerMedDild** [comment]
Fixed by the mod dev.
