### ISSUE TITLE
Can't click complete on the thaumic tinker quests

### ISSUE THREAD

**Issue by FunkyMoneyMan** [NillerMedDild/Enigmatica2#243]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
When clicking "Complete" on any thaumic tinker quest it just sits there at "completing" and does nothing after that. If you close the book and open it up again then the button to click complete is there again and when selected just sits there.

**Modpack version (Do not use "latest")**
1.49

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**
https://i.gyazo.com/9d7efedbe9306bf4ee1e34873cc7abb1.gif

**Additional context**

**Comment by NillerMedDild** [comment]
You'll have to use commands to complete Thaumic Tinkerer research unfortunately, it doesn't work yet.
