### ISSUE TITLE
Backpacks JEI Integration

### ISSUE THREAD

**Issue by rhaejr** [NillerMedDild/Enigmatica2#244]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Many recipes in JEI do not craft correctly. One was the dragon command staff. Also the backpack that the quest book tell you to make doesn't have the correct recipe in JEI. And I wouldn't doubt if there were many more recipe conflicts. 

**Modpack version (Do not use "latest")**
v1.50a

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

![2019-01-08_21 20 35](https://user-images.githubusercontent.com/8333219/50874890-69ec8180-138b-11e9-8d6d-c5630e4e85ee.png)
![2019-01-08_21 20 41](https://user-images.githubusercontent.com/8333219/50874892-71ac2600-138b-11e9-8818-f9ebb5e23cb8.png)

**Additional context**

**Comment by NillerMedDild** [comment]
It's not broken, it's just not displayed in JEI.

**Comment by rhaejr** [comment]
The golden lasso recipe doesn't work even tho it is in JEI.

**Comment by NillerMedDild** [comment]
Did you have 8 levels, and crafted it in a vanilla or Tinkers crafting table?
