### ISSUE TITLE
Minecolonies bugs

### ISSUE THREAD

**Issue by billyty08** [NillerMedDild/Enigmatica2#246]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
After recent update on loading I get-"Error: error while applying actions" and all the minecolonies custom blocks like timberframed rails and shingles are removed from built buildings and JEI along with the building tool 

**Modpack version (Do not use "latest")**
1.55a

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**
![2019-01-09_10 08 58](https://user-images.githubusercontent.com/39845047/50912225-42cb9980-13f7-11e9-8611-f0784c30cd06.png)
![2019-01-09_10 14 44](https://user-images.githubusercontent.com/39845047/50912286-6d1d5700-13f7-11e9-8b64-da9758c8f3be.png)
Holes in builders hut used to be the custom timber blocks

**Additional context**

**Comment by NillerMedDild** [comment]
It appears to be a bug, https://github.com/ldtteam/minecolonies/issues/3134

**Comment by billyty08** [comment]
No worries. I reverted back, started rebuild and went into creative to give builder what he needs instantly and he fixed everything except the surrounding dirt he removed. So may be a great idea to put out a hotfix reverting minecolonies until they fix it for people already started

**Comment by NillerMedDild** [comment]
Good point. Which version did you downgrade to?

**Comment by billyty08** [comment]
minecolonies 1.12.2-0.10.68 release on 12/09/2018
