### ISSUE TITLE
crafting crash

### ISSUE THREAD

**Issue by jayjones87** [NillerMedDild/Enigmatica2#247]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

crash when crafting regardless of which table i use, not constant but about every 4-5 crafts apart, started 
after crafting the advanced solar panel from mekanism 

**Modpack version (Do not use "latest")**

Enigmatica 2 expert 1.50a

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

https://pastebin.com/aaaDNWZB

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Duplicate of #218 - Use a regular crafting table :)
