### ISSUE TITLE
Item Rack from Tinker's Construct

### ISSUE THREAD

**Issue by kleshas** [NillerMedDild/Enigmatica2#248]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Item rack from TC doesn't work.  JEI says 2 slabs in middle row, organized next to each other.  When done, you get a wooden plank

**Modpack version (Do not use "latest")**
1.55a

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
