### ISSUE TITLE
WirelessCharger mod missing from 1.55a

### ISSUE THREAD

**Issue by Selbram** [NillerMedDild/Enigmatica2#249]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The mod WirelessCharger-1.3.0 from version 1.54 is not in 1.55a. No mention of it being removed in the changelog.

**Modpack version (Do not use "latest")**
1.55a

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Woops! I was no longer allowed to include it, as it is not on CurseForge, so it had to go unfortunately.
