### ISSUE TITLE
Just Enough Energistics missing from 1.55a

### ISSUE THREAD

**Issue by Selbram** [NillerMedDild/Enigmatica2#250]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The mod Just Enough Energistics is mentioned in the changelog as being added and does not appear in the pack. (client or server download)

**Modpack version (Do not use "latest")**
1.55a

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Another oversight of mine - It is not compatible with our current JEI version, so I couldn't add it just yet.
