### ISSUE TITLE
severe problem during mod loading

### ISSUE THREAD

**Issue by StephanieUpland** [NillerMedDild/Enigmatica2#251]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
Tried starting up for the first time through twitch, keep getting the following message:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

**Modpack Version**
1.55a

**Additional Context**

crash report: https://pastebin.com/zLSdCCiw

**Comment by Selbram** [comment]
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
You need to assign more memory to server.

**Comment by NillerMedDild** [comment]
The recommended amount of RAM to allocate for this pack is 6GB.
