### ISSUE TITLE
Issue: Duplicate Quests

### ISSUE THREAD

**Issue by LinkTheLinker** [NillerMedDild/Enigmatica2#253]
**Question or Issue**
I found an issue in the "Mekanism Part 2" section of the quests. The quest called "Too Much Pressure" is listed twice within the questline.

**Modpack Version**
Enigmatica 2 - 1.55a

**Additional Context**
No additional Context

**Comment by NillerMedDild** [comment]
I see, thanks!

**Comment by NillerMedDild** [comment]
They're not duplicate.
