### ISSUE TITLE
Tool Forge JEI

### ISSUE THREAD

**Issue by zdragonkillah** [NillerMedDild/Enigmatica2#257]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The block 'tool forge block of iron', is not listed in JEI, only 'tool forge block of steeleaf'.

**Modpack version (Do not use "latest")**
1.55a

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

https://imgur.com/a/5RRzPuC
**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I was unable to fix this.
