### ISSUE TITLE
crash to desktop when I open inventory

### ISSUE THREAD

**Issue by moordoom** [NillerMedDild/Enigmatica2#258]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Since Tuesdays update, I crash to desktop when opening inventory or storage

**Modpack version (Do not use "latest")**
1.55a

Java version 8 - 191 - B12

**Logs**
moordoom / gist:2bcd5aded805abe4f18d73bc697db6bb

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Please fix your link.

**Comment by moordoom** [comment]
[crash-2019-01-12_18.49.01-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/2757890/crash-2019-01-12_18.49.01-client.txt)

**Comment by NillerMedDild** [comment]
Why did you close the issue?

**Comment by moordoom** [comment]
I did not close the issue. I just added a link for my log. I still have the issue. Also I apparently have an issue with Chrome too.
You can reopen it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by NillerMedDild** [comment]
Please change your launch method from Native to Jar in the Twitch launcher's Minecraft settings, and see if that resolves it :)

**Comment by moordoom** [comment]
another crash. Game would not open to select screen in Jar.
[crash-2019-01-15_22.35.37-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/2766771/crash-2019-01-15_22.35.37-client.txt)

**Comment by NillerMedDild** [comment]
Looks like your graphic drivers are outdated. Closing since this isn't modpack related.

**Comment by moordoom** [comment]
Have Nvidia 417.71 and I installed those on Tuesday. And before that 417.35 from back in December.
Still the same issue.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by NillerMedDild** [comment]
That's... odd. Did you pick a Java version from the dropdown? Can I have a screenshot of the settings?

**Comment by moordoom** [comment]
I think I have it narrowed down to an Item in my inventory
I was able to dump my inventory into a chest and was able to play with no issues until I opened the chest I dumped everything into. I will see if I can figure out which Item.
I think it may have been a quest reward and it causing a memory leak with that Item.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by moordoom** [comment]
Ok, was able to get in the container started getting InventoryTweak errors when I tried sorting the container.
The 5 single ingots I got has a quest reward in a Mekanism quest ‘Too Many Variations’ which was 5 different types of Copper Ingots.
But I think the one causing the issue is the Mekanism Steel ingot in Row 7, Column 3.
I was able to get the ingot in the trash can, and My error and crashes are gone.
[cid:image005.png@01D4B03E.C6016C70]
[cid:image006.png@01D4B03E.C6016C70]
[cid:image009.png@01D4B03E.C6016C70]


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by moordoom** [comment]
Nope. That was not it. When trying to clean up that container it crashed again. Will continue to look. The block without a icon was a quest reward and the unopen loot chest was a reward for the a mechanism quest as well.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: James Bates <moordoom@hotmail.com>
Sent: Saturday, January 19, 2019 9:34:36 PM
To: NillerMedDild/Enigmatica2; NillerMedDild/Enigmatica2
Cc: State change
Subject: RE: [NillerMedDild/Enigmatica2] crash to desktop when I open inventory (#258)

Ok, was able to get in the container started getting InventoryTweak errors when I tried sorting the container.
The 5 single ingots I got has a quest reward in a Mekanism quest ‘Too Many Variations’ which was 5 different types of Copper Ingots.
But I think the one causing the issue is the Mekanism Steel ingot in Row 7, Column 3.
I was able to get the ingot in the trash can, and My error and crashes are gone.
[cid:image005.png@01D4B03E.C6016C70]
[cid:image006.png@01D4B03E.C6016C70]
[cid:image009.png@01D4B03E.C6016C70]


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by moordoom** [comment]
Whatever the circled Item is, I was able to punch the container, move the items to another container, then pickup this item and ‘Q’ drop it in a lava and fix my issue.
I do not know where I got this Item, but believe it was from a quest and the update from two weeks ago broke it.


[cid:image003.png@01D4B049.2D1FFFC0], drop i

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: James Bates <moordoom@hotmail.com>
Sent: Saturday, January 19, 2019 9:40:35 PM
To: NillerMedDild/Enigmatica2; NillerMedDild/Enigmatica2
Cc: State change
Subject: RE: [NillerMedDild/Enigmatica2] crash to desktop when I open inventory (#258)

Nope. That was not it. When trying to clean up that container it crashed again. Will continue to look. The block without a icon was a quest reward and the unopen loot chest was a reward for the a mechanism quest as well.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: James Bates <moordoom@hotmail.com>
Sent: Saturday, January 19, 2019 9:34:36 PM
To: NillerMedDild/Enigmatica2; NillerMedDild/Enigmatica2
Cc: State change
Subject: RE: [NillerMedDild/Enigmatica2] crash to desktop when I open inventory (#258)

Ok, was able to get in the container started getting InventoryTweak errors when I tried sorting the container.
The 5 single ingots I got has a quest reward in a Mekanism quest ‘Too Many Variations’ which was 5 different types of Copper Ingots.
But I think the one causing the issue is the Mekanism Steel ingot in Row 7, Column 3.
I was able to get the ingot in the trash can, and My error and crashes are gone.
[cid:image005.png@01D4B03E.C6016C70]
[cid:image006.png@01D4B03E.C6016C70]
[cid:image009.png@01D4B03E.C6016C70]


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by NillerMedDild** [comment]
Alright then, glad you fixed it.
