### ISSUE TITLE
Any plans for Buildcraft and Railcraft in the pack?

### ISSUE THREAD

**Issue by Adamvg** [NillerMedDild/Enigmatica2#263]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
Are there any plans for Buildcraft or Railcraft to be added? Both are updated and great mods.
Cheers and nice work on the brilliant modpack.

**Modpack Version**
N/A

**Additional Context**
N/A

**Comment by NillerMedDild** [comment]
Thank you! :)

I'm afraid not, the pack is very hard to run as it is, more content mods would make it unplayable for a lot of people.

**Comment by NillerMedDild** [comment]
Cool! I wish I could add them, I really wanna build a train network :P
