### ISSUE TITLE
Flying is not enabled on this server

### ISSUE THREAD

**Issue by npo6ka** [NillerMedDild/Enigmatica2#264]
**Issue Description**
I play with friends on the server and we are constantly kicked with it with the following error: 
[00:17:37] [Server thread/WARN] [net.minecraft.network.NetHandlerPlayServer]: sadPIv was kicked for floating too long!
[00:17:37] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: sadPIv lost connection: Flying is not enabled on this server.

At the same time, the parameter allow-flight = true in the server.properties file.

**Modpack version (Do not use "latest")**
1.50a

**Comment by NillerMedDild** [comment]
Which flight method did you use? May I have a copy of the server.properties?

**Comment by npo6ka** [comment]
The player is thrown from the server when the player climbs on top of the assembled rocket from the advanced rocketry mod or when using the air charm.

file server.properties:

#Minecraft server properties
#Mon Jan 14 23:51:02 MSK 2019
spawn-protection=0
max-tick-time=60000
generator-settings=
force-gamemode=false
allow-nether=true
gamemode=0
broadcast-console-to-ops=true
enable-query=false
player-idle-timeout=0
difficulty=3
spawn-monsters=true
op-permission-level=4
pvp=false
snooper-enabled=false 
level-type=BIOMESOP 
hardcore=false
enable-command-block=false
max-players=20
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
server-port=33333
server-ip=0.0.0.0
spawn-npcs=true
allow-flight=true 
level-name=world
view-distance=8
resource-pack=
spawn-animals=true
white-list=false
generate-structures=true
online-mode=true
max-build-height=256
level-seed=
prevent-proxy-connections=false
motd=Enigmatica 2\: Expert 
enable-rcon=false

**Comment by NillerMedDild** [comment]
Possibly silly question, but have you tried restarting the server?

**Comment by npo6ka** [comment]
And more than once. Already updated the server to 1.51, but the problem persists.

**Comment by npo6ka** [comment]
Sorry, I wrote a bug in the wrong modpack. I have a modpack Enigmatica2Expert.

**Comment by npo6ka** [comment]
original string:  allow-flight=true
No space.

**Comment by NillerMedDild** [comment]
Well damn, I do not know then.

**Comment by NillerMedDild** [comment]
Some people recommend adding the mod `GottaGoFast`.

**Comment by npo6ka** [comment]
I'm fixed it.

**Comment by npo6ka** [comment]
Created a new server.properties file and right now everything works fine.
