### ISSUE TITLE
Knightslime Quest Issue

### ISSUE THREAD

**Issue by EnderT5** [NillerMedDild/Enigmatica2#266]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

When I collected 8 Congealed Purple Slime Block, a message telling me I completed Knightslime quest appeared but I can't claim the reward of quest because quest isn't added to the quest book.

**Modpack version (Do not use "latest")**

1.56

**Logs**

Not Needed

**Screenshots**

Not Needed

**Additional context**

Not Needed

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Found it \o/
