### ISSUE TITLE
Bibliocraft chest

### ISSUE THREAD

**Issue by JustLiam040** [NillerMedDild/Enigmatica2#267]
This isnt really an issue, more of a question (i was unsure as to where i should post this), the recipes for chests have been changed to be slightly harder to get, however the framed chests from bibliocraft are still insanrly easy to craft, is this intentional?

**Comment by NillerMedDild** [comment]
Asking questions here is just fine :)

It is intentional, it's a little hidden treat for the few who know of them :P
