### ISSUE TITLE
Recipe Conflict between Builders Wands and Mincolonies Building Tools/Wands

### ISSUE THREAD

**Issue by Creat0n** [NillerMedDild/Enigmatica2#269]
**Issue Description**
When trying to make a Builders wand (Stone Wand and Iron Wand) they get replaced by MineColonies Wands in the Crafting grid

**Modpack version (Do not use "latest")**
1.56

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll get that fixed. In the meantime, you can use the Forestry Workbench to craft the Builder's Wands.
