### ISSUE TITLE
Issue With Optifine?

### ISSUE THREAD

**Issue by BadsyEdgecat** [NillerMedDild/Enigmatica2#27]
#### Issue Description: 
When I try to add Optifine (because chisels and bits is causing fps issues when it hasn't in other packs), when I try to load in a world, it sits for a while in an empty void and then kicks me to the multiplayer server menu with a message about something about a closed channel. Sorry for putting this here despite it being with a mod i tried to add but i genuinely have no clue where else to put it, and the people in the MPD server aren't being very helpful.

#### Modpack version (Do not use "latest"):
V1.36

#### Crash Report
I do not have a log because I can't figure out how to open any logs in the "logs" folder.

**Comment by NillerMedDild** [comment]
I need the exact message you get after getting kicked from the server, please. But I'm pretty sure you've installed Optifine incorrectly, as a server would never kick you for having it.

**Comment by BadsyEdgecat** [comment]
The issue is I got kicked from my own singleplayer world. Unfortunately, the second time i tried it, it just dropped me out of the world without a message.

**Comment by NillerMedDild** [comment]
Does it still happen with Optifine removed?

**Comment by BadsyEdgecat** [comment]
no, but idk how adding optifine would actually cause an issue, due to the fact that all i did was put it in the mods folder

**Comment by NillerMedDild** [comment]
Did you use OptiFine_1.12.2_HD_U_D3?

**Comment by NillerMedDild** [comment]
Closed due to lack of response.
