### ISSUE TITLE
Game crashes when trying to view recipe in JEI

### ISSUE THREAD

**Issue by lucascahill** [NillerMedDild/Enigmatica2#270]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Game crashes to desktop after I open inventory and either press "U" on item to see it's uses, "r" to see recipes, or click on an item in JEI.  Below is what is displayed after crash:

"The game crashed whilst rendering screen
The game crashed whilst rendering screen
Error: java.lang.ArithmeticException: / by zero"

**Modpack version (Do not use "latest")**

version 1.57

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github
[crash-2019-01-17_23.51.52-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/2771767/crash-2019-01-17_23.51.52-client.txt)
.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by lucascahill** [comment]
I did some testing on my own this evening after reinstalling the pack.  Seems like sphax resource pack is the culprit.  Don't know why other than the game runs with no issues when it's disabled.

**Comment by NillerMedDild** [comment]
That's odd. It may be running out of RAM because of the resource pack.
