### ISSUE TITLE
Existing Item Filter from EnderIO broken

### ISSUE THREAD

**Issue by timminkov** [NillerMedDild/Enigmatica2#271]
**Issue Description**
Clear button on the EnderIO existing item filter doesn't work.

**Modpack version (Do not use "latest")**
1.57

**Logs**
Nothing in the server or console.

**Screenshots**
My inventory (also tried with all this in a chest)
![image](https://user-images.githubusercontent.com/3485060/51374300-7a9da580-1ab7-11e9-9b7b-e9c83421a781.png)

What the snapshot looks like (can't change it)
![image](https://user-images.githubusercontent.com/3485060/51374337-94d78380-1ab7-11e9-93b7-5ff0447d235f.png)

**Additional context**
Tried both iron chests and storage drawers. Clear button doesn't do anything.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by timminkov** [comment]
For a workaround, you can clear by crafting it.

**Comment by NillerMedDild** [comment]
It does work, you just need to close the GUI and reopen it. I did update EnderCore, so that might've fixed it.
