### ISSUE TITLE
Crash on startup / Stuck on EnderIO

### ISSUE THREAD

**Issue by ConnerCarnahan** [NillerMedDild/Enigmatica2#273]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Question or Issue**
On initial mod loading the launcher gets stuck at: 
"Loading - Finishing up 6/7 
Registering plugins - crazypants.enderio.base.integration...
EnderIO - Dark Steel Upgrades"
Indefinitely , or crashes after 15-30 minutes

The Crash report (I hope I upload this correctly)
----------------------------------------------------------------------
[crash-2019-01-20_12.30.51-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/2776999/crash-2019-01-20_12.30.51-client.txt)

The Error description from the minecraft launcher : "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)"

**Modpack Version**
v1.57, 1.56

**Additional Context**
I'm using the twitch app to download and run the mod (it has Minecraft 1.12.2 with forge 14.23.5.2781)
I have tried allocating different amounts of ram (2,6,5, and 12 GB)
I have tried reloading the mod and using the last version.
My computer has 32 GB of ram available, and an Intel i7 - 4790K CPU

**Comment by NillerMedDild** [comment]
You're running out of memory during loadup, I recommend trying 7-8GB :)
Please let me know if it works.

**Comment by ConnerCarnahan** [comment]
Hell yeah! It worked (I had changed the ram in the wrong place)

Thank you so much!

**Comment by NillerMedDild** [comment]
Ah, woops :P my pleasure!
