### ISSUE TITLE
Issues With Pam's and Thaumcraft Aspects

### ISSUE THREAD

**Issue by BadsyEdgecat** [NillerMedDild/Enigmatica2#28]
#### Issue Description:
Its not too big of a deal, but Pam's Foods have aspects that shouldn't actually logically come from anything, For example, all of the Jelly Sandwiches have Metallum, despite the fact that none of the ingredients used have metallum and the sandwiches themselves certainly aren't metal.

#### Modpack version (Do not use "latest")
1.36
#### Crash Report

[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
I can't modify the aspects on items at this time, but I'll keep this open to remind myself. Thanks for the report :)

**Comment by BadsyEdgecat** [comment]
speaking of food related issues, a small one is. could twilight forest venison be

**Comment by BadsyEdgecat** [comment]
shit i must've accidentally hit enter too fast. i meant if there was some way to make twilight forest venison be usable in pam's harvestcraft recipes.

**Comment by NillerMedDild** [comment]
I just added it. In the future, I'd prefer that you make a new issue for a seperate enhancement/bug report, it's a lot easier for me to keep track of.

**Comment by NillerMedDild** [comment]
The issue has been reported to Pam's.
