### ISSUE TITLE
Atomic Disassembler(Mekanism) on a Wisdom Wood Log (Wizardry)Tree causes server crash

### ISSUE THREAD

**Issue by thejohnnyxu** [NillerMedDild/Enigmatica2#280]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Using the Atomic Disassembler(Mekanism) on a Wisdom Wood Log (Wizardry)Tree causes server crash

**Modpack version (Do not use "latest")**
1.57

**Logs**
If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).
https://gist.github.com/thejohnnyxu/5ce411d3ebc2b306146cbc9e0d9a4131
https://gist.github.com/thejohnnyxu/e7511eb39aea54553966b9276b9f56b1

**Screenshots**
![2019-01-22_00 21 10](https://user-images.githubusercontent.com/1590657/51518665-ecd5f900-1ddb-11e9-9194-c4dd39180c8a.png)

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report. I need the crash log.

**Comment by thejohnnyxu** [comment]
Here are the two logs.
[crash-2019-01-22_00.14.49-server.txt](https://github.com/NillerMedDild/Enigmatica2/files/2784864/crash-2019-01-22_00.14.49-server.txt)
[crash-2019-01-22_00.07.20-server.txt](https://github.com/NillerMedDild/Enigmatica2/files/2784865/crash-2019-01-22_00.07.20-server.txt)

**Comment by NillerMedDild** [comment]
Seems it has been treated before: https://github.com/TeamWizardry/Wizardry/issues/186

**Comment by NillerMedDild** [comment]
They're looking into pushing out an update :)
