### ISSUE TITLE
Client side crash to desktop on login on private server

### ISSUE THREAD

**Issue by Postension** [NillerMedDild/Enigmatica2#283]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

I am crashing to desktop on my server upon login. I am in base near advanced rocketry machines.

**Modpack version (Do not use "latest")**

1.57

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).
[crash-2019-01-22_22.20.20-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/2785677/crash-2019-01-22_22.20.20-client.txt)

**Screenshots**

**Additional context**

Other players on server are not having same problem

**Comment by NillerMedDild** [comment]
You need to either delete the `options.txt` and `knownkeys.txt` file from your instance, or just reinstall the modpack :) Something has gone wrong when registering your keybindings.

**Comment by NillerMedDild** [comment]
That really means a lot to me, thank you! Stories like yours is what keeps me going :)
