### ISSUE TITLE
Placing ArchitectureCraft blocks inside on a /dank/null causes client crash

### ISSUE THREAD

**Issue by thejohnnyxu** [NillerMedDild/Enigmatica2#286]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Placing Blocks created from ArchitectureCraft inside of a /dank/null crashes the local client.

**Modpack version (Do not use "latest")**
1.57

**Logs**
If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).
https://gist.github.com/thejohnnyxu/081acf88cac942a80594f7b508b7d5c2

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, it has been reported to the appropriate mod developer :)
