### ISSUE TITLE
Issue with Chisel and Quark: yet another small, not super important issue.

### ISSUE THREAD

**Issue by BadsyEdgecat** [NillerMedDild/Enigmatica2#29]
#### Issue Description:
Chisel's Basalt cannot be turned into quark's regular or polished basalt, yet it can be made into quark's basalt bricks. This is an issue because i want to use Quark's Polished Basalt for a build I'm working on, and having to craft Quark Basalt with coal and cobblestone is not a very enjoyable way to get it when it COULD be possible for me to just use Chisel's Basalt.

#### Modpack version (Do not use "latest")
V1.36

**Comment by NillerMedDild** [comment]
Fixed!
