### ISSUE TITLE
Mod Request "ToroHUD"

### ISSUE THREAD

**Issue by SirHaxe** [NillerMedDild/Enigmatica2#298]
**Is your feature request related to a problem? Please describe.**
the mod inside, toro health isnt capable of black/whitelisting entitys, toroHUD, a fork, can! 

**Describe the solution you'd like**
change toroHealth to ToroHUD

**Additional context**

**Comment by SirHaxe** [comment]
got help by the discord, found out my problem wanst even with the mod :)

**Comment by NillerMedDild** [comment]
Cool :D
