### ISSUE TITLE
Golden Lasso multi-crafting

### ISSUE THREAD

**Issue by Pandragoon** [NillerMedDild/Enigmatica2#299]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

When crafting a Golden Lasso, using shift-click, it consumes just one set of items, 4 string and Wood, but creates as many lasso's as my current levels can make. I had items for 1 craft, but 43 levels, it created 5 lassos.

**Modpack version (Do not use "latest")**

1.52

**Logs**
n/a
If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**
n/a

**Additional context**
n/a

**Comment by NillerMedDild** [comment]
Can you confirm that the issue is still in the latest update, 1.58?
