### ISSUE TITLE
Text turning grey

### ISSUE THREAD

**Issue by Dimentive** [NillerMedDild/Enigmatica2#3]
For some reason, text seems to randomly turn grey. This happens to the text above the hotbar when I select an item and the text in the chat.

I added [a few client-side mods](https://pastebin.com/raw/A6pUV1df) to the modpack.

**Modpack version**: 1.20

**Comment by NillerMedDild** [comment]
Due to the large number of added mods, you're sadly on your own.
I will however add, that the following mods you added can influence this:
- Better Foliage
- Optifine
- Mob Dismemberment
- DynamicSurroundings
- TexFix

If you can recreate the bug without added mods, I'll do my best to help.

**Comment by Dimentive** [comment]
I figured out what mod is causing this. It’s the Durability Show mod. This isn’t a problem with the modpack, as it’s one of the mods that I added to the modpack myself. I’ve removed it now, and text no longer turns gray.

[Relevant issue on the Durability Show GitHub](61352151511/Durability-Show/issues/11).

**Comment by Dimentive** [comment]
I figured out what mod is causing this. It’s the Durability Show mod. This isn’t a problem with the modpack, as it’s one of the mods that I added to the modpack myself. I’ve removed it now, and text no longer turns gray.

[Relevant issue on the Durability Show GitHub](https://github.com/61352151511/Durability-Show/issues/11).
