### ISSUE TITLE
Lithium dust can't be smelted in the Energized Smelter

### ISSUE THREAD

**Issue by codeka** [NillerMedDild/Enigmatica2#300]
**Issue Description**
Lithium dust (from IC2) can't be smelted in the Energized Smelter from Mekanism. The IC2 lithium dust is what comes out of the enrichment chamber, so it's clogging up my ore 5x setup :)

It can be smelted in a vanilla furnace, a redstone furnace (from TF) and a few others, looks like it's just the mekanism one that's missing.

**Modpack version (Do not use "latest")**
1.58

**Comment by NillerMedDild** [comment]
I'll get that fixed :) I believe it's because Mekanism only uses Lithium in dust form.
