### ISSUE TITLE
Oil Generator quest not completable

### ISSUE THREAD

**Issue by Lohoydo** [NillerMedDild/Enigmatica2#303]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
In the Actually Additions chapter there is a quest to make an Oil Generator, however this machine is disabled. I've tried using bq_user refresh and admin load both, but the quest remains, making it incompleteable without cheating

**Modpack version (Do not use "latest")**
1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by BattleNachos** [comment]
Is there a work around for this bug?

**Comment by NillerMedDild** [comment]
It's fixed, use the reload command, /bq_admin default load
