### ISSUE TITLE
cannot install - libvulpes version URL in manifest removed

### ISSUE THREAD

**Issue by draeath** [NillerMedDild/Enigmatica2#304]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

libvulpes version listed in pack manifest.json is 404 on curseforge:
    https://minecraft.curseforge.com/projects/libvulpes/files/2665985

This breaks downloads via CMPDL and presumably via Twitch as well.

**Modpack version (Do not use "latest")**

1.58

**Logs**

```
CMPDL log:
Downloading 236541/2665985
Project URL is http://minecraft.curseforge.com/projects/236541
File download URL is https://minecraft.curseforge.com/projects/libvulpes/files/2665985/download
Downloading download
Error: class java.io.FileNotFoundException: Invalid filename
This mod will not be downloaded. If you need the file, you'll have to get it manually:
https://minecraft.curseforge.com/projects/libvulpes/files/2665985/download

...    

WARNING: Some mods could not be downloaded. Either the specific versions were taken down from public download on CurseForge, or there were errors in the download.
The missing mods are the following:
 - https://minecraft.curseforge.com/projects/libvulpes/files/2665985/download
```

**Screenshots**

Not Applicable

**Additional context**

Not Applicable

**Comment by draeath** [comment]
Seems mod versions are not listed in the changelog. This can be worked around, but I'd need to know which libvulpes version was originally present so that I can determine a suitable replacement from curseforge.

**Comment by draeath** [comment]
Huh, it also seems your tagging in git has been mangled somehow. Tags 1.58, 1.57, and 1.56 (didn't check further back) all point to the same commit, 449a665

**Comment by draeath** [comment]
1.57 seems to also be effected, same problem (though the file ID is different than 1.58)

Does the author of libvulpes do this often??

**Comment by NillerMedDild** [comment]
That's odd, Twitch is not affected, but I don't see the version of LibVulpes we're using on CurseForge - Maybe Twitch can access archived files and CMPDL can't.

Did you find the LibVulpes version manually or would you like a download link?

The author does not do this often no, it's the first time afaik.

**Comment by draeath** [comment]
Huh. Odd.

If you have a link, I'd appreciate it! Thanks!

**Comment by NillerMedDild** [comment]
https://drive.google.com/open?id=1TYMDJ1yje6D-YT8s_K0Ikf79P4Z6n5BO

**Comment by NillerMedDild** [comment]
Please let me know when you've downloaded it, I would like to remove the link asap.

**Comment by draeath** [comment]
Got it, thank you!
