### ISSUE TITLE
Unable to craft cyclic - automatic fishing net

### ISSUE THREAD

**Issue by Drachlox** [NillerMedDild/Enigmatica2#305]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Following JEI's recipe to the letter, the "automatic fishing net" is not craftable. 
I put all the ingredients in the correct order. I even used different types of chests, as well as both types of fish, but the finished result does not appear to the right.

**Modpack version (Do not use "latest")**

1.55a

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Can you reproduce this in 1.58?
