### ISSUE TITLE
ME System does not recognize the Enhanced Circuit Boards from Forestry

### ISSUE THREAD

**Issue by mouz1502** [NillerMedDild/Enigmatica2#307]
**Issue Description**
ME System does not recognize the Enhanced Circuit Boards from Forestry in Crafting Recipes and Auto Crafting Patterns. There are a few Circuits Boards in the System. 

Enigmatica 2 Expert Version 1.54

**Screenshots**

![ae2_circuit1](https://user-images.githubusercontent.com/20639318/52174969-79999300-279c-11e9-93bc-a509362cd155.PNG)

![image](https://user-images.githubusercontent.com/20639318/52174973-8cac6300-279c-11e9-941a-2a2b17308f78.png)

Thanks for your help.

**Comment by NillerMedDild** [comment]
Can you reproduce the issue with a newly crafted circuit? I recently changed them.

**Comment by mouz1502** [comment]
Yes, i can reproduce it. I made new Boards and its still not noticed.

**Comment by NillerMedDild** [comment]
And the pattern itself is also new?

**Comment by mouz1502** [comment]
Yes, i also made a new pattern and its still not reconized.

**Comment by mouz1502** [comment]
I also tried it with Carpenter and Advanced Carpenter craftern enhanced Ciruic Boards. Still dont work. Is there a workaround to get it working?

Thanks in advance

**Comment by DrTasslehoff** [comment]
@mouz1502 It works fine for me. If I create the recipe with JEI-adding it you need to enable substitutions as it does not input the right circuit data. If you manually place the circuits into the pattern it should recognize the correct data and work without substitutions.

**Comment by mouz1502** [comment]
Thank you!!! If i manually place the circuits into the pattern it works now. 

great! Now i can automate it.

TY
