### ISSUE TITLE
Syntax error in Biomes O Plenty cofh oregen json

### ISSUE THREAD

**Issue by draeath** [NillerMedDild/Enigmatica2#309]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Observed error during loading process. Does not prevent pack play, but may involve ore generation not proceeding as intended.

Syntax issue in config/cofh/world/06_biomesoplenty_ore.json.

**Modpack version (Do not use "latest")**

1.58

**Logs**

```
cofh.shade.com.typesafe.config.ConfigException$Parse: C:\Games\MultiMC\instances\Enigmatica2-1.58\minecraft\config\cofh\world\06_biomesoplenty_ore.json: 5: expecting a close brace or a field name here, got '{'
```

**Screenshots**

N/A

**Additional context**

File begins as such, currently:
```
{
	# If you want to use this, turn off BoP oregen first.
	#"populate": 
	"dependencies": "biomesoplenty",
	{
		"ruby": {
```

This should be changed to read like this, if this oregen JSON is wanted to function:
```
{
	# If you want to use this, turn off BoP oregen first.
	"dependencies": "biomesoplenty",
	"populate": {
		"ruby": {
```

The comment leads me to think this file is at least intended not to function, though the implementation of that is a bit wonky (the whole populate structure should be commented, not just the one line, and dependencies shouldn't be in the middle - if not the file being removed entirely).

Since I'm unsure which way you mean to go with this pack, I'm putting this in as an issue.

**Comment by NillerMedDild** [comment]
Thank you for the report, it is intended that it does not generate anything. It is a lazy way of disabling it though, I'll get that fixed.
