### ISSUE TITLE
One of my crashes from yesterday

### ISSUE THREAD

**Issue by vMambaaa** [NillerMedDild/Enigmatica2#31]
#### Crash Report

https://pastebin.com/94SPc1WZ

This is the only crash report from yesterday I could find even though there were multiple.  Any help would be awesome.  I don't think I'm going to continue unless I feel like I'm not in danger of losing progress.

**Comment by NillerMedDild** [comment]
Does it happen without Optifine?

**Comment by vMambaaa** [comment]
I can remove OptiFine and then try to launch the game.  If you think it will help even if my current game won't load I'll remove OptiFine and play until another crash does or doesn't happen.

**Comment by vMambaaa** [comment]
It crashed while loading even with optifine removed.  If you think it'll help I'll try to keep playing on my backup and see if that crashes in game with optifine removed.

**Comment by NillerMedDild** [comment]
I think you should try reinstalling and see if it still occurs.

**Comment by vMambaaa** [comment]
I played for about 4 or 5 hours yesterday worth optifine uninstalled and it worked just fine.  My optifine might also have been a slightly older version.
