### ISSUE TITLE
Stuck in bed bug.

### ISSUE THREAD

**Issue by klmendor** [NillerMedDild/Enigmatica2#310]
**Issue Description**

There is "Stuck in bed issue"

**Modpack version (Do not use "latest")**

1.51

Suggesting to add Bed Patch mod https://minecraft.curseforge.com/projects/bed-patch

**Comment by NillerMedDild** [comment]
Please update to 1.58 and verify whether or still happens. 

RandomPatches implements Bed Patch, so adding it wouldn't change anything.
