### ISSUE TITLE
Mana infused Ingot recipe only works in the Metallurgic Infuser

### ISSUE THREAD

**Issue by lhw** [NillerMedDild/Enigmatica2#311]
**Issue Description**
Mana infused Ingot recipe only works in the Metallurgic Infuser and not the factory version of the same machine. Not a big issue but something I noticed.

**Modpack version (Do not use "latest")**
1.54

**Logs**

/

**Screenshots**

![Basic Enriching Factory](https://i.imgur.com/oY2PGK4.png)
vs
![Metallurgic Infuser](https://i.imgur.com/thC3OR6.png)

**Additional context**

**Comment by NillerMedDild** [comment]
That's because the Basic Enriching Factory isn't an upgraded Metallurgic Infuser, it's an upgraded Enrichment Chamber :P
