### ISSUE TITLE
Cooking with Blockhead recipe loading causes lag with storage drawers

### ISSUE THREAD

**Issue by lhw** [NillerMedDild/Enigmatica2#312]
**Issue Description**
Using the Cooking for Blockheads Cooking Table in conjunction with Storage Drawers causes a severe lag on our multiplayer server for a short time. But for some reason this does not cause a "server can't keep up" message. For between 3-20 secs nobody is able to do any server action. More players on the server seem to increase the severity of the issue.

**Modpack version (Do not use "latest")**
1.54

**Logs**

Sadly none. It's not being logged.

**Screenshots**
![Example Setup](https://i.imgur.com/kA7We16.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I see you have 2 Controllers overlapping the same area. Does breaking one remedy the issue?
