### ISSUE TITLE
Actually Additions Farmer tree planting/harvesting bug

### ISSUE THREAD

**Issue by ChelseaMainer** [NillerMedDild/Enigmatica2#313]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

The Actually Additions Farmer only plants Oak Saplings (it seems to convert any saplings it receives into Oak Saplings) and doesn't appear to harvest grown trees.  

**Modpack version (Do not use "latest")**

1.58

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
https://github.com/Ellpeck/ActuallyAdditions/issues/1160
The Farmer is not meant for saplings apparently, it doesn't look like they can fix the issue.
