### ISSUE TITLE
Quark Limestone is missing from Chisel and appears to be otherwise unobtainable

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica2#314]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Quark Limestone is missing from Chisel and appears to be otherwise unobtainable.

**Modpack version (Do not use "latest")**

Enigmatica2-1.58

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

Not applicable

**Screenshots**

Unavailable in Chisel menu: https://imgur.com/a/K3dzjCT

Also apparently cannot use Mekanism or Industrial Foregoing ore dictionary converters to swap: https://imgur.com/a/kpCHzmr 

Mekanism doesn't recognize stoneLimestone as a valid oredictionary and the IF one simply doesn't allow me to insert the block. 

**Additional context**

I was previously able to swap between the Chisel and Quark variants using Chisel mod in 1.54

**Comment by NillerMedDild** [comment]
Quark turned off Chisel support temporarily because of bugs :)

**Comment by MuteTiefling** [comment]
Hrm, So it's just unobtainable for the moment? Or would I start seeing it if I spawned new chunks?

**Comment by NillerMedDild** [comment]
It's unobtainable at the moment :)

**Comment by NillerMedDild** [comment]
Fixed it temporarily :)
