### ISSUE TITLE
Reciepe not working

### ISSUE THREAD

**Issue by nickless07** [NillerMedDild/Enigmatica2#315]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Crafting metal plates with Hammer gives IC2 plates which can't be used for IE or TE
Block of Uranium not craftable.
Ancient Warfare Iron Gear Set not craftable.

**Modpack version (Do not use "latest")**
Enigmatica2-1.58

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by MorganSimic** [comment]
The cause is the issue in #316. The whole MiscRecipes.zs script is broken due to an error with plustic stuff.

**Comment by NillerMedDild** [comment]
All those items are craftable.
Did you remove a mod or something like that?

**Comment by NillerMedDild** [comment]
or did you manually update PlusTiC?
