### ISSUE TITLE
Draconic Evolution Generator Quest

### ISSUE THREAD

**Issue by Hail4Gaming** [NillerMedDild/Enigmatica2#32]
So, the draconic evolution generator quest, labeled: "Fuel for the Fire" has no quest data.
https://i.imgur.com/5PP9mWO.png

Thought I should bring this to your attention!
Hail

**Comment by Lukas45** [comment]
Yeah, quite a few DE quests got through with no data, just haven't had the time to fix it yet

**Comment by NillerMedDild** [comment]
Fixed!
