### ISSUE TITLE
Flux Networks

### ISSUE THREAD

**Issue by codeka** [NillerMedDild/Enigmatica2#324]
**Is your feature request related to a problem? Please describe.**

There's not really a lot of good wireless charging options available (particularly when you start getting into draconic/end-gamey stuff).

**Describe the solution you'd like**

Flux Networks was added to expert, so why not normal :D I know it does a lot more than just wireless charging, but that's really the main thing I'm struggling with.

**Additional context**

**Comment by NillerMedDild** [comment]
I'd love to add it, but I can barely run Enigmatica 2 as it is, I don't think adding more content would be a good idea.

**Comment by bonnedav** [comment]
Flux networks does not add very many blocks and items to the game. I don't think it simply being added will heart performance too much. Maby look into it a little more? It would be really useful to have. Also, good job with the pack, I'm really enjoying it.

**Comment by NillerMedDild** [comment]
The amount of blocks in a mod doesn't determine it's performance impact :P

**Comment by NillerMedDild** [comment]
It's gonna be a no I'm afraid :/ I need to be able to run the pack to develop it, and adding more mods makes my PC struggle.

**Comment by Dimentive** [comment]
One word: [dimensional transceiver](https://ftb.gamepedia.com/Dimensional_Transceiver) from [Ender IO](https://minecraft.curseforge.com/projects/ender-io). Okay, that’s five words, but still, Ender IO is in the pack and adds the dimensional transceiver, which allows you to transfer energy from anywhere in the world to anywhere in the world, including across dimensions, at just a 10% energy loss. It also lets you transfer items and fluids (at no item or fluid loss) in the same way.

There’s also the [powercell](https://ftb.gamepedia.com/Powercell) from RFTools’, which also transfers energy (but not items or fluids) over any distance, including across dimensions, and it has a distance-based energy loss mechanic which caps at 10%, meaning that you lose less energy than if you use Ender IO’s dimensional transceiver unless you’re at the maximum distance. The energy loss is even less if you [infuse](https://github.com/McJtyMods/RFTools/wiki/RFTools-Dimensional-Shards) it.

[Flux Networks](https://minecraft.curseforge.com/projects/flux-networks) definitely looks like a cool mod, but the dimensional transceiver and powercell, too, are great at transferring energy over any distance.
