### ISSUE TITLE
advanced thermionic fabricator

### ISSUE THREAD

**Issue by Tawnyman** [NillerMedDild/Enigmatica2#329]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

advanced thermionic fabricator not making Garden cloche's

**Modpack version (Do not use "latest")**

enigmatica 2 expert
1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

https://imgur.com/a/ulCsSKc

**Additional context**

It dose work setup a recipe for iron tubes and they work fine but cloche's don't

**Comment by NillerMedDild** [comment]
Are you supplying 50.000 RF/t or more?

**Comment by DrTasslehoff** [comment]
The recipe requires 8000mb liquid glass and your hatch only has space for 5000. Upgrade it to hold more and it will work

**Comment by Tawnyman** [comment]
Totally missed that thank you very much and sorry to be a bother

**Comment by NillerMedDild** [comment]
No worries!
