### ISSUE TITLE
Seared glass quest not completing

### ISSUE THREAD

**Issue by codeka** [NillerMedDild/Enigmatica2#332]
## Thank you for helping us improve. #####

**Issue Description**

The "Seared Glass" quest in Tinker's is not completing. Based on the quest page, it looks like you're not supposed to just craft it with a piece of glass and four seared bricks, so I tried casting four in a casting basin. But even after doing that, the quest did not complete.

**Modpack version (Do not use "latest")**
1.58

**Screenshots**

https://imgur.com/a/T7l2xkN

**Comment by NillerMedDild** [comment]
Fixed in dev, it was a mod bug :)
