### ISSUE TITLE
Lag with Mekanism/IC2 AE Autocrafting

### ISSUE THREAD

**Issue by MasterSloth1** [NillerMedDild/Enigmatica2#337]
**Modpack version**
1.55

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
when autocrafting ultimate induction cells with ae2 it causes massive server lag, so i remember reading it somewhere in this github it was a problem not entirely sure if the issue has been closed or what ever but i have found a way of stopping it, in the applied energistics 2 config file appliedEnergistics2.cfg line 245 there is logging under the misc category when that is set to false the console spam and server lag stops, sorry if this has already been resolved but thats the fix i found to stop it 😄

**Comment by NillerMedDild** [comment]
You're awesome. I did not know about this.

**Comment by MasterSloth1** [comment]
soooo it turns out lol sorry it still lags it just doesnt spam the console saying Using CraftingManager fallback: Recipe i know im terrible :/

**Comment by NillerMedDild** [comment]
The actual "fix" is on line 269 :P

**Comment by MasterSloth1** [comment]
will that not break recipes as ae2 is using the fallback recipe for items?

[19:00:39] [Server thread/WARN] [AE2:S]: Using CraftingManager fallback: Recipe <ic2:306> for output <1xic2.cable@0> rejected inputs [1xitem.industrialforegoing_plastic@0, 1xic2.cable@0]. NOT FOUND, please report.

**Comment by MasterSloth1** [comment]
dont worry i disabled it myself and retried the ultimate induction cell and it worked perfectly no errors nor lag

**Comment by NillerMedDild** [comment]
Excellent! I'll be testing it as well.

**Comment by MaxNeedsSnacks** [comment]
Could it be that the recipe @MasterSloth1 was mentioning had an output with the same ID (but different NBT) as one of the inputs?

If so, this should be reported to the AE2 tracker

**Comment by NillerMedDild** [comment]
The issue is that the NBT data on the Energy Cubes and Energy Tablets in JEI differ from the NBT Data the items are created with. This problem can be solved by manually putting a crafted Energy Tablet into the recipe, instead of using the JEI plus.

**Comment by MaxNeedsSnacks** [comment]
Ah, so it's sort of like the glitch with the Circuit Boards I encountered. Interesting.
Either way, the laggy side effects of having to use CraftingManager fallbacks can only be mitigated by disabling OD substitution from what I've tested, and by using things like crafters that keep a passive stock of e.g. Wirecutters.

**Comment by NillerMedDild** [comment]
Or by manually putting the crafted components in the recipe.

**Comment by MaxNeedsSnacks** [comment]
Mhm. Even then, though, I think you need to keep OD substitution disabled because it'll otherwise try to ignore NBT on the item. Then again, having substitution disabled is not that big of a deal anyway because you have UniDict in the pack which should unify **most** things

**Comment by NillerMedDild** [comment]
Yeah you're probably right, I only tested it with OD substitution disabled.
