### ISSUE TITLE
[1.59] Cannot complete [Ritual Diviner] and [Ritual Diviner - Dusk]

### ISSUE THREAD

**Issue by nodey420** [NillerMedDild/Enigmatica2#338]
**Modpack version**
1.59

**Can the issue be reproduced?**
Yes/no/unknown
Unknown

**Logs**
NA

**Issue**
Completed Ritual Diviner and Ritual Diviner - Dusk quests and cannot complete them.  They show as completed, but cannot submit.

Tried to reload the quests, but that did not seem to work.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by nodey420** [comment]
I found something interesting out.

If you do all the requirements and the quest turns aqua follow these steps

1. 1. Go into quest
2. select reward
3. click back
4. go into quest

At this point you should be able to click "claim".  It worked on a couple of other quests I was having difficulties from.  This may be isolated to my world ( it's an older one ).
