### ISSUE TITLE
[1.59] Convert Pam's apples to Minecraft apples

### ISSUE THREAD

**Issue by nodey420** [NillerMedDild/Enigmatica2#339]
**Modpack version**
1.59
**Can the issue be reproduced?**
Yes

**Logs**
NA

**Issue**
Both Pam's and Minecraft apples seem to be part of cropApple and the recipe for the golden apple includes cropApple, but you cannot craft a golden apple from a pam's apple.  I used a forestry farm in an earlier version of the pack and have almost 1000 pam's apples and would like to convert them to minecraft apples so that I can use them in the golden apple recipe.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
The Pam's Apple is meant to be in-world only. Removing it from the oredict `cropApple`.
