### ISSUE TITLE
Dupe bug using Arcane Workbench

### ISSUE THREAD

**Issue by Nightcaste** [NillerMedDild/Enigmatica2#34]
#### Issue Description
Infinite "middle backpack" can be pulled out of Arcane Workbench.  I just now made the workbench, I haven't used it to make anything yet.  The output slot had a "Middle Backpack" from a mod called "Backpack".  If I pull the Middle Backpack out, close and reopen the UI, there's another one in the output slot.  So far I've done this about 10 times.  I can't seem to "open" the bag though.  I'm not familiar with that particular mod, so I don't know if it's a right click or a hotkey or what.

#### Modpack version (Do not use "latest")
1.3.6

#### Crash Report
Not causing crashes

[pastebin/gist/etc link here]
n/a

**Comment by Lukas45** [comment]
Dublicate of #17, but thanks for the report :)
The bags gained are useless, as they don't hold any Data on their size, so it has 0 slots available. Filling up the crystal slots int he Arcane Workbench makes them go away
