### ISSUE TITLE
Quests not updating for partry

### ISSUE THREAD

**Issue by Syrax81** [NillerMedDild/Enigmatica2#343]
**Modpack version**
1.59

**Can the issue be reproduced?**
Yes

**Issue**
I got a friend I usually play MC with and we decided to try this modpack. The first thing we did was create a party from the Better Questing book then started doing quests but the quests one of us completed, did not complete for the other. Does anyone experience the same thing? Anyone know an answer for why this is happening?

**Comment by NillerMedDild** [comment]
Are you in a LAN world, or on a dedicated server?

**Comment by Syrax81** [comment]
Sorry, I forgot to mention that. We are playing on a dedicated server.

**Comment by NillerMedDild** [comment]
I've heard of the issue before, I'll report it to the mod developer :)

Just for the sake of clarity, may I have a screenshot of the party menu of your book?

**Comment by Syrax81** [comment]
![2019-02-18_21 52 20](https://user-images.githubusercontent.com/47722553/52975912-9a323180-33c7-11e9-8895-cea1e6968e44.png)
There seem to be missing the "Shared Loot" button.

**Comment by NillerMedDild** [comment]
Have you tried reforming the party?

**Comment by Syrax81** [comment]
Did now, no difference.

**Comment by Funwayguy** [comment]
@Syrax81 Do you know the specific quest and task type that didn't sync?

**Comment by Syrax81** [comment]
Started the Tinkers quest, by making the book and 8 templates, that did not sync for my friend. He tried making a wood shears from Roots, which he got reward unlock for, but did not unlock for me. I tried making the Tinkers' worktables, but that didn't unlock for my friend.

**Comment by NillerMedDild** [comment]
Can he complete the quests on his own?

**Comment by Syrax81** [comment]
Yes he can. It seem to act like we aren't in a party, both can complete the same quests, but it doesn't look like it syncs between us.

**Comment by Funwayguy** [comment]
I'll double check the functionality of the crafting tasks, might have missed somethin party progress after adding in those new configs

**Comment by Funwayguy** [comment]
Crafting tasks seem fine but there does appears to be a fault in item retrieval tasks not taking party progress into account (but visually saying it does) under certain configurations. I've fixed this for next update but I'm not sure if this was the particular task type you're encountering this issue with or if it's more widespread.

**Comment by NillerMedDild** [comment]
I believe they were all crafting tasks, but I'll be sure to report back if the issue isn't fixed - Thank you :)
