### ISSUE TITLE
Crash on creating world

### ISSUE THREAD

**Issue by jjhowe02** [NillerMedDild/Enigmatica2#344]
**Modpack version**
1.59
**Can the issue be reproduced?**
unknown

**Logs**
https://pastebin.com/GcujjBdV

**Issue**
Achievement manager won't load quartz block

**Comment by NillerMedDild** [comment]
Does it happen every time you try to make a new world?

**Comment by jjhowe02** [comment]
ya

**Comment by jjhowe02** [comment]
also if I use preview it also crashes too, i've been looking up fixes but i keep receiving food related crashes from achievement manager that are related to pam's harvest craft, spice of life, etc

**Comment by NillerMedDild** [comment]
Have you tried re-installing the modpack?
I'll investigate in a few hours.

**Comment by jjhowe02** [comment]
actually I found out the issue, the world type lost cities (BoP) was found in the logs that I had, turns out, changing it to default or something other than lost cities fixed the issue, hope you could find a fix, thanks!

**Comment by NillerMedDild** [comment]
It's a good idea to say in the report if you're using other generation than the default.
