### ISSUE TITLE
Certain quests not completing

### ISSUE THREAD

**Issue by wwaisath** [NillerMedDild/Enigmatica2#345]
**Modpack version**
1.59

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
So far, there are two quests that will not complete that I have run into. One was remarked on a few days ago (Peek-A-Boo! - the Seared Glass quest from Tinker's), and the other one, for me, is the /home quest from Draconic Evolution (the Dislocator quest). While the Tinker's quest is an end-of-line quest, the Draconic Evolution quest has two follow-up quests to it.

**Comment by melbellrocks** [comment]
I am having this same issue.  They have icons at the top of the quest that I have never seen.  Crafting table, furnace, and anvil with a little X on them.  Not sure what these icons mean?

**Comment by NillerMedDild** [comment]
Hm, I thought those were fixed, damn. I'll get it fixed, it's a bug with crafting tasks.

**Comment by Chinthor** [comment]
> I am having this same issue. They have icons at the top of the quest that I have never seen. Crafting table, furnace, and anvil with a little X on them. Not sure what these icons mean?

As far as I can tell, those mean that you should obtain the items without using any of the crafting methods listed above the quest. For seared glass, that leaves the method of pouring liquid seared stone over a piece of glass in a casting basin.

While tracking down issues related to the same thing, I wound up on the Enigmatica 2 Lite issues page. The quest is currently listed as a bug coming from Better Questing not recognizing triggers that it says it should be able to recognize.
