### ISSUE TITLE
Environmental Tech Tier 6 Void Ore Miner not configured right

### ISSUE THREAD

**Issue by mindbane** [NillerMedDild/Enigmatica2#346]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Issue**
The Tier_6.json file ([link](https://github.com/NillerMedDild/Enigmatica2/blob/master/config/environmentaltech/multiblocks/void_miner/ore/tier_6.json)) is missing a large number of ores that the tier 5 ([link](https://github.com/NillerMedDild/Enigmatica2/blob/master/config/environmentaltech/multiblocks/void_miner/ore/tier_5.json)) version is configured to have including important ones like iron. As a result once completing the quest the void miner is rendered useless.

**Comment by NillerMedDild** [comment]
The Tier 6 Void Ore Miner is meant to target rare ores only.
