### ISSUE TITLE
Draconic Evolution Fusion Crafting not working?

### ISSUE THREAD

**Issue by Calibos** [NillerMedDild/Enigmatica2#347]
**Modpack version**

Enigmatica 2 - 1.59 

**Can the issue be reproduced?**
yes?

**Logs**
Input pastebin link to crash-report or latest log, if applicable
no crash, so no report

**Issue**

Draconic Fusion Crafting, no recipe visible in core, no start button, setup correct, I've verified distance between core and injectors, recipe is correct.

![2019-02-18_22 52 45](https://user-images.githubusercontent.com/44527515
/52995783-7d4e2c00-33d0-11e9-80e4-bc11b86cf4d4.png)
![2019-02-18_22 53 03](https://user-images.githubusercontent.com/44527515/52995784-7de6c280-33d0-11e9-9daf-682a4b0ebe3e.png)
![2019-02-18_22 53 08](https://user-images.githubusercontent.com/44527515/52995785-7de6c280-33d0-11e9-93f1-1f271777cb56.png)
![2019-02-18_22 53 12](https://user-images.githubusercontent.com/44527515/52995787-7de6c280-33d0-11e9-9610-7c0d43c1a9b5.png)
![2019-02-18_22 53 20](https://user-images.githubusercontent.com/44527515/52995788-7e7f5900-33d0-11e9-86de-611f6d92d542.png)

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
I believe you need to set your I/O Crystals on the Solar Panel to output, and input on the Crafters.

**Comment by NillerMedDild** [comment]
Please let me know if it works.

**Comment by Calibos** [comment]
sadly, they're already set that way, if you look in the bottom right of the second to last, and last image, you can confirm for yourself. I tried with numerous power options, and apparently the first picture didn't even post properly, it shows the lack of recipe in the core.

**Comment by Calibos** [comment]
I've gone through each mod's method of transferring power, none of them seem to supply power

**Comment by NillerMedDild** [comment]
Have you done Fusion Crafting before?

**Comment by Calibos** [comment]
yep, many times, all the way up to chaos, in 1.12.2 even, which is why frankly I was puzzled that nothing was working

**Comment by NillerMedDild** [comment]
Ah damn, I was hoping you weren't giving the core a redstone signal.

**Comment by Calibos** [comment]
I would have liked it have been something silly and simple, a little embarrassment is good for me from time to time, sadly, no such luck this time, I've been looking online, and I saw something about an interaction with immersive engineering, but I also saw that the mod-maker said that bug was fixed.

**Comment by DrTasslehoff** [comment]
User error.  Injectors must be a minimum of 1 block from the core, and up to 16 blocks away. They may be offset by one block in any direction from the core's lines of axis. This means you can only put a 3x3 of injectors per side of the core at a maximum. When making these make sure there is proper line of sight otherwise that will also break it.

**Comment by NillerMedDild** [comment]
Did that resolve your issue?

**Comment by Calibos** [comment]
sadly not, and it's actually a minimum of 2 blocks in 1.12.2

**Comment by NillerMedDild** [comment]
Sure thing!

- good catch Doctor :)
