### ISSUE TITLE
[Feature Request] Add mod Railcraft 

### ISSUE THREAD

**Issue by Landrash** [NillerMedDild/Enigmatica2#349]
**Modpack version**
1.59

**Feature Request**
Addition of mod.
Reason is simple. In the current iteration there's few things that encourage building over a wide area.
The addition of [Railcraft](https://minecraft.curseforge.com/projects/railcraft/) can be used as a transport system over a wider area if promoted at early gameplay.

**Comment by NillerMedDild** [comment]
Duplicate of #263

**Comment by Landrash** [comment]
Terribly sorry about that. Must have missed it when searching.

**Comment by NillerMedDild** [comment]
That's alright :)
