### ISSUE TITLE
Blood Magic Ritual of Magnetism crash interaction

### ISSUE THREAD

**Issue by VallenFrostweaver** [NillerMedDild/Enigmatica2#35]
#### Issue Description
Server crashes when specific items are effected
#### Modpack version (Do not use "latest")
1.36
#### Crash Report
https://pastebin.com/nBVRVL63

**Comment by NillerMedDild** [comment]
It has been reported to the BM issuetracker by someone else, thank you for the report.
https://github.com/WayofTime/BloodMagic/issues/1335
