### ISSUE TITLE
tin ingot and IE or IC2 hammer result in IC2 tin plate that cant be used

### ISSUE THREAD

**Issue by Huginn-Odinbro** [NillerMedDild/Enigmatica2#351]
**Modpack version**
1.59

**Can the issue be reproduced?**
yes with both Immersive engineering and IC2 hammers

**Logs**
No crash

**Issue**
Trying to make a tin plate with an immersive engineering or IC2 hammer result in the IC2 tin plate, which can't be used in recipes. I've removed a few mods I'll list but I don't think they would have an impact.
Removed mods: 
1: Farseek/Streams
2: Minecolonies
3: Recurrent Complex
4: The Lost Cities

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Readd Minecolonies :)

**Comment by Huginn-Odinbro** [comment]
Ahh I knew it was a good idea to add removed mods. even though I was almost positive it had nothing to do with it. Whenever this kind of stuff comes up, it's usually  me issue. Thanks man.

**Comment by NillerMedDild** [comment]
Sure thing! Removing lines 7-20 in the file `scripts/RecipeConflicts.zs` would also work, without readding Minecolonies :)
