### ISSUE TITLE
Crash on creating world - Lost Cities

### ISSUE THREAD

**Issue by Torinarg123** [NillerMedDild/Enigmatica2#353]
**Modpack version**
1.59

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/CzYTP2c5

**Issue**
Creating a world in default settings works fine. Creating a world with Lost Cities or Lost Cities (BoP) results in a crash. Mentioned in Issue #344

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Should be fixed in an upcoming update :)
https://github.com/McJtyMods/LostCities/issues/185

**Comment by Vercalos** [comment]
Can second this.  Updating the Lost Cities mod fixed it.
