### ISSUE TITLE
Beacons Only Work to South East

### ISSUE THREAD

**Issue by jtgraphic** [NillerMedDild/Enigmatica2#357]
**Modpack version**
1.59

**Can the issue be reproduced?**
Yes

**Logs**
Not Applicable

**Issue**
A standard vanilla beacon only works to the south east of the beacon.

You can replicate this in any brand new world. Create a beacon of any size. Select the buff. Stand in various positions around the beacon to view the refresh mechanic working/not working.

Size of beacon does not matter.
Position of beacon does not matter.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Damn that is weird. I have no idea which mod could be causing this tbh.

**Comment by jtgraphic** [comment]
Right?! I'll make an attempt to enable/disable mods to bisect the problem source.

**Comment by NillerMedDild** [comment]
Thanks!

**Comment by Discomanco** [comment]
Also the case on Expert, just FYI

**Comment by jtgraphic** [comment]
I found this in the SevTech issues and I'm not sure if it's relevant: https://github.com/DarkPacks/SevTech-Ages/issues/1922

**Comment by NillerMedDild** [comment]
Sounds very similar, too bad they didn't find a fix.

**Comment by jtgraphic** [comment]
I'll make an attempt to test it in their pack and if it's broken and we find a fix, I'll shoot it over their way.

**Comment by Tfarcenim** [comment]
Betterfps causes this, disable fast beacon and restart the pack to fix.

**Comment by NillerMedDild** [comment]
Thank you!
