### ISSUE TITLE
AE 2 terminal crash

### ISSUE THREAD

**Issue by ExoVengeance** [NillerMedDild/Enigmatica2#361]
**Modpack version**
1.59

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/XdGNhDnf

**Issue**
I put wireless universal terminal in one of my bauble slot and if i open my inventory i crash so i cant play now.

**Comment by ExoVengeance** [comment]
if you know a workaround please do let me know

**Comment by ExoVengeance** [comment]
i found a workaround

**Comment by NillerMedDild** [comment]
Known issue #327

**Comment by ExoVengeance** [comment]
I fixed the crash by not opening my inventory and using these commands  /baubles view {Name} find the slot it was in and then /baubles clear {name} [slot#] and cleared it i think it should crash i put it back in
