### ISSUE TITLE
Vulpes library Titanium Ingot recipe broken

### ISSUE THREAD

**Issue by Oldmanauchter** [NillerMedDild/Enigmatica2#362]
**Modpack version**
Enigmantica 2 V1.59

**Can the issue be reproduced?**
Yes

**Logs**
Log not applicable to this issue.

**Issue**
Recipe for vulpes library titanium is broken and will not craft. Tried updating to latest version of the pack and issue is still present. Tried by several different players.

**Comment by NillerMedDild** [comment]
Do you get any errors on login? Did you remove any mods?

**Comment by Oldmanauchter** [comment]
No errors. We are running it as packaged from twitch. For us this error has
existed on both v1.54 and v1.59

**Comment by NillerMedDild** [comment]
Okay, I'll look into it :)

**Comment by NillerMedDild** [comment]
It works just fine for me. Are you sure you haven't changed anything?
