### ISSUE TITLE
Visible Claim Borders Tank FPS

### ISSUE THREAD

**Issue by jhagrid77** [NillerMedDild/Enigmatica2#363]
**Modpack version**
1.59

**Can the issue be reproduced?**
Yes

**Logs**

**Issue**
When claiming ~12 chunks or more using the FTB Utility mod, chuck borders become visible, and tank the frame rate (for me anyways).

![2019-03-01_17 42 05](https://user-images.githubusercontent.com/15268715/53670883-4dade800-3c4a-11e9-819c-809fb15d3857.png)

![2019-03-01_17 42 13](https://user-images.githubusercontent.com/15268715/53670887-51416f00-3c4a-11e9-8d96-4e4e4a92976a.png)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Are you sure the issue is with FTB Utilities? I can't reproduce this issue. Also the grid looks like the preview grid of the Digital Miner.

**Comment by jhagrid77** [comment]
Perhaps you are correct. I did have a Digital Miner setup at the same time. Just so weird because the boarders were in the same places as my claim. When I get home I can do further investigation.
