### ISSUE TITLE
Blood Altar Lvl 3 quest

### ISSUE THREAD

**Issue by Calibos** [NillerMedDild/Enigmatica2#365]
**Modpack version**
Input version here
1.59
**Can the issue be reproduced?**
Yes/no/unknown
Yes
**Logs**
Input pastebin link to crash-report or latest log, if applicable
No log necessary
**Issue**
Input short description of the issue here

Quest asks for sea lanterns, x4, altar requires glowstone

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
It asks for either Glowstone or Sea Lanterns, both work.
