### ISSUE TITLE
Tinker's quests are not detecting items

### ISSUE THREAD

**Issue by WinterCept** [NillerMedDild/Enigmatica2#368]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes

**Issue**
I just started this pack on 1.59 and updated today and the Tinker's Construct quests (specifically "Materials and You" and "Pan-Tastic!") are not detecting the items even though I have them in my inventory.

Edit mode for BQ is off and I did /bq_admin default load, issue persists. The "Ent" quest updates just fine.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by darkfr3ak** [comment]
Same here, none of the patterns and the tables are detected. Edit mode is off, "/bq_admin default load" and "/bq_user refresh" did nothing.

**Comment by Rastem88** [comment]
I had the same problem. I used the workaround referenced here https://github.com/NillerMedDild/Enigmatica2/issues/372#issue-417612537 of "changing GroupDetect from 1 to 0 in the Retrieval Tasks section".
