### ISSUE TITLE
Diamonds to Diamond Dust becomes IC2 Diamond Dust and unusable.

### ISSUE THREAD

**Issue by KelticRaven** [NillerMedDild/Enigmatica2#37]
#### Crash Report

[pastebin/gist/etc link here]

**Comment by KelticRaven** [comment]
If you crush Diamond Ore with Actual Additions Crusher, it turns to IC2 Diamond Dust and you can not change into diamonds!! It should changed into AA Diamond Dust that you could use the AA Powered Furnance to change into diamonds.

**Comment by NillerMedDild** [comment]
So... you just left the template blank and went freestyle, huh. That's new.

I don't intend for Diamond Dust to be smeltable, if you want extra Diamonds from Diamond Ore I suggest you use another machine.
