### ISSUE TITLE
 Spice of Life progress reset in pack version 1.60 (easy fix)

### ISSUE THREAD

**Issue by StarkRG** [NillerMedDild/Enigmatica2#370]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes

**Logs**
Logs not necessary.

**Issue**
The version of Spice of Life Carrot Edition in the pack uses a different file for storing player food history and hearts causing people's hearts and history to reset. They released [a new version](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition/files/2683746) a few hours ago, 1.5.1, that reverts that change, restoring the hearts and history progress. Anyone working with the 1.5 version that's currently in the pack will have their progress reverted in the next update, thus I recommend pushing this update ASAP.

**Comment by NillerMedDild** [comment]
Alright :)

**Comment by Dimentive** [comment]
@NillerMedDild Thanks for the fix!

I have a backup of 1.59 Enigmatica 2, but I’m just wondering: Do you know what file or folder has the [Spice of Life: Carrot Edition](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition) history so that I can copy it without having to revert to an entire world backup?

**Comment by StarkRG** [comment]
It's stored in the player .dat so, unless you don't mind losing progress in other things, there's no easy way to restore it (you could use an NBT editor). In the end I just have up and started again.

**Comment by NillerMedDild** [comment]
If you didn't play a lot with 1.60 the data loss should be minimal though, only data gained during 1.60 would be reverted.

**Comment by Dimentive** [comment]
Aw, really? SolC data is not stored in a separate file? That’s a shame. I’m not reverting, then, as I don’t want to lose advancements, XP, and other progress.

Oh well. I guess I’ll just do as @StarkRG and eat everything I can get my hands on again. I haven’t played this world for _that_ long, so it shouldn’t be too hard.
