### ISSUE TITLE
Server not allowing players to join due to wooden doors in version 1.60

### ISSUE THREAD

**Issue by LinkTheLinker** [NillerMedDild/Enigmatica2#371]
**Modpack version**
Enigmatica 2 Version 1.60

**Can the issue be reproduced?**
Unknown

**Logs**
https://pastebin.com/mRhUZB3b

**Issue**
I am a Co-Owner of a modded minecraft server and recently I have installed version 1.60 of the Enigmatica 2 Pack. The server boots up although, when someone joins it gives this error:
![untitled](https://user-images.githubusercontent.com/25944116/53852365-cd5fed80-3f8f-11e9-991f-b8749b162a07.png)
If anyone can help me solve this issue, it would be very helpful!

**Comment by NillerMedDild** [comment]
Reinstall the client and/or server :)

**Comment by appollon41** [comment]
Sorry for the necro, but even reinstalling both, it won't work for me. It happens with some people and not others on my server, it's very annoying.

**Comment by NillerMedDild** [comment]
And the versions are exactly the same?
