### ISSUE TITLE
Beating Starvation quests.

### ISSUE THREAD

**Issue by kleshas** [NillerMedDild/Enigmatica2#372]
**Modpack version**
Enigmatica 2 1.60

**Can the issue be reproduced?**
Yes

**Logs**

**Issue**
Cannot complete Complete Pizza and Midnight Snack quests[EDIT: and others in same section] (basic troubleshooting done like restarting pack, checking latest.log etc).  I poked around in edit mode and managed to complete them by changing GroupDetect from 1 to 0 in the Retrieval Tasks section.

**Comment by NillerMedDild** [comment]
Thanks for the fix ^^
