### ISSUE TITLE
Induction smelter,  dosen't accept Fused Quartz.

### ISSUE THREAD

**Issue by Aranak** [NillerMedDild/Enigmatica2#374]
**Modpack version**
1.57

**Can the issue be reproduced?**
Yes

**Issue**
Can't put Fused Quartz in the induction smelter; 
for using for hardened platinum glass for the Modular Machinery.

**test done in order, who have not worked**
1.Try to put it inside manualy. 

2.Try both slot.

3.Tried to put it inside with a hopper. 

4.Tried in single player mode; in creative and try put it inside manualy. 

5.Ask for someone else to test on his side still dosen't work.

Thank you :)

Edit: I will use the alternative recipe (in crafting table) for continue forward so no stress.

**Comment by NillerMedDild** [comment]
I know :s I've tried to fix it, without luck.

**Comment by Aranak** [comment]
no problem good luck,
Thank you for the fast awnser.

**Comment by NillerMedDild** [comment]
And thank you for the report :)

**Comment by BuggaNoia** [comment]
For me it seems, that the Alloy Furnance has problems if the same material goes into both slots.

Receipe change/addition suggestion: 4 Quartz + 1 Block of Quartz give 2 Fused Quartz

Would be the same ratio (one Fused Quartz for 4 Quartz.

**Comment by NillerMedDild** [comment]
That is entirely unrelated.

**Comment by NillerMedDild** [comment]
That being said, I concur and will change it.

**Comment by FlyingThunder** [comment]
any news on this one? luckily oredict also allows hardnened thermal glass too though so its not impossible to make hardened platinum glass

**Comment by NillerMedDild** [comment]
It's not possible I'm afraid, the Induction Smelter will not accept Fused Quartz for some reason, even if I manually make the recipe. I am unable to fix this.

**Comment by FlyingThunder** [comment]
RIP - maybe its better to remove the quartz from the recipe then? if thats
even possible, idk how recipes with oredict can be configured

Niels Pilgaard Grøndahl <notifications@github.com> schrieb am So., 2. Juni
2019, 21:57:

**Comment by NillerMedDild** [comment]
I can't remove it either :/
