### ISSUE TITLE
Roots starting quest not working

### ISSUE THREAD

**Issue by tnick1** [NillerMedDild/Enigmatica2#376]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes

**Issue**
Just updated the modpack and have a server going, But Ive done the commands to reload and such but the First quest for the Roots 2 "Wooden Shears" Wont detect the shears at all. I've checked this on Single Player as well and it doesn't work either.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by imthatjeremyguy** [comment]
Same issue with this and starting the Tinkers quest chain.

**Comment by nodey420** [comment]
I am experiencing this as well.

**Comment by NillerMedDild** [comment]
These extra comments aren't helpful.
