### ISSUE TITLE
Raubtier5 - Enigmatica 2 Crash

### ISSUE THREAD

**Issue by Raubtier5** [NillerMedDild/Enigmatica2#378]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/Dx2wK19t

**Issue**
When trying to start from twitch launcher game will not open and gives this report - http://prntscr.com/mun6ko

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Re-installing should fix it :)
