### ISSUE TITLE
Barista Trainee quest cannot be obtained by other player in LAN world

### ISSUE THREAD

**Issue by Dimentive** [NillerMedDild/Enigmatica2#382]
**Modpack version**
1.61

**Can the issue be reproduced?**
Yes (I assume)

**Issue**
I’m playing with someone via LAN. He has a Coffee Maker but cannot complete the Barista Trainee quest, even if he clicks “Detect/Submit” and drops the Coffee Maker on the ground and picks it back up. I’m not sure whether I, the host of the LAN world, is able to complete the quest, as I haven’t obtained a Cofee Maker yet. I’ll check if I can later.

**Comment by NillerMedDild** [comment]
Did he make it himself?

**Comment by Dimentive** [comment]
Yes, he crafted it himself.

**Comment by NillerMedDild** [comment]
Ah, issue confirmed!

**Comment by NillerMedDild** [comment]
I was able to trigger it by setting ignoreNBT to true, and dropping it and picking it up again. Hopefully that does the trick for your friend as well, in version 1.62 :)

**Comment by NillerMedDild** [comment]
Please re-open this if he still has trouble in version 1.62.

**Comment by Dimentive** [comment]
He was able to complete the Barista Trainee quest in version 1.62!

Thank you for the fix.
(Sorry for the late update. He hadn’t tried to complete the quest again until just now.)
