### ISSUE TITLE
Tinkers' Construct seared glass quest uncompletable 

### ISSUE THREAD

**Issue by Carzah** [NillerMedDild/Enigmatica2#384]
**Issue**
Can't complete Seared Glass quest. Labeled as a Crafting Task rather than Retrieval Task like the other quests. Has 3 icons with red x's (Crafting Table, Furnace and Anvil).

**Modpack version**
1.62

**Can the issue be reproduced?**
unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

![javaw_1ADIH15bD5](https://user-images.githubusercontent.com/48415541/54089306-8d1db800-435f-11e9-851d-43b4bb966e63.png)

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Use the command `/bq_admin default load` to get the updates :)

**Comment by Carzah** [comment]
> 
> 
> Use the command `/bq_admin default load` to get the updates :)

Oh, sorry. Thanks.

**Comment by NillerMedDild** [comment]
No worries, I should've mentioned it in the changelog.
