### ISSUE TITLE
Phantom quest completion notification, quest not present in Quest Book

### ISSUE THREAD

**Issue by madasi** [NillerMedDild/Enigmatica2#385]
**Modpack version**
1.6.2 
**Can the issue be reproduced?**
Not without manually resetting quest progress

**Logs**
n/a

**Issue**
playing on a private multiplayer server

Teammate was building their minecolonies settlement when we got the noise and on-screen message that a quest had been completed, "Village Improvements". However, when looking through the quest book to claim the reward, this quest does not appear to be listed in any category. I can find it described in config/betterquesting/DefaultQuests.json but do not know my way around the betterquesting mod's JSON structure well enough to see what quest line it should belong to, if any.

It is "51:10"
"desc:8": "Your Minecolony can be expanded by getting your builder to build additional structures. To begin, place the structure block of your choice - For example, placing a GuardTower block will allow your builder to build it. The structures recruit villagers, who can then perform different tasks. Additional details can be found at: http://www.minecol
onies.com/wiki",

**Expected behavior**
Upon completing the quest, find and claim the reward in the quest book. Alternately, if quest is not intended to be active or is locked behind another quest and not currently claimable, no notification when completing it would be expected.

**Observed behavior**
Quest completion notice, but no quest visible to claim in quest book

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
