### ISSUE TITLE
Mekanism Obsidian TNT Infinite Chain explosion (Base Block not despawning if triggered by explosion)

### ISSUE THREAD

**Issue by Anthropomorphed** [NillerMedDild/Enigmatica2#386]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Issue**
Mekanism
Obsidian TNT activated by another explosion, in my case by other Obsidian TNT, wont let the placed Obsidian TNT block disappear and result in infinite chain explosion.

![vlc_2019-03-12_16-33-14](https://user-images.githubusercontent.com/25126266/54213359-8ff5e580-44e4-11e9-9a1c-61c925091352.png)

also video with sound warning as its already doing it until t he placed main blocks are removed:
https://psycho.s-ul.eu/tfuED77J

**Comment by NillerMedDild** [comment]
Damn that's cool :P

**Comment by NillerMedDild** [comment]
I mean err, we'll be switching to the normal branch of Mekanism soon, I'll reproduce it with that and report to them :)

**Comment by NillerMedDild** [comment]
Not sure when it happened, but this has been fixed.
