### ISSUE TITLE
Better Questing uncompletable Quests + No Rewards 1.62

### ISSUE THREAD

**Issue by Anthropomorphed** [NillerMedDild/Enigmatica2#387]
**Modpack version**
1.62 Upgraded from 1.60 > 1.61 > 1.62

**Can the issue be reproduced?**
No
Fresh SP World it worked.
Probably would in fresh MP world.

**Issue**
We play on a server since v1.60. We updated the Server to 1.61 and then 1.62 when it was available.
As there were quests we couldnt complete even with all items at hand we ignored them till now.
So i tried to complete them now, even with newly crafted items and some still wont work.
For now that would be four of Mekanism and one of Draconic Evolution.

Thats how it looks atleast for the draconic one.
Multiplayer:
Looks like that since V1.60
![Multiplayer](https://user-images.githubusercontent.com/25126266/54225879-ef5fef80-44fc-11e9-910b-963b43bb14dc.png)
Singleplayer: 
Worked first try new 1.62 World
![Singleplayer](https://user-images.githubusercontent.com/25126266/54225915-f5ee6700-44fc-11e9-80c7-ffa2d7228a1b.png)

**Comment by NillerMedDild** [comment]
Use the command `/bq_admin default load` to update your quests :)
