### ISSUE TITLE
Can’t use Spice of Life: Carrot Edition commands

### ISSUE THREAD

**Issue by Dimentive** [NillerMedDild/Enigmatica2#389]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Issue**
I can’t use the Spice of Life: Carrot Edition commands (/foodlist size, /foodlist sync). It tells me that I don’t have permission to use /foodlist. How would I give myself the permission to use them? Also, shouldn’t they be able to be used by the player by default?

(I’m not an op or admin.)

**Comment by NillerMedDild** [comment]
You would have to OP yourself through the console, but that sounds like a bug.
Asked the dev about it here: https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues/49

**Comment by juliand665** [comment]
Commenting here as well for exposure. If you're running a recent version of SoL: C, you should find a craftable food book in jei which shows you how many and which foods you've eaten. In the next version (coming soon™), there will actually be a pretty visualization of your progress between milestones, so it'll completely replace `/foodlist size` for most people. I'll try to get the build out within the next couple hours, if possible.

**Comment by Dimentive** [comment]
Oh, wow, I had no clue that the Food Book was a thing. I’m crafting this right away!

Thanks for clearing it up.

**Comment by juliand665** [comment]
[The new update just got approved on CurseForge!](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition/files/2686895)

Let me know if you have any issues with it :)
