### ISSUE TITLE
Wrenching RFtools storage deletes it and all content

### ISSUE THREAD

**Issue by Saereth** [NillerMedDild/Enigmatica2#39]
#### Issue Description
 Wrenching and rftools modular storage completely deletes the block and its entire content.

#### Modpack version (Do not use "latest")
1.26c 

#### Crash Report
No crash
[pastebin/gist/etc link here]

**Comment by Lukas45** [comment]
That should have been for here: https://github.com/NillerMedDild/Enigmatica2Expert/issues (you did ask in the Normal discord channel, so I linked the Normal github).
But also know issue NillerMedDild/Enigmatica2Expert#95

Thanks for the report though!
