### ISSUE TITLE
Add @Pam'sHarvestcraft support for @ImmersiveEngineering fermenter and squeezer

### ISSUE THREAD

**Issue by EthernalVoid** [NillerMedDild/Enigmatica2#390]
I managed to cobble up a list, just exchange <modid:wasteSeed> for some waste material, i don't know how to add a fermenter recipe with no side output...

[QQQ.txt](https://github.com/NillerMedDild/Enigmatica2/files/2963400/QQQ.txt)

**Comment by NillerMedDild** [comment]
Thanks for your contribution :)
