### ISSUE TITLE
Modular Machinery not recognizing fluid input

### ISSUE THREAD

**Issue by CptTbone** [NillerMedDild/Enigmatica2#392]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Attempted to build in both my test world and survival mode gameplay. Following the blueprint and checking the build, the controller does not seem to recognize any of the various tier fluid input hatches available, yet recognizes what the machine I'm trying to build is. This is true for both the Advanced Thermionic Fabricator & Carpenter.

![image](https://user-images.githubusercontent.com/46872696/54319936-c48b9f00-45c1-11e9-9ae2-68ba95e2bfb4.png)

If this is a feature request, feel free to delete the template.

**Comment by CptTbone** [comment]
I should also add that there is pyrotheum fluid in said hatch.

**Comment by NillerMedDild** [comment]
What are you trying to craft, and what is it's recipe?

**Comment by CptTbone** [comment]
It's the multiblock structure recipe used for Modular Machinery Advanced Thermionic Fabricator. The issue appears to be with the input hatch regardless of tier.

**Comment by NillerMedDild** [comment]
But what are you actually trying to craft with it? According to the screenshot the multiblock formed correctly.

**Comment by CptTbone** [comment]
I haven't yet tried to craft anything with it at this point since it is acting as if I needed a fluid input, which is hooked up with the fluid hatch full of liquid pyrotheum. I'll try and run the machine now and see if perhaps that error goes away...stand by.

**Comment by CptTbone** [comment]
Ok...so, it was user error. Wrong fluid. It should've been liquid glass, not pyrotheum. Thanks for bearing with me.

**Comment by NillerMedDild** [comment]
Np :p
