### ISSUE TITLE
Drops sometimes disappear (and other weird behaviour)

### ISSUE THREAD

**Issue by Dimentive** [NillerMedDild/Enigmatica2#393]
**Modpack version**
1.62

**Can the issue be reproduced?**
Unknown

**Logs**
[latest.log](https://zerobin.net/?f2345c49b87258a3#Ov3r1O7tHRWcqJumEvqERXRPBmHOOIJDNYnOWDeCpUA=) (client)

The log was saved right after I mined a marble block that didn’t give me a drop.

**Issue**
Sometimes, when mining blocks or harvesting crops, I’ve noticed that they sometimes don’t drop anything—or the drops immediately disappear.

I’ve also noticed that my buckets empty themselves when I’m picking up a lot of liquid in several buckets at a time. This can happen a second or two after I’ve changed to a different bucket in my hotbar, so it’s not that I’m accidentally placing it down again.

**Comment by NillerMedDild** [comment]
The bucket thing sounds like a client desync, but the issue with drops I know about. We've been looking for the cause for weeks now, without luck.

**Comment by Dimentive** [comment]
Oh, okay. That’s a shame. I experienced the drops issue every once in a while when I played All the Mods 3 last year, too. I hope you find the cause.

**Comment by Dimentive** [comment]
I just opened a loot chest and didn’t get the items inside, too.

**Comment by Dimentive** [comment]
I just opened a loot chest that I got from a quest and didn’t get the items inside, too.

**Comment by NillerMedDild** [comment]
Still no news on this one I'm afraid.
