### ISSUE TITLE
Space and solar

### ISSUE THREAD

**Issue by sgtkwol** [NillerMedDild/Enigmatica2#394]
**Modpack version**
Skyblock 1.24

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
Solar will produce 24 hours per day on space station, except when raining in the overworld.

**Comment by NillerMedDild** [comment]
I wouldn't call that a bug :)

**Comment by sgtkwol** [comment]
Tested with solar neutron activators from mek.

**Comment by sgtkwol** [comment]
Why would rain on overworld cause loss of solar in space?

**Comment by NillerMedDild** [comment]
I'll report that part ^^

**Comment by NillerMedDild** [comment]
There we go:
https://github.com/zmaster587/AdvancedRocketry/issues/1542

I wasn't really thinking before replying to your issue it seems :P
