### ISSUE TITLE
Active cooling with fusion reactor NuclearCraft seem to not work

### ISSUE THREAD

**Issue by Aranak** [NillerMedDild/Enigmatica2#397]
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Issue**
The GUI of the reactor dosent show when i put active cooling, normaly its shows off in the temperature section. I'm using water and right now use a lot of active cooling block fill with water, at first i used few. In the Mod option the active cooling is ON, so it's dosen't seem to be an issue.

From what it seem, it's dosent work at all. Even when i remove the active coolers nothing change in the temperature. 

I will post what i have and what its supose to be.

my cooling
![image](https://user-images.githubusercontent.com/44117604/54495474-8391d400-48ba-11e9-9873-8377bbb5bf8c.png)

my temperature GUI 
![image](https://user-images.githubusercontent.com/44117604/54495491-ab813780-48ba-11e9-8ca7-ce85b7992c3a.png)

The mod creator GUI with active cooling and blue text
![image](https://user-images.githubusercontent.com/44117604/54495567-1cc0ea80-48bb-11e9-81ad-ae54a0bd8170.png)

Thank you very much, and if you need me to change the picture how they are on the post just ask. I will try to host them somehow.

My backup is put the reactor on automatic shutdown so no hurry :)

**Comment by NillerMedDild** [comment]
Hmm that is odd, I think you're doing it correctly. @turbodiesel4598 can you spot the problem? :)

**Comment by turbodiesel4598** [comment]
Yeh, looks fine to me - I'm unable to recreate this. Which version of NC is E2 1.58 using?

**Comment by NillerMedDild** [comment]
NuclearCraft-2.13e--1.12.2

**Comment by turbodiesel4598** [comment]
Have slightly changed the way active cooling is picked up by the core for the next release - I can only hope that this might fix the issue, as I can't fathom why this isn't working :P

**Comment by NillerMedDild** [comment]
Fingers crossed :D

**Comment by Aranak** [comment]
Wanted to say that maybe its could been working and its just the UI who dosent show up. And its so slow that i cant catch it.
