### ISSUE TITLE
Can't scan my rocket

### ISSUE THREAD

**Issue by XxZajoZzO** [NillerMedDild/Enigmatica2#398]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Issue**
When I press scan in the rocket assembling machine nothing happens.

https://i.imgur.com/hBn8k9D.png
https://i.imgur.com/YDYvu4Y.png

**Comment by NillerMedDild** [comment]
Could you try adding a few blocks of any kind to it?

**Comment by XxZajoZzO** [comment]
Tried random block from my inventory (Stone, granite, netherrack) still nothing

**Comment by NillerMedDild** [comment]
Try moving the setup I suppose.

**Comment by XxZajoZzO** [comment]
I moved it and still could not scan it so I cheated in more lauch pads and expanded the pad to 5x5 (from 3x3) and now it's scanning.
