### ISSUE TITLE
Shift clicking the planet id chip into the guidance computer will crash the game

### ISSUE THREAD

**Issue by XxZajoZzO** [NillerMedDild/Enigmatica2#399]
**Modpack version**
1.62

**Can the issue be reproduced?**
unknown

**Logs**
https://pastebin.com/7kcjtkph

**Issue**
If you shift click the planet id chip into the guidance computer the game will crash (Note: rocket was an entity when the crash happened, I didn't click on the computer block)

**Comment by NillerMedDild** [comment]
I'm aware of the issue, it should be resolved in the next update.
