### ISSUE TITLE
Twilight Forest Needing Oxygen

### ISSUE THREAD

**Issue by PB5011** [NillerMedDild/Enigmatica2#4]
#### Issue Description
Players need Oxygen to roam the Twilight Forest
#### What happens
Going into the Twilight Forest Gives a warning saying No Oxygen Detected while the player takes damage.
#### What you expected to happen
Be able to roam the Twilight Forest without the need of Oxygen. Not sure if this is the intended effect as I didn't notice any documentation about it.
#### Modpack version (Do not use "latest")
Version 1.20
#### Your most recent log file where the issue was present

[pastebin/gist/etc link here]
No log file that I could find, I just have a screen shot of it happening.

Screenshot:
![2017-12-15_01 04 43](https://user-images.githubusercontent.com/21052705/34030902-87328152-e134-11e7-8ab6-7806da5e24e9.png)

**Comment by NillerMedDild** [comment]
This is a known bug, I have it fixed in the dev build - Update coming asap.
Thank you for reporting.
