### ISSUE TITLE
Ender IO crashing with Rustic

### ISSUE THREAD

**Issue by VallenFrostweaver** [NillerMedDild/Enigmatica2#40]
#### Issue Description 
Server crashes on start.

#### Modpack version (Do not use "latest")
1.38
#### Crash Report

https://pastebin.com/bYBmD9NX

**Comment by NillerMedDild** [comment]
Sorry about the long wait, I've reported the issue.

https://github.com/SleepyTrousers/EnderIO/issues/4708
https://github.com/the-realest-stu/Rustic/issues/180
