### ISSUE TITLE
Mekanism - Part 2 quests aren't triggering upon crafting

### ISSUE THREAD

**Issue by vtilroe** [NillerMedDild/Enigmatica2#400]
**Modpack version**
1.62

**Can the issue be reproduced?**
unknown

**Logs**
n/a

**Issue**
"Mekanism - Part 2" quests aren't triggering upon crafting:
"Oxydizing sulfur" only triggered after spawning in a chemical oxidizer.  (Also "Oxydizing" is spelt incorrectly)
"Cobble-sulfur" didn't trigger either, and doesn't even recognize the 2 Crushers even after spawning them in.
There may be others...

**Comment by NillerMedDild** [comment]
Thank you for the report, I will fix it asap.
