### ISSUE TITLE
Having issues with quests completing even after updating to latest version

### ISSUE THREAD

**Issue by LinkTheLinker** [NillerMedDild/Enigmatica2#401]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Issue**
I am a co-owner of a modded minecraft server, and unfortunately some players, including me have been having issues with the mekanism part 1 quests, some of the tinkers quests, most of the quests within Beating Starvation and apparently the quest Annhilate! Formulate? #253. I have tried /bq_user refresh and it didn't fix it. I know you can just do the /bq_admin complete (quest id) (username) but this has gotten too tedious. I also did /bq_admin default load and it also didn't work.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by RagingCactus** [comment]
I am currently on version 1.60 and ran into similar issues. I didn't want to update my server, but also didn't want to report my issue with an old version.

Manually completing quests with `/bq_admin complete` got too tedious for me too, so I've tried a few things. What seemed to work (at least we didn't encounter more problems after it) was:
```
sed -i.bak 's/"groupDetect:1": 1/"groupDetect:1": 0/g' DefaultQuests.json
```
, so basically setting `groupDetect` to `0` (or false) on every quest.

I don't know if some quests were specifically designed to use `groupDetect` (which in my understanding means you need to have all required items at the same time?), but as a workaround it's better than a lot of quests not working.

**Comment by Dimentive** [comment]
I’m having the same issue. My friend can’t complete quests in the Mekanism Part 1 tree.

**Comment by Dimentive** [comment]
I’m having the same issue. My friend can’t complete quests in the Mekanism Part 1 tree.

**Modpack version:** 1.63a

**Comment by NillerMedDild** [comment]
Did you run the update command? `/bq_admin default load`

**Comment by Dimentive** [comment]
Yes, I did in the server console when I first updated to version 1.63a.
