### ISSUE TITLE
/spawn and /rtp

### ISSUE THREAD

**Issue by SpiritWolfie** [NillerMedDild/Enigmatica2#403]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes (My group was able to reproduce it repeatedly)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
We just installed the modpack on a freshly installed server (nothing extra)
Typing /spawn or /rtp seems to kick everyone offline

Note:
We are completely new to this mod pack, so if we have something set up incorrectly please let us know, we literary just set it up and been trying to find a mod pack that has things like direwolf 20 but more updated and less buggy xD
If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I can't seem to reproduce this issue.

**Comment by SpiritWolfie** [comment]
> 
> 
> I can't seem to reproduce this issue.

Ya sorry about that it's caused by having AMP (the control panel) running the pack. taking it off the control panel fixed the issue.

**Comment by NillerMedDild** [comment]
Ah alright.
