### ISSUE TITLE
Enigmatica 2 and 2 expert

### ISSUE THREAD

**Issue by RockFubar** [NillerMedDild/Enigmatica2#404]
**Modpack version**
1.62 and 1.58 

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Quest log does not recognize that the metallurgic infuser has been created. 

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Use the command `/bq_admin default load`

**Comment by NillerMedDild** [comment]
oh but update to 1.63 before using it.

**Comment by RockFubar** [comment]
Well couldn't update as it's not out of beta yet, so downloaded the beta. It still has some work. Charcoal doesn't stack in the fast furnace and you can't make stencils.

**Comment by NillerMedDild** [comment]
Errr what. Are you sure? I didn't even update FastFurnace, so it sounds unlikely.

**Comment by NillerMedDild** [comment]
Confirmed the Stencil bug, not the Furnace one.
