### ISSUE TITLE
JEI no longer shows ore gen tabs (added by JER) or Thaumcraft recipes (added by Thaumic JEI)

### ISSUE THREAD

**Issue by Dimentive** [NillerMedDild/Enigmatica2#407]
**Modpack version**
[1.63a](https://minecraft.curseforge.com/projects/enigmatica2/files/2691579)

**Can the issue be reproduced?**
Yes

**Issue**
After updating to version 1.63a of the pack, I’ve noticed that there are no ore gen tabs (added  by [Just Enough Resources](https://minecraft.curseforge.com/projects/just-enough-resources-jer)) when pressing the recipes button on an ore that spawns in the world in [JEI](https://minecraft.curseforge.com/projects/jei).

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Dimentive** [comment]
The Thaumcraft add-on for JEI, [Thaumic JEI](https://minecraft.curseforge.com/projects/thaumic-jei), is also not working in 1.63a. I don’t know if the same goes for any of the other JEI add-ons in this pack, but not every JEI add-on is broken (for instance, JEI Villagers and Block Drops are working).

**Comment by Graeme-L** [comment]
I came to report the world gen tab for ores no longer showing up in JEI and after seeing this report confirmed that I no longer see Thaumcraft recipes either.

**Comment by Graeme-L** [comment]
I came to report the world gen tab for ores no longer showing up in JEI (1.59a expert) and after seeing this report confirmed that I no longer see Thaumcraft recipes either.

**Comment by Dimentive** [comment]
The [Just Enough Resources](https://minecraft.curseforge.com/projects/just-enough-resources-jer) tabs not showing up is fixed by updating to the latest alpha version of the mod, [0.9.0.53](https://minecraft.curseforge.com/projects/just-enough-resources-jer/files/2693889). I haven’t yet tested if the same goes for [Thaumic JEI](https://minecraft.curseforge.com/projects/thaumic-jei), though, but that mod has also recently been updated (newest version: [1.5.6-24](https://minecraft.curseforge.com/projects/thaumic-jei/files/2693893)).
