### ISSUE TITLE
1.63a Mekanica quest All the Alloys! doesn't detect the Metallurgic Infuser

### ISSUE THREAD

**Issue by StefanArmand** [NillerMedDild/Enigmatica2#408]
**Modpack version**
1.63a

**Can the issue be reproduced?**
Unknown

**Logs**

**Issue**
The quest "All the alloys" doesn't detect/submit the metallurgic infuser. I've built two of them just to test if the ownership is the problem but it still can't detect it.

**Comment by NillerMedDild** [comment]
Did you use the reload command, `/bq_admin default load`?

**Comment by StefanArmand** [comment]
Yes, I did.

**Comment by NillerMedDild** [comment]
Damn, I'll look into it. Thanks for the report.

**Comment by StefanArmand** [comment]
Thank you :)

**Comment by RockFubar** [comment]
It's not recognizing the Crusher for Smashing the Power! either.

**Comment by DustRaven** [comment]
I think you should enable "ignore NBT" when detecting the item. I tried that, and it detected it :)

**Comment by RockFubar** [comment]
So I'm an idiot. How do I go about doing that?
    On Friday, March 29, 2019, 7:14:43 AM EDT, S Wulf <notifications@github.com> wrote:  
 
 
I think you should enable "ignore NBT" when detecting the item. I tried that, and it detected it :)

**Comment by DustRaven** [comment]
Uh sorry, i meant @NillerMedDild. There is an option in the detection of the quest progress. You can edit the quest yourself though :)

**Comment by DustRaven** [comment]
@NillerMedDild Apparently, most of the machines and items which can store NBT tags must be detected with ignored NBT.

**Comment by NillerMedDild** [comment]
It's not that simple, Mekanism defines it's machines in the NBT tag.

**Comment by Dimentive** [comment]
I’m having the same issue.

**Comment by NillerMedDild** [comment]
Please don't add that "me too" comment, it adds nothing to a confirmed issue, but still notifies me.
