### ISSUE TITLE
Nutrition JSON outdated

### ISSUE THREAD

**Issue by azaquaz** [NillerMedDild/Enigmatica2#409]
**Modpack version**
1.63a

**Can the issue be reproduced?**
Yes

**Issue**
The JSON files for adding nutrients to food are outdated, so some more recently added harvestcraft foods have no values. Fixing this is as simple as deleting the config>nutrition>nutrients folder and relaunching, but updating this pack rewrites it with the old version again every time.

**Comment by NillerMedDild** [comment]
We made additions to the json as well, so I hope they're included.

**Comment by azaquaz** [comment]
Comparing https://github.com/NillerMedDild/Enigmatica2/blob/master/config/nutrition/nutrients/vegetable.json and https://github.com/WesCook/Nutrition/blob/1.12/src/main/resources/assets/nutrition/configs/nutrients/vegetable.json etc... 
It doesn't seem like there's anything in your configs that aren't in Nutrition's latest, other than BoP ambrosia and other items that no longer exist. Oh, and tofacon and tofeeg are no longer vegetables.
