### ISSUE TITLE
[Suggestion] Minor mod suggestions

### ISSUE THREAD

**Issue by Dimentive** [NillerMedDild/Enigmatica2#410]
I know that no major mods will be added to any of the Enigmatica 2 packs as they are so big already, so I’m suggesting minor mods such as performance-improvement mods, bug-fix mods, and mods with simple features.

### [VanillaFix](https://minecraft.curseforge.com/projects/vanillafix) (client- and server-side)

This mod has various performance improvements, one of which causes the game to only tick animated textures **in view**, so that animated textures can’t cause any lag or frame rate issues when the player isn’t looking at them. This is the same as OptiFine’s “smart animations” feature and is a nice middle-ground between using animated textures and disabling them completely.

It also implements a variety of bug fixes. One other thing the mod does, however, is that it causes crashes to not close the entire game—only the world, saving a lot of time. It also automatically provides a link to a paste of the crash log so that players can easily report the crash. This mod is both server-side and client-side, as some of its features only work on the server, while some only affect the client.

### [Better Than Mending](https://minecraft.curseforge.com/projects/better-than-mending) (server-side)

This simple mod lets you sneak-right-click while holding a tool or weapon enchanted with Mending to repair it with XP you already have, rather than Mending tools and weapons only being repaired upon picking up XP.

### [Mending Fix](https://minecraft.curseforge.com/projects/mending-fix) (server-side)

In vanilla, if you use a tool or weapon with Mending, it randomly selects an item to be repaired, and if the item it selects happens to have full durability, nothing is repaired. This mod makes Mending only try to repair items that actually need to be repaired.

### [HelpFixer](https://minecraft.curseforge.com/projects/helpfixer) (server-side)

Correctly sorts listed commands when using the /help command.

### [Lapis Stays in the Enchanting Table](https://minecraft.curseforge.com/projects/lapis-stays-in-the-enchanting-table) (client- and server-side)

Makes lapis lazuli stay in the enchanting table, similar to how Tinkers’ Construct’s crafting station works. It also adds an Ender enchanting table, which functions similar to an Ender chest and lets players access their lapis lazuli from any Ender enchanting table.

### [NetherPortalFix](https://minecraft.curseforge.com/projects/netherportalfix) (server-side)

Keeps track of what Nether portals players go through so that when they exit, they come out from the same portal that they entered.

### [Login Shield](https://minecraft.curseforge.com/projects/login-shield) (server-side)

Prevents players from dying while loading a world or logging in to a server by making players invulnerable until they are able to interact with the world. Also saves the player from dying in the Void while loading the world. Very configurable.

### [Crafting Tweaks](https://minecraft.curseforge.com/projects/crafting-tweaks) (client- and server-side)

Adds three (well, six, since you can shift-click them) useful buttons to the crafting table GUI (including Tinkers’ Construct’s crafting station). For instance, one can clear the crafting grid and get one’s items out of it quickly or balance the grid to create as many of an item as one can afford without having to do it manually.

**Comment by Dimentive** [comment]
Also, the [Ranged Pumps](https://minecraft.curseforge.com/projects/ranged-pumps) mod would be nice to see in Enigmatica 2. This mod adds only one block: a block that pumps liquids near it to its inventory and any connected inventory.

It’s similar to the Ender-Thermic Pump from Extra Utilities 2, which was removed from the mod sometime last year, for some reason.

**Comment by NillerMedDild** [comment]
I'll consider Mending Fix and re-adding Lapis Stays in the Enchanting Table.

**Comment by Dimentive** [comment]
Another mod suggestion that would be very useful in Enimatica 2 is [ME Capability Adapter](https://minecraft.curseforge.com/projects/capability-adapter). This is another mod that only adds one block. It adds compatibility between Compact Machines and Applied Energetics 2, allowing for ME connections between the overworld and compact machines.

**Comment by Dimentive** [comment]
Another mod suggestion that would be very useful in Enimatica 2 is [ME Capability Adapter](https://minecraft.curseforge.com/projects/capability-adapter). This is another mod that only adds one block, so it’s not very resource-intensive. It adds compatibility between Compact Machines and Applied Energetics 2, allowing for ME connections between the overworld and compact machines.

**Comment by Dimentive** [comment]
Re-adding? Why did you remove Lapis Stays in the Enchanting Table from the modpacks? Just curious.

**Comment by Dimentive** [comment]
“Re-adding”? Why did you remove Lapis Stays in the Enchanting Table from the modpacks? Just curious.

**Comment by NillerMedDild** [comment]
ME Capability Adapter is already in the modpack.

I removed Lapis Stays in the Enchanting Table because I was trimming the modlist, and had a hope removing a lot of the smaller mods would have an impact on performace. I don't think it did make a difference though.

**Comment by Dimentive** [comment]
Would you consider adding [Cloche Call](https://minecraft.curseforge.com/projects/cloche-call) to the pack? It’s an add-on for Immersive Engineering that adds more compatibility between various mods and Immersive Engineering’s garden cloche. For instance, it lets players grow Rustic’s chili and tomato seeds in the cloche, as well as Natura’s cotton and barley. It also adds some compability between mods and IE’s industrial squeezer. There’s also optional tree support for growing saplings in the garden cloche. Every single change that this mod makes can be disabled and configured in the config. Cloche Call adds no blocks, items, or entities (as far as I know), so it shouldn’t make an impact on performance or loading times.

**Comment by NillerMedDild** [comment]
Yes, I will consider it.

**Comment by Dimentive** [comment]
Another mod suggestion that I have is [Waila Harvestability](https://minecraft.curseforge.com/projects/waila-harvestability). It’s a client-side mod and an add-on for Hwyla. It’s extremely useful.

**Comment by Dimentive** [comment]
I have two more mod suggestions:

* [**Waila Harvestability**](https://minecraft.curseforge.com/projects/waila-harvestability), a client-side mod and an add-on for Hwyla. Shows what tool is needed to break a block, the harvest level of a block, and whether you can break it.
* [**Phosphor**](https://minecraft.curseforge.com/projects/phosphor), a server-side mod that optimizes Minecraft’s lighting engine to improve performance. This is _especially_ effective in the Twilight Forest.
