### ISSUE TITLE
Frequent “Error executing task” crashes

### ISSUE THREAD

**Issue by Dimentive** [NillerMedDild/Enigmatica2#411]
**Modpack version**
1.63a

**Can the issue be reproduced?**
Unknown

**Logs**
Crash report: https://pastebin.com/raw/jDTmfez2

**Issue**
Almost every time right after I leave my server—and sometimes right after I _join_ my server (which is what I had done when my most recent crash happened), my client crashes with an “Error executing task” error. It’s also happened in the middle of playing, as well, not just when leaving or joining the server.

Also, when this happens, I get exactly the same crash three to four times in a row, simultaneously.

I have added a few mods to the pack, so it might not be an issue with any of the mods in Enigmatica 2.

**Comment by NillerMedDild** [comment]
The crash report doesn't say anything meaningful, I can't help you. You should however make sure your game uses new Java, not 1.8_51

**Comment by Dimentive** [comment]
I used to use the correct Java version. It looks like the Twitch beta update reverted it back to the old Java version. That was a while ago, and I didn’t even notice. I’ll change it right away.

Thanks for pointing it out!

I don’t know if using 1.8_201 will fix these crashes (it probably won’t), but I guess I’ll just have to live with it.

**Comment by Dimentive** [comment]
I used to use the correct Java version. It looks like the Twitch beta update reverted it back to the old Java version. That was a while ago, and I didn’t even notice. I’ll change it right away.

Thanks for pointing it out!

I don’t know if using 1.8.0.201 will fix these crashes (it probably won’t), but I guess I’ll just have to live with it.

**Comment by Dimentive** [comment]
I used to use the correct Java version. It looks like the Twitch beta update reverted it back to the old Java version. That was a while ago, and I didn’t even notice. I’ll change it right away.

Thanks for pointing it out!

Anyway, I don’t know if using 1.8.0.201 will fix these crashes (it probably won’t), but I guess I’ll just have to live with it.

**Comment by Dimentive** [comment]
I still get similar crashes out of the blue, even when I use the latest Java version (Java 8, version 201). [Here’s the one that happened just now.](https://pastebin.com/raw/9uRcEna9) Every time this happens, I get the same crash two–four times simultaneously, and I have no idea why.

I know you said that the report doesn’t say anything meaningful, but is there no way I could possibly figure out what’s causing this? I couldn’t find any errors or anything out of the ordinary in the log before the crashes happened.

**Comment by NillerMedDild** [comment]
You can start removing mods and see if you can reproduce it, that's about it. It could be caused by Optifine btw, though nothing in the log indicates any particular mod is at fault.
