### ISSUE TITLE
Cannot craft MalisisDoors’ vanilla wood trapdoors

### ISSUE THREAD

**Issue by Dimentive** [NillerMedDild/Enigmatica2#412]
**Modpack version**
1.63a

**Can the issue be reproduced?**
Yes

**Issue**
When trying to craft the different trapdoors made with non-oak vanilla wood, added by [MalisisDoors](https://minecraft.curseforge.com/projects/malisisdoors), it always results in a regular vanilla oak wood door, regardless of which wood type and crafting table are used. This has been the case since I started playing the pack (so, before 1.63a).

![Trapdoor recipe broken (cropped)](https://user-images.githubusercontent.com/34230933/55274003-37d82500-52d3-11e9-9aa0-9b930bfcb808.png)

**Comment by NillerMedDild** [comment]
You can use the Forestry Workbench to cycle through recipes for now :)

**Comment by Dimentive** [comment]
I didn’t know about that. That’s pretty neat.

Still, I wonder why you didn’t fix this in [1.64](https://minecraft.curseforge.com/projects/enigmatica2/files/2697889).

**Comment by NillerMedDild** [comment]
I didn't have time, and I haven't thought of a good fix yet.

**Comment by Dimentive** [comment]
Couldn’t it just be fixed by removing the vanilla trapdoor recipe (`recipes.remove(<minecraft:trapdoor>);`) and adding a recipe for each type of trapdoor from MalisisDoors with CraftTweaker?

**Comment by Dimentive** [comment]
Couldn’t it just be fixed by removing the vanilla trapdoor recipe (`recipes.remove(<minecraft:trapdoor>);`) and adding a recipe for each type of trapdoor from MalisisDoors with CraftTweaker? It might also be fixed by simply removing the vanilla trapdoor recipe, as MalisisDoors should add recipes for each trapdoor on its own, but I’m not 100% sure.

**Comment by NillerMedDild** [comment]
I would have to remove the oredict recipe for trapdoors, meaning I would have to readd trapdoor recipes for all Biomes O' Plenty and Forestry/Binnie's woodtypes.

**Comment by Dimentive** [comment]
I can see how that’d be tedious, but MalisisDoors’ trapdoors are all registered as trapdoorWood in the OreDictionary, so I don’t think you’d have to remove any recipes aside from the recipe for the vanilla trapdoor, unless I’m misunderstanding.

**Comment by NillerMedDild** [comment]
The reason all planks produce the vanilla trapdoor at the moment, is because there's a recipe that says any 6 planks -> vanilla trapdoor. I would have to remove that recipe and readd them all manually to fix it.
