### ISSUE TITLE
Incorrect quest reference to crafting creative item

### ISSUE THREAD

**Issue by pkmnfrk** [NillerMedDild/Enigmatica2#414]
**Modpack version**
1.63a

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
The description of the NuclearCraft -> Fusion Core quest says "You will need the Neutron fluid it produces as a byproduct for the Creative Tank", but as near as I can tell, no such recipe exists.

My guess is that this is pertinent to the Expert pack? This text should either be corrected, or recipes should be added for creative items :)

![image](https://user-images.githubusercontent.com/1333816/55291927-8f00f700-53b2-11e9-970b-36fa48b4ef28.png)

**Comment by NillerMedDild** [comment]
Woops, I'll get that fixed, thanks.

**Comment by Dimentive** [comment]
It’d be pretty nice if there were recipes for creative items in Enigmatica 2, just like in Expert.

**Comment by NillerMedDild** [comment]
There are no items hard enough to obtain in E2 for use in creative item recipes, imo.
