### ISSUE TITLE
Update Minecolonies Scripts

### ISSUE THREAD

**Issue by Foxtrot2Nov** [NillerMedDild/Enigmatica2#415]
I saw an update in January had been tried but there were some bugs; there's been a couple of release candidates put out since then that fix several of the current issues in the .68 version (minecolonies-1.12.2-0.10.68-RELEASE-universal.jar) being used and also implement some new features. Any thought/interest in updating to the newest release candidate (minecolonies-1.12.2-0.10.202-RELEASE-universal.jarminecolonies-1.12.2-0.10.202-RELEASE-universal.jar, released Feb 26 2019)?

**Comment by NillerMedDild** [comment]
The issue is that Minecolony versions past 68-release (iirc) have moved some building blocks into another mod, meaning a ton of current builds will be ruined. I can't do that in good conscience.

**Comment by Foxtrot2Nov** [comment]
Thanks for the fast response! And alright, makes perfect sense. Thanks again for the response!

**Comment by NillerMedDild** [comment]
Sure thing :)

**Comment by SWATr** [comment]
> 
> 
> The issue is that Minecolony versions past 68-release (iirc) have moved some building blocks into another mod, meaning a ton of current builds will be ruined. I can't do that in good conscience.
 
Could you possibly revisit this? I manually updated and everything loaded fine. Structurize appears to be packaged with minecolonies.

**Comment by NillerMedDild** [comment]
I can't test it myself, would you mind testing it? The steps would be: 
* create world with Minecolonies 68
* place some of the unique building blocks from Minecolonies.
* save and close Minecraft
* update Minecolonies 
* launch Minecraft and join the world.
If the Minecolonies blocks are still there, we can update :)

**Comment by SWATr** [comment]
No problem, I have tested it again and took some screenshots for you. There were a few errors but nothing seems to be missing.

Results:
https://imgur.com/a/AdGgbxr

**Comment by NillerMedDild** [comment]
Perfect, thank you.

**Comment by Sadumon** [comment]
Note that a few of the recipe conflict scripts in /scripts/RecipeConflicts.zs need to be updated with the move to parts of the mod in "Structurize".  Specifically, the building and scan tool were moved to structurize from minecolonies:

```
# Building Tool / Builder's Wand Stone
	recipes.remove(<structurize:sceptergold>);
	recipes.addShapedMirrored("structurize_sceptergold_custom", 
	<structurize:sceptergold>, 
	[[null, null, <ore:ingotCopper>], 
	[null, <minecraft:stick>, null], 
	[<minecraft:stick>, null, null]]);

# Scan Tool / Builder's Wand Iron
	recipes.remove(<structurize:sceptersteel>);
	recipes.addShapedMirrored("structurize_sceptersteel_custom", 
	<structurize:sceptersteel>, 
	[[null, null, <ore:ingotTin>], 
	[null, <minecraft:stick>, null], 
	[<minecraft:stick>, null, null]]);
```

With the above fix we updated in place and had no other noticeable issues, and many on our server are heavily using minecolonies.

**Comment by NillerMedDild** [comment]
Excellent, thank you.
