### ISSUE TITLE
Applied Energestics 2 cable facades cannot be crafted with certain Chisel factory blocks

### ISSUE THREAD

**Issue by Dimentive** [NillerMedDild/Enigmatica2#416]
**Modpack version**
1.63a

**Can the issue be reproduced?**
Yes

**Issue**
Although most Chisel blocks can be crafted into Applied Energestics 2 cable facades, there are some that can’t.

Chisel has five different item IDs assigned to its factory blocks: `factory`, `factory1`, `technical`, `technical1`, and `technicalnew` (which are all either the factory block or chiselled versions of it). In Enigmatica 2, you can craft cable facades with the `factory`, `factory1`, and `technicalnew` blocks from Chisel, but you _cannot_ with its `technical` and `technical1` blocks.

Simply adding the following to `AppliedEnergestics2\Facades.cfg` fixes the issue and lets players craft AE2 cable facades with any Chisel factory block.

        chisel {
            I:technical=16
            I:technical1=16
        }

There may be other Chisel blocks that don’t work with AE2 cable facades in this pack, but I’m not aware of any.

**Comment by NillerMedDild** [comment]
Have you tried making those facades after editing the configs? I have a feeling they're animated, and that's why they're not included by default.

**Comment by Dimentive** [comment]
Yes, I tried crafting the facades after editing the config, and it worked. 🙂

**Comment by NillerMedDild** [comment]
Alright nice, and they didn't cause issues when placed?

**Comment by Dimentive** [comment]
No, they didn’t. They work and appear as expected.
