### ISSUE TITLE
Game Crash when selling iron

### ISSUE THREAD

**Issue by ashboy3093** [NillerMedDild/Enigmatica2#418]
**Modpack version**
Engimatica 2 1.63a

**Can the issue be reproduced?**
Unknown

**Logs**
https://pastebin.com/MK8EK5gg

**Issue**
I was using the Village Market block and tried to sell iron. It crashed my game after causing it to freeze a few times. It works for other merchant sales.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Sorry for the wait, your issue slipped past me :)
Can you reproduce it?

**Comment by ashboy3093** [comment]
Seems my original response did not go through. Yes I have done it on the same seed in different villages as well as a different seed. It does work some of the time but other times it will freeze a few times and then crash the game. All the crash reports look the same.

**Comment by NillerMedDild** [comment]
Can you reproduce it without Optifine?
