### ISSUE TITLE
Chest gui

### ISSUE THREAD

**Issue by loadstones** [NillerMedDild/Enigmatica2#42]
When looking in a chest the contents become invisible after a few seconds. If you click on a populated square, sort the contents, or close and reopen the icons return, then a few seconds later they're  gone again. It is doing this with both  vanilla and iron chests. I noticed it first on a mp, but tested on a sp as well. Other inventories seem fine.

version 1.38

**Comment by loadstones** [comment]
The only non stock thing I did was used a resource pack, I removed it and
still get the issue. Not sure which log you are asking for it doesn't
crash, just the video glitch. I had copied the world save from the server
to the local client to test SP but today I will uninstall the local client
and reinstall to see if that is the problem. If not I will reinstall the
server and start a new world and test it ( hopefully not a corrupted world
file). I will let you know what I find.

Thanks for all your work this is a great pack so far.

**Comment by loadstones** [comment]
So I reinstalled both server and client and used old world file and still
had issue. Then reinstalled everything again with new world and problem was
gone so must have been a corruption in my world. Thanks again for your help
and keep up the good work.

**Comment by NillerMedDild** [comment]
Thanks for your extensive testing, I'm glad you got it working. I'll try to find the cause of the issue.

**Comment by TheLostInPlace** [comment]
My friends and I just experienced the same issue. No other mods installed.
