### ISSUE TITLE
Game crash when loading block

### ISSUE THREAD

**Issue by Willsr71** [NillerMedDild/Enigmatica2#420]
**Modpack version**
1.62

**Can the issue be reproduced?**
unknown

**Logs**
https://hastebin.com/izuxiyehif.rb

**Issue**
When loading the chunk in the crash report, the server crashes. I'm not really sure what caused it in the first place.

**Comment by NillerMedDild** [comment]
Updating should fix your issue :)

**Comment by Willsr71** [comment]
Updated to 1.63a, crash is still occurring

**Comment by NillerMedDild** [comment]
Damn. Can Astral Sorcery be updated, or is it the latest already?

**Comment by Willsr71** [comment]
The modpack version is 1.10.11, latest is 1.10.12, and apparently fixes the issue https://minecraft.curseforge.com/projects/astral-sorcery/files/2692104

**Comment by NillerMedDild** [comment]
Woops, I'll update asap :)
