### ISSUE TITLE
Missing Recipe

### ISSUE THREAD

**Issue by Starwind65** [NillerMedDild/Enigmatica2#423]
**Modpack version**
1.63a

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
Am unable to craft Backpack mod's stone sticks. There is no recipe according in JEI, nor does the item exist in JEI.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Use the Tinkers' Construct Stone Rods instead, the Backpack variety is disabled to avoid duplicates.

**Comment by Starwind65** [comment]
I tried using both TInker's Stone Rods and Stone Tool Rods. Neither one would output a valid item (backpack frame).

**Comment by NillerMedDild** [comment]
Okay then, that sounds like a bug.

**Comment by Starwind65** [comment]
Did this get fixed in the 164 beta, or is it marked closed for some other reason?

**Comment by NillerMedDild** [comment]
I forgot to reopen it, my apologies.

**Comment by NillerMedDild** [comment]
Fixed for real this time, the Tinkers' Stone Rod should work (the normal recipe one)
