### ISSUE TITLE
Custom main menu issue

### ISSUE THREAD

**Issue by JustLiam040** [NillerMedDild/Enigmatica2#424]
**Modpack version**
1.63a

**Can the issue be reproduced?**
Yes

**Logs**
N/A (not a crash)

**Issue**
I'm not sure if this is an exclusive issue so i figured id post it here? Me and my friend have just begun playing enigmatica and he has been experiencing this issue also; for some reason the main menu is all squished and out of frame, this happened to me a few months back before i uninstalled and is still present upon a reinstall. I will attach a screenshot of the menu i am referring to.
* This issue occurs whether i am in windowed or fullscreen.

![2019-04-09_17 03 47](https://user-images.githubusercontent.com/33065753/55816121-78148000-5ae9-11e9-8c0a-68ff0424fbff.png)

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
The main menu is affected by your GUI size, you can set it in Video Settings :)
I know it doesn't work equally well with all sizes, but it's a pain to configure for all the different sizes to be honest.
