### ISSUE TITLE
Readd Bread Recipe

### ISSUE THREAD

**Issue by JFMillerUSA** [NillerMedDild/Enigmatica2#425]
**Modpack version**
1.63a

**Can the issue be reproduced?**
Yes

**Issue**
MineColonies bread recipe is broken, can you change back to vanilla recipe

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
I wasn't aware MineColonies even had bread, do you mind giving me a screenshot of the recipe?

**Comment by Dimentive** [comment]
Minecolonies doesn’t have a bread item. They may be referring to vanilla bread made in Minecolonies’ [bakery](https://wiki.minecolonies.com/source/buildings/bakery). I’m not too familiar with the mod, so I can’t confirm.

**Comment by JFMillerUSA** [comment]
It's vanilla recipe, pam's harvestcraft and I think cooking or farming for
blockheads changes the recipe. So the NPCs from minecolonies will not craft
bread.

**Comment by NillerMedDild** [comment]
Is it essential that they can make bread?

**Comment by JFMillerUSA** [comment]
They keeping telling me their hungry. I manually have to make it with
current recipes. Not a big deal I guess. Lol

**Comment by NillerMedDild** [comment]
That sounds annoying, I'll fix it for the next update :P
