### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BlackHoleTON618** [NillerMedDild/Enigmatica2#430]
**Modpack version**
1.6.0

**Can the issue be reproduced?**
unknown
**Logs**
[2019-04-12-3.log](https://github.com/NillerMedDild/Enigmatica2/files/3072843/2019-04-12-3.log)

**Issue**
crash when i update my game i re installed it minecraft java everything

**Comment by NillerMedDild** [comment]
Reinstall the instance, it looks like you have duplicate mods :)

**Comment by BlackHoleTON618** [comment]
[2019-04-12-4.log](https://github.com/NillerMedDild/Enigmatica2/files/3072934/2019-04-12-4.log)

**Comment by BlackHoleTON618** [comment]
i checked it nothing is duplicated

**Comment by NillerMedDild** [comment]
Your mod folder does not contain two EnderCore files?

**Comment by BlackHoleTON618** [comment]
i have 1.12.2. 0.5.53

**Comment by NillerMedDild** [comment]
And you've tried reinstalling the instance?

**Comment by BlackHoleTON618** [comment]
6 times

**Comment by BlackHoleTON618** [comment]
only i didint changed saves folder

**Comment by NillerMedDild** [comment]
Yikes. Could you upload the latest.log please?

**Comment by NillerMedDild** [comment]
So on a complete fresh install, does the issue still occur? You can just move your saves folder there after checking.

**Comment by BlackHoleTON618** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/3072962/latest.log)
here you are

**Comment by BlackHoleTON618** [comment]
okey ill try that without saves
