### ISSUE TITLE
Advanced Rocketry space station not appearing

### ISSUE THREAD

**Issue by wased321** [NillerMedDild/Enigmatica2#432]
**Modpack version**
1.63a

**Can the issue be reproduced?**
unknown

**Logs**

**Issue**
Me and my friend cant get a space station to appear, we've done everything right but when we launch ourselves into space with the space station container, it doesn't appear. (we've also tried launching the container first and then launching ourselves but that doesn't work either)

Im playing on MineWonderland MC version: 1.12

**Comment by NillerMedDild** [comment]
Comprehensive screenshots would be helpful :)

**Comment by wased321** [comment]
I have everything I need to launch it here, I've launched two space stations and both of them didnt work.
![0cb41890fe4cd1d7433a4fcd3ad90077](https://user-images.githubusercontent.com/49594061/56083391-58839d00-5df2-11e9-980a-10d829c29764.png)
![237dce3cf9ba84d814c77203aa77a491](https://user-images.githubusercontent.com/49594061/56083392-59b4ca00-5df2-11e9-99a7-6565947d733f.png)
![f39219ee574d9bb9acafb76f3d50bd16](https://user-images.githubusercontent.com/49594061/56083393-5a4d6080-5df2-11e9-9a42-d1ff593aa881.png)

**Comment by NillerMedDild** [comment]
And you used the Space Station ID Chips to travel to them after you launched them?

**Comment by wased321** [comment]
The first time my friend didn't put the ID in the rocket that had the container in it, and then he used the ID to go to the station but it didnt appear. The second time we made another station and went with the rocket that had the container in it.

**Comment by NillerMedDild** [comment]
Please see this guide: http://arwiki.dmodoomsirius.me/AdvancedRocketry/guides/BuildingSpaceStation.php

**Comment by wased321** [comment]
I did everything the guide told me to, I sent up a rocket with the space station container, and then used the Space Station chip to go to them and it still didnt appear.

**Comment by NillerMedDild** [comment]
Alright then, I'll see what's going on with it when I get some time :)

**Comment by wased321** [comment]
Extra: I got it to work in single player but it wont work in the server im playing in, and it's not banned.

**Comment by NillerMedDild** [comment]
I'm guessing it's a SpongeForge server?

**Comment by wased321** [comment]
I dont think it is but I can't tell.

**Comment by phit** [comment]
this will happen on SpongeForge if the server isn't configured properly, not a pack or mod issue
https://github.com/zmaster587/AdvancedRocketry/issues/1297#issuecomment-390043866
