### ISSUE TITLE
Game crash everytime when trying to break enderio alloy smelter

### ISSUE THREAD

**Issue by zbb5049** [NillerMedDild/Enigmatica2#433]
**Modpack version**
1.60

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable
/gGQchvz0

**Issue**
Input short description of the issue here
game crash everytime when trying to break ender-io alloy smelter
can be fixed by remove alloy furnace entities in mcedit

**Comment by NillerMedDild** [comment]
Please supply the crash report or a link to it.

**Comment by NillerMedDild** [comment]
If you're wearing a magnet ring, the issue will be fixed in a moment :)

**Comment by braustin01** [comment]
I am having the same issue and I am wearing a magnet ring. I have attached my crash report
[crash-2019-04-16_11.41.48-server.txt](https://github.com/NillerMedDild/Enigmatica2/files/3085411/crash-2019-04-16_11.41.48-server.txt)

**Comment by NillerMedDild** [comment]
The update has been delayed, sorry :/ updating Botania fixes this issue, or removing the magnet ring.
