### ISSUE TITLE
Game freezes and crashes upon exiting world and then entering any world

### ISSUE THREAD

**Issue by Dimentive** [NillerMedDild/Enigmatica2#434]
**Modpack version**
[1.65a](https://minecraft.curseforge.com/projects/enigmatica2/files/2700051) (latest)

**Can the issue be reproduced?**
Unknown

**Logs**
**Crash report:** https://pastebin.com/raw/fzWxHJpc
**Relevant part of log (upon trying to join a world after exiting one):** https://pastebin.com/raw/arCDKK9i

**Issue**
Whenever I join my survival world and exit it, I cannot enter any other world, whether it’s a different world or the same world (although I can create a new world with no problems), as my game freezes on “Loading World.” Then, my game is “not responding” forever, and I can’t even open the window again if I alt-tab out.

In case my description isn’t clear, here’s what causes this crash:

1. I join my survival world. I can play just fine.
2. I leave the world.
3. I re-enter the world or enter _another_ world. Either way, my game crashes every time upon doing so.

Even though my game doesn’t exit to the launcher, it still gives a crash report (in fact, it gives me two crash reports in a row).

As you can see, it’s a `java.lang.OutOfMemoryError` crash. However, I’ve allocated 7 GB of RAM, which is more than enough, as my game usually only uses about 66% of that RAM. I have no memory or performance issues aside from this issue with joining worlds. This problem is incredibly frustrating, as I have to restart my client every time I want to leave my world for any reason, whether it’s because of a bug that requires re-logging (such as the infamous [ghost block bug](https://bugs.mojang.com/browse/MC-5694)) or to test something in my creative test world. It takes eight and a half minutes to launch the pack, so I don’t want to have to relaunch every time I exit my world.

The crash report doesn’t really tell you much; however, the log has a lot of messages from Recurrent Complex. I’m not sure if that mod is the cause of this problem, but [I reported it on Recurrent Complex’s issue tracker](https://github.com/Ivorforce/RecurrentComplex/issues/389).

I’m using these JVM arguments:
`-XX:+UseConcMarkSweepGC -XX:ParallelGCThreads=4 -XX:+DisableExplicitGC -XX:+CMSIncrementalMode -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=35`

The next time I relaunch the game, I’ll try using different JVM arguments and see if that fixes this.

#### Versions

* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version 1.65a, latest)
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **IvToolkit:** [1.3.3](https://minecraft.curseforge.com/projects/ivtoolkit/files/2443253) (latest)
* **Recurrent Complex:** [1.4.8.2](https://minecraft.curseforge.com/projects/recurrent-complex/files/2689602) (latest)

**Comment by Dimentive** [comment]
I’ve updated the issue with more information.

**Comment by NillerMedDild** [comment]
Is your modpack instance default, or did you make changes?

**Comment by Dimentive** [comment]
I have made no changes in terms of configs, aside from changing FTB Utilities’ backup settings, but I have added mods to the pack. You can see my mod list in the linked crash report.

I tried launching the game with the following JVM arguments (from [this](https://www.reddit.com/r/feedthebeast/comments/5jhuk9/modded_mc_and_memory_usage_a_history_with_a/) thread by one of the Forge developers) but to no avail:
`-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=35 -XX:G1HeapRegionSize=32M`

Because I’ve added mods to the pack, you will probably close this—that’s all right. I’ve reported this [on Recurrent Complex’s issue tracker](https://github.com/Ivorforce/RecurrentComplex/issues/389) as the log mentions Recurrent Complex quite a lot when my game freezes. Recurrent Complex could easily have nothing to do with this problem, but I hope it does, because if not, I have no clue what could be causing it.

**Comment by NillerMedDild** [comment]
I will indeed close this, I doubt Recurrent Complex has anything to do with it, but I wish you luck.

**Comment by Dimentive** [comment]
Asking for help with any issue on [r/feedthebeast](http://reddit.com/r/feedthebeast) isn’t allowed anymore, so I’m not sure if I’ll get help.

**Comment by Dimentive** [comment]
@NillerMedDild I exited and re-entered my world again, but this time, I waited for a while (about 7 minutes), and for the first time, it gave me [a longer crash report](https://pastebin.com/raw/KHCwuui5) with a suspected mod: [Tips](https://minecraft.curseforge.com/projects/tips). It’s still a `java.lang.OutOfMemoryError` crash, but it now says “Updating screen events“ instead of “Unexpected error.”

However, I disabled Tips, launched my game again, and then entered a world, exited it, and re-entered it; my game still froze, so Tips seems to have been a false positive.

**Comment by Dimentive** [comment]
@NillerMedDild I tried exiting and re-entering my world in a fresh install of the pack (no mods added, no mods removed or disabled, and no config changes made whatsoever), and my game still froze.

Could you re-open this issue?

**Comment by NillerMedDild** [comment]
Sure, please provide the latest.log.
