### ISSUE TITLE
MineColonies NPCs go invisible

### ISSUE THREAD

**Issue by JFMillerUSA** [NillerMedDild/Enigmatica2#437]
**Modpack version**
1.65a

**Can the issue be reproduced?**
Yes

**Issue**
When changing Dimensions, going back to overworld NPCs either disappear or are Invisible. Only way to fix it is to shut down local server and restart.

**Comment by NillerMedDild** [comment]
How did you change dimensions in this particular case?

**Comment by JFMillerUSA** [comment]
The Nether, The End, Compact Machines and Deep Dark

**Comment by NillerMedDild** [comment]
And a relog fixes it?

**Comment by JFMillerUSA** [comment]
Yes, just a pain to do it over and over again

**Comment by NillerMedDild** [comment]
Absolutely, but I'm afraid I am unable to fix this issue, I've tried many times.

**Comment by JFMillerUSA** [comment]
I think I found a fix that works. changes in minecolonies.cfg file

        # Should colonies in other dimensions be allowed (Default = false)?
        B:allowOtherDimColonies=true

doesn't seem to work on Compact Machine they still go invisible going back
to overworld

**Comment by NillerMedDild** [comment]
That config makes them render correctly?

**Comment by JFMillerUSA** [comment]
Yes, changed it and went back and forth from the end and the nether and
they showed up

**Comment by NillerMedDild** [comment]
Cool, changed :)
