### ISSUE TITLE
Tile Entities behave wrong under water

### ISSUE THREAD

**Issue by realmayus** [NillerMedDild/Enigmatica2#439]
**Modpack version**
Newest version

**Can the issue be reproduced?**
Yes, see video below.

**Logs**
No log applicable

**Issue**
several tile entities behave wrong under water.
Tested: Aqueous Accumulator, Fluxducts, Mekanism Universal cables

See this video: https://streamable.com/vjyov

**Comment by NillerMedDild** [comment]
Is it just their rendering or do they not work either?

**Comment by MayusYT** [comment]
They don't work. The guis also don't open

**Comment by MayusYT** [comment]
Also, things like the aqueous accumulator are duplicated when I try to break them.

**Comment by NillerMedDild** [comment]
Interesting O_O

**Comment by MayusYT** [comment]
Those "dead spots" are also at other places:
https://streamable.com/tdc4w
(When I place a chest on the spot where the carrots drop, the gui doesn't open either.)

**Comment by NillerMedDild** [comment]
I'm afraid I can't reproduce this.
