### ISSUE TITLE
Charge Quartz Fixtures block elevators

### ISSUE THREAD

**Issue by sharkbite3105** [NillerMedDild/Enigmatica2#44]
#### 

#### Issue Description: placed a Charged quartz fixture (ae2) on the wool elevator from Open Elevators to replace the torch on it, was unable to use the elevator. from floor below up to elevator with fixture on it.
not sure if this is an issue to take up here or between the two mods

**Comment by NillerMedDild** [comment]
Charged Quartz Fixtures are considered blocks, this is not a bug.

**Comment by sharkbite3105** [comment]
ok thanks
