### ISSUE TITLE
Crashed when i placed a Ender Fluid Pipe next to a Resonant tank that had UU-Matter

### ISSUE THREAD

**Issue by Natchel93** [NillerMedDild/Enigmatica2#442]
**Modpack version**
1.62

**Can the issue be reproduced?**
No

**Logs**
https://pastebin.com/VfXSPfh5

**Issue**
Crashed when i placed a Ender Fluid Pipe next to a Resonant tank that had UU-Matter
I was setting up a Replacator

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Natchel93** [comment]
O I forgot to mention, the tank had holding 4 and shiny enchants

**Comment by Ravalli03** [comment]
I have had a similar crash using Ender fluid conduit, placing them on an EU2 Drum, I don't have the crash log anymore. Once I restarted everything was fine.

**Comment by NillerMedDild** [comment]
The issue no longer occurs as far as I can tell.
