### ISSUE TITLE
Thaumcraft JEI Integration Issues

### ISSUE THREAD

**Issue by DasBraunKaufmann** [NillerMedDild/Enigmatica2#445]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Logs**
[latest log 4_24_19.txt](https://github.com/NillerMedDild/Enigmatica2/files/3114967/latest.log.4_24_19.txt)

**Issue**
Thaumcraft JEI Integration essentia recipes aren't working anymore.

**Comment by NillerMedDild** [comment]
Thank you for the report, this is a known issue: https://github.com/Buuz135/Thaumic-JEI/issues/50

**Comment by Dimentive** [comment]
Also a duplicate of #407.
