### ISSUE TITLE
Can't complete Thinking With Portals #437 quest because receptacle has NBT on it.

### ISSUE THREAD

**Issue by XxZajoZzO** [NillerMedDild/Enigmatica2#447]
**Modpack version**
1.65a

**Can the issue be reproduced?**
Yes/

**Issue**
Can't complete Thinking With Portals (ID:437) quest because receptacle has NBT on it.

![Screenshot](https://user-images.githubusercontent.com/13818400/56913248-70754500-6ab1-11e9-8861-a15ecc2b7806.png)

**Comment by NillerMedDild** [comment]
Thanks for the report :)
