### ISSUE TITLE
Tinker’s bows are broken since previous version.

### ISSUE THREAD

**Issue by Slotherak** [NillerMedDild/Enigmatica2#45]
#### Issue Description
Tinker’s workshop had a nice weapon system. I have never appreciated bows before tinker gave us the Longbow. I can now one shot a zombie, and kill a carminite borer without fear of waking any others. Hell, it two shots a carminite golem! Try that with any other projectile weapon from another mod!
That said, I updated to version 1.39 from 1.38. And a huge problem surfaced.
Try using any bow from the tinkers tools mod. Go on. Try. Oh you can still fire it. ONCE. Then it is replaced with a ghost bow with 0/infinity durability, no traits, and 0 attack. No material given, so it can’t be fixed in a tool bench, and no compensation. This bow was my best weapon. I thought at first it was because of the fact that it had bloodwood in it, since bloodwood doesn’t seem to generate in your modpack at all. But all shortbows and longbows are doing this. Even the WOODEN BOWS.
I can’t even begin to state how broken this is for people who use bows. The vanilla bow pales in comparison, and the arrows that tinkers tools uses are useless with any non-tinkers bow. Either remove the bows and arrows altogether, or please fix this catastrophe! There is pretty much no point in using tinkers toolshop without tinkers portable ballista— I mean longbow, and no point to having the nether trees if you can’t use them with the naphtha strings to make a bow that lights its own arrows.
#### Modpack version (Do not use "latest")
1.39
#### Crash Report
No crash given. Except my attempt to storm the aurora palace. That crashed and burned REAL fast.
[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
A shortstory isn't a good issue report, this could've been 3 lines. It's pretty obvious that it's not intended behaviour.

Thank you for the report regardless.

**Comment by NillerMedDild** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/3544

**Comment by NillerMedDild** [comment]
https://github.com/PrinceOfAmber/Cyclic/issues/853

**Comment by Slotherak** [comment]
I see. Darn. I was looking forward to the Thaumic tinkerer mod... guess I’ll wait in 1.38 with my “Handheld Ballista”. Thanks.

**Comment by NillerMedDild** [comment]
You're not losing out on much anyway, Thaumic Tinkerer only has 2 items at the moment :)
