### ISSUE TITLE
Client crashing when loading into a server hosting a newly generated world. (1.66)

### ISSUE THREAD

**Issue by Aeka80** [NillerMedDild/Enigmatica2#450]
**Modpack version**
1.66

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/13mp2jP6

**Issue**
Client crashes upon loading into a new world on a server. The world loads in and is visible for a few seconds before a CTD. The crash is entirely client side as the server log does not show errors, and seems to be related to Wizardry (possibly UI from it) based on what I can tell from the crash report. The world on the server was newly generated on release 1.66 and the crash has occurred on the first connection to the world and every attempt after. I made a world (different seed) in singleplayer and was able to move around for about a minute before I got the same crash with an identical error report.

Update: It is a wizardry mod issue, and the author is aware of it and said they are working on fixing it for the next update. It causes a crash whenever the mouse wheel is scrolled, so I'd recommend avoiding v0.10.0 of Wizardry until it's fixed.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
