### ISSUE TITLE
Error with ZipFile cause the libmod can't run

### ISSUE THREAD

**Issue by madokaorimura** [NillerMedDild/Enigmatica2#453]
**Modpack version**
1.65a
forge-1.12.2-14.23.5.2831-universal.jar

**Can the issue be reproduced?**
Yes
Just run and get crash 

**Logs**
https://pastelink.net/rasz

**Issue**
Crash when run the modpack on server (get upload success)
Run the first time not load, second times not load too.... (and more times just to start the server)

**Comment by fuckyourmomks** [comment]
Sorry for a username, can't change it........ :<

**Comment by NillerMedDild** [comment]
You're using a newer Forge version that the one the pack comes with, downgrade. I also highly recommend using JRE instead of OpenSDK. Please let me know if you still crash after changing those things.

**Comment by madokaorimura** [comment]
Look like i didn't get luck on it
Have update to 1.66b, forge 2815
Crash report: https://pastelink.net/rcgz
Log: https://pastelink.net/rch0

**Comment by madokaorimura** [comment]
OpenJDK still work perfectly with my SF4 (SkyFactory4) server

**Comment by phit** [comment]
those zip files are corrupted, redownload the pack or reupload those jars to the server, nothing to do with Forge or Java version

**Comment by NillerMedDild** [comment]
Nothing is corrupt, he just didn't update correctly. Delete the old config, mods and scripts folders before moving the new folders in, you have a bunch of duplicate mods.

**Comment by phit** [comment]
> [01:38:15] [main/ERROR] [FML]: Unable to read the jar file EnderIO-1.12.2-5.0.43.jar - ignoring
java.util.zip.ZipException: error in opening zip file
> [01:38:15] [main/ERROR] [FML]: Unable to read the jar file wizardry-0.9.9.jar - ignoring
java.util.zip.ZipException: error in opening zip file

they have duplicate mods and corrupted zip files :P

**Comment by NillerMedDild** [comment]
Ahem, my bad :P

**Comment by madokaorimura** [comment]
ah
download correctly
twice time

**Comment by madokaorimura** [comment]
i just remove all the things (expect the eula file)
have a same problem

**Comment by madokaorimura** [comment]
My bad, upload with VPS is suck :P

**Comment by madokaorimura** [comment]
Solve, now the mod should run with no error :P
