### ISSUE TITLE
Crash when opening Basic Enriching Factory when it has items in the output slots.

### ISSUE THREAD

**Issue by demawno** [NillerMedDild/Enigmatica2#455]
**Modpack version**
1.63

**Can the issue be reproduced?**
Unknown. Happens every time I open the machine interface. 

**Logs**
Input Pastebin link to crash-report or latest log, if applicable
https://pastebin.com/EF3VN7Me
**Issue**
Input short description of the issue here
When opening the machine interface for the basic enriching factory when it has items in the output slots, the game freezes, then crashes.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
This is fixed by version 1.63a, thanks for the report.
