### ISSUE TITLE
Visual Bug: Diagonal lines on blocks

### ISSUE THREAD

**Issue by D1amxnd** [NillerMedDild/Enigmatica2#456]
**Modpack version**
1.65a

**Can the issue be reproduced?**
no

**Logs**
no game crash, its a visual bug
**Issue**
I am getting weird diagonal black lines when looking at the side of a block at a certain angle, I tried to fix it with removing a blueprint from the IE bench, it didnt help.
It also seems to happen only in certain chunks at different angles per chunk.

Here is a screenshot of the issue:
https://imgur.com/a/MWHXJnI

**Comment by D1amxnd** [comment]
I figured it out, it was a sink in combination with a full set of a kitchen.

**Comment by D1amxnd** [comment]
Removing the sink fixed the issue

**Comment by NillerMedDild** [comment]
Odd issue, glad you resolved it.
