### ISSUE TITLE
Streams Mod Streams Disappear

### ISSUE THREAD

**Issue by ZackUmstead** [NillerMedDild/Enigmatica2#457]
**Modpack version**
Enigmatica 2 Light 1.2.2

**Can the issue be reproduced?**
unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
When updating from Enigmatica Light 1.2.1 or earlier to Enigmatica 1.2.2 the blocks from the Streams mod are no longer registered and streams disappear.

**Comment by NillerMedDild** [comment]
Thank you for the report, this issue will be fixed in the next update - Broken streams should also be fixed.
