### ISSUE TITLE
Missing Recipe ??

### ISSUE THREAD

**Issue by warderbrad** [NillerMedDild/Enigmatica2#458]
**Modpack version**
1.65a

**Can the issue be reproduced?**
Yes

**Logs**
NA

**Issue**
The tank from OpenBlocks is not in the JEI, this is about the only multiblock tank that is available in this pack.  Is it disabled on purpose?

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
It's hidden in JEI to reduce lag. The recipe is 5 glass panes In a plus shape, with 4 obsidian in the corners.
