### ISSUE TITLE
Crash: Ticking Player

### ISSUE THREAD

**Issue by shitstainlord** [NillerMedDild/Enigmatica2#459]
**Modpack version**
1.60 expert

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/LJ3ZJ1Ah

**Issue**
The game crashed as soon as I put down my first Ender IO machine onto an universal cable. 
Now it crashes everytime I try to load the save. Can the save file be saved?

Thanks

**Comment by NillerMedDild** [comment]
Yep just update the pack.
