### ISSUE TITLE
Crash on enter Deep Dark (Advancement Conflict)

### ISSUE THREAD

**Issue by K0bus** [NillerMedDild/Enigmatica2#46]
#### Issue Description
Server crash when player entering Deep Dark. Have conflict with the minecraft advancements system.
#### Modpack version
1.40
#### Crash Report
https://hastebin.com/pawabiriwi.sql

**Comment by NillerMedDild** [comment]
I'm afraid this is a Sponge issue, and seeing as Extra Utilities no longer has an issue tracker, I will be unable to request a fix. I suggest trying your luck at the SpongeForge issue tracker.
