### ISSUE TITLE
Mekanism Part 1 - Moving Time #77 Quest

### ISSUE THREAD

**Issue by TheSnowyChickens** [NillerMedDild/Enigmatica2#460]
**Modpack version**
1.65a
(The Client use Forge 2836 and the Server the original version)

**Can the issue be reproduced?**
Yes

**Logs**
No logs, because I play on a Server.

**Issue**
Can't complete this Mekanism Part 1 Quest, because the Quest Item has some nbt tags.
![grafik](https://user-images.githubusercontent.com/29357962/57416193-6fee5400-71ff-11e9-9af9-ab83002e5fe9.png)

![grafik](https://user-images.githubusercontent.com/29357962/57416203-7ed50680-71ff-11e9-87a5-1249f5b47e1e.png)

**Comment by NillerMedDild** [comment]
Please ask an OP to use the command /bq_admin default load

**Comment by TheSnowyChickens** [comment]
Nope, don't work.

**Comment by NillerMedDild** [comment]
Alright, thanks.
