### ISSUE TITLE
Mekanism ore quadrupling setup won't process starmetal ore

### ISSUE THREAD

**Issue by sixlettervariables** [NillerMedDild/Enigmatica2#462]
**Modpack version**
1.65(a)

**Can the issue be reproduced?**
Yes

**Logs**
No crashes.

**Issue**
Attempting ore quadrupling with starmetal ore does not appear to work. The recipes in JEI show it is available, but when putting starmetal ore into the chemical infuser it does not get processed. I can double it using an enrichment chamber, but not anything higher. Not sure if this is a Mekanism issue or an E2 issue.

**Comment by NillerMedDild** [comment]
Are you able to quadruple other ores? Sorry, gotta ask :P

**Comment by sixlettervariables** [comment]
Yep! All the rest. Noticed starmetal clogged it up.

**Comment by NillerMedDild** [comment]
Cool, I'll have a look when I get time :)

**Comment by SWATr** [comment]
Mekanism smelter missing recipe for Stardust to Starmetal Ingots

# Starmetal Ingots
	mods.mekanism.smelter.addRecipe(<astralsorcery:itemcraftingcomponent:2>, <astralsorcery:itemcraftingcomponent:1>);
