### ISSUE TITLE
Invalid or corrupt jarfile InstanceSync.jar

### ISSUE THREAD

**Issue by socks-the-fox** [NillerMedDild/Enigmatica2#465]
**Modpack version**
1.67

**Can the issue be reproduced?**
Yes

**Logs**
`Error: Invalid or corrupt jarfile InstanceSync.jar`

**Issue**
Actual content of InstanceSync.jar in the release packages (both .zip and .tar.gz):

    version https://git-lfs.github.com/spec/v1
    oid sha256:c1a93a339c76744b3e2811bc819040bdaad0dfbc7ae143d66ca9de241caee370
    size 251925

And that's it. Pretty sure that it should be JAR data and not text. The one I can download from the GitHub page appears to be the actual JAR though.

**Comment by socks-the-fox** [comment]
Note that this is the release through here on GitHub, not the one on curseforge which took me longer than I'd like to admit to find in order to download the server files.

**Comment by NillerMedDild** [comment]
Myeah sorry, InstanceSync has a tendency to corrupt often, I have no idea why. The release on the issue tracker isn't meant for actual download though, I recommend you use the CurseForge manifest through Twitch or MultiMC

**Comment by socks-the-fox** [comment]
Since the release here on github isn't the official one people are meant to use this issue can probably just be closed as it doesn't really matter.

**Comment by NillerMedDild** [comment]
I'd like to keep it open while I find a solution :)

**Comment by socks-the-fox** [comment]
Alright! I noticed that the file itself here on github is the real thing, so my guess would be whatever process packages up the .zip release is grabbing some metadata url instead of the real one.

**Comment by NillerMedDild** [comment]
Something was renamed in the minecraftinstance which is crashing the InstanceSync setup step - We reported it about 3 weeks ago, hopefully it'll be fixed soon :p
