### ISSUE TITLE
Quest reward luck is all set up backwards

### ISSUE THREAD

**Issue by Hiagg** [NillerMedDild/Enigmatica2#466]
**Modpack version**
1.62

**Can the issue be reproduced?**
Yes

**Issue**
The quest rewards are backwards. In the harder quests you get punished for completing them because the reward chests are set to high metadata, when in reality, its metadata 0 that has the highest luck and metadata 100 is the lowest possible luck. Attached screenshot is from the mekanism reactor quest, with the other 2 rewards being 75. All the quests not using random (aka metadata 101) are set up in this way. The best rewards available in the pack is the unfired clay bucket, having metadata 0 as seen here https://hiagg.s-ul.eu/i1sglsrC

https://hiagg.s-ul.eu/n3dnd4nz

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I guess the values were reversed at some point, 0 used to be the worst Loot Chest.
