### ISSUE TITLE
Inventory reverting back to older version 

### ISSUE THREAD

**Issue by Krysk461** [NillerMedDild/Enigmatica2#467]
**Modpack version**
Enigmatica 2 1.65a on the twitch launcher 

**Can the issue be reproduced?**
Yes

**Issue**
whenever i save and quit my world when i go back in my inventory dosn't update it goes back to the save that i had a few saves before hand for example ill have a iron pick and shovel the ill play for a few hours then ill have diamond and stuff then when i save and quit when i log back in i'm back to my iron pick and shovel but everything else in the world is the same just not my inventory  i am running minecraft on lan and using hamatchi so my mate can join.

**Comment by NillerMedDild** [comment]
This issue is most likely caused by Hamatchi, I recommend using a server instead.
