### ISSUE TITLE
Cannot run server

### ISSUE THREAD

**Issue by theamazingjz** [NillerMedDild/Enigmatica2#468]
**Modpack version**
1.67d

**Can the issue be reproduced?**
unknown

**Logs**
https://pastebin.com/Qmf3Mskd

**Issue**
Tried to run Minecraft server through serverstart.bat but crashes after running for a bit.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
It works just fine for me, I'm afraid I can't help you atm - Try the support channel on our Discord, link below.

**Comment by Discomanco** [comment]
Looks like the forge jars corrupted to me
