### ISSUE TITLE
Unable to Complete Quest: Mekanism - Part 1, Power Stalk

### ISSUE THREAD

**Issue by Moonchim** [NillerMedDild/Enigmatica2#469]
**Modpack version**
1.67d
**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/j8CLbbfb

**Issue**
In the Quest called Power Stalk for Mekanism: Part 1, I've already have the item, but the quest book isn't detecting the item properly.
![2019-05-20 01_59_45-Window](https://user-images.githubusercontent.com/26265247/58003210-ed3e8200-7aa5-11e9-9803-3f28a7b81232.png)
![2019-05-20 02_11_01-Window](https://user-images.githubusercontent.com/26265247/58003211-edd71880-7aa5-11e9-8d72-bb428647879a.png)

**Comment by NillerMedDild** [comment]
The quest is not set to ignore the data on the Network Reader, I'll get that fixed at some point, thanks for the report.
