### ISSUE TITLE
Ancient Warfare Research broken

### ISSUE THREAD

**Issue by Seegras** [NillerMedDild/Enigmatica2#47]
#### Issue Description

When using the research table of Ancient Warfare, you can't research any topic that needs either a tool (iron pick), weapon (iron sword) or armor. It does not recognize them as valid. I guess some other mod changes something with these. 

#### Modpack version (Do not use "latest")

1.4.0

**Comment by Seegras** [comment]
Also, unrelated, if you're using the engineering table and want to look up a recipe in JEI, the game crashes.

**Comment by LaSainteMouette** [comment]
for me, the "leadership" research doesn't show, so I can't do the mod :'(
