### ISSUE TITLE
Wyvern armor upgrades not transferring to Draconic armor upgrades

### ISSUE THREAD

**Issue by AwesomeLikeThis** [NillerMedDild/Enigmatica2#470]
**Modpack version**
1.6.4d

**Can the issue be reproduced?**
Yes

**Logs**
none

**Issue**
I'm actually surprised I did not find a thread about this, maybe people weren't stupid enough to upgrade their wyvern armor ;-;

Upgrades put on the wyvern armor usually transmit to the draconic armor when upgraded in DE, but they don't. Considering the expense for these upgrades and the fact that you have practically wasted these resources upgrading the armor, I'd consider this more of a bug than anything. There is also no warning anywhere that these upgrades will not transfer.

For example, a wyvern tier shield recovery upgrade on a wyvern will be deleted when upgraded to draconic armor.

![wyvern armor upgrades](https://user-images.githubusercontent.com/18647702/58060883-8d95b480-7b41-11e9-9ef9-63eb79317c74.png)
![Draconic armor upgrades](https://user-images.githubusercontent.com/18647702/58060896-9d14fd80-7b41-11e9-90e3-f52f64a8d29d.png)

Any help is much appreciated

**Comment by NillerMedDild** [comment]
You're the first to upgrade Wyvern Armor as far as I know :P that being said, that is an unfortunate interaction, I'll see what I can do.

**Comment by NillerMedDild** [comment]
No I'm afraid that isn't possible with the type of crafting I'm using.

**Comment by NillerMedDild** [comment]
Oh this was meant for E2E btw.
