### ISSUE TITLE
Unable to Complete Quest: Mekanism - Part 1, *buurp*

### ISSUE THREAD

**Issue by Moonchim** [NillerMedDild/Enigmatica2#471]
**Modpack version**
1.67d
**Can the issue be reproduced?**
Yes

**Logs**
Part 1 - https://pastebin.com/MpEge5FJ
Part 2 - https://pastebin.com/2xA0n9Gh
Part 3 - https://pastebin.com/2y8EZynR
Part 4 - https://pastebin.com/hnMMuq2C
Part 5 - https://pastebin.com/rCPAXSee

**Issue**
Unfortunately, another quest that I've tried to complete is *buurp*. It's wanting you to make a Fluidic Plenisher. As the screenshots that I've included, I already crafted the item, but again, the quest book, just like the Power Stalk quest, isn't accepting the item that I've crafted.
(The Log I've provided is long due to Minecraft running for long period of time. Log 5 may show reason why it won't work).
![2019-05-20 19_37_56-Window](https://user-images.githubusercontent.com/26265247/58061639-a64f9b80-7b3c-11e9-87c3-d90314c6267f.png)
![2019-05-20 19_38_11-Window](https://user-images.githubusercontent.com/26265247/58061646-afd90380-7b3c-11e9-9f4e-01dc834b6c03.png)

**Comment by NillerMedDild** [comment]
Thanks for the report, same issue as the last :)

**Comment by RooksGambit360** [comment]
There are a number of others in the Mekanism line, usually at the ends of a chain that are not completing, the Rotary Condenser is another along with others. ALSO....and for the record... I have poured countless hours of joy into this amazing pack. I love it! Thanks for all your work! Now, if only we can have a praise log along with the bug log :)

**Comment by NillerMedDild** [comment]
D'Aww thanks :)

**Comment by Polariginal** [comment]
Just to let you know the quests for the Metallurgic Infuser and Energy cubes (in Mekanism/Mekanica) also don't work

**Comment by NateDev100** [comment]
Happened to me a bunch, I just opped myself and used the admin command to complete them
