### ISSUE TITLE
Unable to boot the server With SpongeForge

### ISSUE THREAD

**Issue by Mini-kun** [NillerMedDild/Enigmatica2#475]
**Modpack version**
1.67d

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/xjipsjgt

**Issue**
I'm just trying to Boot my server upafter i update it from 1.65a

**Comment by NillerMedDild** [comment]
Please remove the mod Phosphor and try again :)

**Comment by bgottfried91** [comment]
Encountered this as well. Removing Phosphor does resolve the issue and allow the client to start. However, per https://github.com/jellysquid3/Phosphor/issues/15, the issue is that there are two different mods using SpongeForge, one of which is using an older version of Mixins and preventing Phosphor from loading. It would be good to identify which mod this is (Phosphor dev suggests removing mods until you identify it, which ugh, but would work) and see if it can be updated (or else weigh its contribution to the modpack vs the benefits Phosphor provides)

**Comment by Mini-kun** [comment]
soo i remove the mod and this happy https://pastebin.com/JsiaGtjA

**Comment by Mini-kun** [comment]
> Encountered this as well. Removing Phosphor does resolve the issue and allow the client to start. However, per [jellysquid3/Phosphor#15](https://github.com/jellysquid3/Phosphor/issues/15), the issue is that there are two different mods using SpongeForge, one of which is using an older version of Mixins and preventing Phosphor from loading. It would be good to identify which mod this is (Phosphor dev suggests removing mods until you identify it, which ugh, but would work) and see if it can be updated (or else weigh its contribution to the modpack vs the benefits Phosphor provides)

I'm need to stay in the sam modlist as Niller make this mods as it's a Server i'm Host for People soo

**Comment by NillerMedDild** [comment]
Removing SpongeForge would also solve your issue.

**Comment by phit** [comment]
this is not a Sponge or Phosphor issue, see https://github.com/TeamWizardry/LibrarianLib/issues/77

**Comment by NillerMedDild** [comment]
If an issue is only present when SpongeForge is also present, I call it a SpongeForge issue. I'm not saying it's caused by SpongeForge. Either way, looks like it'll be fixed in the upcoming release of LibrarianLib.

**Comment by phit** [comment]
no, it also happens with other mods that use mixin like phosphor or laggoggles, so you don't need SpongeForge for it to happen

**Comment by Mini-kun** [comment]
I hope soo course my servers use it for all the things

**Comment by Bluexin** [comment]
> no, it also happens with other mods that use mixin like phosphor or laggoggles, so you don't need SpongeForge for it to happen

Not true, I've been running Lag Goggles with it. It only happens with specific mixin targets it seems.
Again, we're working on fixing this, but our main ASM guy is not very active atm (and no one could help when asking on the sponge discord directly).
