### ISSUE TITLE
Conflicting Steel Smeltery Alloying Recipes

### ISSUE THREAD

**Issue by socks-the-fox** [NillerMedDild/Enigmatica2#476]
**Modpack version**
1.67d (as well as 1.65a and most likely earlier versions)

**Can the issue be reproduced?**
Yes

**Issue**
There are 3 alloy recipes for steel in the TiCon smeltery.
Two use 9mb iron and 25mb coal, and one uses 18mb iron and 25mb coal.
For some reason, if you do one iron at a time it uses the 9mb one, but if you use multiple (such as dumping a bunch of iron and coal in at the same time) it will use a weird mix of both. This makes it difficult to avoid fractional leftovers when trying to make steel.

**Comment by NillerMedDild** [comment]
That sounds annoying, I'll look into it :)

**Comment by ReiDaTecnologia** [comment]
One fix for this issue is removing the conflicting recipes using the CraftTweaker and re-adding it.
This is the code that i used:
`mods.tconstruct.Alloy.removeRecipe(<liquid:steel>);
mods.tconstruct.Alloy.addRecipe(<liquid:steel> * 18, [<liquid:iron> * 18, <liquid:coal> * 25]);`

**Comment by NillerMedDild** [comment]
Thank you ReiDaTecnologia :)
