### ISSUE TITLE
Mekanism - Part 1 "But can jet fuel melt it?" misinformation

### ISSUE THREAD

**Issue by VioletPhoena** [NillerMedDild/Enigmatica2#477]
**Modpack version**
1.67d

**Can the issue be reproduced?**
Yes

**Issue**
The Mekanism - Part 1 quest "But can jet fuel melt it?" incorrectly states that Steel Blend is created in the Enrichment Chamber rather than the Metallurgic Infuser.

**Comment by NillerMedDild** [comment]
Thank you, I'll get that fixed :)
