### ISSUE TITLE
Server crashes when vein mining

### ISSUE THREAD

**Issue by Shmee** [NillerMedDild/Enigmatica2#478]
**Modpack version**
Enigmatica2ExpertServer-1.64d

**Can the issue be reproduced?**
unknown

**Logs**
https://www.dropbox.com/s/czuequ4azaet6p4/crash-2019-05-25_00.09.28-server.txt?dl=0

**Issue**
Server crashes when I'm vein mining and the tinkers tool is low dura/breaks.

[crash-2019-05-25_00.09.28-server.txt](https://github.com/NillerMedDild/Enigmatica2/files/3218951/crash-2019-05-25_00.09.28-server.txt)

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
What did you veinmine? Can you reproduce the crash while veinmining other blocks?

**Comment by Shmee** [comment]
It has happened to me and a few of my users. I don't think it matters what you're vein mining, just that it happens on the last hit when the tinkers tool durability goes to zero. the next time my tool gets low I'll try and reproduce it.

**Comment by NillerMedDild** [comment]
I can't reproduce this at all :/

**Comment by Calibos** [comment]
this likely isn't actually about the durabilty, this is a thing I've seen with tinkers before when you vein mine with a tool that has a 3x3 area
