### ISSUE TITLE
It's green, just green.

### ISSUE THREAD

**Issue by TheSnowyChickens** [NillerMedDild/Enigmatica2#480]
**Modpack version**
1.67d (you didn't see the 1.27d^^)

**Can the issue be reproduced?**
Yes (I think)

**Logs**
[2019-05-26-1.log.gz](https://github.com/NillerMedDild/Enigmatica2/files/3219958/2019-05-26-1.log.gz)

**Issue**
It is green, just green. I don't know why, but it is green.
(I play on a Server)

![2019-05-26_05 10 02](https://user-images.githubusercontent.com/29357962/58376866-a7396080-7f74-11e9-9a96-3ec4a180d997.png)
![2019-05-26_05 10 07](https://user-images.githubusercontent.com/29357962/58376867-a7d1f700-7f74-11e9-992e-7662380e5f58.png)
![2019-05-26_05 10 13](https://user-images.githubusercontent.com/29357962/58376868-a7d1f700-7f74-11e9-8642-92f854c592bd.png)

**Comment by ReiDaTecnologia** [comment]
Is that near the green wind generator, a nuclear reactor? maybe the reactor is leaking radiation and the wind gens is radioactive now lol

**Comment by TheSnowyChickens** [comment]
@ReiDaTecnologia xDD, good theory. ^^

**Comment by NillerMedDild** [comment]
Version is 1.67d I'm guessing? Do they still function?

**Comment by TheSnowyChickens** [comment]
Oh yes xD
It is 1.67d not 1.27d, sry.

**Comment by NillerMedDild** [comment]
Do they still function?

**Comment by TheSnowyChickens** [comment]
Yes, they produce energy.

**Comment by NillerMedDild** [comment]
I'm guessing it's a graphics driver issue, try updating those. Also, those Wind Generators are yellow not green ^^'

**Comment by TheSnowyChickens** [comment]
My driver is up to date. (430.64 @ GTX 780 TI)

Other player of the server have the same issue.
(and is it rly yellow? lol :D )

**Comment by NillerMedDild** [comment]
I don't know then :/
