### ISSUE TITLE
NoClassDefFound/ClassNotFoundException

### ISSUE THREAD

**Issue by NickehBoi** [NillerMedDild/Enigmatica2#482]
**Modpack version**
1.65a

**Can the issue be reproduced?**
No, unless I give someone my current modpack folder.

**Logs**
https://pastebin.com/7vCSY9Pw

**Issue**
Shortly after starting up the modpack, during Startup on Constructing Mods 1/7 it throws a java.lang.NoClassDefFoundError: Lmcjty/rftools/proxy/CommonProxy among a few other of similar errors as seen in the crash report. The pack is heavily modified from the original (mainly in more mods added that shouldn't be conflicting hardly and a dimension ID changed). I don't expect much help since it is most likely caused by me fiddling around with the pack but if it is somewhat easily fixable and explainable to someone who doesn't know about any coding I could try and fix it.

**Comment by NillerMedDild** [comment]
I would need the crash report to be of any help, but you are correct that I won't help very much :P
