### ISSUE TITLE
No experience gained when smelting vanilla ores

### ISSUE THREAD

**Issue by TheMegaOverlord** [NillerMedDild/Enigmatica2#485]
**Modpack version**
1.67d

**Can the issue be reproduced?**
Yes. This can be reproduced by smelting some iron or gold ore in the furnace, taking the product out, saving and quitting the game, restarting the client and smelting to receive product as usual.

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/3242533/latest.log)

**Issue**
When smelting any vanilla ores like iron or gold into the furnace, no experience is gained when taking the smelted product out of the furnace. Issue occurs when restarting the client after quitting and saving. Experience gains persist for modded ores like black quartz, and are not affected by this issue.

**Comment by ExarKun44** [comment]
I don't know if this is linked to this change but smelting recipe for pulverized iron and gold into their ingot form doesn't exist anymore.
Other ore seem ok.

**Comment by NillerMedDild** [comment]
Yep that's definitely my fault :P hotfixing now.
