### ISSUE TITLE
[Suggestion] Overloaded Armor Bar and Armor Toughness Bar

### ISSUE THREAD

**Issue by yikies** [NillerMedDild/Enigmatica2#486]
these mods would be nice since a lot of the armor in this pack can really add up on your hud (they just make the armor and toughness bar overlap with different colors, similar to how mantle handles heart values over 20)

https://minecraft.curseforge.com/projects/overloaded-armor-bar

https://minecraft.curseforge.com/projects/armor-toughness-bar

edit: also would recommend Attribute Fix to fix the vanilla hard cap on certain values like armor

ps. thank you so much for this incredible pack my friend

**Comment by NillerMedDild** [comment]
All good suggestions, I will most likely add them.

My pleasure!
