### ISSUE TITLE
Buggy Version of Mecreeps in 1.67d

### ISSUE THREAD

**Issue by ChromeMystic** [NillerMedDild/Enigmatica2#487]
**Modpack version**
1.67d

**Can the issue be reproduced?**
Yes

**Logs**
Not needed

**Issue**
Buggy Version of Mecreeps
The Version of Mecreeps installed in the Pack has the Mecreeps unable to do anything, this is fixed in 1.3.1 of Mecreeps

**Comment by NillerMedDild** [comment]
Thanks for letting me know, I'll be sure to update it for 1.68

**Comment by ChromeMystic** [comment]
It took me a while to trace the issue, as the Update for Meecreeps came out the same day as the Update for your pack :)
