### ISSUE TITLE
No way to get Adv. Rock. Tank of Rocket Fuel

### ISSUE THREAD

**Issue by Kzorith** [NillerMedDild/Enigmatica2#49]
#### Issue Description
The Rocket Fuel quest under Advanced Rocketry wants a Tank of Rocket Fuel.  In other packs, I seem to remember that you could put an empty bucket in the fuel output hatch to get one.  That doesn't work.  The only recipe in JEI is a tank of oxygen and a tank of hydrogen in the chemical reactor to get a tank of rocket fuel.

You can't get tanks of oxygen or hydrogen either.  When you put buckets in the electrolyzer, you get 
NuclearCraft filled buckets of the gasses.

Cheating in the tanks of gasses, and placing them in the input hatch of the chemical reactor does not create a tank of rocket fuel either.  Putting them in the fluid input hatch, processes them into rocket fuel but then you can't get it out of the machine.

#### Modpack version (Do not use "latest")
Enigmatica 2 v1.40
containing Advanced Rocketry 1.12.2 1.4.0.84 universal

**Comment by NillerMedDild** [comment]
I am aware of this issue, and have reported it. I'll change the quest.
Thanks for the report.
