### ISSUE TITLE
Bad "Help" info in Mekanism Fusion quest

### ISSUE THREAD

**Issue by Chinthor** [NillerMedDild/Enigmatica2#490]
**Modpack version**
Input version here 1.64d

**Can the issue be reproduced?**
Yes - static info.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Input short description of the issue here

The quest for crafting Mekanism fusion reactor parts offers some help for setting up the reactor in the form of a web address:  https://wiki.aidancbrady.com/wiki/Fusion_reactor
This would be very helpful. Problem is, this page does not exist yet. 

The link should be removed, or updated to point to a valid guild guide, or the wiki updated to include the build guide. 

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Heh, that is some disappointing help. Thanks for the report, I'll get that fixed :)

**Comment by NillerMedDild** [comment]
I can't seem to find this link anywhere in the quests?
