### ISSUE TITLE
Obtaining Titanium for Advanced Rocketry

### ISSUE THREAD

**Issue by have-a-boy** [NillerMedDild/Enigmatica2#491]
**Modpack version**
1.67d

**Can the issue be reproduced?**
unknown

**Issue**
I hope I'm not missing something obvious, but I can't seem to find a way to make titanium ingots for advanced rocketry. According to JEI, Rutile Ore is the only source for it and can not be found in the Overworld. I assume this is accurate, since I haven't found any yet by quarrying. 

Advanced Rocketry tells me I need titanium for all of the stuff that could get me to space, so I'm kind of stuck in some chicken and egg problem here.

Hopefully someone can tell me what I'm doing wrong since googling isn't turning up anything useful.

**Comment by NillerMedDild** [comment]
Check out crafting recipes for Titanium Ingots ^^ They should also have a tooltip, JEI description and quest entry.

**Comment by have-a-boy** [comment]
Yeah, nevermind. I must have messed something up. I started a new instance and the recipe that I was missing shows up in there.
