### ISSUE TITLE
Issue with AE2 quest - it’s peer not pier

### ISSUE THREAD

**Issue by diz9000** [NillerMedDild/Enigmatica2#492]
Away from pc at the moment so don’t have all the version details, but running Enigmatica 2 (not expert) that’s available from twitch launcher,

Issue is currently with AE2 quest - It’s Peer, not Pier
From quest tree says 1/2 complete
But the actual quest only has one requirement , the P2P tunnel -me (from memory),’
This step shows as complete , but the overall quest isn’t completing, so I can’t move on to the 2 quests below it in the book.
I’ve placed 2 p2p-me in the world , made them p2p-item and clicked them with a memory card.
What am I missing

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
There's a second page that requires you to check a checkbox. No idea why though, deleting it now ^^'
