### ISSUE TITLE
IE Shader Duplication Glitch

### ISSUE THREAD

**Issue by jaxx050** [NillerMedDild/Enigmatica2#494]
**Modpack version**
1.67d

**Can the issue be reproduced?**
Yes

**Logs**
No logs applicable

**Issue**
Applying an Immersive Engineering shader to a banner will keep the shader in your inventory, as well as apply it to the banner, allowing you to infinitely duplicate the shader after you break the banner.

**Comment by NillerMedDild** [comment]
I'm pretty sure that's intended :)
