### ISSUE TITLE
Server CPU Usage well over 100%

### ISSUE THREAD

**Issue by MTGGraveyard** [NillerMedDild/Enigmatica2#495]
**Modpack version**
1.67d

**Can the issue be reproduced?**
Unknown, I have gone through multiple restart, clearing in game entities, and all of the sorts, but it still is coming up all the time

**Issue**
I have had issues with overly high CPU usage through the pack with only about 5 people online. It is not a memory issue as I have 30 GB of RAM dedicated to the server, and it is only utilizing 20%. This has caused for some unsavory lag spikes that are hurting the community's ability to play. This is all kept on a dedicated machine, running CentOS 7.

System Specs:
i7-7700k @4.2GHz
32GB of DDR4 RAM at 2133MHz

Currently the server is using 107% CPU usage and 18% RAM usage.

If there is any way this can be resolved, it would all be greatly appreciated! Thank you for your time!

**Comment by NillerMedDild** [comment]
That doesn't sound good :/ I'm afraid I don't have time to troubleshoot the issue at the moment, so I'll redirect you to support. I should have time to help you there in about 12 hours. Please provide your latest.log uploaded to gist.github.com :)
