### ISSUE TITLE
Unicorns are not spawning

### ISSUE THREAD

**Issue by buddergoku** [NillerMedDild/Enigmatica2#498]
**Modpack version**
Wizardry

**Can the issue be reproduced?**
unknown

**Issue**
I have been looking for hours for this unicorn in the dimension where u fall and hit bedrock and never found it

**Comment by NillerMedDild** [comment]
They don't spawn in the Wizardry version we have sadly, updating should fix it.
https://github.com/TeamWizardry/Wizardry/issues/244
