### ISSUE TITLE
Please Ender IO Gas Conduits mod.

### ISSUE THREAD

**Issue by TheSnowyChickens** [NillerMedDild/Enigmatica2#499]
Hi,
I can see, that Ender IO Gas Conduits mod isn't installed by default and I rly like this mod, because it is less buggy than Mekanism Gas Pipes.

So now the question to you: Could you add this mod to the pack ? :)

https://minecraft.curseforge.com/projects/gas-conduits

**Comment by NillerMedDild** [comment]
I'm sorry but no, I cannot add any more content mods :/
