### ISSUE TITLE
Crashes during startup

### ISSUE THREAD

**Issue by morrissimo** [NillerMedDild/Enigmatica2#5]
#### Issue Description
Installed fresh today via Twitch launcher. Crashes during startup

#### Modpack version (Do not use "latest")
v1.24

#### Your most recent log file where the issue was present
https://pastebin.com/y2cF6DK1

**Comment by NillerMedDild** [comment]
Removing Extra Bit Manipulation and optionally DefaultOptions should resolve your issue.

Oddly enough, a fresh install works just fine for me, I suspect it's because you're on a Mac.

**Comment by NillerMedDild** [comment]
In addition, this issue has been reported on the Extra Bit Manipulation issue tracker, so it should be fixed eventually.

**Comment by morrissimo** [comment]
>Oddly enough, a fresh install works just fine for me.

Figures, right? :)

>In addition, this issue has been reported on the Extra Bit Manipulation issue tracker, so it should be fixed eventually.

Oh, nice find! I only checked their project's issues on github; I've +1'd the issue on CurseForge with a link to my pastebin.

Thanks for following up - and thanks for this pack! Looking forward to trying it out: a kitchen-sink style pack + questing sounds like exactly what I've been looking for :)

**Comment by NillerMedDild** [comment]
Glad to hear it! Thanks for reporting your issue :)

Did you get it to launch?

**Comment by morrissimo** [comment]
I did - removed `Extra Bit Manipulation` and it fired right up. Thanks again!

And then I discovered there's an Expert mode version of the pack... :D
