### ISSUE TITLE
Imm. Eng. Metal Press makes IC2 tin plates rather then ImmEng tin plates

### ISSUE THREAD

**Issue by Kzorith** [NillerMedDild/Enigmatica2#50]
#### Issue Description
When using tin ingots in the the Immersive Engineering metal press with plate mold, it generates IC2 tin plates rather than Immersive Enginnering tin plates.  Since these plates are not ore dictionaried, they can not be used in anything but IC2 builds.

#### Modpack version (Do not use "latest")
Enigmatica2 1.41

#### Crash Report
No crash, just not the expected behaviour.

**Comment by NillerMedDild** [comment]
I really appreciate you reporting here in addition to the Discord, thanks :)
