### ISSUE TITLE
Crafting Table Duplication Bug

### ISSUE THREAD

**Issue by Chronoman17** [NillerMedDild/Enigmatica2#501]
**Modpack version**
1.67d (Astral Sorcery updated to latest version, probably not at fault)

**Can the issue be reproduced?**
Yes

**Logs**
Pastebin isn't working for me atm.  I've attached the log file directly here.
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/3317381/latest.log)

**Issue**
When crafting with a vanilla table or Crafting Table on a Stick, putting a recipe in the table, then shift-clicking the item to be crafted while your inventory and hotbar are full (that is, crafting output has nowhere to go, causes you to be able to withdraw an infinite amount of items from the "output" slot by repeatedly doing normal clicks even after all crafting ingredients are used up.  After throwing the items out of the table/inventory, they will be legitimate items able to be picked up.  If, instead, they are placed directly into the inventory, they may behave weirdly and spontaneously disappear when clicked, as many apparently-duped items might do.  Also, if the items thrown out are picked up while the crafting table is still open (this may not be necessary, may only require throwing items out), clicking on the item in the output while you have that same item in hand will double the number of items in your hand instead of incrementing by the amount in your hand.  Shift-clicking the output item after the recipe is exhausted or altered will clear the output.

Now, for the more severe aspect of this duplication.  While the crafting table is in this glitched state, if the recipe is disrupted, by either not having an equal amount of items and running the recipe out or by just clearing the grid and putting other items in the grid, you can still withdraw items from the output slot.  Each time you do so, the number of items in each stack in the grid will be doubled, then have two subtracted from it.  This does not respect max stack size; any stack with initial size greater than two can quickly grow into tens of thousands, even millions of items.  Non-stackable items and single items cannot be duped and will be consumed, as one would expect from the double-then-subtract-two pattern.  In retrospect, I probably shouldn't have tested that with my unbreakable hastester silk touch knightslime-embossed Tinkers' pick.  Guess I can make another one anyway.

**Comment by NillerMedDild** [comment]
Thanks for the report!

Do you know if this bug only occurs with the Vanilla Crafting Table and Crafting Table on a Stick? Did you try the Crafting Station from Tinkers' Construct?

**Comment by Chronoman17** [comment]
I haven't tried it with the Crafting Station.  I imagine it wouldn't work with that, since its behaviors are different from the vanilla crafting table anyway (same crafting gui for all players, maintaining grid inventory, etc.).  I'll test it and see.

**Comment by Chronoman17** [comment]
It doesn't work with the Crafting Station, nor with the AE2 Crafting Terminal (no real surprise there).

**Comment by NillerMedDild** [comment]
Alright, thanks for checking!
I know it's a lot to ask for, but would you mind reposting this issue [here](https://github.com/Shadows-of-Fire/FastWorkbench/issues)?

**Comment by NillerMedDild** [comment]
Oh, nevermind, found this: https://github.com/Shadows-of-Fire/FastWorkbench/issues/15

**Comment by NillerMedDild** [comment]
It was found and fixed, thanks again for your work in tracking it down.
