### ISSUE TITLE
Update Integrated Dynamics

### ISSUE THREAD

**Issue by JHawkley** [NillerMedDild/Enigmatica2#503]
**Issue**
Integrated Dynamics 1.0.2 seems to be responsible for a great many server crashes.  Many of the sources of these crashes have been fixed in later versions of the mod.

I think it would be prudent to update the version of the mod used by Enigmatica 2 as soon as possible, in the interest of server stability.

**Comment by NillerMedDild** [comment]
Noted, I'll try to find some time to update :)
