### ISSUE TITLE
Stuck in bed glitch

### ISSUE THREAD

**Issue by jaxx050** [NillerMedDild/Enigmatica2#504]
**Modpack version**
1.67D

**Can the issue be reproduced?**
Yes - every time I use my personal bed

**Logs**
No logs, can upload any you think would be helpful since I don't crash from it

**Issue**
Essentially, every time I use my bed, I "use" it as normal, it skips to day, yada yada, but then I'm never actually able to *leave* it. Attached is a picture of what my screen looks like when it's stuck on. This is happening in an SMP server. Can provide any other information needed.

![2019-06-27_16 59 03_2](https://user-images.githubusercontent.com/5535296/60300222-8447f680-98fc-11e9-9072-7eaf6ab40277.png)

**Comment by jaxx050** [comment]
Additional note: just tried to cheese my way around this issue with using a plugin's /home command, and it teleported me successfully but i'm still in the "bed" screen even though I'm just laying on the ground. Forced to fully reboot to clear it as I can't even access the escape menu from the screen.

**Comment by Discomanco** [comment]
Old vanilla bug, that not even Modded has been able to fix.
The only solution is to get kicked from the server, where you can use the command `/kickme` (doesn't require OP)
