### ISSUE TITLE
Tinker's Construct Brown Magic teleport tool abilities partially bug client

### ISSUE THREAD

**Issue by jaxx050** [NillerMedDild/Enigmatica2#505]
**Modpack version**
1.67D

**Can the issue be reproduced?**
Yes - Use any Brown Magic TC tool to travel between dimensions

**Logs**
No log

**Issue**
Using any Tinker's Construct tool with the Brown Magic teleportation ability, where you mark a point with one button and return to it with another at any time, will partially glitch your client. It will rarely completely remove your armor GUI from your screen (you still have armor equipped, it just doesn't show that you do), as well as bug out how you receive damage - there are no damage noises at all on your own player until you teleport with a "normal" method, not from enemies, fire, poison, or falling, as well as a few other glitches.

edit: screenshot of what the armor glitch looks like: 
![2019-06-27_17 25 58](https://user-images.githubusercontent.com/5535296/60301576-bdce3100-98ff-11e9-9ba8-921186d0804b.png)

**Comment by NillerMedDild** [comment]
That sounds like the dimensional to glitch, that marks your player as dead. I'm afraid I cannot fix it.

**Comment by NillerMedDild** [comment]
-
