### ISSUE TITLE
Draconic Axe Right click crash

### ISSUE THREAD

**Issue by FlammableTime** [NillerMedDild/Enigmatica2#507]
**Modpack version**
1.67d

**Can the issue be reproduced?**
yes

**Logs**
https://pastebin.com/KWmDbJWR

**Issue**
Game crashes when using the Draconic Axe right click harvest ability.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I reported the issue here: https://github.com/brandon3055/Draconic-Evolution/issues/1333

**Comment by FlammableTime** [comment]
After some more experimenting it seems to only happen when I am using the ability on the large Twilight Oaks in the Twilight Forest

**Comment by NillerMedDild** [comment]
Thanks for the added testing, that helps quite a lot.
