### ISSUE TITLE
Crash upon adding mysticallib/Roots 3 whenever amethyst tries to spawn

### ISSUE THREAD

**Issue by Degsdegsdegs** [NillerMedDild/Enigmatica2#509]
**Modpack version**
1.67d

**Can the issue be reproduced?**
Yes

**Logs**
[Log](https://pastebin.com/XFx232Bb)

**Issue**
I tried adding mystical lib/world and Roots 3 to an Enigmatica 2 server. It seems that whenever amethyst tries to spawn, it crashes. Disabling amethyst lets the server run but obviously, no amethyst.

**Comment by Degsdegsdegs** [comment]
[Link to the issue on the Mystical Lib github.](https://github.com/EpicSquid/MysticalLib/issues/18)

**Comment by duely** [comment]
I'm of the opinion that this is an issue with Mystical World that is unrelated to Enigmatica. The issue can be closed imo.

**Comment by NillerMedDild** [comment]
Cool, thanks for the info regardless :)

**Comment by Degsdegsdegs** [comment]
Seems to have been user error in the config anyways, thanks guys.
