### ISSUE TITLE
Your modpack has been stolen.

### ISSUE THREAD

**Issue by 3rdeye46n2** [NillerMedDild/Enigmatica2#510]
sorry dont know where else to put this. Twitch streamer (german) Rednight has upload a pack to twitch client hes calling his own. It is called Rednight (modpack) as well. after quickly trying said pack, then watching said streamer play this pack, i quickly realized it was Enigamtica 2 he was playing, but claiming his own.

**Comment by NillerMedDild** [comment]
Thank you very much for letting me know, but I can't seem to find Rednight on Twitch, or the modpack on CurseForge?

**Comment by hron84** [comment]
Maybe Twitch/Curse team stepped up earlier and removed the modpack on its own.
