### ISSUE TITLE
Mattock no crafting

### ISSUE THREAD

**Issue by EnderProjects** [NillerMedDild/Enigmatica2#511]
**Modpack version**
Version: 1.67d
**Can the issue be reproduced?**
Yes

**Logs**
No logs

**Issue**
Mattock from Cyclic is uncraftable, the recipe can be shift clicked with JEI but no result

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by SWATr** [comment]
Cyclic.zs
Has:
`
recipes.addShaped("Mattock", <cyclicmagic:mattock>, [[<ore:obsidian>, <ore:blockDiamond>, <ore:obsidian>],[<ore:crystalNetherQuartz>, <ore:stickSteel>, <ore:crystalNetherQuartz>], [null, <ore:stickSteel>, null]]);`

Needs:
`
recipes.addShaped("Mattock", <cyclicmagic:mattock>, [[<ore:obsidian>, <ore:blockDiamond>, <ore:obsidian>],[null, <ore:stickSteel>, null], [null, <ore:stickSteel>, null]]);`

**Comment by NillerMedDild** [comment]
I don't understand that fix? You removed two ingredients?

**Comment by SWATr** [comment]
Yes, the recipe is wrong. JEI shows https://ftb.gamepedia.com/Mattock

**Comment by NillerMedDild** [comment]
Why would I make the default recipe in a script? :P The recipe in E2E is not the default recipe.

**Comment by NillerMedDild** [comment]
I'll revert the Mattock recipe to the default one.
