### ISSUE TITLE
[FEATURE REQUEST] Add usage for Hardened Cell Frame

### ISSUE THREAD

**Issue by hron84** [NillerMedDild/Enigmatica2#512]
**Modpack version**
1.67d

**Can the issue be reproduced?**
Yes

**Feature**

Since quest rewards (loot boxes) are giving Hardened Cell Frame and similar stuffs like in Enigmatica 2 Expert, it would be nice if this pack could also have some - basic - recipes to use them rather than make them rubbish.

For example, add Hardened Cell recipe re-using the normal Cell recipe but with invar instead of lead and let output the Hardened Cell.

**Comment by NillerMedDild** [comment]
I'll look into it :)

**Comment by NillerMedDild** [comment]
I won't have time I'm afraid.
