### ISSUE TITLE
Crash when using Mek jetpack after loading schematic

### ISSUE THREAD

**Issue by raxixor** [NillerMedDild/Enigmatica2#513]
**Modpack version**
1.68a

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/ZDkavrxj

**Issue**
Whenever I load a schematic using Schematica, and then try to fly using my Armored Jetpack, it crashes straight to launcher.

**Extra**
~~I'm testing whether it has to do with my added mod Sound Filters (I like it's reverb and effects), or not. Will edit with findings.~~ It is unrelated.

**Comment by NillerMedDild** [comment]
Seeing as `at com.tmtravlr.soundfilters.SoundEventHandler.playSoundEventHandler(SoundEventHandler.java:29)` is near the top of the crash report, and the other bits all involve sound, I think it's a fair assumption to blame Sound Filters.

**Comment by NillerMedDild** [comment]
May I have the crash log from the crash without Sound Filters please?

**Comment by raxixor** [comment]
Here it is. https://pastebin.com/8kzc1QDV

**Comment by NillerMedDild** [comment]
Thank you :)

**Comment by NillerMedDild** [comment]
Mekanism has changed very very much since this issue was made, I'm gonna go ahead and close it, hoping it's fixed.
