### ISSUE TITLE
Mapping

### ISSUE THREAD

**Issue by kleshas** [NillerMedDild/Enigmatica2#514]
**Modpack version**
1.68a

**Can the issue be reproduced?**
Yes

**Issue**
Mapping seems to be broken.  Whenever I start up (new game or existing), the map is showing cave mode.  Trying to change it makes no difference, nor does going underground and coming back up (which fixes the older occasional bug the map mod has).  Forcing a re-map (choosing ALL) resets 50% of the time but, as stated, only for that game instance and it resets back to cave mode next time I start the game.

**Comment by NillerMedDild** [comment]
Thank you for the report, the issue is reported here: https://github.com/TeamJM/journeymap/issues/127
I recommend downgrading Journeymap yourself while they look into the issue :)

**Comment by mysticdrew** [comment]
Journeymap 5.5.5 Beta 9 fixes this issue.
