### ISSUE TITLE
ID Conflict between Advanced Rocketry Proxima B Dim and Lost Cities Dim

### ISSUE THREAD

**Issue by ReiDaTecnologia** [NillerMedDild/Enigmatica2#516]
**Modpack version**
Input version here
1.68a
**Can the issue be reproduced?**
Yes/no/unknown
Yes.
**Logs**
Input pastebin link to crash-report or latest log, if applicable
I think doesn't need log?
**Issue**
Input short description of the issue here
When u create the Lost Cities portal instead of u go to the LC dim u go to the Advanced Rocketry 's Proxima B dim, after searching the config files i found out that both dims have the same id.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
And Proxima B doesn't have Lost Cities generation?

**Comment by ReiDaTecnologia** [comment]
Nope, the LC portal tp u to the Proxima B making the LC dim inaccessible.

**Comment by NillerMedDild** [comment]
Switched it to 180, sorry for the delay :)
