### ISSUE TITLE
Duplicated Ores

### ISSUE THREAD

**Issue by ReiDaTecnologia** [NillerMedDild/Enigmatica2#517]
**Modpack version**
Input version here
1.68a
**Can the issue be reproduced?**
Yes/no/unknown
Yes.
**Logs**
Input pastebin link to crash-report or latest log, if applicable
I think doesn't need log?
**Issue**
Input short description of the issue here
When i was mining i realized that some ore is duplicated and to confirm i ran the command "/oredistribution" and it confirmed it.
Mystic World ores:
Copper
Silver
ProjectRed ores:
Copper
Silver
Tin
BOP is also adding duplicated ores conflicting with ThaumCraft and ProjectRed:
Amber
Sapphire
Peridot
Ruby

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Ah dammit, I didn't realize they added ores. Thank you.

**Comment by NillerMedDild** [comment]
Heh, you do realize that Project Red isn't in the pack right?

**Comment by ReiDaTecnologia** [comment]
Ops, i think that one was one of the mods that i added, sorry about it.

**Comment by NillerMedDild** [comment]
No worries :P fixed, will be in the next release, thanks again.
