### ISSUE TITLE
Mod Add Request: Gulliver Reborn

### ISSUE THREAD

**Issue by jaxx050** [NillerMedDild/Enigmatica2#518]
https://www.curseforge.com/minecraft/mc-mods/gulliver-reborn

You remember that mod for 1.7.10, right? Morph? The one that let you transform your shape and size to a degree of mobs you found? You remember how you could turn into a bat, and go in between your wall crevices to get in between cables, and wires, and it would let you be a tiny mechanic getting into spaces that would be otherwise impossible to navigate?

Well, this will do that. Somewhat. I know this request is a little off the wall, but, I'm desperate for any mod that is capable of providing a method of shrinking down to become a one-Steve-army to get into cabling and circuitry and figuring out what the heck is going on.

**Comment by NillerMedDild** [comment]
Sorry but no, I will not add more content mods, we have too many as not is.
