### ISSUE TITLE
Roots Quest Log 

### ISSUE THREAD

**Issue by Slaveofsithis** [NillerMedDild/Enigmatica2#519]
**Modpack version**
1.68a

**Can the issue be reproduced?**
Yes/

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Input short description of the issue here

The Wood shears do not exist in the modpack, so you can't do the first roots quest and continue at all.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Oh right... Brain fart :P The Roots questline will be removed.
