### ISSUE TITLE
Loot Chest - Disappear when being used

### ISSUE THREAD

**Issue by MedianAura** [NillerMedDild/Enigmatica2#521]
**Modpack version**
1.69a

**Can the issue be reproduced?**
Yes. Reproduced with a fresh install of the Modpack.

**Logs**
No logs

**Issue**
Trying to use a Loot Chest just seem to swap them between each other without opening them. If you have only one it vanish until you open another inventory.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Kimba659** [comment]
I am having the same issue. Is there anything I can do to help?

**Comment by encero** [comment]
I have same issue. It works on 1.68a release version.

**Comment by NillerMedDild** [comment]
Thanks, I'll look into it this evening.

**Comment by NillerMedDild** [comment]
Should be fix in 1.69b :)
