### ISSUE TITLE
Better Questing: Unable to invite others to party

### ISSUE THREAD

**Issue by Kimba659** [NillerMedDild/Enigmatica2#522]
**Modpack version**
1.69a

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
Running a server using the server file provided on PC A, playing on both PC A and PC B. Neither user is able to be invited to the party while both players are able to create them. Have tried reinstalling both clients and the server but the issue still persists.

**Comment by ritzyuk** [comment]
Also experiencing this issue as of version 1.69a.
All players can create Better Questing parties, though invites are not able to be sent by any players.

Issue can be reproduced constantly.

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll get that fixed :)

**Comment by pacman1983** [comment]
Hey!!!! Since you're going to be updating the pack with the new better questing update. Would you be so kind as to add in Flux Networks? Saw it was in your expert mode ;) 

Plz k thx

**Comment by NillerMedDild** [comment]
@pacman1983 No, and for your information that is a very rude way to suggest adding a mod. It has been suggested about 12 times now, it's still not possible..
