### ISSUE TITLE
Skin becomes blurry when you open JourneyMap

### ISSUE THREAD

**Issue by sentientyeet** [NillerMedDild/Enigmatica2#524]
**Modpack version**
1.68a

**Can the issue be reproduced?**
Yes

**Logs**
https://gist.github.com/sentientyeet/7924b2f1c0797c9ee1949f673aedcb14

**Issue**
When you start or log into a world, your skin looks fine, but the moment you try and open JourneyMap in fullscreen (world map), it blurs your skin and it becomes all disgusting [attached screenshot]
![2019-07-22_20 51 44](https://user-images.githubusercontent.com/53190671/61653800-cb3ec700-acc3-11e9-8f20-b53da177520d.png)

**Comment by NillerMedDild** [comment]
Does this happen on 1.69b?

**Comment by sentientyeet** [comment]
> 
> 
> Does this happen on 1.69b?

happens on 1.69a and 1.69b

**Comment by SWATr** [comment]
This happens to default Alex skin but does not happen to custom player skin.
