### ISSUE TITLE
Game Crashes On Launch - Advanced Rocketry

### ISSUE THREAD

**Issue by NateDev100** [NillerMedDild/Enigmatica2#525]
**Modpack version**
1.69b

**Can the issue be reproduced?**
Unknown it happens randomly

**Logs**
https://del.dog/dofohotuse.md

**Issue**
Randomly sometimes when I load the game it crashes before getting to the main menu, on step 6/7 of loading. Log says something about planetDefs.xml from advanced rocketry, so I open that file and the whole file is just NUL NUL NUL NUL in Notepad++.

To fix it, I have to go https://raw.githubusercontent.com/NillerMedDild/Enigmatica2/master/config/advRocketry/planetDefs.xml here and copy the contents into my planetdefs.xml and it fixes it.

**Comment by NillerMedDild** [comment]
Deleting the planetDefs.xml file also does the trick. We've tried to fix this issue a bunch of times, sadly unsuccessfully :(

**Comment by NillerMedDild** [comment]
It tends to happen after force closing the game FYI.
