### ISSUE TITLE
"Got Grout?" Quest still broken in latest version.

### ISSUE THREAD

**Issue by TheD0ct0r101** [NillerMedDild/Enigmatica2#526]
**Modpack version**
1.69b

**Can the issue be reproduced?**
Unknown. Likely Yes.

**Issue**
Got Grout? Quest is still asking for 128 Air, despite the fact that the changelog stated the issue was fixed. I am playing on a multiplayer server, which is running 1.69b. The server was downloaded from the official curseforge page. I am not sure as to whether this is a personal problem, and if it is, whether or not it is server-side or client-side.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Please use the command /bq_admin default load.   And see if the problem persists.

**Comment by erazuret** [comment]
> Please use the command /bq_admin default load. And see if the problem persists.

did not fix the issue for me

**Comment by NillerMedDild** [comment]
@erazuret In version 1.69b?

**Comment by kcjosh** [comment]
The default load command worked for me in the latest 1.69b version.

**Comment by NillerMedDild** [comment]
Great :)

**Comment by Nerenth** [comment]
This does not fix it for me either, sadly.  I am running the latest version from website both downloaded yesterday:
  
Server - https://www.curseforge.com/minecraft/modpacks/enigmatica2/files/2745593
E2 - 1.69b - https://www.curseforge.com/minecraft/modpacks/enigmatica2/files/2745587

Two bugs I've noticed:  
1.  "Got Grout?" - Requires Air x128, /bq_admin default load  -  does not fix it.
2.  My Smeltery drain does not make blocks nor casts, but it does work for Enigmatica 2 Expert.  

Any thoughts?  =)

**Comment by NillerMedDild** [comment]
Silly question, but you have permission to run the command right?
