### ISSUE TITLE
Forestry Quests appear to be disabled

### ISSUE THREAD

**Issue by urikkiru** [NillerMedDild/Enigmatica2#527]
**Modpack version**
1.69a

**Can the issue be reproduced?**
Yes

**Issue**
On single player or on a server, the Forestry quests are inaccessible for some reason. If you open the quest book, the 'Forestry' tab is darkened, and there's a little check mark next to it. It cannot be selected.

**Comment by NillerMedDild** [comment]
Use the command /bq_admin default load :)
