### ISSUE TITLE
Tree Saplings Dna Extractor

### ISSUE THREAD

**Issue by SgtZocker** [NillerMedDild/Enigmatica2#528]
**Modpack version**
1.66c

**Can the issue be reproduced?**
Yes

**Issue**
Tree Saplings dosn´t work in the DBA Extractor

**Comment by NillerMedDild** [comment]
You need to analyze them in order for it to work. Analyzing the sapling will turn it into a Forestry sapling, which will drop Forestry saplings when grown and harvested.

**Comment by SgtZocker** [comment]
Oh sorry my fault

**Comment by NillerMedDild** [comment]
No worries :)
