### ISSUE TITLE
Backslashes in path names in server zip

### ISSUE THREAD

**Issue by cgushue** [NillerMedDild/Enigmatica2#529]
**Modpack version**
1.69b (server)

**Can the issue be reproduced?**
Yes

**Logs**
n/a

**Issue**
Zip file was created with backslashes for path names instead of forward slashes. Unzipping on Linux (both Arch and Debian stretch) ends up with issues on a lot of config directories, with messed up permissions making them unreadable.

Among other things, this caused oregen to break because the cofh directory was unreadable.

**Comment by NillerMedDild** [comment]
Oh my apologies, I'll find another program to zip with :) do you happen to know if 7zip is Linux compatible?

**Comment by NillerMedDild** [comment]
I'm uploading new server files now, would you mind checking if they work?

**Comment by NillerMedDild** [comment]
Dammit, they've been rejected.
Here they are: https://drive.google.com/open?id=1P_T-h8Kie66kUGK5XlCSjGHh7bEA1ofM

**Comment by cgushue** [comment]
7zip does have a Linux version, though I guess Curseforge didn't want them?

The 1.69c zip you put on Google Drive does appear to work perfectly, though.

**Comment by NillerMedDild** [comment]
Great, thanks for testing.
