### ISSUE TITLE
Feature Request - Changelog textfile

### ISSUE THREAD

**Issue by tsudico** [NillerMedDild/Enigmatica2#53]
It would be nice to have a text file with all the changes that Enigmatica 2 has undergone with each release so I can compare between releases instead of looking at each release between my current version and the most up to date.

This text file could either be on the github or included with the latest release and updated with each release.

**Comment by NillerMedDild** [comment]
https://github.com/TheRandomLabs/ChangelogGenerator/issues/10

**Comment by NillerMedDild** [comment]
https://github.com/TheRandomLabs/ChangelogGenerator/issues/10#issuecomment-406757703
You can use this program to generate a changelog history for the pack, download the latest release and use the command `java -jar ChangelogGenerator.jar enigmatica2expert` in the same folder as the changelog generator jar, in a terminal.
