### ISSUE TITLE
Many Mekanism quests are completed but I can't redeem the reward

### ISSUE THREAD

**Issue by Kakiter12** [NillerMedDild/Enigmatica2#530]
**Modpack version**
1.69
**Can the issue be reproduced?**
Yes

**Issue**
Input short description of the issue here

I completed a few of the early Mekanism part I quests but I can't redeem rewards for them, they just flash blue, I tried using the load command a few times as well

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Did you check if there are choice rewards?

**Comment by Kakiter12** [comment]
Yes, I have, I tried reloading the entire game as well and they're not choice rewards, most of them are just loot chest rewards

**Comment by NillerMedDild** [comment]
I see. Which version are you actually on, and which quests have this issue?

**Comment by Kakiter12** [comment]
the version is 1.69b, I haven't completed all mekanism part I quests yet, but here are the ones I cannot turn in at this point in time: 
1)Powered Furnace
2)Enriched Ores!
3)But can jet fuel melt it?
4)Doing the job for you
5)My first factory
6)Day Light
7)Dayer Light
Those are all quests that I completed so far, sorry for the long wait.

**Comment by NillerMedDild** [comment]
Thanks, I'll look into it.

**Comment by Kakiter12** [comment]
I'll be editing in any further bugs in these quests I come across

**Comment by NillerMedDild** [comment]
Thank you :)

**Comment by Kakiter12** [comment]
Okay it seems it's working now, I don't know what happened...

**Comment by NillerMedDild** [comment]
Sweet! Full inventory? :P
