### ISSUE TITLE
Server I/O Permission Issues

### ISSUE THREAD

**Issue by NillerMedDild** [NillerMedDild/Enigmatica2#532]
I used a new archive function to make the server files for 1.69b, which unfortunately doesn't seem to play nice with Linux. Server files that should be more Linux friendly in the link below:
https://drive.google.com/open?id=1P_T-h8Kie66kUGK5XlCSjGHh7bEA1ofM

Note: I am unable to push them to CurseForge because the DankNull version we use has been removed from CurseForge.

**Comment by XylianZeref** [comment]
Thanks for the fix. But Google Drive is not bot friendly. 
You can not download it with wget (you get 403 forbidden) -.-
Just a note for next time please :)

**Comment by NillerMedDild** [comment]
1.70 is available now, it should be a bit easier to grab :)
