### ISSUE TITLE
Iron Shulker Box causes crash

### ISSUE THREAD

**Issue by erazuret** [NillerMedDild/Enigmatica2#533]
**Modpack version**
1.69b

**Can the issue be reproduced?**
Yes
**Logs**
java.lang.ClassCastException: cpw.mods.ironchest.common.blocks.shulker.BlockIronShulkerBox cannot be cast to net.minecraft.block.BlockShulkerBox

**Issue**
launched my game today to find a shulker box in my inventory that was never there before. game crashes before i can ever get it to a trash bin to try and get rid of the item. no idea how to get rid of it or how to fix this.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
This issue will be fixed as of version 1.70, but in the mean time, you can do the following:
* Go to the file `quark.cfg` in your config folder.
* Open it with something like Notepad
* Edit line 332 from `B:"Shulker box tooltip"=true` to `B:"Shulker box tooltip"=false`

**Comment by frostedclaws** [comment]
Same issue with mine on version 1.65d.  was also getting a plus sign to show up now over containers which i dont recall happening before today.

Rendering screen
java.lang.ClassCastException: cpw.mods.ironchest.common.blocks.shulker.BlockIronShulkerBox cannot be cast to net.minecraft.block.BlockShulkerBox
	at vazkii.quark.client.feature.ShulkerBoxTooltip.renderTooltip(ShulkerBoxTooltip.java:128)

**Comment by NillerMedDild** [comment]
Update ^^
