### ISSUE TITLE
Maxiumum of Loaded Chunks

### ISSUE THREAD

**Issue by SgtZocker** [NillerMedDild/Enigmatica2#534]
how can i Increase the maximum limit for loaded chunks?

No Tutorial in the internet helps me out.
(on a Server)

**Comment by NillerMedDild** [comment]
I'm guessing you mean how to increase the maximum for FTB Utilities?

**Comment by SgtZocker** [comment]
Yes

**Comment by NillerMedDild** [comment]
https://www.curseforge.com/minecraft/mc-mods/ftb-utilities/pages/ranks/config

**Comment by SgtZocker** [comment]
Thanks for your halp i don´t found this page....

**Comment by NillerMedDild** [comment]
Sure thing.
