### ISSUE TITLE
Cyclic's Empty Heart Container - can't regain lost life

### ISSUE THREAD

**Issue by frostedclaws** [NillerMedDild/Enigmatica2#535]
**Modpack version**
Enigmatica2Expert-1.65d

**Can the issue be reproduced?**
yes

**Logs**
~null~

**Issue**
eating @cyclic Empty Heart Container food permanently lowers your max health, no way to fix.
found another issue request Disable Cyclic Hearts #241 that removed the item in question that would have fixed this. - please remove this heart too.

tried editing modpack to enable the gain heart item and restarted server (im admin and lone player) but didn't work.eating pams food is great but im going to be at 49/50 max hearts at the end or something to that nature and it extremely bugs me. was trying to eat one of every food and this counts towards that goal but the downsides are extreme and the counter food was removed. (not sure if theres a console command to undo this somehow, i checked on cyclics page but it looked uninformative with little documentation)

**Comment by NillerMedDild** [comment]
Isn't that the purpose of the empty Heart Container?

**Comment by frostedclaws** [comment]
yes, but it is still an issue.  there is no way to undo it because the normal way has been disabled in the pack.  simplest solution is to remove the other item of the pair. harder issue would be have some way to reverse it (which i would appreciate very much)

**Comment by NillerMedDild** [comment]
Alright, I suppose I'll remove the recipe.

**Comment by frostedclaws** [comment]
Thank you, cheers maybe the next person will be spared lol
