### ISSUE TITLE
Missing Thermal Expansion Ores

### ISSUE THREAD

**Issue by XylianZeref** [NillerMedDild/Enigmatica2#537]
**Modpack version**
1.66c

**Can the issue be reproduced?**
Yes, on my server I deleted 2 times the world, still no thermal foundation ores.

**Issue**
The Thermal Foundation Ores are not generated in my created multiplayer Maps, yet are easily found in all singeplayer maps i created.
I used the Scanner from Scannable with the Scanner module: Block.

**Comment by NillerMedDild** [comment]
Please see #532 for the fix :)

**Comment by NillerMedDild** [comment]
and my apologies for the inconvinience.

**Comment by NillerMedDild** [comment]
and my apologies for the inconvinience.
