### ISSUE TITLE
Crash while looking at recipes

### ISSUE THREAD

**Issue by ThwartAbyss54** [NillerMedDild/Enigmatica2#54]
#### Issue Description
When looking at recipes in JEI, whether in a vanilla crafting station, tinkers construct, or inventory, crashes when looking at item recipes with a shutting down internal server. Not shift clicking just looking through. One i found was consistent was the small storage crate from actually additions. Clicking on the wood casing to see the recipe caused a crash for all 3 of the crash logs i uploaded. This isnt the only 1.12.2 pack that does this. The new direwolf20 2.0 for 1.12.2 also keeps doing it. Im looking for common mods that have been added to dw20 2.0 that are in this one that might cause it.
#### Modpack version (Do not use "latest")
Enigmatica 2 1.42 (release)
#### Crash Report
[crash-2018-07-13_09.00.01-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/2192996/crash-2018-07-13_09.00.01-client.txt)
[crash-2018-07-12_16.09.30-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/2193001/crash-2018-07-12_16.09.30-client.txt)
[crash-2018-07-12_15.56.29-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/2193002/crash-2018-07-12_15.56.29-client.txt)

[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63
