### ISSUE TITLE
Disappearing crafting items?

### ISSUE THREAD

**Issue by Unknow0059** [NillerMedDild/Enigmatica2#545]
**Modpack version**
2.1.70

**Can the issue be reproduced?** 
Unknown

**Issue**
For some reason, when I craft one of something, I can't craft more of that thing.

Ff I make 4 wood out of 1/3 logs, it uses up 1 log to make 4 wood. 

The 2 other logs stay in the crafting area as you'd expect, but in the result area - where I'd grab the 4 wood - there's nothing. 

I have to remove the 2 logs from the crafting table and put them back in; only then will I be able to get the 4 wood.

I didn't install any mods that change the game's crafting or inventory.
Video of the issue: https://streamable.com/d9mgj

**Comment by NillerMedDild** [comment]
Does this occur in singleplayer?

**Comment by Unknow0059** [comment]
> Does this occur in singleplayer?

Yeap, it is in singleplayer.

**Comment by NillerMedDild** [comment]
Ah alright. I recommend that you try to reinstall the modpack while we investigate :)

**Comment by Unknow0059** [comment]
Just some more context: It's in the default workbench. The issue is not present in the Tinker's workbench (which I didn't know existed) - this is the first time I'm playing Minecraft modded, but I'm sure the modpack has been installed correctly. 
It's also present in vanilla Enigmatica 2, meaning I removed the few mods I had personally installed onto it, and checked.
