### ISSUE TITLE
Opening GUI Causes crash?

### ISSUE THREAD

**Issue by TempGuyOnGitHub** [NillerMedDild/Enigmatica2#546]
**Modpack version**
1.70

**Can the issue be reproduced?**
unknown

**Logs**
please see attached

**Issue**
Seems unique, helping a friend set up Enigmatica2 Normal and crashes. The crash log says when opening a GUI but she hasn't been able to recreate it accurately. However, crashes are common and frequent

[crash_report_4_updated.txt](https://github.com/NillerMedDild/Enigmatica2/files/3493985/crash_report_4_updated.txt)
[crash_report_4_.txt](https://github.com/NillerMedDild/Enigmatica2/files/3493986/crash_report_4_.txt)

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thanks for the report.

I'm afraid the logs don't say anything useful, however I can see the Forge version she's using is not the one the modpack comes with. Did you make any other changes?

**Comment by TempGuyOnGitHub** [comment]
As far as I'm aware no changes were made, in fact the twitch launcher and Enigmatica have been completely uninstalled, reinstalled and repaired a few times

**Comment by NillerMedDild** [comment]
Well the Forge version does not match that of Enigmatica 2 version 1.70, so changes have been made.

**Comment by TempGuyOnGitHub** [comment]
Thank you for the help! Will report back tomorrow after some troubleshooting.

**Comment by NillerMedDild** [comment]
Nice, you're welcome :)
