### ISSUE TITLE
Can't get past Forge loading screen with OpenJDK 8/OpenJ9

### ISSUE THREAD

**Issue by LRW1** [NillerMedDild/Enigmatica2#549]
**Modpack version**
Expert 1.67

**Can the issue be reproduced?**
Yes, there are also other people facing this issue on Reddit.

**Logs**
[latest.log](https://pastebin.com/ZDssLmBd) using MultiMC and jdk8u222-b10_openj9-0.15.1

**Issue**
When I try to launch Enigmatica 2 Expert through MultiMC and having OpenJ9 selected as my Java Runtime, I always get stuck at Forge loading screen. 

![stuck](https://user-images.githubusercontent.com/9289029/63159491-5c376280-c024-11e9-82c8-0ceda5c7c4a1.JPG)

**Comment by LRW1** [comment]
Removed Chisel from mods but still, I cannot get past "Initializing mods Phase 1" 

[latest.log](https://pastebin.com/0WjrsULE) after removing Chisel from mods folder.

**Comment by NillerMedDild** [comment]
How much RAM do you have allocated?

**Comment by LRW1** [comment]
6144MB and no additional arguments added.

**Comment by NillerMedDild** [comment]
The log doesn't really help I'm afraid. Have you tried with normal Java?

**Comment by Silly511** [comment]
I was having this same problem using OpenJ9 version 8u232-b09 0.17.0, however downgrading to 8u212-b04 0.14.2 fixed it for me.
