### ISSUE TITLE
Crashing while searching in JEI

### ISSUE THREAD

**Issue by Kimba659** [NillerMedDild/Enigmatica2#550]
**Modpack version**
1.70, 1.69b (I dont think it was an issue with 1.69a)

**Can the issue be reproduced?**
Yes, happening on laptop and and 2 PCs

**Logs**
https://pastebin.com/s8KHNYuc

**Issue**
Crashing while searching for items in JEI. Sometimes it seems like typing 1 letter at a time can help but others it crashes on the first letter. From what I can tell its something to do with item IDs being out of range.

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

**Comment by NillerMedDild** [comment]
Please let me know if changing Java version resolves the issue :)

**Comment by Kimba659** [comment]
As far as I can tell I dont have any other versions of Java installed except for the latest version as shown by the Java Uninstall Tool and Programs and Features on all 3 computers. I have added the argument and will update this thread if I still get crashes. Can probably move to closed if you want.

**Comment by NillerMedDild** [comment]
Both Twitch and Minecraft come with a legacy Java version, it's a bit hidden.
Cool :)

**Comment by Kimba659** [comment]
Hi again. I am still getting crashes with JEI after putting the argument into twitch. Is this the correct location? https://imgur.com/a/OUEgVA2

I have the modpack settings set to 6.6gb not 3.2gb.

Pastebin of the crashlog: https://pastebin.com/uB2FqPWm

Some things can be typed but the number 1 seems to crash 100% of the time on all 3 of my PCs.

**Comment by NillerMedDild** [comment]
Yep that looks correct. Which search is it that crashes you every time?
