### ISSUE TITLE
Funky Locamotion Teleportation removes frame and attached blocks upon logout.

### ISSUE THREAD

**Issue by OutlandSided** [NillerMedDild/Enigmatica2#552]
**Modpack version**
1.68.a

**Can the issue be reproduced?**
unknown

**Logs**
N/A

**Issue**
Built a frame on a funky locomotion teleporter 'A' block. On the tied 'B' block I had a redstone clock activated by a block reader and an inverted vanilla redstone signal to send the frame back to block 'A' after a set amount of time. After logging out and back in, the frame and blocks attached to the frame were nowhere to be found.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
If this is still an issue, feel free to re-open.
