### ISSUE TITLE
Infinite energy with Advanced Generators and Mekanism Ethylene

### ISSUE THREAD

**Issue by GitBenedetti** [NillerMedDild/Enigmatica2#555]
**Modpack version**
1.70

**Can the issue be reproduced?**
Yes

**Logs**
n/a

**Issue**
Infinite energy. I've set up a Gas Turbine from Advanced Generators. Hooked up to a mechanism tank with Ethylene *gas* with a pressurized tube from Mekanism. The turbine's tank is now filled with *liquid* Ethylene, and the turbine will produce infinite energy. The generator itself works correctly, if I remove the tube, it starts emptying it's internal tank. But as long as there is a tube attached, even if the tube is no longer connected to the external mekanism tank, it will keep going without ever using any Ethylene. The tube is also perma-filled with Ethylene gas. It looks to me to be a problem with the Mekanism Tubes, maybe in combination with Advanced generators?

If this is a feature request, feel free to delete the template.

**Comment by GitBenedetti** [comment]
PS
I've build the same in a 1.6x version of the pack, and it worked correctly back then. I'm fairly sure something changed with 1.70

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by YakosWG** [comment]
This seems to work (or well fail) with other Mekanism gases as well (e.g. Hydrogen).

**Comment by NillerMedDild** [comment]
I believe this issue is fixed in 1.75, would you mind verifying when it's available?

**Comment by NillerMedDild** [comment]
I reproduced the bug and reported it here: https://github.com/mekanism/Mekanism/issues/5887

**Comment by NillerMedDild** [comment]
Mostly tracking this bug here: https://github.com/NillerMedDild/Enigmatica2Expert/issues/1517
