### ISSUE TITLE
Request Dank Null Addition 

### ISSUE THREAD

**Issue by Gazzzaa** [NillerMedDild/Enigmatica2#556]
Dank Null has been updated and is apparently fixed.

**Comment by NillerMedDild** [comment]
I will most likely not re-add it, as it could result in massive instability for servers updating from older versions.

**Comment by Mikitiril** [comment]
I can cofirm it works purrfectly with 1.70 E2 normal.

**Comment by NillerMedDild** [comment]
But did you update from a version that still had the mod?

**Comment by Gazzzaa** [comment]
I updated to the one that took it out then added it back.

**Comment by NillerMedDild** [comment]
That's what I thought :/

**Comment by NillerMedDild** [comment]
Readding it now!

**Comment by mpavkovic** [comment]
Hey @NillerMedDild, I don't think /dank/null is quite ready and bugfree to be included in the pack. I've manually added it and it's depending library [p455w0rds-library](https://www.curseforge.com/minecraft/mc-mods/p455w0rds-library) has a serious issue that keeps crashing my client, which is still unresolved p455w0rd/p455w0rds-Library#47

**Comment by NillerMedDild** [comment]
Do you also get the issue with the latest modpack version?

**Comment by p455w0rd** [comment]
just pushed the update which removes shaders which resolves most current bugs..the other bugs have also been fixed in latest /dank/null update...it is pack-ready..also @NillerMedDild I thought ahead..you should be able to convert from older versions to newer version without issue for the most part since I use DataFixers :)

**Comment by p455w0rd** [comment]
also note you need latest pwlib as well!

**Comment by NillerMedDild** [comment]
Sounds good, thank you!
