### ISSUE TITLE
Game Crashing periodically and always at when save and exit

### ISSUE THREAD

**Issue by VIIJordon** [NillerMedDild/Enigmatica2#557]
**Modpack version**
1.7

**Can the issue be reproduced?**
sporadic occurence

**Logs**
https://pastebin.com/5CkyuAkz

**Issue**
I have a lan going with my wife, just the two of us in the world, and every few hours i will freeze, then crash while we are out doing things, and i almost always crash exit when i hit save and exit.

i have 12 GB ram allocated to the instance, and am running a pretty powerful pc (i5 with a 1060 6GB) so i dont know if my specs are to blame

The paste bin shows a few errors i get occasionally regarding  illegal access and a phosphor error

**Comment by NillerMedDild** [comment]
Instability is sadly a known issue for LAN worlds, I highly recommend that you use a server instead :)

**Comment by VIIJordon** [comment]
no problem! figured this might be the case but i just wanted to see if there was anything going wrong

**Comment by NillerMedDild** [comment]
There is something going wrong, but it looks like a LAN only bug, that I don't really have time to debug :/
