### ISSUE TITLE
Magic Bees - No Special Drops

### ISSUE THREAD

**Issue by Greystoke** [NillerMedDild/Enigmatica2#559]
**Modpack version**
1.70 - Normal/non expert

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
Magic Bees not producing special drops.

Using the Magic Bees strains in a Gendustry Apiary, with either the appropriate temperature/humidity modifiers (upgrades) or by using the Genetic Imprinter to align bee traits to local biome, results in bees with no special drops.  Tried this with Plumbum, Leaden, and Withering bees, with and without Production Upgrades: plenty of standard combs but no special products.  Biome is a Savanna Plateau, tried other nearby biomes with similar results.

Forestry bees, Binnie's Extra Bees, and Career Bees don't appear to have this issue, all strains I've tried from those mods produce additional drops as expected.

**Comment by Greystoke** [comment]
Updated to note I did find one Magic Bee that does drop special products: the Big Bad bee produces steak and chicken in addition to combs.

**Comment by NillerMedDild** [comment]
They need to be as happy as possible to give their special drops, I'm guessing that's the issue.
