### ISSUE TITLE
Game Crash after changing any key!

### ISSUE THREAD

**Issue by ReiDaTecnologia** [NillerMedDild/Enigmatica2#56]
Issue Description
When you change the key of any of the default keys, the game freeze for some seconds because it's saving the game and crash after it, the crash report and the log show differents errors of the crash, and for this they is in the same RAR file. I tried two version of the pack (1.4.1 because he do not updated while i have the issue), to see if it's my error, i do not added optifine (What huge lag...) and the same problem. For this test i changed the J key of the Toast Control to \ because it's conflicting with JourneyMap.
ModPack Version?
1.4.2
Crash Report?
https://drive.google.com/open?id=1rPoEIcQSsrRkRal5XyuUU0c2lZCEZPBD

**Comment by NillerMedDild** [comment]
Please upload the crash report to https://gist.github.com/

**Comment by NillerMedDild** [comment]
https://github.com/mezz/JustEnoughItems/issues/1296

**Comment by ReiDaTecnologia** [comment]
Ok, if you don't want Google Drive i will use this. At least i will free some space at my Cloud lol.
https://gist.github.com/ReiDaTecnologia/8aaef619d0229c543875f937023f684b

**Comment by NillerMedDild** [comment]
Have you tried changing it to another key than the one that crashed you?

**Comment by ReiDaTecnologia** [comment]
Looks like if i remove Toast Control (That is in the crash report) fix the problem. At least he is not a big lost as he only remove advancements, the tutorial etc, i can live with this annoying pop ups :P.
If the issue comeback while i'm playing i comeback here and re-open! you can close if you want.

**Comment by NillerMedDild** [comment]
Cool :)
