### ISSUE TITLE
Server hangs without crashing upon client connect

### ISSUE THREAD

**Issue by HandilColdblade** [NillerMedDild/Enigmatica2#561]
**Modpack version**
1.67

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
I run a small server for myself and some friends. After initial boot, the server runs fine for however long someone stays logged in. However, when the server has no clients attached for a period of time, the server will hang when someone connects. Clients are still allowed to connect and can load the game world and interact with some objects (doors) but not others (inventories) mob do not spawn and existing mobs are non responsive. The server, when hung, will not respond immediately to a stop command. Sometimes the server will process the stop command minutes later, other times I will have to shut it down manually. Also, I have noted that when the server is in the hung state and a client logs on, there usually is a backup notification displayed which is stopped at 80 percent or so. I'm not sure how to proceed troubleshooting this issue, so any help would be greatly appreciated! 

P.S. I have in the past hosted numerous large packs on this server without issue, the most recent was FTB: Interactions. All CPU and RAM usage looks to be in the normal parameters. I have tried running the pack with 3, 8, and 12 gigs of RAM dedicated and all configs have had the same problem. 

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
Thanks for reporting the issue. This isn't the first time I've heard of it, it has even occurred on one of the official servers. We were never able to pin down the cause, but it stopped happening all of a sudden. I'm afraid I can't really help you.

**Comment by HandilColdblade** [comment]
I appreciate the quick response! I will keep trying different things on my end and if I happen to figure it out, I'll post again! Aside from this issue, I am really enjoying the pack. Thank you for your hard work and effort that you put into it. I look forward to whatever you may be working on next!

**Comment by NillerMedDild** [comment]
My pleasure :D
