### ISSUE TITLE
Quest Sharing

### ISSUE THREAD

**Issue by molekylspektroskopi** [NillerMedDild/Enigmatica2#563]
**Modpack version**
Enigmatica 2 1.71a

**Can the issue be reproduced?**
Yes

**Issue**
Quest are not synced in party, tried reforming party and same issue. It seems to be the same as in ticket #343 
Google tells me that it seems to work in Expert mode, but haven't tried that as we are running normal. We can complete the quests on our own, so quest progress is ok.

**Comment by NillerMedDild** [comment]
I'm afraid it's currently disabled, pending a rewrite.

**Comment by molekylspektroskopi** [comment]
Good to know, will keep my eyes on this then =)

Ty ty
