### ISSUE TITLE
Airtight Seal is uncraftable

### ISSUE THREAD

**Issue by nukem950** [NillerMedDild/Enigmatica2#564]
**Modpack version**
1.71a

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
In the current version, I am unable to craft the airtight seal enchanted book. The recipe that was added does not work correctly. It currently crafts an auto-smelt enchanted book. 

I was able to resolve the issue in my instance by modifying "scripts/AdvancedRocketry.zs" and changing the id from 28 to 27.

**Comment by NillerMedDild** [comment]
Thanks for the report and solution, I'll get that implemented :)
