### ISSUE TITLE
can not obtain manganese

### ISSUE THREAD

**Issue by frostedclaws** [NillerMedDild/Enigmatica2#565]
**Modpack version**
1.65d

**Issue**
Method to obtain manganese is not displayed in JEI.  It is required for lithium battery chain in nuclearcraft.  Can't find how to make or obtain it either.

Possibly related issue in   Magnesium Diboride Alloy #4944

**Comment by NillerMedDild** [comment]
Look into Sifting :)

**Comment by frostedclaws** [comment]
i see no recipees in the sieve from ex nihilo.  its my main resource gen and what i assume you are referring to.  i do see Magnesium. Manganese is a different element and not there as a product.

**Comment by frostedclaws** [comment]
Not certain if you are able to get notified on closed bug reports so sending this email just in case.  I did go through the Ex Nihilo Sieve and was not able to find it again.  I see no recipees in the sieve from ex nihilo. its my main resource gen and what i assume you are referring to. i do see Magnesium. Manganese is a different element and not there as a product.
    On Monday, September 23, 2019, 11:36:23 PM EDT, Niels Pilgaard Grøndahl <notifications@github.com> wrote:  
 
 
Closed #565.

**Comment by NillerMedDild** [comment]
Ah right, woops. I'll look into not.

**Comment by NillerMedDild** [comment]
https://ftb.gamepedia.com/Manganese_Oxide_Dust

**Comment by NillerMedDild** [comment]
I do get notified :)

Sendt fra min HTC-telefon

----- Svarmeddelelse -----
Fra: "frostedclaws" <notifications@github.com>
Til: "NillerMedDild/Enigmatica2" <Enigmatica2@noreply.github.com>
Cc: "Niels Pilgaard Grøndahl" <niels.pilgaard@hotmail.com>, "State change" <state_change@noreply.github.com>
Emne: [NillerMedDild/Enigmatica2] can not obtain manganese (#565)
Dato: ons., sep. 25, 2019 00:28

Not certain if you are able to get notified on closed bug reports so sending this email just in case.  I did go through the Ex Nihilo Sieve and was not able to find it again.  I see no recipees in the sieve from ex nihilo. its my main resource gen and what i assume you are referring to. i do see Magnesium. Manganese is a different element and not there as a product.
On Monday, September 23, 2019, 11:36:23 PM EDT, Niels Pilgaard Grøndahl <notifications@github.com> wrote:


Closed #565.

**Comment by frostedclaws** [comment]
Thank you very much!  That recipe does exist. I'd share my ice cream bar if I could

**Comment by NillerMedDild** [comment]
Haha thanks :D
