### ISSUE TITLE
Mods Not Working Together

### ISSUE THREAD

**Issue by hydro77** [NillerMedDild/Enigmatica2#566]
**Modpack version**
1.71a

**Can the issue be reproduced?**
Yes

**Issue**
Actually Additions' Worms do not work with Rustic's Fertile Soil.

**Comment by NillerMedDild** [comment]
I don't really see that as a bug to be honest, more a limitation of the Worms.

**Comment by hydro77** [comment]
That's a fair take on it. Thanks.

**Comment by NillerMedDild** [comment]
And thank you for the report :)
