### ISSUE TITLE
Quest requiring air blocks

### ISSUE THREAD

**Issue by taiyoko** [NillerMedDild/Enigmatica2#568]
**Modpack version**
1.72

**Can the issue be reproduced?**
unknown

**Logs**
![Image of quest requiring air blocks](https://i.imgur.com/sn5Te4V.png)

**Issue**
In Mekansim Part 2, the quest "Can it make batteries?" is requesting 128 air blocks instead of presumably the evaporation chamber blocks.

**Comment by NillerMedDild** [comment]
The issue you are experiencing has been fixed, please run the command `/bq_admin default load` to reload your quests.
You need admin rights to run the command. If you're playing singleplayer and don't have cheats enabled, Open to LAN from the Esc menu, with cheats enabled.
