### ISSUE TITLE
Request: Update Minecolonies

### ISSUE THREAD

**Issue by tecrogue** [NillerMedDild/Enigmatica2#569]
With how often Minecolonies updates I know it is not really feasible to update the pack every time the mod updates, however even so the current version in the pack (minecolonies-1.12.2-0.10.259-RELEASE-universal.jar 4/11/19) is about 5 months out of date from the last Release titled version of the mod ([minecolonies-1.12.2-0.10.348-RELEASE-universal.jar](https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/2768873) 8/24/19) which includes months of updates, bug fixes, and corrections to the pathfinding system in the mod.

Since there is not a Minecolonies questline I can understand if this request would be low-priority.

**Comment by NillerMedDild** [comment]
Sure, I didn't realize we were that far behind. Do you happen to know if the latest release works on E2?

**Comment by tecrogue** [comment]
I just shut down my system for the night, but I can toss that version in
the pack after work tomorrow.

**Comment by NillerMedDild** [comment]
Sounds good, thanks!

**Comment by tecrogue** [comment]
Updating Minecolonies to minecolonies-1.12.2-0.10.348-RELEASE-universal.jar (the most recent version marked as release instead of alpha) everything seems to be working fine. It did throw a warning message on first load of an existing save that there were missing sounds (which is an expected result due to the colonist callouts changing between versions).

Testing the most recent version (minecolonies-1.12.2-0.10.409-ALPHA-universal.jar) also seems to work fine, but as it is named as an alpha I can understand not wanting to move to that one.

**Comment by NillerMedDild** [comment]
Great!

**Comment by tecrogue** [comment]
As an update: The most recent version (1.12.2-0.10.436-BETA) that came out yesterday is seeming to work well so far with the pack on both SP and MP.

**Comment by NillerMedDild** [comment]
I updated to the latest release :) it's available now, forgot to close this.
