### ISSUE TITLE
Ancient Warfare Crashes the game

### ISSUE THREAD

**Issue by Calletje234** [NillerMedDild/Enigmatica2#570]
**Modpack version**
1.72

**Can the issue be reproduced?**
Yes
**Logs**
-- Head --
Thread: Client thread
Stacktrace:
	at net.shadowmage.ancientwarfare.core.util.parsing.ItemStackMatcher.test(ItemStackMatcher.java:26)
	at net.shadowmage.ancientwarfare.core.util.parsing.ItemStackMatcher.test(ItemStackMatcher.java:10)
	at net.shadowmage.ancientwarfare.automation.tile.worksite.treefarm.Sapling.matches(Sapling.java:19)
	at net.shadowmage.ancientwarfare.automation.registry.TreeFarmRegistry.lambda$isPlantable$6(TreeFarmRegistry.java:75)
	at net.shadowmage.ancientwarfare.automation.registry.TreeFarmRegistry$$Lambda$6963/1975951120.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1561)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at net.shadowmage.ancientwarfare.automation.registry.TreeFarmRegistry.isPlantable(TreeFarmRegistry.java:75)
	at net.shadowmage.ancientwarfare.automation.tile.worksite.treefarm.WorkSiteTreeFarm.isPlantable(WorkSiteTreeFarm.java:55)
	at net.shadowmage.ancientwarfare.automation.tile.worksite.TileWorksiteFarm$1.insertItem(TileWorksiteFarm.java:61)
	at net.minecraftforge.items.SlotItemHandler.func_75214_a(SlotItemHandler.java:58)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:272)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at net.shadowmage.ancientwarfare.core.gui.GuiContainerBase.func_146274_d(GuiContainerBase.java:106)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.shadowmage.ancientwarfare.automation.gui.GuiWorksiteTreeFarm

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['calletje234'/656, l='MpServer', x=229.71, y=68.00, z=644.81]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-145,64,317), Chunk: (at 15,4,13 in -10,19; contains blocks -160,0,304 to -145,255,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1021662 game time, 1332954 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 107 total; [EntityPlayerSP['calletje234'/656, l='MpServer', x=229.71, y=68.00, z=644.81], EntityBat['Bat'/827, l='MpServer', x=165.49, y=25.86, z=588.98], EntityButterfly['Marbled White'/829, l='MpServer', x=188.87, y=67.02, z=601.25], EntityCreeper['Creeper'/831, l='MpServer', x=166.50, y=24.00, z=594.50], EntityCreeper['Creeper'/834, l='MpServer', x=180.83, y=22.00, z=572.48], EntityCreeper['Creeper'/835, l='MpServer', x=186.50, y=24.00, z=568.50], EntityCreeper['Creeper'/836, l='MpServer', x=177.50, y=41.00, z=573.50], EntityZombie['Zombie'/837, l='MpServer', x=166.50, y=28.00, z=586.50], EntityCreeper['Creeper'/838, l='MpServer', x=170.50, y=41.00, z=589.50], EntityFrog['Frog'/839, l='MpServer', x=169.45, y=69.00, z=581.49], EntityCreeper['Creeper'/853, l='MpServer', x=224.50, y=31.00, z=573.50], EntityZombieVillager['Zombie Villager'/854, l='MpServer', x=190.53, y=59.00, z=601.75], EntityBat['Bat'/855, l='MpServer', x=197.53, y=60.75, z=609.91], EntityBat['Bat'/856, l='MpServer', x=203.02, y=60.29, z=613.52], EntityButterfly['Palaeno Sulphur'/857, l='MpServer', x=206.12, y=67.00, z=602.34], EntityCreeper['Creeper'/858, l='MpServer', x=219.50, y=30.00, z=584.50], EntityBat['Bat'/859, l='MpServer', x=221.81, y=34.00, z=570.43], EntityWorm['Worm'/860, l='MpServer', x=221.50, y=66.50, z=590.50], EntityButterfly['Leopard Lacewing'/871, l='MpServer', x=204.32, y=67.09, z=608.31], EntityBat['Bat'/872, l='MpServer', x=217.25, y=35.10, z=570.75], EntityZombie['Zombie'/873, l='MpServer', x=215.49, y=34.00, z=573.29], EntityBat['Bat'/874, l='MpServer', x=168.25, y=54.10, z=617.75], EntityZombie['Zombie'/875, l='MpServer', x=189.50, y=60.00, z=601.50], EntityBat['Bat'/876, l='MpServer', x=191.42, y=61.10, z=595.60], EntityBat['Bat'/877, l='MpServer', x=205.82, y=60.64, z=613.78], EntityButterfly['Marsh Fritillary'/878, l='MpServer', x=190.82, y=67.05, z=607.15], EntityChicken['Chicken'/880, l='MpServer', x=215.22, y=67.00, z=642.47], EntityButterfly['Marsh Fritillary'/881, l='MpServer', x=205.92, y=68.00, z=629.15], EntityButterfly['Blue Wing'/882, l='MpServer', x=217.65, y=71.27, z=620.18], EntityButterfly['Brimstone'/883, l='MpServer', x=192.96, y=68.09, z=631.27], EntityButterfly['Small Heath'/884, l='MpServer', x=216.23, y=69.00, z=636.25], EntityButterfly['Kaiser I Hind'/885, l='MpServer', x=217.54, y=78.45, z=636.81], EntityAncientGolem['Ancient Golem'/886, l='MpServer', x=180.50, y=13.00, z=669.50], EntityZombieVillager['Zombie Villager'/887, l='MpServer', x=180.49, y=47.00, z=675.19], EntityAncientGolem['Ancient Golem'/895, l='MpServer', x=222.52, y=49.00, z=611.75], EntityWorm['Worm'/896, l='MpServer', x=237.50, y=65.50, z=594.50], EntityWorm['Worm'/897, l='MpServer', x=227.50, y=66.50, z=594.50], EntityWorm['Worm'/898, l='MpServer', x=225.50, y=66.50, z=594.50], EntityButterfly['Marsh Fritillary'/899, l='MpServer', x=204.35, y=71.39, z=632.88], EntityButterfly['Brimstone'/900, l='MpServer', x=194.99, y=67.09, z=645.90], EntityButterfly['Canary Speckled Wood'/901, l='MpServer', x=214.74, y=67.04, z=617.52], EntityButterfly['Speckled Wood'/905, l='MpServer', x=224.74, y=69.00, z=616.24], EntityButterfly['Blue Wing'/908, l='MpServer', x=207.80, y=67.00, z=597.53], EntityWorm['Worm'/909, l='MpServer', x=224.50, y=66.50, z=590.50], EntityWorm['Worm'/910, l='MpServer', x=231.50, y=66.50, z=590.50], EntityButterfly['Citrus Swallowtail'/911, l='MpServer', x=223.93, y=68.39, z=604.67], EntityButterfly['Monarch'/912, l='MpServer', x=203.86, y=68.02, z=624.52], EntityZombie['Zombie'/914, l='MpServer', x=243.46, y=43.00, z=628.76], EntityButterfly['Wall'/915, l='MpServer', x=237.28, y=70.07, z=635.42], EntityButterfly['Zebra Swallowtail'/916, l='MpServer', x=259.70, y=90.00, z=609.70], EntitySkeleton['Skeleton'/917, l='MpServer', x=217.50, y=13.00, z=669.50], EntityZombie['Zombie'/918, l='MpServer', x=188.50, y=14.00, z=688.50], EntityFrog['Frog'/919, l='MpServer', x=199.40, y=66.00, z=704.54], EntityBat['Bat'/920, l='MpServer', x=194.46, y=26.10, z=682.52], EntityCreeper['Creeper'/921, l='MpServer', x=195.50, y=22.00, z=673.50], EntityStoneling['Stoneling'/922, l='MpServer', x=198.50, y=22.00, z=675.50], EntityCreeper['Creeper'/923, l='MpServer', x=192.47, y=46.00, z=678.21], EntityFrog['Frog'/924, l='MpServer', x=202.28, y=67.00, z=678.60], EntityFrog['Frog'/926, l='MpServer', x=174.27, y=67.00, z=703.57], EntitySpider['Spider'/927, l='MpServer', x=235.29, y=49.00, z=619.82], EntityZombie['Zombie'/928, l='MpServer', x=234.69, y=57.00, z=624.20], EntityCreeper['Creeper'/929, l='MpServer', x=235.73, y=57.00, z=622.68], EntityCreeper['Creeper'/930, l='MpServer', x=239.55, y=58.00, z=616.83], EntitySkeleton['Skeleton'/931, l='MpServer', x=242.56, y=57.00, z=623.58], EntityBat['Bat'/932, l='MpServer', x=236.87, y=57.50, z=623.74], EntitySkeleton['Skeleton'/933, l='MpServer', x=197.50, y=17.00, z=666.47], EntityZombie['Zombie'/934, l='MpServer', x=187.50, y=14.00, z=686.50], EntityBat['Bat'/935, l='MpServer', x=175.87, y=19.05, z=693.80], EntityZombieVillager['Zombie Villager'/936, l='MpServer', x=186.48, y=44.00, z=672.70], EntityChicken['Chicken'/937, l='MpServer', x=185.72, y=67.00, z=672.85], EntityZombie['Zombie'/938, l='MpServer', x=286.50, y=34.00, z=572.50], EntityZombie['Zombie'/939, l='MpServer', x=233.70, y=48.00, z=624.00], EntitySkeleton['Skeleton'/940, l='MpServer', x=235.49, y=50.00, z=623.70], EntitySkeleton['Skeleton'/941, l='MpServer', x=242.45, y=57.00, z=620.12], EntityAncientGolem['Ancient Golem'/942, l='MpServer', x=234.48, y=50.00, z=625.25], EntityBat['Bat'/943, l='MpServer', x=226.96, y=50.17, z=624.06], EntityBat['Bat'/944, l='MpServer', x=228.84, y=51.36, z=616.37], EntityBat['Bat'/945, l='MpServer', x=228.45, y=49.57, z=620.30], EntityBat['Bat'/946, l='MpServer', x=230.11, y=51.63, z=619.52], EntityWorm['Worm'/947, l='MpServer', x=245.50, y=65.50, z=594.50], EntitySheep['Sheep'/948, l='MpServer', x=305.74, y=67.00, z=603.52], EntitySkeleton['Skeleton'/950, l='MpServer', x=225.50, y=45.00, z=679.50], EntitySkeleton['Skeleton'/951, l='MpServer', x=228.50, y=45.00, z=677.50], EntitySheep['Sheep'/955, l='MpServer', x=307.41, y=65.00, z=584.77], EntityCreeper['Creeper'/956, l='MpServer', x=217.50, y=35.00, z=681.50], EntityCreeper['Creeper'/962, l='MpServer', x=291.25, y=37.00, z=583.50], EntityBullFriesian['Friesian Bull'/963, l='MpServer', x=288.98, y=65.09, z=591.95], EntityCreeper['Creeper'/965, l='MpServer', x=306.30, y=12.00, z=624.69], EntitySkeleton['Skeleton'/966, l='MpServer', x=286.50, y=12.00, z=662.50], EntitySkeleton['Skeleton'/967, l='MpServer', x=284.50, y=12.00, z=663.50], EntityPig['Pig'/968, l='MpServer', x=270.16, y=68.00, z=674.45], EntityPig['Pig'/969, l='MpServer', x=273.84, y=69.00, z=673.11], EntityChicken['Chicken'/970, l='MpServer', x=221.21, y=68.00, z=720.39], EntityBat['Bat'/972, l='MpServer', x=292.61, y=22.87, z=622.60], EntitySkeleton['Skeleton'/973, l='MpServer', x=304.86, y=12.00, z=623.70], EntityStoneling['Stoneling'/974, l='MpServer', x=281.50, y=13.00, z=654.50], EntityCreeper['Creeper'/975, l='MpServer', x=230.50, y=14.00, z=692.50], EntitySkeleton['Skeleton'/976, l='MpServer', x=240.48, y=17.00, z=678.89], EntityZombie['Zombie'/977, l='MpServer', x=245.50, y=20.00, z=684.22], EntityZombie['Zombie'/978, l='MpServer', x=246.50, y=20.00, z=681.50], EntityCreeper['Creeper'/982, l='MpServer', x=287.17, y=15.00, z=705.47], EntityPig['Pig'/988, l='MpServer', x=277.61, y=69.00, z=678.04], EntityPig['Pig'/989, l='MpServer', x=271.79, y=69.00, z=688.43], EntityZombie['Zombie'/995, l='MpServer', x=291.70, y=14.00, z=714.70], EntityZombie['Zombie'/996, l='MpServer', x=293.50, y=16.00, z=714.50], EntityCreeper['Creeper'/1005, l='MpServer', x=283.50, y=16.00, z=704.50], EntityPig['Pig'/1019, l='MpServer', x=289.61, y=67.00, z=722.79]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1145414560 bytes (1092 MB) / 4755292160 bytes (4535 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2836 274 mods loaded, 274 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

**Issue**
When i want to put a tree sappling into the tree farm of ancient warfare. The game freezes and then crashes

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

Additionally, please don't put the log right in the issue, paste it somewhere or just upload the file.
