### ISSUE TITLE
Party sync don't work

### ISSUE THREAD

**Issue by Sos0Burger** [NillerMedDild/Enigmatica2#571]
**Modpack version**
1.72

**Can the issue be reproduced?**
unknown

**Logs**

**Issue**
I connect to my friend. 1) He can create party and me too but i can't accept his invite.
2) if he accept my invite to party, quset counted to me but  after
disappear immediately and again counted and i can't claim reward.

**Comment by NillerMedDild** [comment]
Thanks for the report. We are investigating this issue on the Expert pack's issuetracker. I highly recommend switching to a dedicated server if possible.
