### ISSUE TITLE
Slab to blocks

### ISSUE THREAD

**Issue by SpiritGoblin** [NillerMedDild/Enigmatica2#573]
![slab2plank](https://user-images.githubusercontent.com/56564069/66783386-78e6fe00-eee0-11e9-8d5a-080ee587dc7b.jpg)
**Modpack version**
Enigmatica 2 Expert

**Can the issue be reproduced?**
Unknown

**Logs**
No Crash

**Issue**
I noticed that turning blocks/planks specificly is allright, but turning slabs to blocks
have no image , im not sure if you want to fix this or not, but I thought i'd give ya'll
a heads up incase no one have this problem.

**Comment by NillerMedDild** [comment]
So the issue is, that you can't craft wooden slabs back into wooden planks, correct?
