### ISSUE TITLE
Industrial foregoing auto brewer world crash

### ISSUE THREAD

**Issue by madmacf** [NillerMedDild/Enigmatica2#574]
**Modpack version**
Enigmatica 2 expert 1.68

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/P7nqHH0w

**Issue**
Messed around with the industrial foregoing auto brewer and a bit with the potion generator from ExUt2. The brewer made my world crash. When loading the world again, it crashes out immediately. Had a EnderIO tank with bottles next to it loading into it.

**Comment by madmacf** [comment]
MCedit'ed the brewer away, and the problem disappeared.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by madmacf** [comment]
Tak skal du have :-)
