### ISSUE TITLE
Problems with Astral Sorcery and Thaumcraft

### ISSUE THREAD

**Issue by MgDeception** [NillerMedDild/Enigmatica2#575]
**Modpack version**
 AS - 1.10.2 TC - Thaumcraft-1.12.2-6.1.BETA26

**Can the issue be reproduced?**
unknown

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
I cannot craft anything needed for Astral Sorcery with a prespawned floating crystal or a spawned in one even with enough starlight. Thaumcraft crafting table isn't collecting anymore vis so I cannot progress with that either. 

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment]
You need to craft the Astral Sorcery crafting table to use it.
Move your Thaumcraft crafting table to a different chunk.
