### ISSUE TITLE
One player getting extra yellow hearts and not needing any special foods (me)

### ISSUE THREAD

**Issue by galori** [NillerMedDild/Enigmatica2#576]
**Modpack version**
1.72

**Issue**
We're playing multiplayer with a few friends. i keep getting extra yellow hearts and not needing to drink or eat anything special. I just eat bread and potatoes. The other players say they need to drink different things and eat different foods to keep their hunger at bay.  Sounds like a game mechanic is not working correctly for me.

I haven't done anything that should give me yellow hearts, in fact the opposite, I'm not eating all the different foods I think I'm supposed to be eating.

![image](https://user-images.githubusercontent.com/70486/67135326-61a05d00-f1cd-11e9-888a-e67a05d96d73.png)

The only difference I can think of is that as the server owner I sometimes `/op` myself to do server maintenance stuff, but I always `/deop` myself immediately after.

Another symptom is that sometimes the nutrition measures:"

![image](https://user-images.githubusercontent.com/70486/67135374-ceb3f280-f1cd-11e9-8b43-a4ce002222d0.png)

Shows all the colorful bar graphs at the same level for me (at about 50%) even though the numbers keep showing different values. Here in the screenshot they popped back to actually representing the values. I'll try to catch a screenshot next time they are out of sync with the numbers again.

Its also constantly giving me the toughness enchantment

![image](https://user-images.githubusercontent.com/70486/67135450-c27c6500-f1ce-11e9-88d3-9524a83b0957.png)

**Logs**
n/a

**Comment by galori** [comment]
ok here is an example of the nutrition bars being incorrect:

![image](https://user-images.githubusercontent.com/70486/67166621-eb733600-f345-11e9-928b-c8d8e639ef11.png)

**Comment by NillerMedDild** [comment]
You gain one level of toughness per nutrient type above 90. Dying sets all nutrients below 30% to 30%.
Does relogging fix the display?

**Comment by galori** [comment]
The nutrition bar problem is intermittent. Right now its displayed correctly but earlier today it wasn't. Next time I see it happening I'll log out and back in to see if that causes it to snap back into displaying correctly.

Is there any way to see a log or history of what affected my nutrition, hearts & toughness levels, to understand if it is working correctly?

**Comment by NillerMedDild** [comment]
Sounds good, thanks. There's a food history log in game, but that's it sadly.
