### ISSUE TITLE
Water noises cause massive lag/crashing

### ISSUE THREAD

**Issue by alanapants** [NillerMedDild/Enigmatica2#578]
**Modpack version**
1.7.2

**Issue**
When in water (or any splashable liquid), or when a nearby player is in water, the game occasionally experiences severe lag. Sometimes it will recover on its own if the other player leaves the liquid, but usually it causes Minecraft to stop responding. The issue is not solved by using the mufflers from Super Sound Muffler, either in placeable or bauble form. We have tried reinstalling the assets folder, and the entire modpack, but both my husband and I still experience this issue.

**Logs**
No crash log is generated, and the normal logs do not indicate that anything out of the ordinary has happened.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
You haven't added any mods right?

**Comment by alanapants** [comment]
Nope, the pack is untouched. Nothing added or removed!

**Comment by ReiDaTecnologia** [comment]
I think the possible source of the problem is "Streams" i looked at his github and i saw several issues related with this issue, u could try to remove it to test if it's true.

**Comment by NillerMedDild** [comment]
Removing Streams would be world breaking. I would rather wait and see if the mod author manages to fix the issue.

**Comment by alanapants** [comment]
The issue my husband and I are having doesn't quite line up with what I'm seeing in the Streams github, tbh. The areas we crash in aren't Streams-generated -- it's just any old puddle of liquid -- and we don't get a crash log or any weird log notes at all.

**Comment by NillerMedDild** [comment]
I'd like to have a look at your latest.logs.

**Comment by alanapants** [comment]
Okay! Updates! I have a log below.

We experimented with me splashing around in the water to see if we could get my husband's client to hard crash. It never died entirely, but it would lock up until 5+ minutes after I left the water. Eventually we narrowed it down not to the sound, but to the splashing particles. He turned particle effects to the minimum and experiences no problems now. At line 9775 of the log, it reads

[19:34:40] [Client thread/WARN]: Something's taking too long! 'root.tick.particles' took aprox 260250.647471 ms

and that's what got him on that avenue. No idea what the reason is, because his computer is running on almost all shiny new pieces, and all but the graphics card is the exact same as my own PC :P

https://paste.ubuntu.com/p/sWgSq7Ch9k/

**Comment by NillerMedDild** [comment]
Great work! I'm fairly certain AI know why he has the issue. He's running on very very old Java. Check below snippet for details.

You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

**Comment by dosfx** [comment]
Alana's husband here:

Confirmed that the edit to the settings did indeed force minecraft to use the OS installed java. Right click > Properties on javaw in the task manager and it points at `C:\Program Files\Java\jre1.8.0_231\bin\javaw.exe`.

However, I still got a lag spike after looking at Alana in the water. Can we provide any more debug info?

**Comment by NillerMedDild** [comment]
I would like your new latest.log, so I can inform the mod author :)

**Comment by NillerMedDild** [comment]
It appears as if Streams has changed quite a bit, it no longer uses it's own water sources, so I think this is fixed.
