### ISSUE TITLE
Placing IE Fluid Pipe next to EIO Pressurized Fluid Conduit causes corrupting crash

### ISSUE THREAD

**Issue by Targren** [NillerMedDild/Enigmatica2#58]
#### Issue Description

There appears to be a mod interaction bug between Immersive Engineering 0.12-82 and EnderIO 5.0.26.  When placing a fluid pipe next to a pressurized fluid conduit, the game crashes. Attempts to reload the world subsequently continue to crash.

I've verified that this interaction bug exists between the above two mods with no other mods present. It does not appear after replacing IE 0.12-82 with IE 0.12-84

#### Modpack version (Do not use "latest")

1.42

#### Crash Report

[Crashlog](https://gist.github.com/Targren/7c7e96556090fcc0f50019c679328b17)

**Comment by NillerMedDild** [comment]
Thank you for the well made report :)
