### ISSUE TITLE
Requesting Deep Mob Learning Addition

### ISSUE THREAD

**Issue by yunyunls** [NillerMedDild/Enigmatica2#580]
**Modpack version**
1.73b

**Issue**
not a issue, but a suggestion to add deep mob learning which is a mob looting/spawning mod which is very easy on the server since it doesnt actually spawn  mobs. Should help improve performance of servers and overall FPS for some bases.

**Comment by NillerMedDild** [comment]
Good suggestion, but I am not going to add more mods at this point.
