### ISSUE TITLE
Compact Drawers - Visual Glitch after update

### ISSUE THREAD

**Issue by TInyTim917** [NillerMedDild/Enigmatica2#581]
**Modpack version**
1.73b

**Issue**
After I updated to 1.73b. When I right click my existing compact drawers. The Items visually disappears, and the drawer displays empty on WALIA. But I can still right click more to withdraw items. After Relogged the items are displayed again until I right click again.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Ravalli03** [comment]
Having same issue on server. I can use drawers just find, but when other player tries to insert items in, it rotates the drawer, and they can't use it

**Comment by NillerMedDild** [comment]
I have no way of testing or fixing this I'm afraid.
