### ISSUE TITLE
Dark Armor Upgrades Duplication Bug

### ISSUE THREAD

**Issue by quietassassin16** [NillerMedDild/Enigmatica2#584]
**Modpack version**
1.74

**Issue**
If you equip armor pieces from your hotbar by right clicking upgrades besides empowered 1 get duplicated.

**Comment by NillerMedDild** [comment]
Thank you for the report, I am investigating the issue.

**Comment by NillerMedDild** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/5262

**Comment by HenryLoenwind** [comment]
add-label: fixed, just update endercore

;)

**Comment by NillerMedDild** [comment]
Thanks!
