### ISSUE TITLE
Install Error 1.74b

### ISSUE THREAD

**Issue by TheLawrenceWolf** [NillerMedDild/Enigmatica2#588]
**Modpack version**
1.74b

**Issue**
When trying to install using Twitch after reboot and running as admin, I receive these errors.
Unable to get Addon: Enigmatica 2 (269353) - File ID: 2832000
Failed to get mod loader from manifest!

**Logs**

**Comment by beasleyboy** [comment]
Same, I haven't been able to download the modpack all day
Addon/Dependency is missing

**Comment by NillerMedDild** [comment]
Works fine for me at the moment, any progress for your guys? :)

**Comment by TheLawrenceWolf** [comment]
It works fine now. It was all Twitch having a fit.
