### ISSUE TITLE
Crash when trying to pick up EnderIO Machines with any Wrench

### ISSUE THREAD

**Issue by MollyXVI** [NillerMedDild/Enigmatica2#589]
**Modpack version**
Enigmatica 2 Version: 1.74b

**Issue**
Client Crash when trying to pick up EnderIO Machines with any Wrench

**Logs**
[https://paste.md-5.net/enecayaqen.rb](url)

**Comment by NillerMedDild** [comment]
Thank you for the report. Do you happen to be in a claimed chunk? (Through FTBUtilities)

**Comment by MollyXVI** [comment]
Yes, claimed and chunk loaded by me

**Comment by NillerMedDild** [comment]
Alright, while we investigate you should be able to resolve the issue by removing the claim.

**Comment by NillerMedDild** [comment]
Aha, it has been fixed, I'll update soon :)
https://github.com/FTBTeam/FTB-Utilities/issues/1047

**Comment by MollyXVI** [comment]
Wonderful ! I'm glad i could help, i'll make sure to post as much issues i find

**Comment by NillerMedDild** [comment]
Thanks!
