### ISSUE TITLE
 Thermal Expansion induction smelter doesn't accept pulverized coal (thermal foundation) to the left slot which blocks a few valid receipts.

### ISSUE THREAD

**Issue by igrvak** [NillerMedDild/Enigmatica2#59]
Issue Description: Thermal Expansion induction smelter doesn't accept pulverized coal (thermal foundation) to the left slot which blocks a few valid receipts.

Modpack version: 1.42

**Comment by NillerMedDild** [comment]
Have you tried unlocking it?

**Comment by igrvak** [comment]
Oh, I got it. I just don't know how to use Thermal Expansion. Sorry for wasting your time!

**Comment by NillerMedDild** [comment]
No worries, honest mistake :)
