### ISSUE TITLE
IC2 chuck loader corrupts world chunks

### ISSUE THREAD

**Issue by Pultex** [NillerMedDild/Enigmatica2#591]
**Modpack version**
Version: 1.72

**Issue**
IC2 chunk loader world corruption

IC2 chunk loader makes chunks not the same after entering another dimension 
The world will get unstable and areas will get corrupted

Stop use will prevent the problem

**Logs**
no log just trying to find what is breaking my world
The only thing change was not using that item

The other claim chunk, load chunk method works with some dupe problems
logging out and back in seem to fix that problem

**request**
add a different chunk loader to prevent corruption

**Comment by NillerMedDild** [comment]
Do you have any sort of proof or... anything? Screenshots, logs?
