### ISSUE TITLE
Crash when opening world

### ISSUE THREAD

**Issue by TheSphereWizard** [NillerMedDild/Enigmatica2#593]
**Modpack version**
1.74

**Issue**
Crash when opening world

**Logs**
https://paste.ee/p/ZzwEI

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
Please try version 1.75b and let me know if it resolves the issue.

**Comment by Harlekin13** [comment]
Not quite a crash for me, but 0-1FPS isn't far away from it... Perhaps that's the same issue?

**Comment by NillerMedDild** [comment]
@Harlekin13 If you have an AMD GPU, please try removing FoamFix and see if that fixes your issue.
