### ISSUE TITLE
Smelt Pulverized Iron

### ISSUE THREAD

**Issue by TInyTim917** [NillerMedDild/Enigmatica2#594]
**Modpack version**
1.75a

**Issue**
Cannot smelt Pulverized Iron. It look like I cannot put Pulverized Iron in a furnace to smelt it. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Update to 1.75b.

**Comment by TInyTim917** [comment]
Thanks Niller!
