### ISSUE TITLE
Server won't go past Applying holder lookups 

### ISSUE THREAD

**Issue by ObiJuanKenobi2223** [NillerMedDild/Enigmatica2#597]
**Modpack version**
1.75b

**Issue**
server not launching

Pasted log removed by NillerMedDild

**Comment by NillerMedDild** [comment]
Please supply your logs, don't just paste what you assume is the important part. 
And please, do not ever paste a log into chat, upload it somewhere like pastebin or gist.github.

**Comment by Pelargir42** [comment]
not the OP but had the same problem.

https://pastebin.com/mm63icLJ

**Comment by NillerMedDild** [comment]
@Pelargir42 The last thing it says is it's installing Forge, so if it doesn't ever load, you should try downloading manually :)
