### ISSUE TITLE
I can't uninstall the modpack or fix it.

### ISSUE THREAD

**Issue by MotionlessGrins** [NillerMedDild/Enigmatica2#598]
**Modpack version**
Enigmatica 2 Version 1.74b

**Issue**
I can't fix the files or update the pack because on the Twitch launcher it says, "Cannot update, files are already in use. Please exit any applications that may be using the files in this profile folder." I have nothing running any where. I just want to delete the pack at this point because I can't even play it.

**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Navigate to the folder the modpack is in, and right click it. Click Properties, I think that's the name atleast (lowest option)
That'll open a window, where the bottom looks like this:
![billede](https://user-images.githubusercontent.com/21295394/71740254-042abc80-2e5c-11ea-830a-09facd1f9613.png)
Untick the box that you can see ticked on the image.
That should be it.
