### ISSUE TITLE
Immersive Engineering Steel Plate recipes

### ISSUE THREAD

**Issue by Garubis** [NillerMedDild/Enigmatica2#6]
#### Issue Description
I was able to use an Immersive Engineering hammer to make steel plates and then craft a metal press mold: plate. After crafting this I went to use the metal press to make more steel plates for other molds.
#### What happens
The press makes steel plates from Immersive Engineering, but they cannot be used to craft any other molds for the metal press.
#### What you expected to happen
I expected any steel plate, whether crafted by hammer or metal press, to be able to be used where other steel plates work.
#### Modpack version (Do not use "latest")
1.24

Edit: This also happens with IE constantan plates, they can't be used or melted down.

**Comment by Garubis** [comment]
Same with the immersive engineering constantan plate made in the metal press, they can't be used or melted back down.

**Comment by NillerMedDild** [comment]
The Metal Press is supposed to make Thermal Expansion Plates, I removed all Immersive Engineering plates - or so I thought. I'll look into it asap :)

**Comment by NillerMedDild** [comment]
Fixed - Thank you for reporting!
