### ISSUE TITLE
Recipe Conflict: Iron Chain(Rustic) and Iron Torque Shaft(Ancient Warfare Core)

### ISSUE THREAD

**Issue by tsudico** [NillerMedDild/Enigmatica2#60]
#### Issue Description
To create an Iron Chain for Rustic, JEI shows three iron ingots in a vertical line. When put in a crafting table, the output is an Iron Torque Shaft from Ancient Warfare Core.

#### Modpack version (Do not use "latest")
1.43

#### Crash Report
No crash report

Since a chain is more flexible than a torque shaft, I added the following to RecipeConflicts.zs:
```
# Rustic Iron Chain
	recipes.remove(<rustic:chain>);
	recipes.addShaped("Rustic Iron Chain", 
	<rustic:chain> * 12, 
	[[<ore:ingotIron>, null, null],
	[null, <ore:ingotIron>, null], 
	[<ore:ingotIron>, null, null]]);
```
This recipe doesn't appear to conflict with any existing recipe.

**Comment by NillerMedDild** [comment]
Thank you for the fix, added to my dev instance. Good work!
