### ISSUE TITLE
Reactor electromagnets problem

### ISSUE THREAD

**Issue by Jerryongithub** [NillerMedDild/Enigmatica2#601]
**Modpack version**
1.75b

**Issue**
Fusion reactor electromagnets do no share energy they all need to be connected separately to a power source which is annotying because even after being all powered up if you take the connection out they lose the power.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
I thought that was enabled, it will be in the next version :)

**Comment by Jerryongithub** [comment]
Ok, thanks
