### ISSUE TITLE
Astral Sorcery Recipe Not Working

### ISSUE THREAD

**Issue by Warped2pt0** [NillerMedDild/Enigmatica2#602]
**Modpack version**
1.74b

**Issue**
Unable to craft Resonating Wand in vanilla Crafting Table. Recipe calls for "starlight", but unable to craft at nighttime.

**Logs**
Included image to show issue:

![2020-01-09_11 38 21](https://user-images.githubusercontent.com/42042640/72086776-82141b00-32d5-11ea-904c-b4aaee6e6e3c.png)

**Comment by NillerMedDild** [comment]
You need to use the Astral Sorcery starter crafting table. I highly recommend that you read the Astral Sorcery guidebook that you're given.

**Comment by Warped2pt0** [comment]
Ah, thanks. Found the correct way to craft. Always hard to know which recipe to use with recipe tweaked modpacks.

**Comment by NillerMedDild** [comment]
Very true :)
