### ISSUE TITLE
Building Gadgets NullPointerException

### ISSUE THREAD

**Issue by mgibbs1322** [NillerMedDild/Enigmatica2#603]
**Modpack version**
Enigmatica 2 expert 1.74

**Issue**
Immediately after attempting to select Xnet cable with Building Gadgets build tool, game crashed with a NullPointerException.  Problem reoccurs immediately after loading the saved world.

**Logs**
https://pastebin.com/iNWFthwx

**Comment by NillerMedDild** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments
