### ISSUE TITLE
Multiplayer quests broken

### ISSUE THREAD

**Issue by Cupcakez1** [NillerMedDild/Enigmatica2#606]
Version 1.75b

So I'm playing on a LAN server with my boyfriend and we will party up one of us will complete a quest and then the other can't claim the quest. We thought it was because we added new mods (for decoration) but when doing it again without these mods it does the same thing. We have tried refreshing it with admin commands and tried every known command for the questing books but it doesn't seem to work.

**Comment by NillerMedDild** [comment]
We are aware of the issue and have reported it :)
