### ISSUE TITLE
Infinite power - Wireless Crafting Terminal

### ISSUE THREAD

**Issue by Defman** [NillerMedDild/Enigmatica2#608]
**Modpack version**
Enigmatica2Expert-1.73

**Issue**
Charging the "Wireless Crafting Terminal" in a "Induction Matrix" from "Mekanism" results in negative -2^31 AE on the "Wireless Crafting Terminal" and a constant max input rate of RF into the "Induction Matrix". If the "Induction Matrix" contains a single "Advanced Induction Cell" and "Advanced Induction Provider" it will charge with 204.8kRF/t until its full at 3.2GRF.

![image](https://user-images.githubusercontent.com/1496019/72265998-c11bd680-361d-11ea-9d0a-382b99acf4e0.png)

**Comment by NillerMedDild** [comment]
This issue is being tracked on the Expert tracker, OP made a new issue there.
