### ISSUE TITLE
Many different wood planks make the Oak Trapdoor

### ISSUE THREAD

**Issue by GrokDuckFarmer** [NillerMedDild/Enigmatica2#609]
**Modpack version**
Enigmatica2 1.75b

**Issue**
Many different non-vanilla wood planks make oak trapdoors by default rather than their own.  Crafting amaranth planks into a trapdoor gives the oak trapdoor instead of the amarath one.

**Logs**
N/A

**WorkAround**
The Forestry worktable has arrows that allow a player to select from different outputs when there is a conflict.  But players who don't know about the Forestry worktable get frustrated that they cannot create the trapdoor they want.

**Comment by NillerMedDild** [comment]
Thanks for the report - I know this worked a few updates ago, so I don't know what's up, but I'll have a look.

**Comment by NillerMedDild** [comment]
Turns out I was wrong, this never worked :P It will in the next update though!
