### ISSUE TITLE
Unable to progress in Twilight Forest

### ISSUE THREAD

**Issue by aaj2005** [NillerMedDild/Enigmatica2#610]
**Version:**
1.75

**Issue**
So I decided to start Twilight Forest, however, I am unable to obtain the advancements in any way including the /advancement command. I tried resetting the dimension, revoking the advancements and starting again. Nothing works.

Thanks

**Comment by NillerMedDild** [comment]
I'm afraid you will have to delete or edit your player.data. if you need help, please go to my discords support section. I'll give you a link below.
