### ISSUE TITLE
JER World Gen entries not matching Adv Rocketry planets

### ISSUE THREAD

**Issue by Void-Concept** [NillerMedDild/Enigmatica2#611]
**Modpack version**
1.75b

**Issue**
It looks like the World Gen entries for the Advanced Rocketry planets don't line up. I looked for Iridium ore on Europa, and Dimensional Shard ore on Stella like JER suggests, but haven't found any on those planets. 

I've tried looking in 2 ways: Mekanism's Digital Miner and the /oredistribution command. Neither are able to find the ores I'm looking for.

I am playing on a server and haven't tried on a single player world yet

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Void-Concept** [comment]
I'll point out two instances of a mismatch:
In planetDefs, Stella is DIMID 114
https://github.com/NillerMedDild/Enigmatica2/blob/560c544c8030f7f5a397bc6a19cbed9dc38e6455/config/advRocketry/planetDefs.xml#L138

In CoFH World Adv Rocketry planet config, Iridium (thermalfoundation:ore meta 7) spawns on 114
https://github.com/NillerMedDild/Enigmatica2/blob/560c544c8030f7f5a397bc6a19cbed9dc38e6455/config/cofh/world/15_advanced_rocketry_planets_ore.json#L270

However, if you search through world-gen.json for `thermalfoundation:ore:7`, none of the matches are `Stella`
https://github.com/NillerMedDild/Enigmatica2/blob/master/config/jeresources/world-gen.json

And I can confirm that iridium does spawn on Stella

----

Another instance:
world-gen.json says that dimensional shards spawn on Stella (line 54913)

Stella is DIMID 114 as linked above

However, CoFH World doesn't whitelist dimensional shards on 114
https://github.com/NillerMedDild/Enigmatica2/blob/560c544c8030f7f5a397bc6a19cbed9dc38e6455/config/cofh/world/15_advanced_rocketry_planets_ore.json#L52

**Comment by NillerMedDild** [comment]
Excellent bug confirmation, thanks. I'll try to find time to get this fixed :)

**Comment by NillerMedDild** [comment]
I'd love to fix this, but I crash to desktop when I try to run the `/jer_profile 100` command ><

**Comment by NillerMedDild** [comment]
Yeah no, I keep crashing. Sorry, won't be able to fix this.

**Comment by ReiDaTecnologia** [comment]
> I'd love to fix this, but I crash to desktop when I try to run the `/jer_profile 100` command ><
> 
> Edit: `/jer_profile 50` worked, but `jer_profile 50 all` crashed me after a few minutes.

Hello, looks like i can do this command just fine in Stella, Europa and the overworld, do u want me to give u the world-gen.json or u need something else?

**Comment by NillerMedDild** [comment]
That's nice of you, thanks, but I would need nearly all dimensions, ideally.

At the very least dimensions -1, 0, 1, Deep Dark (-11345?) and 100-125. We're working on making the `/jer_profile 50 all` command run without crashing, but there are quite a few crashes to sift through.
