### ISSUE TITLE
Binnie's Mods - Binnie's Extra Trees give unlimited berries on right click.

### ISSUE THREAD

**Issue by TooMuchTyme** [NillerMedDild/Enigmatica2#612]
**Modpack version**
1.76

**Issue**
Binnie's Mods - Binnie's Extra Trees give unlimited berries on right click.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thanks for the report, it has been reported to the mod author here: https://github.com/ForestryMC/Binnie/issues/624
