### ISSUE TITLE
Overbuff on IC2 RTG

### ISSUE THREAD

**Issue by ikkonoishi** [NillerMedDild/Enigmatica2#614]
**Modpack version**
1.76a 

**Issue**
IC2 RTG cannot physically output the amount of EU it generates with more than 3 cells.

As a tier 1 machine it can only output 32EU/t.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
More cables should do the trick.
Please let me know whether it works or not :)

**Comment by ikkonoishi** [comment]
It's a hard limit. If more cables are connected they will alternate between them.  Generators can only output one packet per tick but transformers can output one per face. You can test this by putting three cells in and then placing a mekanism cube next to it. The energy buffer in the rtg will stay the same since it is outputing at the same rate it produces. Putting a second cube next to it will split the power between them but not drain the buffer.

**Comment by NillerMedDild** [comment]
I can't really do anything to remedy this I'm afraid.
