### ISSUE TITLE
Game menus not fitting in window

### ISSUE THREAD

**Issue by Scorch5000** [NillerMedDild/Enigmatica2#616]
**Modpack version**
1.76

**Issue**
the images in the menus and settings menus are not fitting in the screen, and yes, it is on full-screen. This causes me to not be able to change my controls. help, please!

![Annotation 2020-02-07 224706](https://user-images.githubusercontent.com/59297113/74078734-ea9d0780-49fb-11ea-8858-351fe8982eac.png)
.

![image](https://user-images.githubusercontent.com/59297113/74078634-db698a00-49fa-11ea-8e7f-af74eab91bb9.png)

**Comment by NillerMedDild** [comment]
Try changing your GUI size :)
