### ISSUE TITLE
Add the mod Aurora (Guide mod for FTB Utilities)

### ISSUE THREAD

**Issue by merak69** [NillerMedDild/Enigmatica2#617]
**Modpack version**
1.76

**Issue**
Idle timeout on player login to a brand new dedicated server.  It immediately kicks anyone that tries to join.  I've tried adjusting the config in RandomPatches and even removing RandomPatches mod.  I have 8gb allocated to the server and I've run dozens of mod packs without issue.  I've also tried removing the world folder and starting over to no avail.  Nothing crashes, server stays running just fine.

The server isn't a slouch either: i5-9600K, 32gb ram, Samsung 970 NVMe SSD

Any idea of what's going on?

**Logs**
https://pastebin.com/A8M4N6Hv

**Comment by merak69** [comment]
Here's server.properties file
https://pastebin.com/0uhtQufN

**Comment by merak69** [comment]
So it seems to only affect those in the ops.json file... If I remove myself I can login just fine.

I went to the server console and opped myself with the /op command and it immediately kicked me with the same message as before "idle too long".  Totally confused.

**Comment by merak69** [comment]
I figured it out... There was a permission on my "admin" rank configured wrong.  Because the Aurora mod is missing from the server (https://www.curseforge.com/minecraft/mc-mods/aurora), I had to guess on the permission name.

The FTB group made changes to stop writing out the "all_permissions.html" files in the local/ftbutilities directory.  Instead you need to use the Aurora mod to get the details.

I installed it server side only and everything works fine so you might want to look at adding this to the pack.

**Comment by NillerMedDild** [comment]
I'm glad you figured it out :)

I don't think I will add Aurora, since there's no issue with default config.

**Comment by merak69** [comment]
As a server admin, how would you propose anyone knows the available
permissions for FTB Utilities without this mod then?

**Comment by NillerMedDild** [comment]
Has the FTB Utilities wiki been discontinued?

**Comment by merak69** [comment]
This isn't something that can be documented on a wiki as each mod pack is different.

In older versions of the FTB Utilities mod, the mod would create a file called "all_permissions.html" in your local/ftbutilities directory in the server.  It would dynamically create this file based on all of the mods in the pack that subscribed to the permissions system so you could open it and know how to configure permissions for said pack.

In the new version of the mod, they removed the code to create the "all_permissions.html" file and instead integrated into the new Aurora mod they created which now displays this information as a local built in webserver.

Without this mod in the server pack, anyone installing Enigmatica 2 server would also need to install this mod if they wanted to correctly do permissions on their server.

**Comment by NillerMedDild** [comment]
Ah alright, I thought we still had the html file in addition to a wiki - Thanks for the explaination, I'll add Aurora in the next update.

**Comment by merak69** [comment]
Cool, thanks!  Sorry if I wasn't very clear.

**Comment by NillerMedDild** [comment]
We will not be adding this mod after all, as it can cause issues with servers that run VMWare.
