### ISSUE TITLE
Slag violates laws of thermodynamics 

### ISSUE THREAD

**Issue by ikkonoishi** [NillerMedDild/Enigmatica2#618]
Input version here
1.76a

Input short description of the issue here
One coal = one coal coke. One coal coke + iron = One slag + steel. One slag = 4 coal dust + 1 tiny gold dust (IC2 Centrifuge). 4 coal dust = 400 mb liquefacated coal(Nuclearcraft melter). 400 mb liquid coal = 4 coal (Tinkers casting gem cast).

May or may not be energy positive. Economies of scale likely kick in later on. Preheaters make build more compact, but use more power. Idle time on the Centrifuge wastes power. Creosote byproducts can be used as fuel, and it creates more coke than one advanced blast furnace can use. Creates more coal than 12ish unpreheated advanced coke ovens can cook with just one centrifuge. Spent time should be sleeping to test. 2:30AM now. Should stop typing. Hey Issue201 this is why you don't oredictionary things together randomly. No hate though love you man. Peace.

**Comment by NillerMedDild** [comment]
This is one of the best bug reports I've received, thanks for sacrificing your sleep :P
