### ISSUE TITLE
Problem with the questbook on the tinker's construct chapter

### ISSUE THREAD

**Issue by Mushwoom** [NillerMedDild/Enigmatica2#619]
**Modpack version**
Version 1.76

**Issue**
On the tinker's construct chapter, [instead of grout it says air](https://imgur.com/a/xw6T8Cx)

**Logs**
none

**Comment by NillerMedDild** [comment]
The issue you are experiencing has been fixed, please run the command `/bq_admin default load` to reload your quests.
You need admin rights to run the command. If you're playing singleplayer and don't have cheats enabled, Open to LAN from the Esc menu, with cheats enabled.
