### ISSUE TITLE
Items in TiC casting table and casting basin invisible

### ISSUE THREAD

**Issue by dockeith** [NillerMedDild/Enigmatica2#62]
**#### Issue Description**
All items in Tinkers' Construct Casting Table and Casting Basin are invisible. This applies to molds and parts in Casting Table as well as all finished products like blocks in Casting Basin and ingots and parts in Casting Table.

The tapping animation works for both the table and basin as you can see them filling up and cooling off. Once the product is cooled off and finished, the item disappears. It is still collectable by right clicking the seemingly empty table or basin.

Have tried removing and replacing the table and basin, as well as doing a quick search for this issue elsewhere.

**#### Modpack version**
1.43

**Comment by NillerMedDild** [comment]
Update
