### ISSUE TITLE
Crafting villager Market in AE2 

### ISSUE THREAD

**Issue by Masharibzaheer** [NillerMedDild/Enigmatica2#621]
#604 i am playing newest version of this mode pack and when i shift click villager market in AE2 crafting terminal it freeze me game and i have to force close minecraft i tried removing forestry it fixed it...can you fix this in next update

**Comment by Masharibzaheer** [comment]
just want to report it

**Comment by NillerMedDild** [comment]
Thanks for the report, I would rather not remove one of the mods that add planks, but I'll see what I can do.

**Comment by NillerMedDild** [comment]
Gonna close this issue and track the issue in the issue you linked.
