### ISSUE TITLE
Hard Carbon Weapons/Tools from Tinker's Won't Repair

### ISSUE THREAD

**Issue by scottmmuc** [NillerMedDild/Enigmatica2#623]
**Modpack version**
1.76

**Issue**
I have a couple tinker's weapons made with hard carbon elements that can't be repaired. One is a broadsword where the main sword blade is hard carbon, and one is a crossbow bolt where the arrow shaft is enderium and the bolt tip is hard carbon. In both cases, when the item is placed on the tool forge with hard carbon as the repairing material, the tool shows up in the output box as if it's being repaired but the durability doesn't go up, and if I claim the item from the output box it'll consume 1 hard carbon ingot without repairing at all.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by scottmmuc** [comment]
Awesome, thanks for the quick reply!

**Comment by NillerMedDild** [comment]
Looks like our config was messing it up, I think I've fixed it ^^

**Comment by scottmmuc** [comment]
Yup this works! I just updated my server and client configs with the new data values for the Nuclearcraft materials and everything's working normally now :D

**Comment by NillerMedDild** [comment]
Sweet, thanks for the confirmation.
