### ISSUE TITLE
Pam's Carrot Cake does not register as eaten

### ISSUE THREAD

**Issue by GamerXD8991** [NillerMedDild/Enigmatica2#627]
**Modpack version**
1.77

**Issue**
Eating the Cake ingame does not register in SoL:Carrot.
Looking throught the book i discovered that the Carrot cake is listed twice (!) as not yet tried. I opened the playerdata file in NBT explorer and there is an entry called "harvestcraft:carrotcake@0". using the ingame command "/foodlist sync" but it doesn't fix the issue.

**Logs**
no logs but if you need something else I'm willing to help

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by GamerXD8991** [comment]
Update:
Some other cakes won't register as well (Cherry Cheese and Chocolade Sprinkles) and apperantly all Pams Cakes show up twice in the book, which brings me to believe that there's a problem with Item/Block Cake and Block Cake with NBT/Block State (bites eaten) furthermore on cakes that register you get it on the first bite (defenitly) and on the last one (not sure about this part).

So this could be a config problem or a problem with the SoL:Carrot Mod itself

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
