### ISSUE TITLE
[Suggestion] EnderIO's Endergy

### ISSUE THREAD

**Issue by ReiDaTecnologia** [NillerMedDild/Enigmatica2#628]
Iirc u don't receive mod suggestion anymore but as i don't believe in my memory and i really would like for this **[must have mod](https://www.curseforge.com/minecraft/mc-mods/ender-io-endergy)** to be in the modpack by default, i will do this suggestion anyway :)

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, but we are not adding new content mods at this time :)

**Comment by ReiDaTecnologia** [comment]
yup my memory was right :(
