### ISSUE TITLE
Quest - Band Of Mana no detections

### ISSUE THREAD

**Issue by TInyTim917** [NillerMedDild/Enigmatica2#629]
**Modpack version**
1.7.6

**Issue**
Band on Mana Quest won't detect the band of Mana. I crafted the Band of Mana and the quest will not detect it.

**Comment by NillerMedDild** [comment]
Hun, alright, I'll get that fixed :)

**Comment by Jobever** [comment]
It is still (or again) not registering propperly. version 1.78

**Comment by NillerMedDild** [comment]
Did you remember to run the command `/bq_admin default load`? :)

**Comment by Jobever** [comment]
Thanks, that solved it
