### ISSUE TITLE
Unable to create Treated Wood Planks using Fluid Transposer

### ISSUE THREAD

**Issue by dockeith** [NillerMedDild/Enigmatica2#63]
#### Issue Description
Trying to create treated wood for the Immersive Engineering quests using the recipe from JEI telling me to use 1 logWood with 125 mB Creosote Oil to create 1 Treated Wood Planks. The Fluid Transposer from Thermal Expansion won't accept any of the displayed logWood types in its input slot.

Either the JEI recipe needs to be removed if it is not intended to work, the recipe fixed if it is not correct, or the bug with FT not accepting logWood needs to be addressed.

Have tried all the types of logWood i have, including several not listed in the JEI recipe. Also tried with different types of planks, as that would be more logical in my eyes. I see that the alternative is using the Fluid Infuser for NuclearCraft, but that is so expensive compared to the Fluid Transposer. The Fluid Infuser uses plankWood as opposed to logWood.

#### Modpack version (Do not use "latest")
1.43

**Comment by NillerMedDild** [comment]
There's a normal crafting recipe for Treated Wood Planks. 8 Planks around 1 Bucket of Creosote.

**Comment by NillerMedDild** [comment]
Looks like this issue will be resolved whenever Thermal Expansion updates.
https://github.com/CoFH/Feedback/issues/1159
