### ISSUE TITLE
Crafting Recipe for Iron Dust from Iron Grains dissapeared

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [NillerMedDild/Enigmatica2#630]
**Modpack version**
1.77
**Issue**
Recipe used to be available (1.69), is now gone. Can't seem to find anything pertaining to this in the changelog, so assume its an issue.

If this was intentional, how would I go about undoing it? Thank in advance

**Comment by NillerMedDild** [comment]
Hmm.. WWhat is Iron Grain? Which mod is it from and how do you get it?

**Comment by ErnestoPeroPezzi** [comment]
Iron Grains from Binnie's mod. Point of note, gold grains were also affected. It is the produce of the combs from Rusty bees

**Comment by NillerMedDild** [comment]
Have you checked the changelog for Binnies mod?

**Comment by ErnestoPeroPezzi** [comment]
I did not find anything there regarding the grains, and boy was it a long one

**Comment by NillerMedDild** [comment]
Alright I'll have a look :)

**Comment by JVital2013** [comment]
I can confirm the issue. I just worked my way all the way up to Rusty Bees, only to find that I can't craft anything with the iron grains

**Comment by Lennart247** [comment]
Are you sure that this script completely fixes the Issue? I added it to server and client, but it doesnt seem to fix the bug serverside. I can craft iron dust in SP but not in MP.

**Comment by NillerMedDild** [comment]
User comment in the PR, note to self:
> I would suggest adding the following line to the script:
recipes.addShapeless(thermalfoundation:material:768, [extrabees:misc:18,extrabees:misc:18,extrabees:misc:18,extrabees:misc:18]);
fixes the coal grain recipe (if removing this wasnt intended) which didnt work either (at least for me).
