### ISSUE TITLE
Blocks from enviromental tech dissapear when broken with the atomic disassembler.

### ISSUE THREAD

**Issue by frophithe** [NillerMedDild/Enigmatica2#631]
**Modpack version**
1.7.6

**Issue**
When mining multiple blocks from environmental tech with the atomic dissasembler from mekanism in extended vein only drop one block. I have tested this with structure frames, structure panels, laser cores and modifiers. If there is more than one block touching when mined with the atomic dissasembler all break but only one is dropped.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thanks for the report. Could you please update to 1.77 and see if that fixes the issue? That pack version has a Mekanism update.
