### ISSUE TITLE
IC2 Coal Coke in Macerator

### ISSUE THREAD

**Issue by GamerXD8991** [NillerMedDild/Enigmatica2#632]
**Modpack version**
1.77

**Issue**
The Coal Coke from Immersive Engineering and from Thermal Foundation can be crushed in the Macerator into Coke Dust. The one from IC2 can't. Is this a bug/missing recipe or inteted?

**Comment by NillerMedDild** [comment]
I didn't think IC2 was obtainable tbh, it's a bug :P
