### ISSUE TITLE
Mob Farms

### ISSUE THREAD

**Issue by gamercraft30x** [NillerMedDild/Enigmatica2#634]
**Modpack version**
1.77

**Issue**
Going to try to keep it short - I created a small mob farm in a new world save, like I had in previous versions of this pack, but with 1.77 I am not getting a single mob spawn in the farm. I do outside the farm (in the world), but not in it.

I tried it in different locations in the world, no luck.
I tried it 128 blocks above base. No luck.
I tried it in creative mode, different world save, you guess it no luck. Etc

I'm not saying this is a bug but I'm not sure if something has changed that I missed? Or maybe it is a bug I don't know, but it's frustrating lol.

Any help would be appreciated,
Thanks! 

EDIT: Please close, problem solved, I forgot I needed the Drop of Evil for the dirt. sorry for the dumb post!

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
No worries, glad it works :D
