### ISSUE TITLE
Draconic Ore has no OreDict Entry

### ISSUE THREAD

**Issue by maginator** [NillerMedDild/Enigmatica2#635]
**Modpack version**
1.77

**Issue**
Draconic Overworld Ore has no OreDict entry

**Comment by NillerMedDild** [comment]
Does it cause any issues? :)

**Comment by Discomanco** [comment]
IIRC, this is actually intended (that the ores don't have OreDict) by the DE Dev, since the 3 versions give different amounts of Draconium.

So technically, this would be a suggestion?

**Comment by NillerMedDild** [comment]
Disco to the rescue :D Right, I remember we changed it a while back and it caused multiple issues.

**Comment by maginator** [comment]
Ok thanks the only thing is just that it is not "easy" to use with the Digiminer but there is another way

**Comment by Discomanco** [comment]
What you can do, is do it by Mod ID, and if I remember correctly, it should be set to `Draconic Evolution` to pick it up
