### ISSUE TITLE
Sub-chunk not visually updating, machines such as ME behaving inconsistently

### ISSUE THREAD

**Issue by DJenss** [NillerMedDild/Enigmatica2#638]
**Modpack version**
Enigmatica 2 1.76

**Issue**
Me and my friends are playing for on a server together, and a specific chunk in our base refuses to load visually every time we try to load it by teleporting for instance. Machines behave very strangely in this sub chunk, thinking they are out of RF even though they are not. We have tried removing all our machines , fluxducts and cable covers but nothing fixed it.

**Comment by DJenss** [comment]
I am unsure if I can upload images, but the subchunk is basically invisible for minutes, but still mostly fuctional. When a fluxduct is removed for instance, the others do not update and have a open side to nothing.

**Comment by NillerMedDild** [comment]
Sounds like a support issue I'm afraid, let's talk on my Discord
