### ISSUE TITLE
Wizardry stuff

### ISSUE THREAD

**Issue by Gr1mJ0ck3r** [NillerMedDild/Enigmatica2#64]
#### Issue Description
Orbs altars dont render the orbs;
Spell crafting doesnt let you tweak with the configurations of the spells and stuff
#### Crash Report

[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
I don't know anything about Wizardry whatsoever I'm afraid, would you mind reposting this at https://github.com/TeamWizardry/Wizardry/issues?

**Comment by Gr1mJ0ck3r** [comment]
Author said to check the version of the mod. Because there may be a upate that fixed this

**Comment by NillerMedDild** [comment]
Well which modpack version are you on?

**Comment by Gr1mJ0ck3r** [comment]
1.44

**Comment by NillerMedDild** [comment]
Ofcourse you do :P I put the mod version in your issue over there - thanks for making it.
