### ISSUE TITLE
Incorrect Energy Transfer amount stated in Quantum Entangloporter quest

### ISSUE THREAD

**Issue by merak69** [NillerMedDild/Enigmatica2#640]
**Modpack version**
1.76

**Issue**
This is purely cosmetic but the quest text says it's limited to 400k rf/tick but as configured currently, it's 6.4mil rf/tick.  Mekanism config says 16mil (16e7) Joules/Tick which when you take 40% for the conversion gets you the 6.4 mil above.  I've verified that 400k rf/tick is not the limit by pushing much more than that through :)

[https://i.imgur.com/pKkP890.png](https://i.imgur.com/pKkP890.png)

**Comment by NillerMedDild** [comment]
Thanks for letting me know :)
