### ISSUE TITLE
TiCo Battle Sign Quest not completing

### ISSUE THREAD

**Issue by AlucedIcen** [NillerMedDild/Enigmatica2#641]
**Modpack version**
1.77

**Issue**
The quest of making a flint battle sign on the Tinker's Construct chapter shows "Completed" on both the flint tool rod and the flint sign but the "Claim" button remains greyed out. On the overview of the chapter, it show me as only 1/2 completed, Edit: Actually crafting the battle sign completes the quest, but it is not mentioned in the quest requirements.

**Logs**
None

**Comment by NillerMedDild** [comment]
There is more than one page :)
