### ISSUE TITLE
No craft for P2P - tunnels - Light & Redstone & FE

### ISSUE THREAD

**Issue by Idaren** [NillerMedDild/Enigmatica2#642]
**Modpack version**
1.77

**Issue**
No craft for P2P - tunnels - Light & Redstone & FE

**Logs**
Input pastebin link to crash-report or latest log, if applicable
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/4340110/latest.log)

**Comment by NillerMedDild** [comment]
Have you tried clicking a P2P tunnel with Redstone Dust, a torch or an FE conduit/pipe?

**Comment by Idaren** [comment]
I didn't know it's possible by this way. Sorry for the disagrement. 
By the way this is a very great modpack, I really enjoy it.
Keep going, you're awesome.

**Comment by NillerMedDild** [comment]
Thanks, I'm glad you like it :D
