### ISSUE TITLE
Run.bat is not working on minecraft forge sever

### ISSUE THREAD

**Issue by popuphudson** [NillerMedDild/Enigmatica2#644]
**Issue**
My run.bat file will run then shut itself down after a couple of seconds can anyone help me to fix this?

**Comment by NillerMedDild** [comment]
We don't supply any file by that name, so that could be the issue :P 
Please supply the server-start log, found in the logs folder.

**Comment by popuphudson** [comment]
i don't see a server start log but i do see latest log
do i show that

**Comment by popuphudson** [comment]
i am using a run.bat file to increase the ram input

**Comment by popuphudson** [comment]
> We don't supply any file by that name, so that could be the issue :P
> Please supply the server-start log, found in the logs folder.

i have no server-start log

**Comment by NillerMedDild** [comment]
I'm not here to fix scripts you made :) you can input RAM amount in the settings file, and use the server-start script from the server files.
