### ISSUE TITLE
Cursed earth mob farm not chunkloading correctly

### ISSUE THREAD

**Issue by Chachava** [NillerMedDild/Enigmatica2#645]
**Modpack version**
1.76 (Server and SP) & 1.77 (SP)

**Issue**
Apologies for the lengthy post, I tried to be as thorough as I could testing things before opening an issue

I set up my regular cursed earth mob farm on a 1.76 server (the only change being chance cubes added with default configs) that I've used in the pack in previous version with no problems, I set this up quite away away from my main build and used FTB chunk loading to keep it loaded. The farm worked fine while I was there, when I went back to my main base/storage area items weren't coming through (I had an ender chest linked). 

I checked all my other chunk loading (advanced generators/Void ore miner), that was all working fine. 

I went into spectator mode by the farm and unloaded the chunks, this stopped the mobs spawning entirely as expected, loading the chunks again started the mobs spawning. 

In a creative world I made the same set up with the same results. I also tried connecting an ender pouch to the ender chest and flying away, periodically checking the pouch to see when drops stopped rolling in. It was around 128 blocks away, which is usually the range mobs will instantly despawn, but this shouldn't happen with cursed earth, or at least hasn't in the past.

Finally I loaded up a 1.77 SP creative world and tried the same setup with the exact same outcome. 

I'm completely stumped as to what could be causing this, hopefully it's just me being an idiot and missing something simple.

**Comment by NillerMedDild** [comment]
We've had this reported a few times actually, and have never been able to track down the issue, it seems that occasionally chunkloading will simply fail to load Extra Utilities things, though that seems really strange.

**Comment by Chachava** [comment]
That really is strange, did anybody ever find a workaround for it?

**Comment by NillerMedDild** [comment]
Nothing reliable, sometimes moving the setup helps, sometimes it requires a new world, sometimes a new form of chunk loading, and so on :P

**Comment by Chachava** [comment]
I've tried the same thing in 3 different worlds in 1.76 now, all in multiple locations and with both FTB & Chicken Chunks chunk loading and still nothing. Going to try rolling back to an older version and see if that helps.

**Comment by pixelblob** [comment]
Anyone found a solution to this yet?

**Comment by NillerMedDild** [comment]
This may be fixed in the next update, but I'm not entirely certain as I have a hard time reproducing it in the first place.
