### ISSUE TITLE
This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 235328

### ISSUE THREAD

**Issue by Zenohate** [NillerMedDild/Enigmatica2#646]
**Modpack version**
1.77

**Issue**
Twitch launcher unpacking fails with `This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 235328`

**Additional information**
I saw you solved a similar issue on the expert version with another addon.

**Comment by NillerMedDild** [comment]
This error is almost always temporary, and caused by some Twitch issue. Please try again later :)
