### ISSUE TITLE
Server crash related to chunk errors.

### ISSUE THREAD

**Issue by DoverDemon** [NillerMedDild/Enigmatica2#647]
**Modpack version**
1.77

**Issue**
Server crashes whenever players enter specific chunks in world.

**Logs**
See attached.
[crash-2020-03-25_04.14.26-server.txt](https://github.com/NillerMedDild/Enigmatica2/files/4379012/crash-2020-03-25_04.14.26-server.txt

**Comment by NillerMedDild** [comment]
Looks like some block with a ton of data is causing the server to run not of RAM, finding and removing it should fix the issue. It might be from Recurrent Complex.
