### ISSUE TITLE
Advanced Rocketry Space Stations Do Not Generate

### ISSUE THREAD

**Issue by NightAngel21** [NillerMedDild/Enigmatica2#648]
**Modpack version**
1.77

**Issue**
When attempting to create a space station via Advanced Rocketry, the space station does not actually load. The dimension loads, but no amount of space station packages actually load. This doesn't seem to throw any errors or exceptions either.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thanks for the report. How did you send your Space Station up? :)

**Comment by NightAngel21** [comment]
Built a standard rocket with guidance computer, station id chip, and satellite bay.
Did the mod's standard process for compressing the station into a package and programming the station ID chip, and launching it into space.
I'm still testing to see if I did anything wrong, but I've followed through most station tutorials I can find and I've done this in both survival and creative.
