### ISSUE TITLE
Enigmatica 2 Server won't start with Spongeforge

### ISSUE THREAD

**Issue by Zerabiii** [NillerMedDild/Enigmatica2#649]
**Modpack version**
1.77

**Issue**
Enigmatica 2 Server won't start with Spongeforge installed.

**Logs**
https://pastebin.com/tt4VYBHE

**Comment by Zerabiii** [comment]
Just saw that I had installed an old version of Spongeforge. But it doesn't work with newer versions either. . . (I tried it with spongeforge-1.12.2-2838-7.1.10.jar this time) Still getting the same error

**Comment by NillerMedDild** [comment]
We do not support SpongeForge, but good luck :)

**Comment by fcpwiz** [comment]
@Zerabiii try manually updating Farseek to its latest version
