### ISSUE TITLE
Items from Mekanism's "Personal Chest" not consumed by bound copy-paste gadget

### ISSUE THREAD

**Issue by lesteenman** [NillerMedDild/Enigmatica2#650]
**Modpack version**
Enigmatica 2 Light 1.4.5

**Issue**
When binding a copy-paste gadget from Builder's Gadgets to a Personal Inventory block from Mekanism, items will not actually be consumed when pasting. The items still need to be in there, but after the paste, they are still there.

Tested with a setup with both a normal and a personal chest.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
