### ISSUE TITLE
Shulker Shell doesn't spawn

### ISSUE THREAD

**Issue by Niggle-del** [NillerMedDild/Enigmatica2#652]
**Modpack version**
1.79a

**Issue**
Hey there,

when I kill shulker, they only drop shulker_pearls, no more shulker_shells?
If I could remeber, in earlier version they dropped them.

Or I'm just stupid?

TY

**Comment by NillerMedDild** [comment]
Hmm, I can't remember to be honest, I'll check it out.

**Comment by NillerMedDild** [comment]
Why did you close this issue?

**Comment by Niggle-del** [comment]
It was my fault =D, sorrey it wasn't buggy (damn gamerules).
Btw it is a very nice and exciting modpack

**Comment by NillerMedDild** [comment]
Heh alright. Thanks!
