### ISSUE TITLE
Crashes while loading

### ISSUE THREAD

**Issue by Blaster84x** [NillerMedDild/Enigmatica2#654]
**Modpack version**
1.77

**Issue**
Game crashes before fully loading, during PostInitialization after loading AncientWarfare NPCs (with recommended Java options) or JEI (without)

**Logs**
Minecraft/MultiMC logs because no crash report .txt was generated
Recommended setup: [https://paste.ee/p/eeMys](https://paste.ee/p/eeMys)
Default MultiMC: [https://paste.ee/p/KfPNA](https://paste.ee/p/KfPNA)

**Comment by NillerMedDild** [comment]
Based on the logs, my guess would be that you are running out of RAM, without having a crash report I can't do much more than guess I'm afraid :(
