### ISSUE TITLE
Forestry squeezer outputs fruit juice instead of grape juice in 1.8.0

### ISSUE THREAD

**Issue by ahze** [NillerMedDild/Enigmatica2#657]
**Modpack version**
1.8.0

**Issue**
Previous versions would output rustic grape juice instead of fruit juice.  Not sure if this was intended or not?

**Logs**
n/a

**Comment by NillerMedDild** [comment]
I'm guessing you mean from Grapes?

**Comment by ahze** [comment]
Yes, from rustic grapes.
