### ISSUE TITLE
Inventory in game won't work, throws out items.

### ISSUE THREAD

**Issue by 3d4g** [NillerMedDild/Enigmatica2#658]
**Modpack version**
1.77

**Issue**
Been playing for a few days and now for some reason overtime I try to use any inventory other than modded inventories, it shoots my mouse to a random spot and throws the item. I can eat, and use modded interfaces like Mekanism's blocks and tinker's crafting table but I can't use any chests or regular crafting tables, or my regular inventory.

**Logs**
N/A

**Comment by NillerMedDild** [comment]
Please supply your latest.log :)

**Comment by 3d4g** [comment]
Everything got fixed when I reloaded game, sorry! But now my game is crashing as soon as I spawn in so I need to open another issue.

**Comment by NillerMedDild** [comment]
Feel free to upload the crash report here, it's probably just old java.
