### ISSUE TITLE
Ancient Warfare tree farm crashes game when using Forestry saplings

### ISSUE THREAD

**Issue by EL-ITIAGO** [NillerMedDild/Enigmatica2#659]
**Modpack version**
1.77

**Issue**
When using Forestry saplings (or at least Desert Acacia saplings) in a tree farm from Ancient Warfare, a "Ticking block entity" error crashes the game and prevents the world from loading.

**Logs**
https://pastebin.com/1WCMSu64

**Comment by NillerMedDild** [comment]
Thanks for the report, I relayed it :)

**Comment by ashboy3093** [comment]
Hello! Not sure what trees I used BUT same issue here. I used the two trees that came with the quest rewards.

[crash-2020-10-02_16.30.56-server.txt](https://github.com/NillerMedDild/Enigmatica2/files/5321270/crash-2020-10-02_16.30.56-server.txt)
[crash-2020-10-03_02.07.48-server.txt](https://github.com/NillerMedDild/Enigmatica2/files/5321271/crash-2020-10-03_02.07.48-server.txt)
