### ISSUE TITLE
Deleted buildings after relog

### ISSUE THREAD

**Issue by AndrzejBaran** [NillerMedDild/Enigmatica2#66]
Issue Description
-When I started playing I've chosen living with villagers (easy start :P). After some time when I logged into my world everything in the village was reseted. It's like the whole village regenerated, even with the same setup of buildings, but everything what I had built disappeared. My structures and items outside the village stayed the same. Any way to restore my world?

Modpack version (Do not use "latest")
-1.34

Crash Report
-No crash

**Comment by NillerMedDild** [comment]
I'm afraid you would have to load up a backup. They are found in the `backups` folder of your save.
