### ISSUE TITLE
EnderIO armor upgrades dupe while trying to enchant

### ISSUE THREAD

**Issue by hallowlock** [NillerMedDild/Enigmatica2#662]
**Modpack version**
1.77

**Issue**
Applying enchantments to upgraded EnderIO armor on an anvil causes the upgrades to duplicate and drop on the ground in item form. This doesn't seem to work with creative mode.

**How to replicate**
Upgrade a piece of Dark Armor, take it off, apply enchantments and put it back on. The armor piece will still have the upgrades it had applied, while the upgrade items appear in your inventory.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
