### ISSUE TITLE
Redstone rakes a few seconds to enter inventory

### ISSUE THREAD

**Issue by PxlRift** [NillerMedDild/Enigmatica2#663]
**Modpack version**
1.77

**Issue**
When I mine redstone or throw it onto the ground, it takes a few seconds for the items to enter my inventory, I thought it was AE2 in-world crafting but considering I is also when I mine it, I'm not sure if it can be that.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by EL-ITIAGO** [comment]
Can confirm, it happens to me too. This only affects redstone dust, weirdly enough.

**Comment by Marumarsudev** [comment]
Any update on this, happening to me too with console spamming Fetching addPacket for removed entity.

**Comment by NillerMedDild** [comment]
Not yet nope.

**Comment by WesCook** [comment]
If I had to guess, I'd say it's Wizardry causing this.  It modifies redstone to not burn in fire.

**Comment by NillerMedDild** [comment]
Nice lead, thanks!

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
