### ISSUE TITLE
Integrated Dynamics quests show completion popups, but quests do not appear in book

### ISSUE THREAD

**Issue by EL-ITIAGO** [NillerMedDild/Enigmatica2#664]
**Modpack version**
1.77

**Issue**
When first picking up Menril Tree drops, a quest completion popup appears for quest "Menril Trees", but in the book, the quest does not appear in any quest tree. This issue with Integrated Dynamics quests happens after the quest database is reloaded with /bq_admin default load, too.

**Logs**
I've had to snip the log to only show lines for a testing world due to pastebin's limits. I'm including some screenshots as well.
https://imgur.com/a/xMBuCqn
https://pastebin.com/BKb7tEvL

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
