### ISSUE TITLE
Cannot load world. SIngle player or multiplayer

### ISSUE THREAD

**Issue by ChocolateNinja** [NillerMedDild/Enigmatica2#665]
**Modpack version**
Input version here
1.77
**Issue**
Input short description of the issue here
I was having an Issue where it would say  "Error: java.lang.NullPointerException: Unexpected error" after trying to load a world. But now its just throwing an error after i boot up the game. I tried following the settings and java arguments provided on the guide but now i cant even boot the game. I have 16gb or ram and I am allocating about 6. 
**Logs**
Input pastebin link to crash-report or latest log, if applicable
https://pastebin.com/sUrp9qA0 
this is just the tail end of the log, the whole thing was too large to upload

**Comment by NillerMedDild** [comment]
Sounds like you installed 32-bit Java, you need 64-Bit as the guide says :) 
That crash report sadly doesn't tell me anything other than the fact that your java is outdated, and RAM allocation is on the low end.

**Comment by ChocolateNinja** [comment]
Thanks @NillerMedDild. I thought that might have been an issue and I reinstalled java twice and even uninstalled the older versions. I'm not sure if it was just a restart that was needed but its all working now. Thanks for responding back so quickly!

**Comment by NillerMedDild** [comment]
Sure thing :)
