### ISSUE TITLE
Default Java args don't match your recommendations

### ISSUE THREAD

**Issue by m5m1th** [NillerMedDild/Enigmatica2#667]
https://github.com/NillerMedDild/Enigmatica2/blob/bb83f88193d04a20ca227cd78c85317a83d6a69b/settings.cfg#L6

Hi there, the default settings don't match your recommended settings here: https://gist.github.com/NillerMedDild/40b4992b7a3e5e653a353fe1d45f2185

**Comment by NillerMedDild** [comment]
Hi! Top arguments are for servers, the others for clients.
