### ISSUE TITLE
Minecolonies update

### ISSUE THREAD

**Issue by Zafaranec** [NillerMedDild/Enigmatica2#668]
Hello, I know, that is low priority, but if you have some other things collected for update of modpack, may I please for update of Minecolonies mod, I know they have new versions maybe daily, or maybe if you can recommend which version for update...

**Comment by NillerMedDild** [comment]
Hi! There won't be an update any time soon I don't think, but you should be able to safely update to this version: https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/2917234
Remember to update Structurize to the latest Release version as well.
