### ISSUE TITLE
Advanced Rocketry space station not appearing 

### ISSUE THREAD

**Issue by yelsmirgd** [NillerMedDild/Enigmatica2#669]
**Modpack version**
1.70 221

**Issue**
Space station not loading when I launch my rocket. I spawn in space and fall in darkness with it constantly saying you wake up finding yourself back on the station. I am connection to a forge server 1.12.2. I have sent the rocket into space with the space station loaded into the satellite bay and then when I launch my rocket with the station id chip in the computer guidance system the above issue happens. any help would be great. 

![unknown](https://user-images.githubusercontent.com/66090852/83190107-d35c6400-a129-11ea-861d-b0405b77cb8b.png)

**Comment by NillerMedDild** [comment]
Thanks for the report! 1.70 221 is not a valid modpack version, could you check again please?

**Comment by yelsmirgd** [comment]
> Thanks for the report! 1.70 221 is not a valid modpack version, could you check again please?

hi sorry in the mod folder it is 1.12.2-1.7.0-221-universal

**Comment by NillerMedDild** [comment]
That is the version of the mod, I need the modpack version, the version you see in Twitch near the play button :)

**Comment by yelsmirgd** [comment]
> That is the version of the mod, I need the modpack version, the version you see in Twitch near the play button :)

hi sorry i spoke to the guy that runs the server and he said its a custom mod pack with various mods installed. best i can do is list the mods that are running

**Comment by NillerMedDild** [comment]
Errr okay.. Well this issue tracker is for the modpack Enigmatica 2. You would have to ask the guy who runs the server for help.

**Comment by yelsmirgd** [comment]
> Errr okay.. Well this issue tracker is for the modpack Enigmatica 2. You would have to ask the guy who runs the server for help.

ah ok ive tried that but ill keep trying

**Comment by Nabbieshtron** [comment]
Hello have same issue modpack version enigmatica2Expert 1.82a
