### ISSUE TITLE
Recommend disabling "Shimmer" enchant from Ender IO

### ISSUE THREAD

**Issue by darchitectlp** [NillerMedDild/Enigmatica2#67]
When enchanting Thermal Expansion storage blocks (tanks/satchels/boxes), Shimmer (which literally does nothing but apply a visual shimmer to the item) gets applied a LOT, since the only enchants those items are able to pull from are Holding/Soulbound/Shimmer.

Not sure why the Ender IO devs even made this enchant. Seems lame. Disabled it in my instance.

Thanks for making an amazing pack!

https://github.com/SleepyTrousers/EnderIO/blob/1206f5c0f7b62d4c5e910e5daa1579b42bdb150c/enderio-base/src/main/resources/assets/enderio/lang/en_us.lang

**Comment by NillerMedDild** [comment]
It does seem a bit weird, disabled in dev :)
