### ISSUE TITLE
Steam Dynamo Steam Usage Problem

### ISSUE THREAD

**Issue by wailong96** [NillerMedDild/Enigmatica2#670]
**Modpack version**
Enigmatica 2 Expert 1.81a

**Issue**
Resonant Steam Dynamo with 1 Turbine Conversion and 3 Auxiliary Transmission Coil upgrade.
It use **5040 mb/t** of Steam but its internal buffer had only **4000 mb**.
Its steam usage is larger than its buffer and the machine stops.
The machine stops and not produce power.
May be need to increase the amount of internal buffer of a Steam Dynamo?

**Logs**
No logs for it.

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll get that fixed :)

**Comment by NillerMedDild** [comment]
This was fixed in E2E 1.82
