### ISSUE TITLE
Coal Coke Ore Dictionary conversion not working

### ISSUE THREAD

**Issue by tirish** [NillerMedDild/Enigmatica2#671]
**Modpack version**
1.77

**Issue**
Immersive Engineering Coal Coke and Thermal Foundation Coal Coke have the same ore dictionary name (`fuelCoke`) according to ingame tooltip, but the Ore Dictionary Converter (Industrial Foregoing) and Oredictionifcator (Mekanism) do not respect it and won't allow conversion.

**Comment by NillerMedDild** [comment]
May I ask why you want to convert between them? :)

**Comment by tirish** [comment]
Was trying to use the Thermal Expansion augment for the Furnace to generate it easier/quicker than using a coke oven from Immersive Engineering.. but I already had a ton of the Immersive Engineering version in storage and wanted them to stack nicely (mostly for ME auto crafting purposes).

**Comment by NillerMedDild** [comment]
Ah okay, thanks.

**Comment by NillerMedDild** [comment]
I don't really have time to fix things like this, sorry.
