### ISSUE TITLE
Embers Rekindled Stamper

### ISSUE THREAD

**Issue by afolk2** [NillerMedDild/Enigmatica2#672]
**Modpack version**
1.77

**Issue**
The Embers Rekindled Stamper with the plate cast still produces embers plates that are not in the oreDict making them unusable for recipes.
Ingots made with the bar cast produce ingots that are from Thermal Foundation, not Embers. This makes them still usable.

**Comment by NillerMedDild** [comment]
Thanks for the report, we'll get that fixed.
