### ISSUE TITLE
Metal duplication involving Tinkers' Smeltery and Advanced Rocketry rods

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica2#673]
**Modpack version**
1.77, non-expert

**Issue**
Metal duplication involving Advanced Rocketry rods

Advanced rocketry rods gives you 108mB (3/4 ingot) when melted in smeltery, but you get 2 rods from 1 ingot from a Lathe. This means that you can make 3 ingots out of 2 for metals that has rods in AR. 
Some metals (Copper, TE Iridium, and Titanium) give you AR rods when put in Immersive Engineering metal press, so you can start duplicating these earlier in the game, if you have enough fuel.

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by RomkeVdMeulen** [comment]
In expert mode the lathe turns 1 titanium ingot into 8 rods, which can be melted in the Tinker's smeltery at three nuggets per rod, so 1 ingot turns into roughly 2.5.
