### ISSUE TITLE
Network issues possibly due to NetworkDispatcher exception

### ISSUE THREAD

**Issue by DenTommes** [NillerMedDild/Enigmatica2#674]
**Modpack version**
Enigmatica 2 1.77

**Issue**
The server I'm hosting has HUGE connectivity issues for some players. Some have huge lags while others can play freely. Sometimes a player loses connection to the server and times out when trying to reconnect, after which no player can reconnect after disconnecting from the server. The logs don't even show any hint of anyone trying to reconnect. All while showing the NetworkDispatcher Exception

To - temporarily - fix this I have to restart the server... which also can't be done correctly. Trying to stop the server via console doesn't work. The console just keep on showing the Error and keeps on running. I have to kill the server process to get it to shutdown.

It has to be noted that the exception only starts to show up after I connect to the server - the logs start to get spammed right after I connect.

The issue started after I used the teleportation added by PlusTic's material osgloglas. I pressed to key to teleport while not holding the Osgloglas item - as expected, nothing happened. I then switched over to the correct item and I lost connection to the game. The network dispatcher error appeared for the first time in the logs and I couldn't reconnect to the server - I had to kill the server and restarted it to get it to work again. After rejoining, I noticed that I indeed teleported and the Error got spammed in the logs.

Further testing revealed, that pushing the teleport key while not holding the correct item "queues up" the teleportations, which will all be executed once switched to the osgloglas item.

restarting the server does solve the issue for some time, after which it starts happening again

**Logs**
I am reluctant to supply an entire log of the server - the hoster I use uses my full name as root directory for the server. my name shows up every time a backup is made.

Here's the error shown in the log.

https://pastebin.com/fUz9tVmX

I now deleted my playerdata and see if this helps the issue.

Are there any other steps anyone could recommend if this doesn't solve the problem?

**Comment by NillerMedDild** [comment]
I would guess deleting your playerdata is you did would solve the issue, I'll think harder once you check if that helps :P

**Comment by DenTommes** [comment]
deleting the playerdata didn't help.

The error also now showed up without me being on the server... could it be unrelated to the PlusTic teleporting after all?

I edited out the offending parts of the latest log, but I'm unable to upload the log to pastebin since it's 180MB.

the browsers just crash when I try to paste all of it

**Comment by NillerMedDild** [comment]
O_O jesus christ
Could you try restarting the server, and then upload the latest.log just when it starts happening? So it's not 180MB :P

**Comment by DenTommes** [comment]
the start of the error isn't consistent. I'm currently editing the log to get the file size down

**Comment by NillerMedDild** [comment]
Sounds good

**Comment by DenTommes** [comment]
https://pastebin.com/nAvv0qbs

incomplete list off the network dispatcher errors. the only difference I could see was that #6 changed around. I can hunt for specific errors if needed

https://pastebin.com/Mphchiaj First part of the start log, was to big to post at once in pastebin
https://pastebin.com/p5pWATEG second part of the start log

https://pastebin.com/au8AD29E error that happened during disconnect for all players. no further errors since then

**Comment by NillerMedDild** [comment]
There's nothing helpful I could find in any of those I'm afraid. My best bet is that the internet connection is bad, tbh.
