### ISSUE TITLE
Start.bat not working on mac 

### ISSUE THREAD

**Issue by SomeRando16** [NillerMedDild/Enigmatica2#675]
Vanilla 1.15

I'm on a mac and I've been trying to make my own minecraft server without using hosting websites. All of them have gone good until one part, making the start.bat file. Every time I put in the text you usually need to (java -Xmx1024M -Xms1024M -jar minecraft_server.1.16.1.jar nogui), it just does nothing. I haven't been able to find anyone with the same problem as me, and others who have their start.bat not working say it flashes up for a bit then crashes, but mine just does nothing. Can someone find anything wrong with what I'm doing?
<img width="769" alt="Screen Shot 2020-07-19 at 3 02 36 PM" src="https://user-images.githubusercontent.com/68518919/87886336-e7f20580-c9d0-11ea-8fec-4fd7e3b4c54d.png">
<img width="1143" alt="Screen Shot 2020-07-19 at 3 02 23 PM" src="https://user-images.githubusercontent.com/68518919/87886337-eb858c80-c9d0-11ea-8498-cb7b3349ca78.png">
<img width="768" alt="Screen Shot 2020-07-19 at 3 01 53 PM" src="https://user-images.githubusercontent.com/68518919/87886338-ecb6b980-c9d0-11ea-8b8c-7440661e5970.png">

**Comment by Discomanco** [comment]
Not really sure why you came here to ask that question. But the .bat files are really only for Windows, and the .sh file for Linux. We don't include a MacOSX file by default, as it seems they need extra manual permissions to run.
You can follow this guide here to help you set up a vanilla server: https://www.wikihow.com/Make-a-Minecraft-Server-on-a-Mac
