### ISSUE TITLE
Issues on T6 Void Miner and Laser Drill ore list

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica2#676]
**Modpack version**
1.77

**Issue**
Void Miner: Up until tier 5, thermalfoundation:ore:4 (Aluminum) has weight 26, and is white. In tier 6, it is weight 13, and green. I noticed that uranium ore is missing in T6, and it is what Aluminium ore is in T6, up until T5. Is uranium ore supposed to go there instead of aluminum ore?

Laser Drill: In the default_ores.json, there is a duplicate oreCobalt entry. It has the Nether listed in blacklist (unlike the sole Ardite ore entry) so I assume it is bugged.

**Comment by NillerMedDild** [comment]
Thanks for the report, both of these issues have been fixed and will be in version 1.82. Uranium hasn't been added to the T6 void ore miner though.

**Comment by HaxtonSale1** [comment]
> Uranium hasn't been added to the T6 void ore miner though.

Is this because Uranium ore is relatively easy to come by, compared to other ores from T6?

**Comment by NillerMedDild** [comment]
It is indeed :)
