### ISSUE TITLE
Laser Drill not getting ardite and cobalt in all nether biomes

### ISSUE THREAD

**Issue by Porcy** [NillerMedDild/Enigmatica2#677]
**Modpack version**
1.81a

**Issue**
Not sure how intended it is, but when I setup my laser drill in phantasmagoric inferno, even with the blue and yellow lenses, no ardite or cobalt where mined. I installed another drill in the Hell biome, and sure enough, ardite and cobalt where there. I would assume all the nether biomes should count as "hell", or some kind of mention somewhere about the specificity of the choice of biome be added.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Thanks for the report! Were you between Y 34 and 94 in the first attempt?

**Comment by Porcy** [comment]
In the first attempt, the laser base was at level 7. I tought it was the problem so I configured it (in the GUI) to mine at level 50. Left it a few hours with no ardite/cobalt. Moved it to level 100 or so, installed the lenses (I thought they might be mandatory in an expert pack), still no cobalt/ardite. All of this in the phantasmagoric inferno BOP biome. The day after, I installed a new laser base in the Hell biome and bam! ardite/cobalt where coming in.

**Comment by NillerMedDild** [comment]
So... No, you weren't between Y 34 and 94? Would you mind trying that in a hell biome?

**Comment by Porcy** [comment]
Well, right now, the laser base that gets me ardite/cobalt sits in the hell biome at y:122. In the gui, I setup the "drill depth" to 50. Works perfect. The first laser base, in the phantasmagoric inferno, sits a y:121, drill depth set to 40. No cobalt/ardite.

**Comment by NillerMedDild** [comment]
Ah alright, thanks, I'll get that fixed.
