### ISSUE TITLE
Mod pack lags even with 12Gb of ram

### ISSUE THREAD

**Issue by Mic700** [NillerMedDild/Enigmatica2#679]
**Modpack Version**
Version 1.77

**Issue**
Iev added and reduced the amount of ram i allocate to the pack but no matter what i allocated I would always have stutters on my own server when my friends aren't. The server itself has 10gb of ram while i usually allocate around 9 to the pack my PC has a total of 32gb of ddr4 ram. The other thing is it doesn't show any issues in my logs and i don't crash but i'm getting constant stutters and fps drops

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/5022592/latest.log)

**Comment by Mic700** [comment]
My Pc specs are:
Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz 3.19 GHz
NVIDIA RTX 2070 
32Gb ddr4 ram

**Comment by NillerMedDild** [comment]
Thanks for the report. I highly recommend that you have a look at our setup documentation [here](https://gist.github.com/NillerMedDild/40b4992b7a3e5e653a353fe1d45f2185). Your issues are most likely allocating too much RAM, old Java, and additional java arguments would most likely also help.

Please let me know if any of that helps :)

**Comment by Mic700** [comment]
Im still having the same issue and now that i turned the ram down its using even more ram it took all 12 Gb even though I only allocated 7 with the addition arguments.
![image](https://user-images.githubusercontent.com/69204934/89312490-511a7f80-d645-11ea-962d-04a753ab3a98.png)
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/5022958/latest.log)

**Comment by NillerMedDild** [comment]
Hmm that's odd, I'll dig into the log this evening. Would you mind restarting the PC and trying again, just in case?

**Comment by Mic700** [comment]
Yes ill try that

**Comment by NillerMedDild** [comment]
I noticed 2 things in the second latest log:
* You're pregenerating 4000 chunks. This causes lag.
* You've added MrCrayFish's Furniture mod - Did you add any other mods?

**Comment by Mic700** [comment]
yes we add quite a few others but my friends have the same mods as me but im the only one having the issue
We added
Abyssal craft
Advanced fishing
Alchemistry
Alib
Aquaculture
Bewitchment
Cucumber
DeepMobLearning newer version
Dimensional doors
Fast Leaf Decay
Furniture
ICBM
Levelup 2
Magical Psi
Millenaire
MobGrindingUtils
Mystical Agriculture
Potion Fingers
Prefab
Randomthings
RefinedStorage
Trinkets and Baubles
Vamprism
Waystones
Woot

**Comment by NillerMedDild** [comment]
Jesus, those are quite a few extra mods. Most of them could be the cause to be honest, you're on your own here :(
