### ISSUE TITLE
Game Crashing after opening save

### ISSUE THREAD

**Issue by ama11deus** [NillerMedDild/Enigmatica2#68]
Im on v 1.44 and my game crashed randomly. Since then i can only load up my save if i set the render distance to 2 chunks. What's the possible cause? I dont wanna play with that much limited visibility D:

**Comment by Discomanco** [comment]
We can't do anything without a crashlog :)
Upload the crashlog to http://pastebin.com and link it here, and we can take a look

**Comment by ama11deus** [comment]
https://pastebin.com/1kin2dct
I pasted the first and the second crash. I can paste more if that will help

**Comment by NillerMedDild** [comment]
Go into your config folder, and open the forge.cfg file with any text editor. On line 53, change `B:removeErroringEntities=false` to `B:removeErroringEntities=true`

**Comment by NillerMedDild** [comment]
https://github.com/capnkirok/animaniamod/issues/84

**Comment by ama11deus** [comment]
That fixed it! Thank you very much and sorry for the late response.

**Comment by NillerMedDild** [comment]
You're welcome :)
