### ISSUE TITLE
Environmental Tech Solar Rounding Error

### ISSUE THREAD

**Issue by nyanlathotep** [NillerMedDild/Enigmatica2#680]
**Modpack version**
1.77

**Issue**
Environmental Tech Solars have no exponential growth on tier 2, because the mod appears to be improperly flooring its exponential factor before using it. Higher tiers are affected, but not by as much. The issue is that the exponent is being floored before being applied, so the actual per-cell formula appears to be:

floor(baseProduction * floor(exponent^(tier - 1)) * min(maxEfficiency, averageEfficiency))

On integer exponents, like default, it's fine, but exponents below 2 make this particularly problematic. With the pack's setting of 1.8, tier 2 arrays have 80% less output than expected, and the higher tiers have something like 5-15% less. The real factors are 1, 3, 5, 10, and 18 rather than 1.8, 3.2, 5.8, 10.5, and 18.9.

**Comment by NillerMedDild** [comment]
Oh that's the reason the tier 2 is off!

Would you mind re-posting this on the ET issue tracker? It sounds like you would be better at answering any questions about it than I would ^^

https://github.com/ValkyrieofNight/EnvironmentalTech/issues

**Comment by nyanlathotep** [comment]
Done. ET issue is [here](https://github.com/ValkyrieofNight/EnvironmentalTech/issues/208).
