### ISSUE TITLE
Issues Missing textures and Crashes.

### ISSUE THREAD

**Issue by Enethim** [NillerMedDild/Enigmatica2#681]
**Modpack version**
0.2.7

**Issue**
Missing Textures and crashing on Botania tab in Creative.
Don't have any of these issues on 0.26
https://imgur.com/a/6q0owAT

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I would like the crash report by the way :)

**Comment by Enethim** [comment]
[crash-2020-08-17_01.23.09-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/5081401/crash-2020-08-17_01.23.09-client.txt)

Forgot to mention it only happens when i add optifine! I did also tried disabling "TipTheScales-1.16.1-3.0.0.3" since it's incompatible but still doesn't help.

**Comment by NillerMedDild** [comment]
Ah ^^ this has been reported here: https://github.com/NillerMedDild/Enigmatica6/issues/154
