### ISSUE TITLE
Enigmatica 2 power tweeks

### ISSUE THREAD

**Issue by CactusCool** [NillerMedDild/Enigmatica2#683]
**Modpack version**
V.1.77

**Issue**
Is there a list of the power generation tweaks in enigmatic 2 I can't find documentation of this anywhere.

**Comment by NillerMedDild** [comment]
I'm afraid not :/

**Comment by CactusCool** [comment]
is there a config file for this I just want to know what I can do for power lol

**Comment by NillerMedDild** [comment]
There are many config files for this yes :P I suggest you ask around in the E2 channel on our Discord for tips on what to use, GitHub isn't for this kind of help :)
