### ISSUE TITLE
I have added mystical agriculture to this pack and some of the crafting recopies are missing

### ISSUE THREAD

**Issue by CactusCool** [NillerMedDild/Enigmatica2#686]
**Modpack version**
1.77

**Issue**
I have added mystical agriculture to this pack and some of the crafting recopies are missing, these include copper, tin, steel, silver and lead. I was wondering what scripts I have to add to get these recipes to work

**Comment by NillerMedDild** [comment]
I'm guessing you would need to make CraftTweaker scripts for the recipes :)
