### ISSUE TITLE
Crashing while crafting facade

### ISSUE THREAD

**Issue by WhiteTigerNOR** [NillerMedDild/Enigmatica2#687]
**Modpack version**
1.12.2

**Issue**
Game crashes every time I craft a facade. tried with skystone and cobblestone.

**Logs**
Input pastebin link to crash-report or latest log, if applicable
[crash-2020-09-13_17.50.23-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/5214512/crash-2020-09-13_17.50.23-client.txt)

**Comment by NillerMedDild** [comment]
Thanks for the report. Which crafting table are you using?

**Comment by WhiteTigerNOR** [comment]
So tested a little more. Seems its only on the engineering station. No
problem if I craft it on the ME crafting terminal.

søn. 13. sep. 2020, 20:12 skrev Niels Pilgaard Grøndahl <
notifications@github.com>:

**Comment by NillerMedDild** [comment]
Thought so, that station isn't really meant to be used for general crafting afaik :)
