### ISSUE TITLE
Cannot complete "Peers of Peers"

### ISSUE THREAD

**Issue by gpkvt** [NillerMedDild/Enigmatica2#688]
**Modpack version**
Enigmatica 2 Version: 1.77, Minecraft Version: 1.12.2, (modded) forge-14.23.5.2847
Updated on 25/06/2020

**Issue**
Cannot complete "Peers of Peers".

I have all three P2P Tunnels working as the Quest demands. But the Questlog still says INCOMPLETE. "It's Peer, not Pier" worked fine, but I'm not sure if it was completed after having an ME P2P Tunnel working or when I had the P2P ME Tunnel item in my inventory. The latter seems not possible with light, energy or redstone P2P as they convert back to P2P ME Tunnel items when harvested (even with silk touch).

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by kleshas** [comment]
We've had this before - you have to click the tunnel when placed with a redstone torch/redstone? or something to lock it to the type it is, then you can break it?  Something like that.

**Comment by gpkvt** [comment]
Nevermind, when I use a wrench (like yeta from ender-io) I receive the P2P tunnel with it settings (light, redstone, energy) and the questlog accepts it. Discovered this accidentially, so it might worth a hint in the quest description.

Thanks for your quick reply.
