### ISSUE TITLE
[1.44] [Quest][8MB... Highly Fragmented...] Biometric Card not being recognized

### ISSUE THREAD

**Issue by nodey420** [NillerMedDild/Enigmatica2#69]
#### Issue Description

Crafted the ME Security Terminal and the Biometric Card and put it in inventory from crafting grid.  Clicked "Detect/Submit" but that didn't change the issue.  The terminal is recognized, but the card is not.  I ran the two reload commands but that didn't seem to help.

#### Modpack version (Do not use "latest")
1.44

#### Crash Report
Not applicable, but can provide logs if required.

**Comment by nodey420** [comment]
It seems Copy/Paste and Yet Another Better Barrels Attempt are also not triggering.

**Comment by NillerMedDild** [comment]
Alright, I'll get them fixed :) The issue is that most of the AE quests are marked as NBT strict, and they should not be.

**Comment by nodey420** [comment]
Thanks man.  I appreciate all your hard work.  Let me know if I can do anything.

**Comment by NillerMedDild** [comment]
That means a lot, thanks :D
