### ISSUE TITLE
Rutile ore bug

### ISSUE THREAD

**Issue by Syhinite** [NillerMedDild/Enigmatica2#691]
**Modpack version**
1.77

**Issue**
Rutile ore is required to craft ingots of titanium, but JEI does not display how to find it other than going to the moon, which requires titanium to get there.

**Comment by NillerMedDild** [comment]
Titanium Ingots are directly craftable :)

**Comment by Syhinite** [comment]
how so, there isnt a way to acquire the titanium ingots other than from rutile ore as stated by the jei

**Comment by NillerMedDild** [comment]
There is a crafting recipe for Titanium Ingots. 2 Steel Ingots + 2 Aluminium Ingots + Magma Block in a plus shape, with the magma in the middle.

**Comment by Syhinite** [comment]
why does it not show that in the jei then?

**Comment by Syhinite** [comment]
ah, never mind, I found it, so sorry to bother you
