### ISSUE TITLE
Tinker's Construct On Multiplayer Server

### ISSUE THREAD

**Issue by OziasNC** [NillerMedDild/Enigmatica2#692]
**Modpack version**
1.77

**Issue**
Smeltry not pouring out of any drains.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Is the smeltery placed near spawn? :)

**Comment by OziasNC** [comment]
It is placed near the base we have started about 500m from spawn.

**Comment by NillerMedDild** [comment]
Alright, sounds like it's not an issue with spawn chunks then. 
Is the area claimed by someone other than yourself? Do you have permission to use other blocks in the area?

**Comment by OziasNC** [comment]
Its claimed by our team, only 3 people on the server and all on the same
team and all cant use it. Have no issues with any other blocks, chests,
storage drawers. Quadruple checked the construction of it.

**Comment by NillerMedDild** [comment]
Could you please try unclaiming the chunk(s) that it's in and see if the issue persists?

**Comment by OziasNC** [comment]
We tore down the smeltry and rebuilt it in our claimed area and it is
functioning now! think we had built it before we claimed the chunks and
therefore needed to build it again in the claimed chunks! Thanks!!!!

**Comment by NillerMedDild** [comment]
Awesome :D
