### ISSUE TITLE
FarSeek 2.4 causes incompatibility with SpongeForge

### ISSUE THREAD

**Issue by Snaptraks** [NillerMedDild/Enigmatica2#693]
**Modpack version**
1.77

**Issue**
Server cannot start when SpongeForge is present. Updating FarSeek from 2.4 to 2.5 fixes the issue

**Logs**
https://pastebin.com/xgCWtHFW

also information found here: https://docs.spongepowered.org/stable/en/server/spongineer/incompatible.html#farseek

I don't know yet if updating FarSeek creates other issues with other mods, sadly

**Comment by NillerMedDild** [comment]
Thanks for letting me know, I'll make sure to get that fixed eventually, but no ETA :)
