### ISSUE TITLE
Minecolonies settlers are shining through

### ISSUE THREAD

**Issue by Snajper20161** [NillerMedDild/Enigmatica2#694]
**Modpack version**
1.77

**Issue**
I can see trough every Minecolonies settler, which is confusing
![2020-10-31_10 37 24](https://user-images.githubusercontent.com/73739839/97776432-2a96b280-1b68-11eb-8ffc-97a5cff707b4.png)
![2020-10-31_10 37 41](https://user-images.githubusercontent.com/73739839/97776435-34201a80-1b68-11eb-93f6-447d07fc6cc3.png)

**Logs**
The issue doesnt make game crash which means there is no logs

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll look into it.

**Comment by NillerMedDild** [comment]
Forgot to ask: Are you using Optifine, VanillaFix, anything like that?

**Comment by Snajper20161** [comment]
> Forgot to ask: Are you using Optifine, VanillaFix, anything like that?

only Optifine

**Comment by NillerMedDild** [comment]
I'm afraid that is almost certainly the issue. Could you please check if removing Optifine resolves the issue?

**Comment by Snajper20161** [comment]
I will try but i play with optifine for very long time

**Comment by Snajper20161** [comment]
Before deleting Optifine i launched the modpack to see something but then i saw that settlers are back to normal.

**Comment by NillerMedDild** [comment]
Huh, alright then :)

**Comment by Snajper20161** [comment]
Before deleting optifine i checked my save and ive seen that settlers are back to normal , i guess its time to close topic
