### ISSUE TITLE
Immersive Tech should be updated

### ISSUE THREAD

**Issue by Runaris** [NillerMedDild/Enigmatica2#695]
**Modpack version**
1.7.7
**Issue**
Immersive Tech should be updated, as the version that this pack uses is 2 years out of date and has since moved to a new author.

I am unsure if this is the right place to report these things, but the version of Immersive Tech in this modpack is quite old, and is abandoned by its author. : https://www.curseforge.com/minecraft/mc-mods/immersive-tech this is the abandoned one

It however was picked up again and a brand new version is available here https://www.curseforge.com/minecraft/mc-mods/mct-immersive-technology it is updated very regularly.

It features greater compatibility with the mods already in the pack and less bugs overall. 

Ignore if an update to this is already planned in a future version of the modpack :) thanks

**Comment by NillerMedDild** [comment]
Thanks for the report, I will most likely do this down the line :)
