### ISSUE TITLE
Immersive Engineering Crusher

### ISSUE THREAD

**Issue by Spinx60** [NillerMedDild/Enigmatica2#696]
**Modpack version**
Enigmatica 2 Expert version 1.82a

**Issue**
Crusher is not outputing any crushed ores it just eats them no output

**Logs**
no logs

**Comment by NillerMedDild** [comment]
Thanks for the report. This has been reported a few times already :) https://github.com/NillerMedDild/Enigmatica2Expert/issues/1841
