### ISSUE TITLE
Game keeps crashing on load in

### ISSUE THREAD

**Issue by ChezyGun** [NillerMedDild/Enigmatica2#697]
**Modpack version**
1.77

**Issue**
Every time I load into my world, just before i get in the game crashes.

**Logs**
https://pastebin.com/g7dFE3fD

**Comment by Discomanco** [comment]
Are you using shaders by chance? It's crashing trying to render the sky

**Comment by ChezyGun** [comment]
No its a fresh install with no shaders. All I added was optifine.

**Comment by ChezyGun** [comment]
I think it was optifine

**Comment by NillerMedDild** [comment]
So do I :P glad you got it working.
