### ISSUE TITLE
Animania needs additional addons to work

### ISSUE THREAD

**Issue by HayleyGeek** [NillerMedDild/Enigmatica2#698]
Hello, I realised that Animania animals were not spawning in world. I found the animania base and library installed. However, according to their forge page, you now need to install all of the following: The library itself Craft Studio API, Animania Base, Animania Farm and Animania Extra, to get the entire experience as it used to be for 1.12.2. 

I was super confused as both base and craft studio do not spawn the mobs, only vanilla. You need the other 2 also to have animals in world. Just to let you know for updating this fantastic modpack. Thanks :))

**Comment by NillerMedDild** [comment]
The version of Animania we're using is before the split up - Did you update it yourself?

**Comment by HayleyGeek** [comment]
Hi yes I did. I updated the .jar files mostly because it auto updates on
the curse forge launcher or at least shows their are updates available per
mod. Never mind then lol, my own fault I guess. I've added them anyway and
hopefully they work otherwise I'll roll back to the older mod version
