### ISSUE TITLE
Random Crashes on picking up lava with bucket

### ISSUE THREAD

**Issue by SigmaChi07** [NillerMedDild/Enigmatica2#7]
#### Issue Description
Client crashes while attempting to pick up lava with normal buckets.

#### What happens
The game stalls, then crashes to desktop.

#### What you expected to happen
I expected to pick up a bucket of lava.

#### Modpack version (Do not use "latest")
Enig 2 Expert 1.08 (release)

#### Your most recent log file where the issue was present
(1st crash) https://pastebin.com/VmeJDtkM
(2nd crash in a row) https://pastebin.com/K1WbMQtB
(3rd crash in a row) https://pastebin.com/6mJR9xFp

Thanks dude!

**Comment by NillerMedDild** [comment]
Thanks for reporting, it was fixed in an Advanced Rocketry update earlier today, I'll release an update asap.
