### ISSUE TITLE
Better questing mod/Book

### ISSUE THREAD

**Issue by shinauko33** [NillerMedDild/Enigmatica2#70]
#### Better quersting mod book keeps going blank. 
![2018-08-12_18 04 33](https://user-images.githubusercontent.com/42321665/44123719-e85f0a74-9fe6-11e8-8953-64f02a100415.png)

**Comment by NillerMedDild** [comment]
I'm afraid this is a known issue, we've reported it. You can fix it with /bq_admin default load
