### ISSUE TITLE
Wizardry mod should be updated

### ISSUE THREAD

**Issue by AwesomeDog86** [NillerMedDild/Enigmatica2#702]
**Modpack version**
1.77

**Issue**
The Wizardry mod by Escapee_ needs to be updated. It is currently running 0.10.8 which has a bug causing frame drops when creating higher level spells. The 0.11.0 patch has fixed that and has been out since August. 

**Logs**
[https://github.com/TeamWizardry/Wizardry/issues/305](url)

**Comment by NillerMedDild** [comment]
No need to make issues for updating, but thanks :)
