### ISSUE TITLE
mekanism cables

### ISSUE THREAD

**Issue by brad1274** [NillerMedDild/Enigmatica2#705]
![2021-01-14_14 06 37](https://user-images.githubusercontent.com/77460868/104637569-ff096b80-5672-11eb-81ea-e62c6d90c054.png)
![2021-01-14_14 07 47](https://user-images.githubusercontent.com/77460868/104637571-ffa20200-5672-11eb-9109-29136b630933.png)

**Modpack version**
0.3.5

**Issue**
cables glitch out

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment]
Are you using Optifine? :)
