### ISSUE TITLE
Brown Magic from PlusTic won't activate

### ISSUE THREAD

**Issue by onefishtwofishthree** [NillerMedDild/Enigmatica2#706]
**Modpack version**
Enigmatica 2 1.77

**Issue**
I am able to set the teleport location (confirmation in the chatbox with coordinates) for the Brown Magic trait from PlusTiC (on a laser gun), but the activate key does nothing, there is no sign of anything happening or registering. I've made sure there are no keybinding conflicts (and I tried some half a different untaken keys just to be sure).

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment]
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)
