### ISSUE TITLE
Crashing when opening Inventory

### ISSUE THREAD

**Issue by UglyBoiDesu** [NillerMedDild/Enigmatica2#708]
**Modpack version**
Enigmatica 2 : Expert 1.82a | Via ATLauncher
Raw version: 14.23.5.2847

**Issue**
Opening Inventory after loading into game causes a crash.
When i initially load into the game i can walk around and break blocks but when i open my inventory i crash immediately.
I am using Java 1.8+ so it doesn't seem to be a java issue.
**Logs**
Crash report via PasteBin : https://pastebin.com/wJGwDM5J
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/5870599/latest.log)
[crash-2021-01-25_19.13.08-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/5870601/crash-2021-01-25_19.13.08-client.txt)

**Comment by NillerMedDild** [comment]
Optifine is causing this issue, remove it :)

**Comment by UglyBoiDesu** [comment]
Just want to leave this here. I disabled anisotropic filtering so now i don't need to remove optifine.

**Comment by NillerMedDild** [comment]
Oh interesting, thanks.
