### ISSUE TITLE
Cheat mode on by default in JEI at the start of a new game

### ISSUE THREAD

**Issue by gsmith2885** [NillerMedDild/Enigmatica2#709]
**Modpack version**
1.77

**Issue**
After a fresh install on a new computer when opening JEI for the first time cheat mode is on. I know to turn it off but I'm teaching some friends how to play for the first time and they don't know to do this.

**Logs**
Not applicable

**Comment by TGMax233Michael** [comment]
Is there a version number of 1.77?

**Comment by NillerMedDild** [comment]
Thanks for the report, I'll get that fixed.
