### ISSUE TITLE
Space Station not appearing

### ISSUE THREAD

**Issue by DarkWarMind** [NillerMedDild/Enigmatica2#710]
**Modpack version**
MC Eternal 1.12.2

**Issue**
After properly building a space station and rocket using the space station ID Chip, the rocket doesnt land on the space station, then endlessly floating in space.

**Logs**
Unknown
![Issue1](https://user-images.githubusercontent.com/78570615/106967043-754e3a80-6714-11eb-81a4-458be04eaf6c.png)
![Issue2](https://user-images.githubusercontent.com/78570615/106967049-77b09480-6714-11eb-9665-544b117e554b.png)
![Issue3](https://user-images.githubusercontent.com/78570615/106967057-7a12ee80-6714-11eb-9c4c-34231cd2f7fe.png)

**Comment by Merlo17** [comment]
I think you have the wrong issue tracker buddy :P

**Comment by theboo** [comment]
Yeah... Wrong pack haha... Also, that's a looooong standing AR bug that I don't think is getting fixed any time soon
