### ISSUE TITLE
Server Internal Error with online-mode=false

### ISSUE THREAD

**Issue by Coraz97** [NillerMedDild/Enigmatica2#713]
**Modpack version**
1.77

**Issue**
After a death, the client exits out from the server due to an "Internal Server Error". The server logs show an error in handling the packet. After some testing I found out that changing online-mode to false in server.properties causes the issue described.

**Logs**
I couldn't paste on pastebin since it exceeded the 512 KB limit, so here it is.
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/6056719/latest.log)

**Comment by NillerMedDild** [comment]
I recommend you don't use that property :) Just enable whitelist and whitelist yourself only.
