### ISSUE TITLE
Mana band quest detection not working.

### ISSUE THREAD

**Issue by xxmmc** [NillerMedDild/Enigmatica2#718]
**Modpack version**
1.78

**Issue**
The quest for the Band of Mana in the Botania line isn't working. I've crafted 3 different mana bands. Two of them in the ME terminal, where I crafted one with a full mana tablet and one with an empty mana tablet. The third I used an empty mana tablet and it was crafted in a vanilla crafting table. The quest is still incomplete for me.

**Comment by NillerMedDild** [comment]
Use the command `/bq_admin default load` :)
