### ISSUE TITLE
complete game freeze when opening inventory

### ISSUE THREAD

**Issue by unknownjims** [NillerMedDild/Enigmatica2#72]
#### Crash Report

[pastebin/gist/etc link here]

![image](https://user-images.githubusercontent.com/29684155/44296758-82fd7480-a2bc-11e8-99f4-6cdda2715368.png)

[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/2299212/latest.log)

i have updated to the latest java already and no luck.

**Comment by NillerMedDild** [comment]
Try removing MouseTweaks.

**Comment by NillerMedDild** [comment]
Also, you're not using the latest Java, according to your log.

**Comment by unknownjims** [comment]
Thanks that seem to have fixed the issue.

**Comment by NillerMedDild** [comment]
You're welcome :)
