### ISSUE TITLE
Issue with the Dank Null

### ISSUE THREAD

**Issue by Jobever** [NillerMedDild/Enigmatica2#720]
**Modpack version**
1.78

**Issue**
When Shift+rightclicking with the "Dank Null" the inventory opens normal, but the items inside the Dank Null are not correct (regarding the visual aspect). The item type and amount are not shown properly.
Example 1: I click on a square that has cobble in it and I get dirt. 
Example 2: I click on an empty square and I get items. 
The number of items I get is correct, but the GUI is broken. 

**Logs**
Not applicable

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by ChaoticElements** [comment]
p455w0rds-MC-Mods/DankNull#343

I'd been meaning to note an issue about this - appears to be the same thing as in the above issue, just needs to update /dank/null to 1.7.101 as noted in that issue

**Comment by NillerMedDild** [comment]
Would one of you mind trying to update to `1.7.101`, and see if there are any issues? I'm particularly scared of an issue where the DankNull gets cleared between updates, so you'd have to make a backup before updating. No sweat if you'd rather not do it ofc.

**Comment by ChaoticElements** [comment]
Just did this with a world-download of my server. The DankNull gets cleared between the updates:
https://i.imgur.com/rugTxnO.png
On the other hand, the Dank/null/ is between annoying and unusable with the visual bugs, so it may be the lesser evil?

**Comment by NillerMedDild** [comment]
Thanks for testing! The Dank/Null version in the pack is `DankNull-1.12.2-1.7.91` though, did you update it yourself to begin with?

**Comment by ChaoticElements** [comment]
Oops! That's a typo in my picture. I used the current instance from curseforge, fresh download.

**Comment by NillerMedDild** [comment]
Aw damn :P

**Comment by NillerMedDild** [comment]
Hmm, could you perhaps try downgrading to `DankNull-1.12.2-1.7.90`?
