### ISSUE TITLE
Server did start when using putty ( sh remote connection )

### ISSUE THREAD

**Issue by Kalvelign** [NillerMedDild/Enigmatica2#721]
Enigmatica2

The .sh of the server pack wont start if we start in sh remote connection ( putty or other logicial ) .

Pls add that information into the SERVER_GUIDE or on the curse forge pages , thx.

Also i found that in the ServerStartLinux.sh 
https://cdn.discordapp.com/attachments/824446632451112960/824450593246543902/unknown.png

**Comment by NillerMedDild** [comment]
Sure thing, added to the server guide going forward.
