### ISSUE TITLE
Found a way to duplicate the crystal cell from ember

### ISSUE THREAD

**Issue by Jobever** [NillerMedDild/Enigmatica2#722]
**Modpack version**
1.78
**Issue**
When pushing the "crystal cell from the mod ember" upwards with a piston, you duplicate the item. WHen you break the upper cell you see that the bottom one is missing the middle block. Both cells can be mined to obtain the cell (so duplicating the block).
![Ember bug](https://user-images.githubusercontent.com/80709390/113342913-5ee8e780-932f-11eb-834b-a02024967c72.PNG)

**Comment by NillerMedDild** [comment]
Thanks for the report. I thought I had fixed that issue in 1.78 ^^'
