### ISSUE TITLE
[not an issue/bug] what is the minimum and recommened specs for this modpack?

### ISSUE THREAD

**Issue by reiha7** [NillerMedDild/Enigmatica2#723]
**Modpack version**
2 1.78

**Issue**
hey, not an issue here, but what is the minimum specs for the modpack? here are my specs:

cpu: core i3
processor: i3-6006U
gpu: intel(r) hd graphics 520
hdd: 300gb free

**Logs**
N/A

**Comment by NillerMedDild** [comment]
It's mostly dependant on RAM, you need at least 8GB. Your CPU could also be an issue though, to be honest. 
I recommend that you try another modpack, or perhaps Enigmatica 2: Light :)
