### ISSUE TITLE
Mining Level resetting on pickaxe?

### ISSUE THREAD

**Issue by dom11990** [NillerMedDild/Enigmatica2#724]
**Modpack version**
1.82a

**Issue**
For some reason, the mining level on my pickaxe resets when I use it on a block for the first time. For example, I have an iron pickaxe which was made using iron head, stone binding, wood rod. When I try to use it on a Lead block it says it is not harvestable and takes a long time to mine. After completion, the lead block drops! I've tried using sharpening kits with the same effect. Here I've upgraded the pickaxe head to lead, but the mining level is still certus. What am I doing wrong or is this a bug? My nutrition levels are all above 50%.

![image](https://user-images.githubusercontent.com/4545056/122632723-f828ce00-d0d4-11eb-946b-b5c38797908c.png)

**Comment by NillerMedDild** [comment]
Please double check that you're on modpack version 1.82a and not 1.82 - 1.82 had a major issue with mining levels.

**Comment by dom11990** [comment]
Confirm version was 1.82a

**Comment by sirajknana** [comment]
![miceraft problem](https://user-images.githubusercontent.com/88626578/128638866-a1679c12-b901-4093-b1d2-6088118fea35.PNG)
please help i can't open the start-server from the curse forge 
this keeps popping up
and I didn't find anything online

**Comment by NillerMedDild** [comment]
@dom11990 please reinstall and see of that fixes the issue :)
@sirajknana please ask for help in the support channel on our Discord.

**Comment by sirajknana** [comment]
i talked to the team and they helped me thanks!
