### ISSUE TITLE
Game crashes if you save while the world is open to LAN

### ISSUE THREAD

**Issue by SimoonDude** [NillerMedDild/Enigmatica2#725]
**Modpack version**
Engimatica2Expert-1.82a

**Issue**
The game stops responding if you click "Save and Quit to Menu" if the world is open to LAN

**Logs**
[Logs](https://pastebin.com/Kpr3ERgL)

**Comment by NillerMedDild** [comment]
Thanks for the report. We've been aware of this issue for years at this point, and have not been able to fix it unfortunately :/
