### ISSUE TITLE
Magic bees x Thaumcraft mismatch

### ISSUE THREAD

**Issue by squishey123** [NillerMedDild/Enigmatica2#727]
**Modpack version**
1.79

**Issue**
The bees from "Magic Bees" for producing the 6 primal Vis crystals for thaumcraft make crystals worth 8 of their respective vis rather than the standard 1. Thus these crystals can not be used for crafting in the arcane crafting table and can only be converted through the thaumcraft smeltery with a lot of flux as a byproduct

**Comment by NillerMedDild** [comment]
I believe that is intended :)
