### ISSUE TITLE
[Question] Why are specters from RandomThings Disabled?

### ISSUE THREAD

**Issue by V2LenKagamine** [NillerMedDild/Enigmatica2#728]
**Modpack version**
Latest [1.82a]

**Issue**

Just wondering, I can understand some of the specter tools are too good for how early you can get them, but why disable specters entirely if you can just remove the recipes in question? Do the mobs cause an issue? If so, could you kindly add a recipe for the ectoplasm/specter Illuminator? I find that they are a more concentrated and useful for base building than the cave illuminator from astral.
Please respond, Len.

**Comment by NillerMedDild** [comment]
Hi there. They're disabled because I think the energy they can produce is too strong for their cost, and because I don't really like the entire mechanic, tbf.
