### ISSUE TITLE
Glitch That Makes Game Unplayabe, please help.

### ISSUE THREAD

**Issue by crazydave686** [NillerMedDild/Enigmatica2#73]
All textures glitching out

version 1.45

Game did not crash

Screenshot of issue
https://imgur.com/a/edAZM5r

Extra information i loaded a biomes-o-plenty world and spawned to this

**Comment by crazydave686** [comment]
https://imgur.com/a/2JHwPZe
https://imgur.com/a/bhTg1j3

More stuff, chests work and some other minecraft blocks, so does text.

**Comment by NillerMedDild** [comment]
Are you using Optifine? Have you tried reinstalling?

**Comment by crazydave686** [comment]
No I have not used options and have tried reinstalling

**Comment by NillerMedDild** [comment]
I'm hoping "used options" was a typo.

I'm guessing none of the Reddit tips helped either?

**Comment by NillerMedDild** [comment]
Any update?

**Comment by crazydave686** [comment]
Yeah I have come to the conclusion that my graphics card is just dying

**Comment by NillerMedDild** [comment]
That sucks :(
