### ISSUE TITLE
0 FPS with a great PC?

### ISSUE THREAD

**Issue by SoftGuardian** [NillerMedDild/Enigmatica2#730]
**Modpack version**
1.79

**Issue**
Game loading and world loading are fine, but once the world is loaded and starts, I can't play, 0 FPS with no crashing... It just updates every 30s. I waited so much and nothing. I allocated 9GB of ram since I have 16GB, My CPU is an i3 10th gen 3.6GHz. How do I fix it?

**Comment by JoaGamo** [comment]
do you have java args? I remember using them a lot in other packs.
Also check your graphics settings in minecraft (like, set max fps to your screen's refresh rate, lower render distance etc)

**Comment by SoftGuardian** [comment]
First I didn't used arguments but since there are issues I tried to use them but nothing. Can you please give me some  that can fix it? For the graphics nothing changed. I checked the mods in the folder and there is FPS Reducer mod which helps running programs when minecraft is minimized. Is there a way to delete it? I don't need it so.
