### ISSUE TITLE
.Bat file not working

### ISSUE THREAD

**Issue by Zaridus** [NillerMedDild/Enigmatica2#731]
Skyfactory 4.2.2

Whenever I use the forge server file, My friend is able to join with my public ip. Whenever i use the .bat file to start the server my friend isnt allowed to join, i checked my firewall and my port fowards. It doesnt even show he joined the server on the logs when using the bat file, and I cant use my public ip address i need to use my private, but with my private ip it shows the server on the server list but it does not allow him to join

**Comment by NillerMedDild** [comment]
This issue tracker is for the modpack Enigmatica 2, SkyFactory 4's issue tracker can be found here: https://github.com/DarkPacks/SkyFactory-4/issues

However, it doesn't sound like a modpack issue to me to be honest.
