### ISSUE TITLE
infinite sulfur

### ISSUE THREAD

**Issue by Floppa-8765** [NillerMedDild/Enigmatica2#734]
**Modpack version**
e2e 1.8.3

**Issue**
with an enrichment chamber, pulverizer, and stack of coal you can get infinite sulfur

![2021-08-31_22 41 37](https://user-images.githubusercontent.com/51796333/131603098-254fee69-3544-4163-8006-720336597221.png)
![2021-08-31_22 41 42](https://user-images.githubusercontent.com/51796333/131603102-62a36794-044c-4d4f-b4db-6d804c7ca2f2.png)

**Comment by NillerMedDild** [comment]
Thanks for the report. There are many ways to get infinite sulfur, this is intended :)

**Comment by Floppa-8765** [comment]
hey niller funny story, I posted this in the wrong thread... oops
