### ISSUE TITLE
[1.45] Tier 6 Ore Miner does not have iron ore in it's minable blocks.

### ISSUE THREAD

**Issue by nodey420** [NillerMedDild/Enigmatica2#74]
#### Issue Description

1. Setup Tier 6 Miner
2. Provide a crap ton of RF
3. Give it somewhere to store the goodness.
3. Reap the benefits....except `oreIron`.

I could check other ores, if you want.  Let me know.

#### Modpack version (Do not use "latest")

1.45

#### Crash Report

N/A

**Comment by nodey420** [comment]
There are actually a lot of ores missing. Is that by design to only have a few in the tier 6?

**Comment by NillerMedDild** [comment]
Yes it is by design, it only targets rare ore.
