### ISSUE TITLE
BetterQuesting parties are not working.

### ISSUE THREAD

**Issue by TheLostInPlace** [NillerMedDild/Enigmatica2#75]
#### Crash Report: None as it doesn't crash.

Here's a picture of the [https://imgur.com/FZhkpOY](url) of what the party GUI looks like, as you can tell it looks out of place and wonky, and it's not due to the large GUI scaling, as I tried all of them.

**Comment by NillerMedDild** [comment]
The issue has been reported, thank you for the report.

**Comment by NillerMedDild** [comment]
Did you also update Standard Expansion?
