### ISSUE TITLE
enigmatica 2 server possibly compromised

### ISSUE THREAD

**Issue by lemmingsmasher** [NillerMedDild/Enigmatica2#78]
#### Issue Description
I downloaded the enigmatica 2 server an hour ago from curseforge and double checked i didn't get it from a fake/impersonating/spoof site after this issue was observed. I scanned the server zip with both windows defender and malwarebytes. On first server run, I received a virus warning. i took a picture of the server window right when windows defender picked up the virus. https://imgur.com/a/xmQ4VpL
#### Modpack version (Do not use "latest")
1.45
#### Crash Report
n/a

**Comment by NillerMedDild** [comment]
Several anti-virus programs are detecting forge 2750 as a virus, I can assure you it's a false positive.
