### ISSUE TITLE
Crashing when trying to click anything or open inventory

### ISSUE THREAD

**Issue by unknownjims** [NillerMedDild/Enigmatica2#79]
#### Crash Report

[pastebin/gist/etc link here]
[debug.log](https://github.com/NillerMedDild/Enigmatica2/files/2327789/debug.log)
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/2327790/latest.log)

**Comment by NillerMedDild** [comment]
Crashlog please.

**Comment by unknownjims** [comment]
[crash-2018-08-27_14.57.09-server.txt](https://github.com/NillerMedDild/Enigmatica2/files/2327935/crash-2018-08-27_14.57.09-server.txt)

**Comment by NillerMedDild** [comment]
Are you holding an AE Terminal? If you are, toss it.

**Comment by unknownjims** [comment]
Woow thanks again that solved the issue.

**Comment by NillerMedDild** [comment]
You're welcome :)
