### ISSUE TITLE
Buckets cause crashes when used on non liquid-source blocks

### ISSUE THREAD

**Issue by NotUnix** [NillerMedDild/Enigmatica2#8]
#### Issue Description
Whenever an empty bucket is used on empty air accidentally (fluid block out of range, no source block selected, etc) the game does a CTD
#### Modpack version (Do not use "latest")
1.26
#### Your most recent log file where the issue was present
https://pastebin.com/4xppuVPF

**Comment by NillerMedDild** [comment]
Will fix asap, thanks for reporting. While you wait, you can fix the issue by manually updating Advanced Rocketry, if you'd like.

**Comment by NillerMedDild** [comment]
Fixed!
