### ISSUE TITLE
Fission Controller not recognized?

### ISSUE THREAD

**Issue by CaveJohnsonn** [NillerMedDild/Enigmatica2#80]
#### Modpack version (Do not use "latest") 1.4

![2018-08-30_03 19 58](https://user-images.githubusercontent.com/41660739/44839283-05166300-ac04-11e8-9a35-0582b3e21cba.png)

![2018-08-30_03 26 17](https://user-images.githubusercontent.com/41660739/44839483-840b9b80-ac04-11e8-8f45-e8e1c90adf17.png)

As you can see, even with the item in my inventory, it's still failed to recognize it in the quest log.

**Comment by NillerMedDild** [comment]
This is the wrong issue tracker -.-
https://github.com/Discomanco/Enigmatica2ExpertSkyblock/issues
