### ISSUE TITLE
Client Side Kick From Server Ender Storage

### ISSUE THREAD

**Issue by Silvyies** [NillerMedDild/Enigmatica2#83]
I am Kicked from a local server every time i attempt to log on after picking up a ender storage tank dyed all green with carryon

1.46

**Comment by NillerMedDild** [comment]
Don't just delete the issue template, it's there for a reason. I need your log and the server's log aswell.

**Comment by Silvyies** [comment]
Sorry For The Delay In Response Let Me Know If There Are Any Issues Viewing Them Or If I Need To Put Them Somewhere Else
[2018-09-03-2(Client).log](https://github.com/NillerMedDild/Enigmatica2/files/2354328/2018-09-03-2.Client.log)
[crash-2018-09-03_19.33.34-server.txt](https://github.com/NillerMedDild/Enigmatica2/files/2354329/crash-2018-09-03_19.33.34-server.txt)
[latest(Server).log](https://github.com/NillerMedDild/Enigmatica2/files/2354330/latest.Server.log)

**Comment by NillerMedDild** [comment]
[forge.zip](https://github.com/NillerMedDild/Enigmatica2/files/2355745/forge.zip)

Unzip that file into your config folder and you should be good to go. You will crash the first time you log in, but the second should be fine.
