### ISSUE TITLE
Unable to put items into Advanced Inscriber

### ISSUE THREAD

**Issue by blitzyuk** [NillerMedDild/Enigmatica2#84]
I'm Playing on a server and since the server updated to version 1.46 I can no longer put items into the Advanced Inscribers. On version 1.45 they worked as I had them automated.  Whenever I try to put the presses in or the required items to craft the processors as soon as I come out of the Inscriber GUI they are back in my Inventory. I thought this might be a desync issue but I have disconnected from server also tried after server restart. Also now someone else on the server has run into this issue.

Enigmatica 2 Normal Version 1.26

No Crash report.

**Comment by NillerMedDild** [comment]
Have you tried breaking and replacing it?

**Comment by blitzyuk** [comment]
Yup tried breaking and replacing, Tried removing security terminal and reconfiguring it.

**Comment by blitzyuk** [comment]
Hi I made a GIF of the issue just to show what i mean. Also the Advanced Inscribers are permanently showing sleeping too no matter what I do too. here's the GIF https://i.imgur.com/Tk87q7K.gifv

**Comment by blitzyuk** [comment]
Also Normal Inscribers too https://i.imgur.com/iujQBJw.gifv

**Comment by NillerMedDild** [comment]
Can you interact with Furnaces, Chests etc in the area?

**Comment by blitzyuk** [comment]
yes. I've just tried this in single player and it works in Creative game

**Comment by NillerMedDild** [comment]
Yes... try breaking the Security Station and restarting the server. 
The machines are powered directly with cable right?

**Comment by blitzyuk** [comment]
yes powered directly with the cable from an energy acceptor. The other person on the server has no Security terminal. Also tried it just using using a seperate ME controller cables and energy acceptor still no joy.

**Comment by NillerMedDild** [comment]
So weird xD I'm out of ideas, again.

**Comment by blitzyuk** [comment]
your not the only one.

**Comment by Paxination** [comment]
Me and blitzyuk play on the same server and I am now having the same issue as well.

**Comment by blitzyuk** [comment]
Could it be a bad server install?

**Comment by NillerMedDild** [comment]
Sure, why not :P

**Comment by NillerMedDild** [comment]
I'm gonna chalk this up to a bad server install, as I still cannot replicate it.
