### ISSUE TITLE
weird lag in single player world and now crash when trying to load into world

### ISSUE THREAD

**Issue by unknownjims** [NillerMedDild/Enigmatica2#85]
#### Crash Report

[pastebin/gist/etc link here]
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/2350490/latest.log)
[crash-2018-09-03_01.06.06-client.txt](https://github.com/NillerMedDild/Enigmatica2/files/2350492/crash-2018-09-03_01.06.06-client.txt)

**Comment by NillerMedDild** [comment]
Seems like your world has corrupted, delete this file from your save:
`/C:/Users/NTI/Documents/Curse/Minecraft/Instances/Enigmatica%202%20Expert%20Skyblock%20(1)%20(1)%20(1)/saves/jims%20world/advRocketry/planetDefs.xml`

**Comment by unknownjims** [comment]
no luck with that still crashes :(

**Comment by NillerMedDild** [comment]
Please link the new crashlog.

**Comment by unknownjims** [comment]
its fine i went back to a previous save and that works but i still have the block lag for some reason

**Comment by unknownjims** [comment]
[https://drive.google.com/open?id=1L5GMVHZn3ckSWBXsQyyucpl-E-0ccL0y](url)

**Comment by NillerMedDild** [comment]
Alright, nice it's fixed!

I'm guessing you have a bunch of entities somewhere causing lag, or simply a lot of lagging machines. 

I will not open drive links.
