### ISSUE TITLE
Mod pack error

### ISSUE THREAD

**Issue by ayexjordan** [NillerMedDild/Enigmatica2#86]
Whenever I load the pack on the twitch launcher, it starts to load 1/7 and then crashes and shows “8 errors were found on minecraft”. It shows the mods that aren’t installed but when I check the mod folder, everything is installed as/where it should be. It started at 13 errors and is now 8, I tried deleting and reinstalling several times and nothing seems to help. If anyone can help it would be greatly appreciated!

**Comment by NillerMedDild** [comment]
Don't just delete the issue template, fill it out. Please open a new issue, with the correct information.
