### ISSUE TITLE
Game Freezes When User Sleeps

### ISSUE THREAD

**Issue by Scar689** [NillerMedDild/Enigmatica2#89]
My game keeps freezing with Enigmatica 2 every time I sleep in the bed of change the time to day. My character is able to move around freely but unable to interact with anything, all mobs and npc's also stop moving in their tracks.

Modpack version 1.46
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/2364214/latest.log)

**Comment by NillerMedDild** [comment]
Did you manage to fix the issue?

**Comment by Scar689** [comment]
I did yes, thanks. It turned out to be a issue with the mega torches, as soon as I removed them it returned to normal.
