### ISSUE TITLE
Cannot complete AE2 quest [It's Peer, Not Pier]

### ISSUE THREAD

**Issue by angryansari** [NillerMedDild/Enigmatica2#9]
#### Issue Description
Cannot complete quest it's Peer, Not Pier
#### What happens
Cannot craft P2p Tunnel - Item, recipe does not cycle from P2P Tunnel - ME like the quest book says it should
#### What you expected to happen
P2P tunnel - ME should turn into P2P tunnel - Item in a crafting grid by itself
#### Modpack version (Do not use "latest")
1.26
#### Your most recent log file where the issue was present
N/A
[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
Will try to fix it - Can you make the Item P2P Tunnel by placing the P2P Tunnel, and clicking it with an Itemduct?

**Comment by NillerMedDild** [comment]
And finally fixed aswell, sorry about the wait.

**Comment by diz9000** [comment]
Still having issue with this quest.
From quest tree says 1/2 complete
But the actual quest only has one requirement , the P2P tunnel -me (from memory),’
This step shows as complete , but the overall quest isn’t completing, so I can’t move on to the 2 quests below it in the book.
I’ve placed 2 p2p-me in the world , made them p2p-item and clicked them with a memory card.
What am I missing

**Comment by NillerMedDild** [comment]
I'll have another look :)
