### ISSUE TITLE
ServerStart.bat not launching/working

### ISSUE THREAD

**Issue by Nick-House** [NillerMedDild/Enigmatica2#90]
#### Issue Description
ServerStart.bat not working
    - I run the serverstart.bat file, it flashes the cmd for a brief moment, not long enough to read what anything says
    - Forge or minecraft server .jar's are not downloading 

Just curious if I'm missing something or if I'll have to download the server.jar and forge.jar separately, and if this is the case I'm not sure where to start for the .bat script to run the server. I'm sure I can figure it out, but just would like a point in the right direction

#### Modpack version (Do not use "latest")
1.4.5, 1.4.6, 1.4.7 (attempted on all 3)

#### Crash Report
N/A
serverstart.log: https://pastebin.com/UbtfkG17

**Comment by NillerMedDild** [comment]
Which OS does the PC you're trying this on have?
Is it a dedicated server, or through a hosting company?

**Comment by NillerMedDild** [comment]
Strange. Do you have Java on your PC?

**Comment by NillerMedDild** [comment]
You downloaded and extracted the entire serverpackage into a folder, and ran the bat script from there, right?

**Comment by Nick-House** [comment]
Yep, latest version of Java (ver 8 update 81) is installed, both 64 and 32 bit. Extracted the server file from the curse download to a folder, changed the MAX_RAM in settings.cfg to 8G and then attempting running the ServerStart.bat, however I also tried extracting to another folder and not touching anything and still no luck.

**Comment by NillerMedDild** [comment]
Could you try removing the 32-bit Java?
I doubt that's the issue, but since the bat isn't even printing errors as it normally does, there's very little to go on.

**Comment by Nick-House** [comment]
Just removed 32-bit Java, still no luck. Another thing I tried earlier but just realized what happens is when I run the ServerStart.bat I get the following output in serverstart.log: 
https://pastebin.com/zHkDNGw9

Here it almost looks like it's not assigning the values properly from settings.cfg. This only happens when I run as admin, when I run normally I get the original output in the pastebin linked in my original issue report.

**Comment by Nick-House** [comment]
If it helps, I know I can run a vanilla Minecraft server just fine. Had one running before I attempted getting Enigmatica setup to ensure my port forwarding worked just fine. Still runs fine, so I don't think the issue would be Java related, but I'm not educated there so it's just a wild assumption.

**Comment by NillerMedDild** [comment]
Running a bat script as admin forces it to use 32-bit mode, which is the issue you're seeing.

That does help, and yes, you're correct that the issue is not java if you can run a vanilla server.

I'm afraid I don't know how to resolve this.

**Comment by NillerMedDild** [comment]
What kind of drive is your F drive?

**Comment by Nick-House** [comment]
Ahh, that makes sense. Would it be possible for me to download the proper release of Forge and the MC 1.12.2 server.jar and somehow make a bat to run that properly? I'm not too familiar with servers, especially Forge ones, but it sounds like basically all the bat script does is downloads the jars and sets the configuration for them. 

It certainly isn't acquiring the forge or vanilla jar files right now, so I guess I'm just thinking manually download and then configure directly through a new bat script? I wouldn't know where to begin there, but if that's what will make it work, I wouldn't mind at least trying.

**Comment by Nick-House** [comment]
F Drive is a Western Digital Black 1TB HDD.

**Comment by Nick-House** [comment]
Got the following error: https://pastebin.com/9KdyYvcb

Full script I used:
`@ECHO OFF
java -Xms8192M -Xmx8192M -jar forge.jar nogui
pause`

From what I found online this basically means the libraries for forge aren't complete? Not sure what that means or how I would acquire them, redownload it into my server?

Thanks for all your help thus far!

**Comment by NillerMedDild** [comment]
Oh right, you will have to get the Forge installer, run it and let it install libraries in your server folder. You need to have the Minecraft Server jar in the folder before starting.

Sure thing :)

**Comment by Nick-House** [comment]
Well sadly the thing is I did run the Forge installer. I just attempted running it again into an empty folder then extracting the contents of the server.zip into it after forge and the server are installed, as well as the libraries folder being there. After extracting those files I recreated the script.bat and renamed the forge-version.jar to forge.jar and still getting the same error. 

I'm so lost on this one. I even tried an All the Mods 3 server with no luck. Not sure what I'm doing wrong at this point, I feel like I triple checked everything all the way through. Yet I can still run vanilla server just fine with a start.bat 🙃

**Comment by NillerMedDild** [comment]
I don't have any more ideas then I'm afraid :/

**Comment by Nick-House** [comment]
No worries, thank you for all of your help thus far! I'll be sure to close if a solution is found.

**Comment by Nick-House** [comment]
So apparently I also had Java 10 installed and Forge doesn't work with Java versions higher than Java 8, so I just uninstalled my Java 10 and now the START.bat that I created works properly.

**Comment by NillerMedDild** [comment]
I see, great that it's working :D

**Comment by sirolf01** [comment]
For anyone visiting this on a later date because you're experiencing simular issues.

As he stated above Java 10 indeed doesn't work.
So ensure you're running Java 8

And something i encountered a Java Toolkit,

As such check your programs (by searching for the general Windows Uninstall menu)
And see if you have any Java Toolkits. If you do and aren't using them Uninstall them and try again..


Posting them so others don't need to spend 10 hours trying.
