### ISSUE TITLE
Quantum Entangloporter:

### ISSUE THREAD

**Issue by infaerina** [NillerMedDild/Enigmatica2#91]
#### Crash Report (N/A)

I am not certain if it is a Mekanism problem or an Enigmatica 2 problem, but I am not able to consistently pull power from the Quantum Entangloporters. 

I tried to add pictures in the correct sequence: [https://imgur.com/a/Ca87PPJ](url)

I place a Quantum Entangloporter in the correct channel and it fills with power. 

I set it to output and eject energy, then connect a universal cable. 

I have a tremendous amount of power available, but it does not provide any remotely. 

Frustrated I restart the server and when I log back in, the Quantum Entangloporter is properly providing power. I put another one beside the first and it is working, as well as working on my other ones. 

The final picture is tonight, about 18 hours later, the Quantum Entangloporter not working again. 

P.S. I'm loving the mod pack, thanks so much for your time!

**Comment by NillerMedDild** [comment]
Are both Quantum Entangloporters chunkloaded?

I'm really glad you like the pack, and you're welcome :)

**Comment by infaerina** [comment]
Yes, though I do not have the anchor in them, they are chunkloaded through the claim chunks menu. It is giving me the same problem in the same chunk as my entire power production / storage as well now. 

And it's a pleasure, most fun I've had so far :D

**Comment by NillerMedDild** [comment]
Could you try with Anchor Upgrades please?

**Comment by infaerina** [comment]
Sorry for the delay, I was at work. It does not seem to affect the problem.

**Comment by NillerMedDild** [comment]
It seems similar to this issue: https://github.com/aidancbrady/Mekanism/issues/4800
Could you provide screenshots of each Quantum Entangloporter setup please? Preferably with chunk boundaries shown (F9)

**Comment by NillerMedDild** [comment]
The Quantum Entangloporter does not push energy, you have to pull it out - Try fiddling with pull/push settings of the attached Universal Cable.

**Comment by NillerMedDild** [comment]
Errr... the energy cable you have on it is in a different chunk, so it is not loaded by the Anchor upgrade.

**Comment by infaerina** [comment]
I have 20 chunks around the area I am in loaded and have tried various combinations of push / pull. The work around I am using now is setting my energy on a channel for gas on equipment that cannot accept gas. It just seems off to me. 
![image](https://user-images.githubusercontent.com/2001643/45574226-4b430780-b83d-11e8-87bb-154ae8f59f93.png)
