### ISSUE TITLE
Iridium bee.

### ISSUE THREAD

**Issue by Andersen2311** [NillerMedDild/Enigmatica2#92]
Would it be possible to make a bee that gives tiny pile of iridium? I just don't really see a point using bee's besides questing. Though im haven't finished yet, so i might be wrong.

**Comment by NillerMedDild** [comment]
Bees can generate a ton of different resources, even diamonds and emeralds. 

Iridium isn't really used in the pack, why do you want a bee for it? :)

**Comment by Andersen2311** [comment]
For the singularity, or am i just missing a huge and relatively simple way to get it. Thats faster than uumatter

**Comment by NillerMedDild** [comment]
You're in the wrong issue tracker, this isn't Expert.

**Comment by NillerMedDild** [comment]
And yes, you're missing several relatively simple ways of obtaining it.
