### ISSUE TITLE
Peridot?

### ISSUE THREAD

**Issue by DingleFlop** [NillerMedDild/Enigmatica2#93]
#### Issue Description
Peridot ore doesn't spawn. I am in a singleplayer world that I am sharing over LAN.
#### Modpack version (Do not use "latest")
1.47
#### Crash Report
N/A
[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
Peridot only spawns in certain biomes, in worlds generated with Biomes o' Plenty.
