### ISSUE TITLE
Using Item Laser Relays with Storage Drawers

### ISSUE THREAD

**Issue by Tyrokas** [NillerMedDild/Enigmatica2#94]
**Actually Additions - Item Laser Relay** wont pull/transfer items from or into a **Storage Drawer's - Drawer** or **Controller**.
Problem was encountered while attemting to automate Canola Oil - Energy Production. All the other Laser Relays such as Energy and Fluid were working as they should. 

**Modpack version 1.47**

**Comment by z64555** [comment]
Do you have a picture of your set up?

Remember that the item laser relay placed on inventories mark that inventory as "internal" storage.  All items pushed into the relay network by way of interfaces (with item relays attached to them) will push items to the inventory, and items pull from the interfaces will likewise pull from the inventory.

Another thing to remember is that the Drawer Controller is directional, you must place piping on the face of the controller for it to work. Drawer Slaves on the other hand can have piping attached on any side.

**Comment by NillerMedDild** [comment]
@Tyrokas Could you supply a picture as asked, please?
