### ISSUE TITLE
connection problems

### ISSUE THREAD

**Issue by eniolas** [NillerMedDild/Enigmatica2#95]
#### Issue Description
when i try to connect to my friends server on creeper host, it keeps saying that the server booted me, but the server client says I left. I managed to get to connect for a few days straight, then the problem happened again. when I managed to reconnect i'd closed my discord, my twitch, and set the Java run time environment to run in admin, i'd also set priority to Realtime I keep 6 gigs of RAM allotted. all of my firewalls are disabled. running 1.46 of the modpack. yes it matches the server version.
i'm at my wits end on this. I can play LAN games just fine. me and my fiancé play local multiplayer pretty often. but connecting outside my network is impossible. However my fiances laptop can connect and play just fine. I can play on her laptop logged into my accounts just fine. I even took my rig over to my mothers and hooked it up to see if it was something up with my router/modem and it still doesn't work. I've uninstalled and reinstalled just about everything but windows.
#### Modpack version (Do not use "latest")
1.46
#### Crash Report
connection has been forcibly closed by the Remote Host
[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment]
This isn't a modpack issue, it's your PC.

I will need your latest.log and the servers latest.log, from a session where you tried to connect.

**Comment by eniolas** [comment]
i can connect to vanilla servers and realms tho, so I assumed it'd be
something up with the mudpack. i'lll get it to you as soon as I can.

**Comment by NillerMedDild** [comment]
Vanilla and modded are two very very different things.

**Comment by eniolas** [comment]
i'll get you my logs, but I wont be able to get you server logs, server
owner has gone to bed. gimme just a few

**Comment by NillerMedDild** [comment]
No rush :)

**Comment by eniolas** [comment]
those are the logs from the moment the connection itself was successful

**Comment by eniolas** [comment]
02:05:34 net.minecraft.client.multiplayer.GuiConnecting Connecting to
springfall810.playat.ch, 25565
02:05:39 FML Server protocol version 2
02:05:39 FML Attempting connection with missing mods [betteradvancements,
blockdrops, controlling, ctgui, ctm, custombackgrounds, custommainmenu,
defaultoptions, discordsuite, fpsreducer, ikwid, inventorytweaks, jehc,
jeivillagers, justenoughpetroleum, jeresources, moreoverlays, mousetweaks,
neat, nonvflash, resourceloader, solcarrot, thaumicjei, tipthescales,
toastcontrol, torohealthmod, reauth] at SERVER
02:05:40 FML Injecting existing registry data into this client instance
02:05:40 FML Registry IRecipe: Found a missing id from the world
exchangers:pulsating_exchanger_normal
02:05:40 FML Registry IRecipe: Found a missing id from the world
exchangers:electricalsteel_exchanger_normal
02:05:40 FML Registry IRecipe: Found a missing id from the world
exchangers:eio_core_tier1
02:05:40 FML Registry IRecipe: Found a missing id from the world
exchangers:darksteel_exchanger_normal
02:05:40 FML Registry IRecipe: Found a missing id from the world
exchangers:vibrant_exchanger_normal
02:05:40 FML Registry IRecipe: Found a missing id from the world
exchangers:conductive_exchanger
02:05:40 FML Registry IRecipe: Found a missing id from the world
exchangers:energetic_exchanger_normal
02:05:40 FML Registry IRecipe: Found a missing id from the world
exchangers:eio_core_tier3_normal
02:05:40 FML Registry IRecipe: Found a missing id from the world
exchangers:eio_core_tier2_normal
02:05:52 foamfix JEI search tree manager injection complete!
02:05:54 jei Recipe registry plugin is slow, took 1.765 s. class
binnie.extratrees.integration.jei.multifence.MultiFenceRecipeRegistryPlugin
02:05:54 jei Recipe registry plugin is slow, took 20.48 ms. class
crazypants.enderio.machines.integration.jei.PainterRegistryPlugin
02:05:54 FML Applying holder lookups
02:05:54 FML Holder lookups applied
02:05:54 FML [Netty Client IO #1] Client side modded connection established
02:05:54 mcjty.lib.varia.Logging DimensionSyncPacket: Registering:
02:05:54 Astral Sorcery [AstralSorcery] Using gateway screenshots for
folder 'springfall810.playat.ch_198.206.13.58_25565'
02:05:54 mcjty.lib.varia.Logging Received dimension information from server
02:05:55 STDOUT [biomesoplenty.common.world.BiomeProviderBOP:<init>:61]:
settings for world:
02:05:55 STDOUT
[biomesoplenty.common.world.BiomeProviderBOP:initialLandAndSeaLayer:93]:
Setting up landmass VANILLA
02:08:55 STDERR [p455w0rdslib.util.ContributorUtils$DLThread:run:328]:
java.io.FileNotFoundException: http://hindsley.us/patrons.txt
02:08:55 STDERR [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: at
sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
02:08:55 STDERR [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: at
sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
02:08:55 STDERR [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: at
sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
02:08:55 STDERR [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: at
sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
02:08:55 STDERR [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: at
java.security.AccessController.doPrivileged(Native Method)
02:08:55 STDERR [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: at
java.security.AccessController.doPrivileged(AccessController.java:713)
02:08:55 STDERR [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: at
sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
02:08:55 STDERR [p455w0rdslib.util.ContributorUtils$DLThread:run:328]: at
p455w0rdslib.util.ContributorUtils$DLThread.run(ContributorUtils.java:316)
02:08:58 Waila Received server authentication msg. Remote sync will be
activated
02:09:04 EnderCore Reset configs to client values for
com.enderio.core.common.config.ConfigHandler
02:09:04 Astral Sorcery [AstralSorcery] Cleaning client cache...
02:09:04 Astral Sorcery [AstralSorcery] Cleared cached client data!
Disconnected from server.
02:09:04 scannable Building block state lookup table...
02:09:09 scannable No shader mod found, we'll do our own hacks to inject a
depth texture when needed.
02:09:09 scannable Some mod returns null from Block.getPickBlock, should
return ItemStack.EMPTY at this point. Block in question:
Block{architecturecraft:shape}
02:09:09 scannable Some mod returns null from Block.getPickBlock, should
return ItemStack.EMPTY at this point. Block in question:
Block{architecturecraft:shape}
02:09:09 scannable Some mod returns null from Block.getPickBlock, should
return ItemStack.EMPTY at this point. Block in question:
Block{architecturecraft:shape}
02:09:09 scannable Some mod returns null from Block.getPickBlock, should
return ItemStack.EMPTY at this point. Block in question:
Block{architecturecraft:shape}
02:09:09 scannable Some mod returns null from Block.getPickBlock, should
return ItemStack.EMPTY at this point. Block in question:
Block{architecturecraft:shape}
02:09:09 scannable Some mod returns null from Block.getPickBlock, should
return ItemStack.EMPTY at this point. Block in question:
Block{architecturecraft:shape}
02:09:09 scannable Some mod returns null from Block.getPickBlock, should
return ItemStack.EMPTY at this point. Block in question:
Block{architecturecraft:shape}
02:09:09 scannable Some mod returns null from Block.getPickBlock, should
return ItemStack.EMPTY at this point. Block in question:
Block{architecturecraft:shape}
02:09:09 scannable Some mod returns null from Block.getPickBlock, should
return ItemStack.EMPTY at this point. Block in question:
Block{architecturecraft:shape}
02:09:09 scannable Some mod returns null from Block.getPickBlock, should
return ItemStack.EMPTY at this point. Block in question:
Block{architecturecraft:shape}
02:09:09 scannable Some mod returns null from Block.getPickBlock, should
return ItemStack.EMPTY at this point. Block in question:
Block{architecturecraft:shape}
02:09:09 scannable Some mod returns null from Block.getPickBlock, should
return ItemStack.EMPTY at this point. Block in question:
Block{architecturecraft:shape}
02:09:09 scannable Some mod returns null from Block.getPickBlock, should
return ItemStack.EMPTY at this point. Block in question:
Block{architecturecraft:shape}
02:09:09 scannable Some mod returns null from Block.getPickBlock, should
return ItemStack.EMPTY at this point. Block in question:
Block{architecturecraft:shape}
02:09:09 scannable Some mod returns null from Block.getPickBlock, should
return ItemStack.EMPTY at this point. Block in question:
Block{architecturecraft:shape}
02:09:09 scannable Some mod returns null from Block.getPickBlock, should
return ItemStack.EMPTY at this point. Block in question:
Block{architecturecraft:shape}
02:09:11 scannable Built block state lookup table in 6539 ms.
02:09:11 schematica Scheduling client settings reset.
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockCheeseMold attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockCheeseMold attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockCheeseMold attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockCheeseMold attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockCheeseMold attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockCheeseMold attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockCheeseMold attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockCheeseMold attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockTrough attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockTrough attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockTrough attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockTrough attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockTrough attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockTrough attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockTrough attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockTrough attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockNest attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockNest attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockNest attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockNest attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockNest attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockNest attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockNest attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockNest attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockHamsterWheel attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockHamsterWheel attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockHamsterWheel attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockHamsterWheel attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockHamsterWheel attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockHamsterWheel attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockHamsterWheel attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:20 chiselsandbits Unable to determine blocks eligibility for
chiseling, com.animania.common.blocks.BlockHamsterWheel attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:22 chiselsandbits Unable to determine blocks eligibility for
chiseling, org.dave.compactmachines3.block.BlockMachine attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:22 chiselsandbits Unable to determine blocks eligibility for
chiseling, org.dave.compactmachines3.block.BlockMachine attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:22 chiselsandbits Unable to determine blocks eligibility for
chiseling, org.dave.compactmachines3.block.BlockMachine attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:22 chiselsandbits Unable to determine blocks eligibility for
chiseling, org.dave.compactmachines3.block.BlockMachine attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:22 chiselsandbits Unable to determine blocks eligibility for
chiseling, org.dave.compactmachines3.block.BlockMachine attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:22 chiselsandbits Unable to determine blocks eligibility for
chiseling, org.dave.compactmachines3.block.BlockMachine attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:22 chiselsandbits Unable to determine blocks eligibility for
chiseling, org.dave.compactmachines3.block.BlockMachine attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:22 chiselsandbits Unable to determine blocks eligibility for
chiseling, org.dave.compactmachines3.block.BlockMachine attempted to load
mcjty/theoneprobe/api/ProbeMode
02:09:22 chiselsandbits Unable to determine blocks eligibility for
chiseling, org.dave.compactmachines3.block.BlockFieldProjector attempted to
load mcjty/theoneprobe/api/ProbeMode
02:09:22 chiselsandbits Unable to determine blocks eligibility for
chiseling, org.dave.compactmachines3.block.BlockFieldProjector attempted to
load mcjty/theoneprobe/api/ProbeMode
02:09:22 chiselsandbits Unable to determine blocks eligibility for
chiseling, org.dave.compactmachines3.block.BlockFieldProjector attempted to
load mcjty/theoneprobe/api/ProbeMode
02:09:22 chiselsandbits Unable to determine blocks eligibility for
chiseling, org.dave.compactmachines3.block.BlockFieldProjector attempted to
load mcjty/theoneprobe/api/ProbeMode
02:09:22 chiselsandbits Unable to determine blocks eligibility for
chiseling, org.dave.compactmachines3.block.BlockFieldProjector attempted to
load mcjty/theoneprobe/api/ProbeMode
02:09:22 chiselsandbits Unable to determine blocks eligibility for
chiseling, org.dave.compactmachines3.block.BlockFieldProjector attempted to
load mcjty/theoneprobe/api/ProbeMode
02:09:22 chiselsandbits Unable to determine blocks eligibility for
chiseling, org.dave.compactmachines3.block.BlockFieldProjector attempted to
load mcjty/theoneprobe/api/ProbeMode
02:09:22 chiselsandbits Unable to determine blocks eligibility for
chiseling, org.dave.compactmachines3.block.BlockFieldProjector attempted to
load mcjty/theoneprobe/api/ProbeMode
02:09:30 foamfix JEI search tree manager injection complete!
02:09:32 jei Recipe registry plugin is slow, took 1.765 s. class
binnie.extratrees.integration.jei.multifence.MultiFenceRecipeRegistryPlugin
02:09:32 jei Recipe registry plugin is slow, took 20.48 ms. class
crazypants.enderio.machines.integration.jei.PainterRegistryPlugin
02:09:32 FML Applying holder lookups
02:09:32 FML Holder lookups applied
02:09:38 schematica Client settings have been reset.
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 1
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 2
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 3
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 4
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 5
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 6
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 7
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 8
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 9
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 10
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 11
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 12
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 13
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 14
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 15
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 16
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 17
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 18
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 19
entries)
02:09:39 Mekanism Finished loading Cardboard Box blacklist (loaded 20
entries)
02:09:39 Mekanism Reloaded config.
02:09:56 ReAuth Session validation successful
02:10:17 foamfix Unloaded world
<net.minecraft.client.multiplayer.WorldClient@417ec8f3 0
MultiplayerChunkCache: 0, 0> is still hanging around after 60 seconds.
02:10:17 foamfix This may be due to a world leak, or there is little memory
pressure.
02:10:17 foamfix Use the relevant FoamFix options to adjust the wait time.

**Comment by eniolas** [comment]
there, that looks much better.

**Comment by eniolas** [comment]
there's plenty rush, servers been up for 3 weeks now, and i've maybe been
able to play 4-ish days? lmao i'm so far behind my friends. no worries tho,
thanks for helping

**Comment by NillerMedDild** [comment]
Please upload your logs to hastebin.com, the readability of the stuff you posted is awful.

**Comment by eniolas** [comment]
https://pastebin.com/sqTPJLuB

**Comment by eniolas** [comment]
https://hastebin.com/adajimakec.makefile

**Comment by NillerMedDild** [comment]
If you're using the Twitch launcher, try setting launch method to Jar instead of Native. How much RAM does your PC have, and which OS?

**Comment by eniolas** [comment]
8Gigs, DD4, 1330 MHz DRAM frequency. Windows 10

**Comment by eniolas** [comment]
still no good. same error message. connection being forcibly closed by a
remote host. i ran Task manager side by side, and idk if this helps at all,
but i have a process called "system" that as soon as i click join server,
it skyrockets to 70+% disk usage. i've disable superfetch, skype, and
cortana, and this still happens. the property files show ntoskrnl.

**Comment by NillerMedDild** [comment]
Please answer the questions.

**Comment by eniolas** [comment]
i did, 8gigs of ram, windows 10.

**Comment by NillerMedDild** [comment]
Oh so you did, sorry about that.

**Comment by NillerMedDild** [comment]
Allocating less RAM (5-5.5GB) might do the trick, I doubt it though.

I'm out of ideas. The complete server and client latest.logs may be helpful.

**Comment by eniolas** [comment]
https://media.discordapp.net/attachments/493048319522766852/493049516493373440/unknown.png?width=830&height=467

this is what the server host sent me, that work at all?

**Comment by NillerMedDild** [comment]
Wow that is.. not nice. Anyhow, that doesn't help. And your latest.log, the clients? The complete file.
