### ISSUE TITLE
World Saves not working correctly

### ISSUE THREAD

**Issue by GldnSabre74** [NillerMedDild/Enigmatica2#97]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I have now had to start over twice, after returning to my single player game, my world is missing my base and all stored items in chests.

**Modpack version (Do not use "latest")**
1.47

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment]
Does the save disappear, or does the world reset to the default?

**Comment by GldnSabre74** [comment]
It sort of resets, 30% above the ground  stays however anything underground is gone.

**Comment by GldnSabre74** [comment]
Just a heads up it might be a corrupt world save as I have seen this before (abit a long time ago (MC 1.4 and before) but it might be a mod that is crashing on exit(aka not saving completely). So this might be a non-issue I just wanted to give you a heads up about it just in case it was a modpack related issue.

**Comment by NillerMedDild** [comment]
Advanced Rocketry has a tendency to save incorrectly when force-closed, that might be the cause. 

Your latest.log would be helpful :)

**Comment by NillerMedDild** [comment]
Any update on this issue?

**Comment by GldnSabre74** [comment]
Sorry I work a lot so I just now am able to look for that log. Will try to get it posted tonight.

**Comment by GldnSabre74** [comment]
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/2432062/latest.log)

**Comment by NillerMedDild** [comment]
Did you manage to fix it? :D
