### ISSUE TITLE
unexpected / unwanted open Inventory hotbarcycling

### ISSUE THREAD

**Issue by NLinCH** [NillerMedDild/Enigmatica2#98]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
when opening the Inventory / when inventory open pressing any Buton
Makes the inventory cycle so that the hotbar moves upwards 

**Modpack version (Do not use "latest")**
Enigmatica Version 1.47

**Logs**

[latest.txt.log](https://github.com/NillerMedDild/Enigmatica2/files/2429576/latest.txt.log)

two because I reentered the world for looking if it was a constant 
_It is_
[2018-09-27-3.log.gz](https://github.com/NillerMedDild/Enigmatica2/files/2429578/2018-09-27-3.log.gz)
[2018-09-27-2.log.gz](https://github.com/NillerMedDild/Enigmatica2/files/2429579/2018-09-27-2.log.gz)

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**I was trying to open the DebugPie and The Lagometer and did a lot of F3 Combinations bevor it ocured**
I hope it is a thing that can easly solved playerside i think it might be.
Thx for continiously working on this Mod pack It is exactly ad a lot of Fun

**Comment by NillerMedDild** [comment]
This is a feature from Cyclic, try rebinding the key.

My pleasure :D

**Comment by NLinCH** [comment]
Thanks for the Informations
And Time

Op zondag 30 september 2018 heeft Niels Pilgaard Grøndahl <
notifications@github.com> het volgende geschreven:

**Comment by NLinCH** [comment]
Hallo,

ich habe gerade die Petition „Stoppt die Zensurmaschine – Rettet das
Internet! #Uploadfilter" unterschrieben und wollte dich fragen, ob du auch
mitmachst.

Unser Ziel ist es, 1.679.392 Unterschriften zu sammeln und dafür brauchen
wir Unterstützung. Hier kannst du mehr über die Petition erfahren:

https://chn.ge/2Do4pcc

Vielen Dank!
Niels
